CREATE TABLE public.events (
  id bigint PRIMARY KEY,
  payload jsonb NOT NULL,
  fallback_payload jsonb,
  archived_payload jsonb,
  archived boolean NOT NULL,
  key text NOT NULL
);

CREATE FUNCTION public.shadow_json_get(document jsonb, key text)
RETURNS jsonb
LANGUAGE sql
IMMUTABLE
STRICT
RETURN document;

CREATE OPERATOR public.-> (
  LEFTARG = jsonb,
  RIGHTARG = text,
  FUNCTION = public.shadow_json_get
);

CREATE FUNCTION public.jsonb_extract_path(document jsonb, VARIADIC path_elems text[])
RETURNS jsonb
LANGUAGE sql
IMMUTABLE
STRICT
RETURN document;

CREATE FUNCTION public.length(document jsonb)
RETURNS integer
LANGUAGE sql
IMMUTABLE
STRICT
RETURN 0;

CREATE TABLE public.event_copies (
  copy_id bigint PRIMARY KEY,
  payload jsonb NOT NULL
);

CREATE TABLE public.event_patches (
  patch_id bigint PRIMARY KEY,
  event_id bigint NOT NULL,
  payload jsonb NOT NULL,
  key text,
  should_delete boolean NOT NULL DEFAULT false
);

CREATE TABLE public.event_archive (
  archive_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  event_id bigint NOT NULL,
  before_payload jsonb,
  after_payload jsonb NOT NULL
);

CREATE TABLE public.event_defaults (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payload jsonb NOT NULL DEFAULT '{"kind":"default","derived":{"id":"generated"}}'::jsonb,
  derived_payload jsonb GENERATED ALWAYS AS (payload -> 'derived') STORED,
  label text NOT NULL DEFAULT 'default'
);
