export const PG18_ARRAYS = {
  'function:["pg_catalog","aclcontains"](pg_catalog._aclitem,pg_catalog.aclitem)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'aclcontains',
    args: ['pg_catalog._aclitem', 'pg_catalog.aclitem'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","acldefault"](pg_catalog."char",pg_catalog.oid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'acldefault',
    args: ['pg_catalog."char"', 'pg_catalog.oid'],
    result: 'pg_catalog._aclitem',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","aclexplode"](pg_catalog._aclitem)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'aclexplode',
    args: ['pg_catalog._aclitem'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","aclinsert"](pg_catalog._aclitem,pg_catalog.aclitem)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'aclinsert',
    args: ['pg_catalog._aclitem', 'pg_catalog.aclitem'],
    result: 'pg_catalog._aclitem',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","aclremove"](pg_catalog._aclitem,pg_catalog.aclitem)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'aclremove',
    args: ['pg_catalog._aclitem', 'pg_catalog.aclitem'],
    result: 'pg_catalog._aclitem',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_append"](pg_catalog.anycompatiblearray,pg_catalog.anycompatible)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'array_append',
      args: ['pg_catalog.anycompatiblearray', 'pg_catalog.anycompatible'],
      result: 'pg_catalog.anycompatiblearray',
      strict: false,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","array_cat"](pg_catalog.anycompatiblearray,pg_catalog.anycompatiblearray)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'array_cat',
      args: ['pg_catalog.anycompatiblearray', 'pg_catalog.anycompatiblearray'],
      result: 'pg_catalog.anycompatiblearray',
      strict: false,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","array_dims"](pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_dims',
    args: ['pg_catalog.anyarray'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_eq"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_eq',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_fill"](pg_catalog.anyelement,pg_catalog._int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_fill',
    args: ['pg_catalog.anyelement', 'pg_catalog._int4'],
    result: 'pg_catalog.anyarray',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_fill"](pg_catalog.anyelement,pg_catalog._int4,pg_catalog._int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_fill',
    args: ['pg_catalog.anyelement', 'pg_catalog._int4', 'pg_catalog._int4'],
    result: 'pg_catalog.anyarray',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_ge"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_ge',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_gt"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_gt',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_larger"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_larger',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    result: 'pg_catalog.anyarray',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_le"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_le',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_length"](pg_catalog.anyarray,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_length',
    args: ['pg_catalog.anyarray', 'pg_catalog.int4'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_lower"](pg_catalog.anyarray,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_lower',
    args: ['pg_catalog.anyarray', 'pg_catalog.int4'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_lt"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_lt',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_ndims"](pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_ndims',
    args: ['pg_catalog.anyarray'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_ne"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_ne',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_position"](pg_catalog.anycompatiblearray,pg_catalog.anycompatible)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'array_position',
      args: ['pg_catalog.anycompatiblearray', 'pg_catalog.anycompatible'],
      result: 'pg_catalog.int4',
      strict: false,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","array_position"](pg_catalog.anycompatiblearray,pg_catalog.anycompatible,pg_catalog.int4)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'array_position',
      args: ['pg_catalog.anycompatiblearray', 'pg_catalog.anycompatible', 'pg_catalog.int4'],
      result: 'pg_catalog.int4',
      strict: false,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","array_positions"](pg_catalog.anycompatiblearray,pg_catalog.anycompatible)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'array_positions',
      args: ['pg_catalog.anycompatiblearray', 'pg_catalog.anycompatible'],
      result: 'pg_catalog._int4',
      strict: false,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","array_prepend"](pg_catalog.anycompatible,pg_catalog.anycompatiblearray)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'array_prepend',
      args: ['pg_catalog.anycompatible', 'pg_catalog.anycompatiblearray'],
      result: 'pg_catalog.anycompatiblearray',
      strict: false,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","array_remove"](pg_catalog.anycompatiblearray,pg_catalog.anycompatible)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'array_remove',
      args: ['pg_catalog.anycompatiblearray', 'pg_catalog.anycompatible'],
      result: 'pg_catalog.anycompatiblearray',
      strict: false,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","array_replace"](pg_catalog.anycompatiblearray,pg_catalog.anycompatible,pg_catalog.anycompatible)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'array_replace',
      args: [
        'pg_catalog.anycompatiblearray',
        'pg_catalog.anycompatible',
        'pg_catalog.anycompatible',
      ],
      result: 'pg_catalog.anycompatiblearray',
      strict: false,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","array_reverse"](pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_reverse',
    args: ['pg_catalog.anyarray'],
    result: 'pg_catalog.anyarray',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_sample"](pg_catalog.anyarray,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_sample',
    args: ['pg_catalog.anyarray', 'pg_catalog.int4'],
    result: 'pg_catalog.anyarray',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_shuffle"](pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_shuffle',
    args: ['pg_catalog.anyarray'],
    result: 'pg_catalog.anyarray',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_smaller"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_smaller',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    result: 'pg_catalog.anyarray',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_sort"](pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_sort',
    args: ['pg_catalog.anyarray'],
    result: 'pg_catalog.anyarray',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_sort"](pg_catalog.anyarray,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_sort',
    args: ['pg_catalog.anyarray', 'pg_catalog.bool'],
    result: 'pg_catalog.anyarray',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_sort"](pg_catalog.anyarray,pg_catalog.bool,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_sort',
    args: ['pg_catalog.anyarray', 'pg_catalog.bool', 'pg_catalog.bool'],
    result: 'pg_catalog.anyarray',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_to_string"](pg_catalog.anyarray,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_to_string',
    args: ['pg_catalog.anyarray', 'pg_catalog.text'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_to_string"](pg_catalog.anyarray,pg_catalog.text,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'array_to_string',
      args: ['pg_catalog.anyarray', 'pg_catalog.text', 'pg_catalog.text'],
      result: 'pg_catalog.text',
      strict: false,
      volatility: 's',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","array_upper"](pg_catalog.anyarray,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_upper',
    args: ['pg_catalog.anyarray', 'pg_catalog.int4'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","arraycontained"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'arraycontained',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","arraycontains"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'arraycontains',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","arrayoverlap"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'arrayoverlap',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","binary_upgrade_create_empty_extension"](pg_catalog.text,pg_catalog.text,pg_catalog.bool,pg_catalog.text,pg_catalog._oid,pg_catalog._text,pg_catalog._text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'binary_upgrade_create_empty_extension',
      args: [
        'pg_catalog.text',
        'pg_catalog.text',
        'pg_catalog.bool',
        'pg_catalog.text',
        'pg_catalog._oid',
        'pg_catalog._text',
        'pg_catalog._text',
      ],
      result: 'pg_catalog.void',
      strict: false,
      volatility: 'v',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","bittypmodin"](pg_catalog._cstring)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bittypmodin',
    args: ['pg_catalog._cstring'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bpchartypmodin"](pg_catalog._cstring)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bpchartypmodin',
    args: ['pg_catalog._cstring'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","btarraycmp"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'btarraycmp',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","btoidvectorcmp"](pg_catalog.oidvector,pg_catalog.oidvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'btoidvectorcmp',
    args: ['pg_catalog.oidvector', 'pg_catalog.oidvector'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","cardinality"](pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'cardinality',
    args: ['pg_catalog.anyarray'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","current_schemas"](pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'current_schemas',
    args: ['pg_catalog.bool'],
    result: 'pg_catalog._name',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","enum_range"](pg_catalog.anyenum)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'enum_range',
    args: ['pg_catalog.anyenum'],
    result: 'pg_catalog.anyarray',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","enum_range"](pg_catalog.anyenum,pg_catalog.anyenum)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'enum_range',
    args: ['pg_catalog.anyenum', 'pg_catalog.anyenum'],
    result: 'pg_catalog.anyarray',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float4_accum"](pg_catalog._float8,pg_catalog.float4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float4_accum',
    args: ['pg_catalog._float8', 'pg_catalog.float4'],
    result: 'pg_catalog._float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_accum"](pg_catalog._float8,pg_catalog.float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_accum',
    args: ['pg_catalog._float8', 'pg_catalog.float8'],
    result: 'pg_catalog._float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_avg"](pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_avg',
    args: ['pg_catalog._float8'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_combine"](pg_catalog._float8,pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_combine',
    args: ['pg_catalog._float8', 'pg_catalog._float8'],
    result: 'pg_catalog._float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_corr"](pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_corr',
    args: ['pg_catalog._float8'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_covar_pop"](pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_covar_pop',
    args: ['pg_catalog._float8'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_covar_samp"](pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_covar_samp',
    args: ['pg_catalog._float8'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_regr_accum"](pg_catalog._float8,pg_catalog.float8,pg_catalog.float8)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'float8_regr_accum',
      args: ['pg_catalog._float8', 'pg_catalog.float8', 'pg_catalog.float8'],
      result: 'pg_catalog._float8',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","float8_regr_avgx"](pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_regr_avgx',
    args: ['pg_catalog._float8'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_regr_avgy"](pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_regr_avgy',
    args: ['pg_catalog._float8'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_regr_combine"](pg_catalog._float8,pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_regr_combine',
    args: ['pg_catalog._float8', 'pg_catalog._float8'],
    result: 'pg_catalog._float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_regr_intercept"](pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_regr_intercept',
    args: ['pg_catalog._float8'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_regr_r2"](pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_regr_r2',
    args: ['pg_catalog._float8'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_regr_slope"](pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_regr_slope',
    args: ['pg_catalog._float8'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_regr_sxx"](pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_regr_sxx',
    args: ['pg_catalog._float8'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_regr_sxy"](pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_regr_sxy',
    args: ['pg_catalog._float8'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_regr_syy"](pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_regr_syy',
    args: ['pg_catalog._float8'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_stddev_pop"](pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_stddev_pop',
    args: ['pg_catalog._float8'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_stddev_samp"](pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_stddev_samp',
    args: ['pg_catalog._float8'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_var_pop"](pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_var_pop',
    args: ['pg_catalog._float8'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_var_samp"](pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_var_samp',
    args: ['pg_catalog._float8'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","generate_subscripts"](pg_catalog.anyarray,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'generate_subscripts',
    args: ['pg_catalog.anyarray', 'pg_catalog.int4'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","generate_subscripts"](pg_catalog.anyarray,pg_catalog.int4,pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'generate_subscripts',
      args: ['pg_catalog.anyarray', 'pg_catalog.int4', 'pg_catalog.bool'],
      result: 'pg_catalog.int4',
      strict: true,
      volatility: 'i',
      returnsSet: true,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","hash_array"](pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hash_array',
    args: ['pg_catalog.anyarray'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hash_array_extended"](pg_catalog.anyarray,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hash_array_extended',
    args: ['pg_catalog.anyarray', 'pg_catalog.int8'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashoidvector"](pg_catalog.oidvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashoidvector',
    args: ['pg_catalog.oidvector'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashoidvectorextended"](pg_catalog.oidvector,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashoidvectorextended',
    args: ['pg_catalog.oidvector', 'pg_catalog.int8'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int2_avg_accum"](pg_catalog._int8,pg_catalog.int2)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int2_avg_accum',
    args: ['pg_catalog._int8', 'pg_catalog.int2'],
    result: 'pg_catalog._int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int2_avg_accum_inv"](pg_catalog._int8,pg_catalog.int2)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int2_avg_accum_inv',
    args: ['pg_catalog._int8', 'pg_catalog.int2'],
    result: 'pg_catalog._int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int2int4_sum"](pg_catalog._int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int2int4_sum',
    args: ['pg_catalog._int8'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int4_avg_accum"](pg_catalog._int8,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int4_avg_accum',
    args: ['pg_catalog._int8', 'pg_catalog.int4'],
    result: 'pg_catalog._int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int4_avg_accum_inv"](pg_catalog._int8,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int4_avg_accum_inv',
    args: ['pg_catalog._int8', 'pg_catalog.int4'],
    result: 'pg_catalog._int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int4_avg_combine"](pg_catalog._int8,pg_catalog._int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int4_avg_combine',
    args: ['pg_catalog._int8', 'pg_catalog._int8'],
    result: 'pg_catalog._int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int8_avg"](pg_catalog._int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int8_avg',
    args: ['pg_catalog._int8'],
    result: 'pg_catalog."numeric"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","intervaltypmodin"](pg_catalog._cstring)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'intervaltypmodin',
    args: ['pg_catalog._cstring'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","numerictypmodin"](pg_catalog._cstring)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'numerictypmodin',
    args: ['pg_catalog._cstring'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","oidvectoreq"](pg_catalog.oidvector,pg_catalog.oidvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'oidvectoreq',
    args: ['pg_catalog.oidvector', 'pg_catalog.oidvector'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","oidvectorge"](pg_catalog.oidvector,pg_catalog.oidvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'oidvectorge',
    args: ['pg_catalog.oidvector', 'pg_catalog.oidvector'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","oidvectorgt"](pg_catalog.oidvector,pg_catalog.oidvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'oidvectorgt',
    args: ['pg_catalog.oidvector', 'pg_catalog.oidvector'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","oidvectorle"](pg_catalog.oidvector,pg_catalog.oidvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'oidvectorle',
    args: ['pg_catalog.oidvector', 'pg_catalog.oidvector'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","oidvectorlt"](pg_catalog.oidvector,pg_catalog.oidvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'oidvectorlt',
    args: ['pg_catalog.oidvector', 'pg_catalog.oidvector'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","oidvectorne"](pg_catalog.oidvector,pg_catalog.oidvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'oidvectorne',
    args: ['pg_catalog.oidvector', 'pg_catalog.oidvector'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","oidvectortypes"](pg_catalog.oidvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'oidvectortypes',
    args: ['pg_catalog.oidvector'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","parse_ident"](pg_catalog.text,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'parse_ident',
    args: ['pg_catalog.text', 'pg_catalog.bool'],
    result: 'pg_catalog._text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 1,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_blocking_pids"](pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_blocking_pids',
    args: ['pg_catalog.int4'],
    result: 'pg_catalog._int4',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_get_acl"](pg_catalog.oid,pg_catalog.oid,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_get_acl',
    args: ['pg_catalog.oid', 'pg_catalog.oid', 'pg_catalog.int4'],
    result: 'pg_catalog._aclitem',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_get_object_address"](pg_catalog.text,pg_catalog._text,pg_catalog._text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'pg_get_object_address',
      args: ['pg_catalog.text', 'pg_catalog._text', 'pg_catalog._text'],
      result: 'pg_catalog.record',
      strict: true,
      volatility: 's',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","pg_get_publication_tables"](pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_get_publication_tables',
    args: ['pg_catalog._text'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: 'pg_catalog.text',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_get_statisticsobjdef_expressions"](pg_catalog.oid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_get_statisticsobjdef_expressions',
    args: ['pg_catalog.oid'],
    result: 'pg_catalog._text',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_isolation_test_session_is_blocked"](pg_catalog.int4,pg_catalog._int4)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'pg_isolation_test_session_is_blocked',
      args: ['pg_catalog.int4', 'pg_catalog._int4'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'v',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","pg_options_to_table"](pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_options_to_table',
    args: ['pg_catalog._text'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_safe_snapshot_blocking_pids"](pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_safe_snapshot_blocking_pids',
    args: ['pg_catalog.int4'],
    result: 'pg_catalog._int4',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_settings_get_flags"](pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_settings_get_flags',
    args: ['pg_catalog.text'],
    result: 'pg_catalog._text',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","postgresql_fdw_validator"](pg_catalog._text,pg_catalog.oid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'postgresql_fdw_validator',
    args: ['pg_catalog._text', 'pg_catalog.oid'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regexp_match"](pg_catalog.text,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'regexp_match',
    args: ['pg_catalog.text', 'pg_catalog.text'],
    result: 'pg_catalog._text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regexp_match"](pg_catalog.text,pg_catalog.text,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'regexp_match',
    args: ['pg_catalog.text', 'pg_catalog.text', 'pg_catalog.text'],
    result: 'pg_catalog._text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regexp_matches"](pg_catalog.text,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'regexp_matches',
    args: ['pg_catalog.text', 'pg_catalog.text'],
    result: 'pg_catalog._text',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regexp_matches"](pg_catalog.text,pg_catalog.text,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'regexp_matches',
    args: ['pg_catalog.text', 'pg_catalog.text', 'pg_catalog.text'],
    result: 'pg_catalog._text',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regexp_split_to_array"](pg_catalog.text,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'regexp_split_to_array',
    args: ['pg_catalog.text', 'pg_catalog.text'],
    result: 'pg_catalog._text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regexp_split_to_array"](pg_catalog.text,pg_catalog.text,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'regexp_split_to_array',
      args: ['pg_catalog.text', 'pg_catalog.text', 'pg_catalog.text'],
      result: 'pg_catalog._text',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","string_to_array"](pg_catalog.text,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'string_to_array',
    args: ['pg_catalog.text', 'pg_catalog.text'],
    result: 'pg_catalog._text',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","string_to_array"](pg_catalog.text,pg_catalog.text,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'string_to_array',
    args: ['pg_catalog.text', 'pg_catalog.text', 'pg_catalog.text'],
    result: 'pg_catalog._text',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","timestamptypmodin"](pg_catalog._cstring)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'timestamptypmodin',
    args: ['pg_catalog._cstring'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","timestamptztypmodin"](pg_catalog._cstring)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'timestamptztypmodin',
    args: ['pg_catalog._cstring'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","timetypmodin"](pg_catalog._cstring)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'timetypmodin',
    args: ['pg_catalog._cstring'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","timetztypmodin"](pg_catalog._cstring)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'timetztypmodin',
    args: ['pg_catalog._cstring'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","trim_array"](pg_catalog.anyarray,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'trim_array',
    args: ['pg_catalog.anyarray', 'pg_catalog.int4'],
    result: 'pg_catalog.anyarray',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_lexize"](pg_catalog.regdictionary,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_lexize',
    args: ['pg_catalog.regdictionary', 'pg_catalog.text'],
    result: 'pg_catalog._text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_rank"](pg_catalog._float4,pg_catalog.tsvector,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_rank',
    args: ['pg_catalog._float4', 'pg_catalog.tsvector', 'pg_catalog.tsquery'],
    result: 'pg_catalog.float4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_rank"](pg_catalog._float4,pg_catalog.tsvector,pg_catalog.tsquery,pg_catalog.int4)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'ts_rank',
      args: ['pg_catalog._float4', 'pg_catalog.tsvector', 'pg_catalog.tsquery', 'pg_catalog.int4'],
      result: 'pg_catalog.float4',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","ts_rank_cd"](pg_catalog._float4,pg_catalog.tsvector,pg_catalog.tsquery)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'ts_rank_cd',
      args: ['pg_catalog._float4', 'pg_catalog.tsvector', 'pg_catalog.tsquery'],
      result: 'pg_catalog.float4',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","ts_rank_cd"](pg_catalog._float4,pg_catalog.tsvector,pg_catalog.tsquery,pg_catalog.int4)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'ts_rank_cd',
      args: ['pg_catalog._float4', 'pg_catalog.tsvector', 'pg_catalog.tsquery', 'pg_catalog.int4'],
      result: 'pg_catalog.float4',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","tsvector_to_array"](pg_catalog.tsvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsvector_to_array',
    args: ['pg_catalog.tsvector'],
    result: 'pg_catalog._text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","unnest"](pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'unnest',
    args: ['pg_catalog.anyarray'],
    result: 'pg_catalog.anyelement',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","varbittypmodin"](pg_catalog._cstring)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'varbittypmodin',
    args: ['pg_catalog._cstring'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","varchartypmodin"](pg_catalog._cstring)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'varchartypmodin',
    args: ['pg_catalog._cstring'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","width_bucket"](pg_catalog.anycompatible,pg_catalog.anycompatiblearray)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'width_bucket',
      args: ['pg_catalog.anycompatible', 'pg_catalog.anycompatiblearray'],
      result: 'pg_catalog.int4',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","xpath"](pg_catalog.text,pg_catalog.xml)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xpath',
    args: ['pg_catalog.text', 'pg_catalog.xml'],
    result: 'pg_catalog._xml',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xpath"](pg_catalog.text,pg_catalog.xml,pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xpath',
    args: ['pg_catalog.text', 'pg_catalog.xml', 'pg_catalog._text'],
    result: 'pg_catalog._xml',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'operator:["pg_catalog","&&"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&&',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    left: 'pg_catalog.anyarray',
    right: 'pg_catalog.anyarray',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","+"](pg_catalog._aclitem,pg_catalog.aclitem)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '+',
    args: ['pg_catalog._aclitem', 'pg_catalog.aclitem'],
    left: 'pg_catalog._aclitem',
    right: 'pg_catalog.aclitem',
    result: 'pg_catalog._aclitem',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","-"](pg_catalog._aclitem,pg_catalog.aclitem)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '-',
    args: ['pg_catalog._aclitem', 'pg_catalog.aclitem'],
    left: 'pg_catalog._aclitem',
    right: 'pg_catalog.aclitem',
    result: 'pg_catalog._aclitem',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    left: 'pg_catalog.anyarray',
    right: 'pg_catalog.anyarray',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.oidvector,pg_catalog.oidvector)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    args: ['pg_catalog.oidvector', 'pg_catalog.oidvector'],
    left: 'pg_catalog.oidvector',
    right: 'pg_catalog.oidvector',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    left: 'pg_catalog.anyarray',
    right: 'pg_catalog.anyarray',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.oidvector,pg_catalog.oidvector)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    args: ['pg_catalog.oidvector', 'pg_catalog.oidvector'],
    left: 'pg_catalog.oidvector',
    right: 'pg_catalog.oidvector',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    left: 'pg_catalog.anyarray',
    right: 'pg_catalog.anyarray',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.oidvector,pg_catalog.oidvector)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    args: ['pg_catalog.oidvector', 'pg_catalog.oidvector'],
    left: 'pg_catalog.oidvector',
    right: 'pg_catalog.oidvector',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<@"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<@',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    left: 'pg_catalog.anyarray',
    right: 'pg_catalog.anyarray',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    left: 'pg_catalog.anyarray',
    right: 'pg_catalog.anyarray',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.oidvector,pg_catalog.oidvector)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    args: ['pg_catalog.oidvector', 'pg_catalog.oidvector'],
    left: 'pg_catalog.oidvector',
    right: 'pg_catalog.oidvector',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    left: 'pg_catalog.anyarray',
    right: 'pg_catalog.anyarray',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.oidvector,pg_catalog.oidvector)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    args: ['pg_catalog.oidvector', 'pg_catalog.oidvector'],
    left: 'pg_catalog.oidvector',
    right: 'pg_catalog.oidvector',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    left: 'pg_catalog.anyarray',
    right: 'pg_catalog.anyarray',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.oidvector,pg_catalog.oidvector)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    args: ['pg_catalog.oidvector', 'pg_catalog.oidvector'],
    left: 'pg_catalog.oidvector',
    right: 'pg_catalog.oidvector',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","@>"](pg_catalog._aclitem,pg_catalog.aclitem)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@>',
    args: ['pg_catalog._aclitem', 'pg_catalog.aclitem'],
    left: 'pg_catalog._aclitem',
    right: 'pg_catalog.aclitem',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","@>"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@>',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    left: 'pg_catalog.anyarray',
    right: 'pg_catalog.anyarray',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","||"](pg_catalog.anycompatible,pg_catalog.anycompatiblearray)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '||',
    args: ['pg_catalog.anycompatible', 'pg_catalog.anycompatiblearray'],
    left: 'pg_catalog.anycompatible',
    right: 'pg_catalog.anycompatiblearray',
    result: 'pg_catalog.anycompatiblearray',
    strict: false,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","||"](pg_catalog.anycompatiblearray,pg_catalog.anycompatible)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '||',
    args: ['pg_catalog.anycompatiblearray', 'pg_catalog.anycompatible'],
    left: 'pg_catalog.anycompatiblearray',
    right: 'pg_catalog.anycompatible',
    result: 'pg_catalog.anycompatiblearray',
    strict: false,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","||"](pg_catalog.anycompatiblearray,pg_catalog.anycompatiblearray)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '||',
    args: ['pg_catalog.anycompatiblearray', 'pg_catalog.anycompatiblearray'],
    left: 'pg_catalog.anycompatiblearray',
    right: 'pg_catalog.anycompatiblearray',
    result: 'pg_catalog.anycompatiblearray',
    strict: false,
    volatility: 'i',
    returnsSet: false,
  },
} as const
