export const PG18_ARRAYS = {
  'function:["pg_catalog","aclcontains"](pg_catalog._aclitem,pg_catalog.aclitem)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'aclcontains',
    rustName: 'sql__pg_catalog__aclcontains__90xb',
    args: ['pg_catalog._aclitem', 'pg_catalog.aclitem'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","acldefault"](pg_catalog."char",pg_catalog.oid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'acldefault',
    rustName: 'sql__pg_catalog__acldefault__yt1r',
    args: ['pg_catalog."char"', 'pg_catalog.oid'],
    result: 'pg_catalog._aclitem',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","aclexplode"](pg_catalog._aclitem)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'aclexplode',
    rustName: 'sql__pg_catalog__aclexplode__qcf0',
    args: ['pg_catalog._aclitem'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","aclinsert"](pg_catalog._aclitem,pg_catalog.aclitem)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'aclinsert',
    rustName: 'sql__pg_catalog__aclinsert__6jtk',
    args: ['pg_catalog._aclitem', 'pg_catalog.aclitem'],
    result: 'pg_catalog._aclitem',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","aclremove"](pg_catalog._aclitem,pg_catalog.aclitem)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'aclremove',
    rustName: 'sql__pg_catalog__aclremove__yg4b',
    args: ['pg_catalog._aclitem', 'pg_catalog.aclitem'],
    result: 'pg_catalog._aclitem',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_append"](pg_catalog.anycompatiblearray,pg_catalog.anycompatible)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'array_append',
      rustName: 'sql__pg_catalog__array_append__k9mc',
      args: ['pg_catalog.anycompatiblearray', 'pg_catalog.anycompatible'],
      result: 'pg_catalog.anycompatiblearray',
      strict: false,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","array_cat"](pg_catalog.anycompatiblearray,pg_catalog.anycompatiblearray)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'array_cat',
      rustName: 'sql__pg_catalog__array_cat__6rla',
      args: ['pg_catalog.anycompatiblearray', 'pg_catalog.anycompatiblearray'],
      result: 'pg_catalog.anycompatiblearray',
      strict: false,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","array_dims"](pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_dims',
    rustName: 'sql__pg_catalog__array_dims__01ex',
    args: ['pg_catalog.anyarray'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_eq"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_eq',
    rustName: 'sql__pg_catalog__array_eq__3awo',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_fill"](pg_catalog.anyelement,pg_catalog._int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_fill',
    rustName: 'sql__pg_catalog__array_fill__8l6w',
    args: ['pg_catalog.anyelement', 'pg_catalog._int4'],
    result: 'pg_catalog.anyarray',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_fill"](pg_catalog.anyelement,pg_catalog._int4,pg_catalog._int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_fill',
    rustName: 'sql__pg_catalog__array_fill__3xoe',
    args: ['pg_catalog.anyelement', 'pg_catalog._int4', 'pg_catalog._int4'],
    result: 'pg_catalog.anyarray',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_ge"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_ge',
    rustName: 'sql__pg_catalog__array_ge__2z0c',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_gt"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_gt',
    rustName: 'sql__pg_catalog__array_gt__3l95',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_larger"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_larger',
    rustName: 'sql__pg_catalog__array_larger__9l3m',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    result: 'pg_catalog.anyarray',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_le"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_le',
    rustName: 'sql__pg_catalog__array_le__oyzm',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_length"](pg_catalog.anyarray,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_length',
    rustName: 'sql__pg_catalog__array_length__pebh',
    args: ['pg_catalog.anyarray', 'pg_catalog.int4'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_lower"](pg_catalog.anyarray,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_lower',
    rustName: 'sql__pg_catalog__array_lower__3uq2',
    args: ['pg_catalog.anyarray', 'pg_catalog.int4'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_lt"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_lt',
    rustName: 'sql__pg_catalog__array_lt__tefm',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_ndims"](pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_ndims',
    rustName: 'sql__pg_catalog__array_ndims__8wu3',
    args: ['pg_catalog.anyarray'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_ne"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_ne',
    rustName: 'sql__pg_catalog__array_ne__4nzg',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_position"](pg_catalog.anycompatiblearray,pg_catalog.anycompatible)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'array_position',
      rustName: 'sql__pg_catalog__array_position__zv3u',
      args: ['pg_catalog.anycompatiblearray', 'pg_catalog.anycompatible'],
      result: 'pg_catalog.int4',
      strict: false,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","array_position"](pg_catalog.anycompatiblearray,pg_catalog.anycompatible,pg_catalog.int4)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'array_position',
      rustName: 'sql__pg_catalog__array_position__xcpr',
      args: ['pg_catalog.anycompatiblearray', 'pg_catalog.anycompatible', 'pg_catalog.int4'],
      result: 'pg_catalog.int4',
      strict: false,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","array_positions"](pg_catalog.anycompatiblearray,pg_catalog.anycompatible)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'array_positions',
      rustName: 'sql__pg_catalog__array_positions__jonj',
      args: ['pg_catalog.anycompatiblearray', 'pg_catalog.anycompatible'],
      result: 'pg_catalog._int4',
      strict: false,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","array_prepend"](pg_catalog.anycompatible,pg_catalog.anycompatiblearray)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'array_prepend',
      rustName: 'sql__pg_catalog__array_prepend__0tgl',
      args: ['pg_catalog.anycompatible', 'pg_catalog.anycompatiblearray'],
      result: 'pg_catalog.anycompatiblearray',
      strict: false,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","array_remove"](pg_catalog.anycompatiblearray,pg_catalog.anycompatible)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'array_remove',
      rustName: 'sql__pg_catalog__array_remove__wiwe',
      args: ['pg_catalog.anycompatiblearray', 'pg_catalog.anycompatible'],
      result: 'pg_catalog.anycompatiblearray',
      strict: false,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","array_replace"](pg_catalog.anycompatiblearray,pg_catalog.anycompatible,pg_catalog.anycompatible)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'array_replace',
      rustName: 'sql__pg_catalog__array_replace__whg5',
      args: [
        'pg_catalog.anycompatiblearray',
        'pg_catalog.anycompatible',
        'pg_catalog.anycompatible',
      ],
      result: 'pg_catalog.anycompatiblearray',
      strict: false,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","array_reverse"](pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_reverse',
    rustName: 'sql__pg_catalog__array_reverse__iwk0',
    args: ['pg_catalog.anyarray'],
    result: 'pg_catalog.anyarray',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_sample"](pg_catalog.anyarray,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_sample',
    rustName: 'sql__pg_catalog__array_sample__br85',
    args: ['pg_catalog.anyarray', 'pg_catalog.int4'],
    result: 'pg_catalog.anyarray',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_shuffle"](pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_shuffle',
    rustName: 'sql__pg_catalog__array_shuffle__8vsk',
    args: ['pg_catalog.anyarray'],
    result: 'pg_catalog.anyarray',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_smaller"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_smaller',
    rustName: 'sql__pg_catalog__array_smaller__xp88',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    result: 'pg_catalog.anyarray',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_sort"](pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_sort',
    rustName: 'sql__pg_catalog__array_sort__hxzh',
    args: ['pg_catalog.anyarray'],
    result: 'pg_catalog.anyarray',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_sort"](pg_catalog.anyarray,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_sort',
    rustName: 'sql__pg_catalog__array_sort__x65f',
    args: ['pg_catalog.anyarray', 'pg_catalog.bool'],
    result: 'pg_catalog.anyarray',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_sort"](pg_catalog.anyarray,pg_catalog.bool,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_sort',
    rustName: 'sql__pg_catalog__array_sort__f418',
    args: ['pg_catalog.anyarray', 'pg_catalog.bool', 'pg_catalog.bool'],
    result: 'pg_catalog.anyarray',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_to_string"](pg_catalog.anyarray,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_to_string',
    rustName: 'sql__pg_catalog__array_to_string__jpbb',
    args: ['pg_catalog.anyarray', 'pg_catalog.text'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_to_string"](pg_catalog.anyarray,pg_catalog.text,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'array_to_string',
      rustName: 'sql__pg_catalog__array_to_string__prn2',
      args: ['pg_catalog.anyarray', 'pg_catalog.text', 'pg_catalog.text'],
      result: 'pg_catalog.text',
      strict: false,
      volatility: 's',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","array_upper"](pg_catalog.anyarray,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_upper',
    rustName: 'sql__pg_catalog__array_upper__lnz3',
    args: ['pg_catalog.anyarray', 'pg_catalog.int4'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","arraycontained"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'arraycontained',
    rustName: 'sql__pg_catalog__arraycontained__uyb2',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","arraycontains"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'arraycontains',
    rustName: 'sql__pg_catalog__arraycontains__ipqq',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","arrayoverlap"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'arrayoverlap',
    rustName: 'sql__pg_catalog__arrayoverlap__lwrw',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","binary_upgrade_create_empty_extension"](pg_catalog.text,pg_catalog.text,pg_catalog.bool,pg_catalog.text,pg_catalog._oid,pg_catalog._text,pg_catalog._text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'binary_upgrade_create_empty_extension',
      rustName: 'sql__pg_catalog__binary_upgrade_create_empty_extension__q47o',
      args: [
        'pg_catalog.text',
        'pg_catalog.text',
        'pg_catalog.bool',
        'pg_catalog.text',
        'pg_catalog._oid',
        'pg_catalog._text',
        'pg_catalog._text',
      ],
      result: 'pg_catalog.void',
      strict: false,
      volatility: 'v',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","bittypmodin"](pg_catalog._cstring)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bittypmodin',
    rustName: 'sql__pg_catalog__bittypmodin__syzh',
    args: ['pg_catalog._cstring'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bpchartypmodin"](pg_catalog._cstring)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bpchartypmodin',
    rustName: 'sql__pg_catalog__bpchartypmodin__qmlm',
    args: ['pg_catalog._cstring'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","btarraycmp"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'btarraycmp',
    rustName: 'sql__pg_catalog__btarraycmp__bmnb',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","btoidvectorcmp"](pg_catalog.oidvector,pg_catalog.oidvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'btoidvectorcmp',
    rustName: 'sql__pg_catalog__btoidvectorcmp__6oyf',
    args: ['pg_catalog.oidvector', 'pg_catalog.oidvector'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","cardinality"](pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'cardinality',
    rustName: 'sql__pg_catalog__cardinality__m1rn',
    args: ['pg_catalog.anyarray'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","current_schemas"](pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'current_schemas',
    rustName: 'sql__pg_catalog__current_schemas__7ae8',
    args: ['pg_catalog.bool'],
    result: 'pg_catalog._name',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","enum_range"](pg_catalog.anyenum)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'enum_range',
    rustName: 'sql__pg_catalog__enum_range__p6cj',
    args: ['pg_catalog.anyenum'],
    result: 'pg_catalog.anyarray',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","enum_range"](pg_catalog.anyenum,pg_catalog.anyenum)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'enum_range',
    rustName: 'sql__pg_catalog__enum_range__ecgl',
    args: ['pg_catalog.anyenum', 'pg_catalog.anyenum'],
    result: 'pg_catalog.anyarray',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float4_accum"](pg_catalog._float8,pg_catalog.float4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float4_accum',
    rustName: 'sql__pg_catalog__float4_accum__nnxi',
    args: ['pg_catalog._float8', 'pg_catalog.float4'],
    result: 'pg_catalog._float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_accum"](pg_catalog._float8,pg_catalog.float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_accum',
    rustName: 'sql__pg_catalog__float8_accum__ma58',
    args: ['pg_catalog._float8', 'pg_catalog.float8'],
    result: 'pg_catalog._float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_avg"](pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_avg',
    rustName: 'sql__pg_catalog__float8_avg__zn36',
    args: ['pg_catalog._float8'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_combine"](pg_catalog._float8,pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_combine',
    rustName: 'sql__pg_catalog__float8_combine__5got',
    args: ['pg_catalog._float8', 'pg_catalog._float8'],
    result: 'pg_catalog._float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_corr"](pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_corr',
    rustName: 'sql__pg_catalog__float8_corr__8af8',
    args: ['pg_catalog._float8'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_covar_pop"](pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_covar_pop',
    rustName: 'sql__pg_catalog__float8_covar_pop__704y',
    args: ['pg_catalog._float8'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_covar_samp"](pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_covar_samp',
    rustName: 'sql__pg_catalog__float8_covar_samp__eicx',
    args: ['pg_catalog._float8'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_regr_accum"](pg_catalog._float8,pg_catalog.float8,pg_catalog.float8)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'float8_regr_accum',
      rustName: 'sql__pg_catalog__float8_regr_accum__iufl',
      args: ['pg_catalog._float8', 'pg_catalog.float8', 'pg_catalog.float8'],
      result: 'pg_catalog._float8',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","float8_regr_avgx"](pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_regr_avgx',
    rustName: 'sql__pg_catalog__float8_regr_avgx__fe05',
    args: ['pg_catalog._float8'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_regr_avgy"](pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_regr_avgy',
    rustName: 'sql__pg_catalog__float8_regr_avgy__29af',
    args: ['pg_catalog._float8'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_regr_combine"](pg_catalog._float8,pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_regr_combine',
    rustName: 'sql__pg_catalog__float8_regr_combine__nbvr',
    args: ['pg_catalog._float8', 'pg_catalog._float8'],
    result: 'pg_catalog._float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_regr_intercept"](pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_regr_intercept',
    rustName: 'sql__pg_catalog__float8_regr_intercept__m3ss',
    args: ['pg_catalog._float8'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_regr_r2"](pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_regr_r2',
    rustName: 'sql__pg_catalog__float8_regr_r2__e7fd',
    args: ['pg_catalog._float8'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_regr_slope"](pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_regr_slope',
    rustName: 'sql__pg_catalog__float8_regr_slope__qjk2',
    args: ['pg_catalog._float8'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_regr_sxx"](pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_regr_sxx',
    rustName: 'sql__pg_catalog__float8_regr_sxx__n77a',
    args: ['pg_catalog._float8'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_regr_sxy"](pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_regr_sxy',
    rustName: 'sql__pg_catalog__float8_regr_sxy__16cy',
    args: ['pg_catalog._float8'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_regr_syy"](pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_regr_syy',
    rustName: 'sql__pg_catalog__float8_regr_syy__9soz',
    args: ['pg_catalog._float8'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_stddev_pop"](pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_stddev_pop',
    rustName: 'sql__pg_catalog__float8_stddev_pop__mt1l',
    args: ['pg_catalog._float8'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_stddev_samp"](pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_stddev_samp',
    rustName: 'sql__pg_catalog__float8_stddev_samp__duzt',
    args: ['pg_catalog._float8'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_var_pop"](pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_var_pop',
    rustName: 'sql__pg_catalog__float8_var_pop__fml0',
    args: ['pg_catalog._float8'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8_var_samp"](pg_catalog._float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8_var_samp',
    rustName: 'sql__pg_catalog__float8_var_samp__6u1n',
    args: ['pg_catalog._float8'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","generate_subscripts"](pg_catalog.anyarray,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'generate_subscripts',
    rustName: 'sql__pg_catalog__generate_subscripts__z71o',
    args: ['pg_catalog.anyarray', 'pg_catalog.int4'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","generate_subscripts"](pg_catalog.anyarray,pg_catalog.int4,pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'generate_subscripts',
      rustName: 'sql__pg_catalog__generate_subscripts__dxd8',
      args: ['pg_catalog.anyarray', 'pg_catalog.int4', 'pg_catalog.bool'],
      result: 'pg_catalog.int4',
      strict: true,
      volatility: 'i',
      returnsSet: true,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","hash_array"](pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hash_array',
    rustName: 'sql__pg_catalog__hash_array__bk1m',
    args: ['pg_catalog.anyarray'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hash_array_extended"](pg_catalog.anyarray,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hash_array_extended',
    rustName: 'sql__pg_catalog__hash_array_extended__8jvn',
    args: ['pg_catalog.anyarray', 'pg_catalog.int8'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashoidvector"](pg_catalog.oidvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashoidvector',
    rustName: 'sql__pg_catalog__hashoidvector__hb8d',
    args: ['pg_catalog.oidvector'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashoidvectorextended"](pg_catalog.oidvector,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashoidvectorextended',
    rustName: 'sql__pg_catalog__hashoidvectorextended__hlbf',
    args: ['pg_catalog.oidvector', 'pg_catalog.int8'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int2_avg_accum"](pg_catalog._int8,pg_catalog.int2)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int2_avg_accum',
    rustName: 'sql__pg_catalog__int2_avg_accum__7nj2',
    args: ['pg_catalog._int8', 'pg_catalog.int2'],
    result: 'pg_catalog._int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int2_avg_accum_inv"](pg_catalog._int8,pg_catalog.int2)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int2_avg_accum_inv',
    rustName: 'sql__pg_catalog__int2_avg_accum_inv__vtyq',
    args: ['pg_catalog._int8', 'pg_catalog.int2'],
    result: 'pg_catalog._int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int2int4_sum"](pg_catalog._int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int2int4_sum',
    rustName: 'sql__pg_catalog__int2int4_sum__8u9i',
    args: ['pg_catalog._int8'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int4_avg_accum"](pg_catalog._int8,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int4_avg_accum',
    rustName: 'sql__pg_catalog__int4_avg_accum__tsby',
    args: ['pg_catalog._int8', 'pg_catalog.int4'],
    result: 'pg_catalog._int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int4_avg_accum_inv"](pg_catalog._int8,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int4_avg_accum_inv',
    rustName: 'sql__pg_catalog__int4_avg_accum_inv__dt0r',
    args: ['pg_catalog._int8', 'pg_catalog.int4'],
    result: 'pg_catalog._int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int4_avg_combine"](pg_catalog._int8,pg_catalog._int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int4_avg_combine',
    rustName: 'sql__pg_catalog__int4_avg_combine__gmvg',
    args: ['pg_catalog._int8', 'pg_catalog._int8'],
    result: 'pg_catalog._int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int8_avg"](pg_catalog._int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int8_avg',
    rustName: 'sql__pg_catalog__int8_avg__pgr2',
    args: ['pg_catalog._int8'],
    result: 'pg_catalog."numeric"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","intervaltypmodin"](pg_catalog._cstring)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'intervaltypmodin',
    rustName: 'sql__pg_catalog__intervaltypmodin__8wvt',
    args: ['pg_catalog._cstring'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","numerictypmodin"](pg_catalog._cstring)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'numerictypmodin',
    rustName: 'sql__pg_catalog__numerictypmodin__6l8z',
    args: ['pg_catalog._cstring'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","oidvectoreq"](pg_catalog.oidvector,pg_catalog.oidvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'oidvectoreq',
    rustName: 'sql__pg_catalog__oidvectoreq__bpvf',
    args: ['pg_catalog.oidvector', 'pg_catalog.oidvector'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","oidvectorge"](pg_catalog.oidvector,pg_catalog.oidvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'oidvectorge',
    rustName: 'sql__pg_catalog__oidvectorge__bgvu',
    args: ['pg_catalog.oidvector', 'pg_catalog.oidvector'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","oidvectorgt"](pg_catalog.oidvector,pg_catalog.oidvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'oidvectorgt',
    rustName: 'sql__pg_catalog__oidvectorgt__kevo',
    args: ['pg_catalog.oidvector', 'pg_catalog.oidvector'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","oidvectorle"](pg_catalog.oidvector,pg_catalog.oidvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'oidvectorle',
    rustName: 'sql__pg_catalog__oidvectorle__3fct',
    args: ['pg_catalog.oidvector', 'pg_catalog.oidvector'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","oidvectorlt"](pg_catalog.oidvector,pg_catalog.oidvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'oidvectorlt',
    rustName: 'sql__pg_catalog__oidvectorlt__6p1s',
    args: ['pg_catalog.oidvector', 'pg_catalog.oidvector'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","oidvectorne"](pg_catalog.oidvector,pg_catalog.oidvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'oidvectorne',
    rustName: 'sql__pg_catalog__oidvectorne__5v7o',
    args: ['pg_catalog.oidvector', 'pg_catalog.oidvector'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","oidvectortypes"](pg_catalog.oidvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'oidvectortypes',
    rustName: 'sql__pg_catalog__oidvectortypes__w22j',
    args: ['pg_catalog.oidvector'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","parse_ident"](pg_catalog.text,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'parse_ident',
    rustName: 'sql__pg_catalog__parse_ident__uh6p',
    args: ['pg_catalog.text', 'pg_catalog.bool'],
    result: 'pg_catalog._text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 1,
    defaultArguments: 'true',
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_blocking_pids"](pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_blocking_pids',
    rustName: 'sql__pg_catalog__pg_blocking_pids__569p',
    args: ['pg_catalog.int4'],
    result: 'pg_catalog._int4',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_get_acl"](pg_catalog.oid,pg_catalog.oid,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_get_acl',
    rustName: 'sql__pg_catalog__pg_get_acl__ytdp',
    args: ['pg_catalog.oid', 'pg_catalog.oid', 'pg_catalog.int4'],
    result: 'pg_catalog._aclitem',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_get_object_address"](pg_catalog.text,pg_catalog._text,pg_catalog._text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'pg_get_object_address',
      rustName: 'sql__pg_catalog__pg_get_object_address__szp2',
      args: ['pg_catalog.text', 'pg_catalog._text', 'pg_catalog._text'],
      result: 'pg_catalog.record',
      strict: true,
      volatility: 's',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","pg_get_publication_tables"](pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_get_publication_tables',
    rustName: 'sql__pg_catalog__pg_get_publication_tables__i8cq',
    args: ['pg_catalog._text'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: 'pg_catalog.text',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_get_statisticsobjdef_expressions"](pg_catalog.oid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_get_statisticsobjdef_expressions',
    rustName: 'sql__pg_catalog__pg_get_statisticsobjdef_expressions__2eif',
    args: ['pg_catalog.oid'],
    result: 'pg_catalog._text',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_isolation_test_session_is_blocked"](pg_catalog.int4,pg_catalog._int4)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'pg_isolation_test_session_is_blocked',
      rustName: 'sql__pg_catalog__pg_isolation_test_session_is_blocked__vlf5',
      args: ['pg_catalog.int4', 'pg_catalog._int4'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'v',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","pg_options_to_table"](pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_options_to_table',
    rustName: 'sql__pg_catalog__pg_options_to_table__jf7y',
    args: ['pg_catalog._text'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_safe_snapshot_blocking_pids"](pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_safe_snapshot_blocking_pids',
    rustName: 'sql__pg_catalog__pg_safe_snapshot_blocking_pids__9lob',
    args: ['pg_catalog.int4'],
    result: 'pg_catalog._int4',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_settings_get_flags"](pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_settings_get_flags',
    rustName: 'sql__pg_catalog__pg_settings_get_flags__n5vt',
    args: ['pg_catalog.text'],
    result: 'pg_catalog._text',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","postgresql_fdw_validator"](pg_catalog._text,pg_catalog.oid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'postgresql_fdw_validator',
    rustName: 'sql__pg_catalog__postgresql_fdw_validator__g0wo',
    args: ['pg_catalog._text', 'pg_catalog.oid'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regexp_match"](pg_catalog.text,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'regexp_match',
    rustName: 'sql__pg_catalog__regexp_match__v82p',
    args: ['pg_catalog.text', 'pg_catalog.text'],
    result: 'pg_catalog._text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regexp_match"](pg_catalog.text,pg_catalog.text,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'regexp_match',
    rustName: 'sql__pg_catalog__regexp_match__816h',
    args: ['pg_catalog.text', 'pg_catalog.text', 'pg_catalog.text'],
    result: 'pg_catalog._text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regexp_matches"](pg_catalog.text,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'regexp_matches',
    rustName: 'sql__pg_catalog__regexp_matches__zpcl',
    args: ['pg_catalog.text', 'pg_catalog.text'],
    result: 'pg_catalog._text',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regexp_matches"](pg_catalog.text,pg_catalog.text,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'regexp_matches',
    rustName: 'sql__pg_catalog__regexp_matches__6bwj',
    args: ['pg_catalog.text', 'pg_catalog.text', 'pg_catalog.text'],
    result: 'pg_catalog._text',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regexp_split_to_array"](pg_catalog.text,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'regexp_split_to_array',
    rustName: 'sql__pg_catalog__regexp_split_to_array__b4o9',
    args: ['pg_catalog.text', 'pg_catalog.text'],
    result: 'pg_catalog._text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regexp_split_to_array"](pg_catalog.text,pg_catalog.text,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'regexp_split_to_array',
      rustName: 'sql__pg_catalog__regexp_split_to_array__pmgu',
      args: ['pg_catalog.text', 'pg_catalog.text', 'pg_catalog.text'],
      result: 'pg_catalog._text',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","string_to_array"](pg_catalog.text,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'string_to_array',
    rustName: 'sql__pg_catalog__string_to_array__yhwp',
    args: ['pg_catalog.text', 'pg_catalog.text'],
    result: 'pg_catalog._text',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","string_to_array"](pg_catalog.text,pg_catalog.text,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'string_to_array',
    rustName: 'sql__pg_catalog__string_to_array__umps',
    args: ['pg_catalog.text', 'pg_catalog.text', 'pg_catalog.text'],
    result: 'pg_catalog._text',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","timestamptypmodin"](pg_catalog._cstring)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'timestamptypmodin',
    rustName: 'sql__pg_catalog__timestamptypmodin__yoyv',
    args: ['pg_catalog._cstring'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","timestamptztypmodin"](pg_catalog._cstring)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'timestamptztypmodin',
    rustName: 'sql__pg_catalog__timestamptztypmodin__c2m2',
    args: ['pg_catalog._cstring'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","timetypmodin"](pg_catalog._cstring)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'timetypmodin',
    rustName: 'sql__pg_catalog__timetypmodin__ngni',
    args: ['pg_catalog._cstring'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","timetztypmodin"](pg_catalog._cstring)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'timetztypmodin',
    rustName: 'sql__pg_catalog__timetztypmodin__fswv',
    args: ['pg_catalog._cstring'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","trim_array"](pg_catalog.anyarray,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'trim_array',
    rustName: 'sql__pg_catalog__trim_array__uzie',
    args: ['pg_catalog.anyarray', 'pg_catalog.int4'],
    result: 'pg_catalog.anyarray',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_lexize"](pg_catalog.regdictionary,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_lexize',
    rustName: 'sql__pg_catalog__ts_lexize__1osr',
    args: ['pg_catalog.regdictionary', 'pg_catalog.text'],
    result: 'pg_catalog._text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_rank"](pg_catalog._float4,pg_catalog.tsvector,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_rank',
    rustName: 'sql__pg_catalog__ts_rank__hfbf',
    args: ['pg_catalog._float4', 'pg_catalog.tsvector', 'pg_catalog.tsquery'],
    result: 'pg_catalog.float4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_rank"](pg_catalog._float4,pg_catalog.tsvector,pg_catalog.tsquery,pg_catalog.int4)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'ts_rank',
      rustName: 'sql__pg_catalog__ts_rank__wvbm',
      args: ['pg_catalog._float4', 'pg_catalog.tsvector', 'pg_catalog.tsquery', 'pg_catalog.int4'],
      result: 'pg_catalog.float4',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","ts_rank_cd"](pg_catalog._float4,pg_catalog.tsvector,pg_catalog.tsquery)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'ts_rank_cd',
      rustName: 'sql__pg_catalog__ts_rank_cd__w5px',
      args: ['pg_catalog._float4', 'pg_catalog.tsvector', 'pg_catalog.tsquery'],
      result: 'pg_catalog.float4',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","ts_rank_cd"](pg_catalog._float4,pg_catalog.tsvector,pg_catalog.tsquery,pg_catalog.int4)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'ts_rank_cd',
      rustName: 'sql__pg_catalog__ts_rank_cd__81i4',
      args: ['pg_catalog._float4', 'pg_catalog.tsvector', 'pg_catalog.tsquery', 'pg_catalog.int4'],
      result: 'pg_catalog.float4',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","tsvector_to_array"](pg_catalog.tsvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsvector_to_array',
    rustName: 'sql__pg_catalog__tsvector_to_array__rv21',
    args: ['pg_catalog.tsvector'],
    result: 'pg_catalog._text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","unnest"](pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'unnest',
    rustName: 'sql__pg_catalog__unnest__rgi2',
    args: ['pg_catalog.anyarray'],
    result: 'pg_catalog.anyelement',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","varbittypmodin"](pg_catalog._cstring)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'varbittypmodin',
    rustName: 'sql__pg_catalog__varbittypmodin__0rb2',
    args: ['pg_catalog._cstring'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","varchartypmodin"](pg_catalog._cstring)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'varchartypmodin',
    rustName: 'sql__pg_catalog__varchartypmodin__jam6',
    args: ['pg_catalog._cstring'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","width_bucket"](pg_catalog.anycompatible,pg_catalog.anycompatiblearray)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'width_bucket',
      rustName: 'sql__pg_catalog__width_bucket__ecky',
      args: ['pg_catalog.anycompatible', 'pg_catalog.anycompatiblearray'],
      result: 'pg_catalog.int4',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","xpath"](pg_catalog.text,pg_catalog.xml)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xpath',
    rustName: 'sql__pg_catalog__xpath__nuen',
    args: ['pg_catalog.text', 'pg_catalog.xml'],
    result: 'pg_catalog._xml',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xpath"](pg_catalog.text,pg_catalog.xml,pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xpath',
    rustName: 'sql__pg_catalog__xpath__abvz',
    args: ['pg_catalog.text', 'pg_catalog.xml', 'pg_catalog._text'],
    result: 'pg_catalog._xml',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'operator:["pg_catalog","&&"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&&',
    implementation:
      'function:["pg_catalog","arrayoverlap"](pg_catalog.anyarray,pg_catalog.anyarray)',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    left: 'pg_catalog.anyarray',
    right: 'pg_catalog.anyarray',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","+"](pg_catalog._aclitem,pg_catalog.aclitem)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '+',
    implementation: 'function:["pg_catalog","aclinsert"](pg_catalog._aclitem,pg_catalog.aclitem)',
    args: ['pg_catalog._aclitem', 'pg_catalog.aclitem'],
    left: 'pg_catalog._aclitem',
    right: 'pg_catalog.aclitem',
    result: 'pg_catalog._aclitem',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","-"](pg_catalog._aclitem,pg_catalog.aclitem)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '-',
    implementation: 'function:["pg_catalog","aclremove"](pg_catalog._aclitem,pg_catalog.aclitem)',
    args: ['pg_catalog._aclitem', 'pg_catalog.aclitem'],
    left: 'pg_catalog._aclitem',
    right: 'pg_catalog.aclitem',
    result: 'pg_catalog._aclitem',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    implementation: 'function:["pg_catalog","array_lt"](pg_catalog.anyarray,pg_catalog.anyarray)',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    left: 'pg_catalog.anyarray',
    right: 'pg_catalog.anyarray',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.oidvector,pg_catalog.oidvector)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    implementation:
      'function:["pg_catalog","oidvectorlt"](pg_catalog.oidvector,pg_catalog.oidvector)',
    args: ['pg_catalog.oidvector', 'pg_catalog.oidvector'],
    left: 'pg_catalog.oidvector',
    right: 'pg_catalog.oidvector',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    implementation: 'function:["pg_catalog","array_le"](pg_catalog.anyarray,pg_catalog.anyarray)',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    left: 'pg_catalog.anyarray',
    right: 'pg_catalog.anyarray',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.oidvector,pg_catalog.oidvector)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    implementation:
      'function:["pg_catalog","oidvectorle"](pg_catalog.oidvector,pg_catalog.oidvector)',
    args: ['pg_catalog.oidvector', 'pg_catalog.oidvector'],
    left: 'pg_catalog.oidvector',
    right: 'pg_catalog.oidvector',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    implementation: 'function:["pg_catalog","array_ne"](pg_catalog.anyarray,pg_catalog.anyarray)',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    left: 'pg_catalog.anyarray',
    right: 'pg_catalog.anyarray',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.oidvector,pg_catalog.oidvector)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    implementation:
      'function:["pg_catalog","oidvectorne"](pg_catalog.oidvector,pg_catalog.oidvector)',
    args: ['pg_catalog.oidvector', 'pg_catalog.oidvector'],
    left: 'pg_catalog.oidvector',
    right: 'pg_catalog.oidvector',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<@"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<@',
    implementation:
      'function:["pg_catalog","arraycontained"](pg_catalog.anyarray,pg_catalog.anyarray)',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    left: 'pg_catalog.anyarray',
    right: 'pg_catalog.anyarray',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    implementation: 'function:["pg_catalog","array_eq"](pg_catalog.anyarray,pg_catalog.anyarray)',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    left: 'pg_catalog.anyarray',
    right: 'pg_catalog.anyarray',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.oidvector,pg_catalog.oidvector)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    implementation:
      'function:["pg_catalog","oidvectoreq"](pg_catalog.oidvector,pg_catalog.oidvector)',
    args: ['pg_catalog.oidvector', 'pg_catalog.oidvector'],
    left: 'pg_catalog.oidvector',
    right: 'pg_catalog.oidvector',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    implementation: 'function:["pg_catalog","array_gt"](pg_catalog.anyarray,pg_catalog.anyarray)',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    left: 'pg_catalog.anyarray',
    right: 'pg_catalog.anyarray',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.oidvector,pg_catalog.oidvector)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    implementation:
      'function:["pg_catalog","oidvectorgt"](pg_catalog.oidvector,pg_catalog.oidvector)',
    args: ['pg_catalog.oidvector', 'pg_catalog.oidvector'],
    left: 'pg_catalog.oidvector',
    right: 'pg_catalog.oidvector',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    implementation: 'function:["pg_catalog","array_ge"](pg_catalog.anyarray,pg_catalog.anyarray)',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    left: 'pg_catalog.anyarray',
    right: 'pg_catalog.anyarray',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.oidvector,pg_catalog.oidvector)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    implementation:
      'function:["pg_catalog","oidvectorge"](pg_catalog.oidvector,pg_catalog.oidvector)',
    args: ['pg_catalog.oidvector', 'pg_catalog.oidvector'],
    left: 'pg_catalog.oidvector',
    right: 'pg_catalog.oidvector',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","@>"](pg_catalog._aclitem,pg_catalog.aclitem)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@>',
    implementation: 'function:["pg_catalog","aclcontains"](pg_catalog._aclitem,pg_catalog.aclitem)',
    args: ['pg_catalog._aclitem', 'pg_catalog.aclitem'],
    left: 'pg_catalog._aclitem',
    right: 'pg_catalog.aclitem',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","@>"](pg_catalog.anyarray,pg_catalog.anyarray)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@>',
    implementation:
      'function:["pg_catalog","arraycontains"](pg_catalog.anyarray,pg_catalog.anyarray)',
    args: ['pg_catalog.anyarray', 'pg_catalog.anyarray'],
    left: 'pg_catalog.anyarray',
    right: 'pg_catalog.anyarray',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","||"](pg_catalog.anycompatible,pg_catalog.anycompatiblearray)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '||',
    implementation:
      'function:["pg_catalog","array_prepend"](pg_catalog.anycompatible,pg_catalog.anycompatiblearray)',
    args: ['pg_catalog.anycompatible', 'pg_catalog.anycompatiblearray'],
    left: 'pg_catalog.anycompatible',
    right: 'pg_catalog.anycompatiblearray',
    result: 'pg_catalog.anycompatiblearray',
    strict: false,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","||"](pg_catalog.anycompatiblearray,pg_catalog.anycompatible)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '||',
    implementation:
      'function:["pg_catalog","array_append"](pg_catalog.anycompatiblearray,pg_catalog.anycompatible)',
    args: ['pg_catalog.anycompatiblearray', 'pg_catalog.anycompatible'],
    left: 'pg_catalog.anycompatiblearray',
    right: 'pg_catalog.anycompatible',
    result: 'pg_catalog.anycompatiblearray',
    strict: false,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","||"](pg_catalog.anycompatiblearray,pg_catalog.anycompatiblearray)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '||',
    implementation:
      'function:["pg_catalog","array_cat"](pg_catalog.anycompatiblearray,pg_catalog.anycompatiblearray)',
    args: ['pg_catalog.anycompatiblearray', 'pg_catalog.anycompatiblearray'],
    left: 'pg_catalog.anycompatiblearray',
    right: 'pg_catalog.anycompatiblearray',
    result: 'pg_catalog.anycompatiblearray',
    strict: false,
    volatility: 'i',
    returnsSet: false,
  },
} as const
