export const PG18_BINARY = {
  'function:["pg_catalog","anyarray_send"](pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'anyarray_send',
    args: ['pg_catalog.anyarray'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","anycompatiblearray_send"](pg_catalog.anycompatiblearray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'anycompatiblearray_send',
    args: ['pg_catalog.anycompatiblearray'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_send"](pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_send',
    args: ['pg_catalog.anyarray'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bit"](pg_catalog."bit",pg_catalog.int4,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bit',
    args: ['pg_catalog."bit"', 'pg_catalog.int4', 'pg_catalog.bool'],
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bit"](pg_catalog.int4,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bit',
    args: ['pg_catalog.int4', 'pg_catalog.int4'],
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bit"](pg_catalog.int8,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bit',
    args: ['pg_catalog.int8', 'pg_catalog.int4'],
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bit_count"](pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bit_count',
    args: ['pg_catalog."bit"'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bit_count"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bit_count',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bit_length"](pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bit_length',
    args: ['pg_catalog."bit"'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bit_length"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bit_length',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bit_send"](pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bit_send',
    args: ['pg_catalog."bit"'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bitand"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bitand',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bitcat"](pg_catalog.varbit,pg_catalog.varbit)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bitcat',
    args: ['pg_catalog.varbit', 'pg_catalog.varbit'],
    result: 'pg_catalog.varbit',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bitcmp"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bitcmp',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","biteq"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'biteq',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bitge"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bitge',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bitgt"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bitgt',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bitle"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bitle',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bitlt"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bitlt',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bitne"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bitne',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bitnot"](pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bitnot',
    args: ['pg_catalog."bit"'],
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bitor"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bitor',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bitshiftleft"](pg_catalog."bit",pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bitshiftleft',
    args: ['pg_catalog."bit"', 'pg_catalog.int4'],
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bitshiftright"](pg_catalog."bit",pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bitshiftright',
    args: ['pg_catalog."bit"', 'pg_catalog.int4'],
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bitxor"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bitxor',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","boolsend"](pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'boolsend',
    args: ['pg_catalog.bool'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","box_send"](pg_catalog.box)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'box_send',
    args: ['pg_catalog.box'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bpcharsend"](pg_catalog.bpchar)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bpcharsend',
    args: ['pg_catalog.bpchar'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","brin_bloom_summary_send"](pg_catalog.pg_brin_bloom_summary)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'brin_bloom_summary_send',
    args: ['pg_catalog.pg_brin_bloom_summary'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","brin_minmax_multi_summary_send"](pg_catalog.pg_brin_minmax_multi_summary)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'brin_minmax_multi_summary_send',
      args: ['pg_catalog.pg_brin_minmax_multi_summary'],
      result: 'pg_catalog.bytea',
      strict: true,
      volatility: 's',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","btrim"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'btrim',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bytea"](pg_catalog.int2)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bytea',
    args: ['pg_catalog.int2'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bytea"](pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bytea',
    args: ['pg_catalog.int4'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bytea"](pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bytea',
    args: ['pg_catalog.int8'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bytea_larger"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bytea_larger',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bytea_smaller"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bytea_smaller',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","byteacat"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'byteacat',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","byteacmp"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'byteacmp',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","byteaeq"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'byteaeq',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","byteage"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'byteage',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","byteagt"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'byteagt',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","byteale"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'byteale',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bytealike"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bytealike',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bytealt"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bytealt',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","byteane"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'byteane',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","byteanlike"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'byteanlike',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","byteasend"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'byteasend',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","cash_send"](pg_catalog.money)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'cash_send',
    args: ['pg_catalog.money'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","charsend"](pg_catalog."char")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'charsend',
    args: ['pg_catalog."char"'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","cidr_send"](pg_catalog.cidr)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'cidr_send',
    args: ['pg_catalog.cidr'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","cidsend"](pg_catalog.cid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'cidsend',
    args: ['pg_catalog.cid'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","circle_send"](pg_catalog.circle)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'circle_send',
    args: ['pg_catalog.circle'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","convert"](pg_catalog.bytea,pg_catalog.name,pg_catalog.name)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'convert',
    args: ['pg_catalog.bytea', 'pg_catalog.name', 'pg_catalog.name'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","convert_from"](pg_catalog.bytea,pg_catalog.name)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'convert_from',
    args: ['pg_catalog.bytea', 'pg_catalog.name'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","convert_to"](pg_catalog.text,pg_catalog.name)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'convert_to',
    args: ['pg_catalog.text', 'pg_catalog.name'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","crc32"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'crc32',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","crc32c"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'crc32c',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","date_send"](pg_catalog.date)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'date_send',
    args: ['pg_catalog.date'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","decode"](pg_catalog.text,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'decode',
    args: ['pg_catalog.text', 'pg_catalog.text'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","encode"](pg_catalog.bytea,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'encode',
    args: ['pg_catalog.bytea', 'pg_catalog.text'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","enum_send"](pg_catalog.anyenum)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'enum_send',
    args: ['pg_catalog.anyenum'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float4send"](pg_catalog.float4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float4send',
    args: ['pg_catalog.float4'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8send"](pg_catalog.float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8send',
    args: ['pg_catalog.float8'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","get_bit"](pg_catalog."bit",pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'get_bit',
    args: ['pg_catalog."bit"', 'pg_catalog.int4'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","get_bit"](pg_catalog.bytea,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'get_bit',
    args: ['pg_catalog.bytea', 'pg_catalog.int8'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","get_byte"](pg_catalog.bytea,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'get_byte',
    args: ['pg_catalog.bytea', 'pg_catalog.int4'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashbytea"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashbytea',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashbyteaextended"](pg_catalog.bytea,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashbyteaextended',
    args: ['pg_catalog.bytea', 'pg_catalog.int8'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","inet_send"](pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'inet_send',
    args: ['pg_catalog.inet'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int2"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int2',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.int2',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int2send"](pg_catalog.int2)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int2send',
    args: ['pg_catalog.int2'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int2vectorsend"](pg_catalog.int2vector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int2vectorsend',
    args: ['pg_catalog.int2vector'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int4"](pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int4',
    args: ['pg_catalog."bit"'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int4"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int4',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int4send"](pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int4send',
    args: ['pg_catalog.int4'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int8"](pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int8',
    args: ['pg_catalog."bit"'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int8"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int8',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int8send"](pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int8send',
    args: ['pg_catalog.int8'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","interval_send"](pg_catalog."interval")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'interval_send',
    args: ['pg_catalog."interval"'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_send"](pg_catalog."json")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_send',
    args: ['pg_catalog."json"'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_send"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_send',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonpath_send"](pg_catalog.jsonpath)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonpath_send',
    args: ['pg_catalog.jsonpath'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","length"](pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'length',
    args: ['pg_catalog."bit"'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","length"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'length',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","length"](pg_catalog.bytea,pg_catalog.name)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'length',
    args: ['pg_catalog.bytea', 'pg_catalog.name'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","like"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'like',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","like_escape"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'like_escape',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","line_send"](pg_catalog.line)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'line_send',
    args: ['pg_catalog.line'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","lo_get"](pg_catalog.oid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'lo_get',
    args: ['pg_catalog.oid'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","lo_get"](pg_catalog.oid,pg_catalog.int8,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'lo_get',
    args: ['pg_catalog.oid', 'pg_catalog.int8', 'pg_catalog.int4'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","loread"](pg_catalog.int4,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'loread',
    args: ['pg_catalog.int4', 'pg_catalog.int4'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","lowrite"](pg_catalog.int4,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'lowrite',
    args: ['pg_catalog.int4', 'pg_catalog.bytea'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","lseg_send"](pg_catalog.lseg)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'lseg_send',
    args: ['pg_catalog.lseg'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ltrim"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ltrim',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr8_send"](pg_catalog.macaddr8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr8_send',
    args: ['pg_catalog.macaddr8'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr_send"](pg_catalog.macaddr)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr_send',
    args: ['pg_catalog.macaddr'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","md5"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'md5',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","multirange_send"](pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'multirange_send',
    args: ['pg_catalog.anymultirange'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","namesend"](pg_catalog.name)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'namesend',
    args: ['pg_catalog.name'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","notlike"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'notlike',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","numeric_send"](pg_catalog."numeric")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'numeric_send',
    args: ['pg_catalog."numeric"'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","octet_length"](pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'octet_length',
    args: ['pg_catalog."bit"'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","octet_length"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'octet_length',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","oidsend"](pg_catalog.oid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'oidsend',
    args: ['pg_catalog.oid'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","oidvectorsend"](pg_catalog.oidvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'oidvectorsend',
    args: ['pg_catalog.oidvector'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","overlay"](pg_catalog."bit",pg_catalog."bit",pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'overlay',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"', 'pg_catalog.int4'],
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","overlay"](pg_catalog."bit",pg_catalog."bit",pg_catalog.int4,pg_catalog.int4)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'overlay',
      args: ['pg_catalog."bit"', 'pg_catalog."bit"', 'pg_catalog.int4', 'pg_catalog.int4'],
      result: 'pg_catalog."bit"',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","overlay"](pg_catalog.bytea,pg_catalog.bytea,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'overlay',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea', 'pg_catalog.int4'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","overlay"](pg_catalog.bytea,pg_catalog.bytea,pg_catalog.int4,pg_catalog.int4)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'overlay',
      args: ['pg_catalog.bytea', 'pg_catalog.bytea', 'pg_catalog.int4', 'pg_catalog.int4'],
      result: 'pg_catalog.bytea',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","path_send"](pg_catalog.path)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'path_send',
    args: ['pg_catalog.path'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_ddl_command_send"](pg_catalog.pg_ddl_command)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_ddl_command_send',
    args: ['pg_catalog.pg_ddl_command'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_dependencies_send"](pg_catalog.pg_dependencies)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_dependencies_send',
    args: ['pg_catalog.pg_dependencies'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_lsn_send"](pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lsn_send',
    args: ['pg_catalog.pg_lsn'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_mcv_list_send"](pg_catalog.pg_mcv_list)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_mcv_list_send',
    args: ['pg_catalog.pg_mcv_list'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_ndistinct_send"](pg_catalog.pg_ndistinct)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_ndistinct_send',
    args: ['pg_catalog.pg_ndistinct'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_node_tree_send"](pg_catalog.pg_node_tree)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_node_tree_send',
    args: ['pg_catalog.pg_node_tree'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_read_binary_file"](pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_read_binary_file',
    args: ['pg_catalog.text'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_read_binary_file"](pg_catalog.text,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_read_binary_file',
    args: ['pg_catalog.text', 'pg_catalog.bool'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_read_binary_file"](pg_catalog.text,pg_catalog.int8,pg_catalog.int8)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'pg_read_binary_file',
      args: ['pg_catalog.text', 'pg_catalog.int8', 'pg_catalog.int8'],
      result: 'pg_catalog.bytea',
      strict: true,
      volatility: 'v',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","pg_read_binary_file"](pg_catalog.text,pg_catalog.int8,pg_catalog.int8,pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'pg_read_binary_file',
      args: ['pg_catalog.text', 'pg_catalog.int8', 'pg_catalog.int8', 'pg_catalog.bool'],
      result: 'pg_catalog.bytea',
      strict: true,
      volatility: 'v',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","pg_snapshot_send"](pg_catalog.pg_snapshot)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_snapshot_send',
    args: ['pg_catalog.pg_snapshot'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","point_send"](pg_catalog.point)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'point_send',
    args: ['pg_catalog.point'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","poly_send"](pg_catalog.polygon)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'poly_send',
    args: ['pg_catalog.polygon'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","position"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'position',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","position"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'position',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_send"](pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_send',
    args: ['pg_catalog.anyrange'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","record_send"](pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'record_send',
    args: ['pg_catalog.record'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regclasssend"](pg_catalog.regclass)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'regclasssend',
    args: ['pg_catalog.regclass'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regcollationsend"](pg_catalog.regcollation)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'regcollationsend',
    args: ['pg_catalog.regcollation'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regconfigsend"](pg_catalog.regconfig)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'regconfigsend',
    args: ['pg_catalog.regconfig'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regdictionarysend"](pg_catalog.regdictionary)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'regdictionarysend',
    args: ['pg_catalog.regdictionary'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regnamespacesend"](pg_catalog.regnamespace)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'regnamespacesend',
    args: ['pg_catalog.regnamespace'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regoperatorsend"](pg_catalog.regoperator)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'regoperatorsend',
    args: ['pg_catalog.regoperator'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regopersend"](pg_catalog.regoper)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'regopersend',
    args: ['pg_catalog.regoper'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regproceduresend"](pg_catalog.regprocedure)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'regproceduresend',
    args: ['pg_catalog.regprocedure'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regprocsend"](pg_catalog.regproc)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'regprocsend',
    args: ['pg_catalog.regproc'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regrolesend"](pg_catalog.regrole)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'regrolesend',
    args: ['pg_catalog.regrole'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regtypesend"](pg_catalog.regtype)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'regtypesend',
    args: ['pg_catalog.regtype'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","reverse"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'reverse',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","rtrim"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'rtrim',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","set_bit"](pg_catalog."bit",pg_catalog.int4,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'set_bit',
    args: ['pg_catalog."bit"', 'pg_catalog.int4', 'pg_catalog.int4'],
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","set_bit"](pg_catalog.bytea,pg_catalog.int8,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'set_bit',
    args: ['pg_catalog.bytea', 'pg_catalog.int8', 'pg_catalog.int4'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","set_byte"](pg_catalog.bytea,pg_catalog.int4,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'set_byte',
    args: ['pg_catalog.bytea', 'pg_catalog.int4', 'pg_catalog.int4'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","sha224"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'sha224',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","sha256"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'sha256',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","sha384"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'sha384',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","sha512"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'sha512',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","substr"](pg_catalog.bytea,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'substr',
    args: ['pg_catalog.bytea', 'pg_catalog.int4'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","substr"](pg_catalog.bytea,pg_catalog.int4,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'substr',
    args: ['pg_catalog.bytea', 'pg_catalog.int4', 'pg_catalog.int4'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","substring"](pg_catalog."bit",pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'substring',
    args: ['pg_catalog."bit"', 'pg_catalog.int4'],
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","substring"](pg_catalog."bit",pg_catalog.int4,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'substring',
    args: ['pg_catalog."bit"', 'pg_catalog.int4', 'pg_catalog.int4'],
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","substring"](pg_catalog.bytea,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'substring',
    args: ['pg_catalog.bytea', 'pg_catalog.int4'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","substring"](pg_catalog.bytea,pg_catalog.int4,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'substring',
    args: ['pg_catalog.bytea', 'pg_catalog.int4', 'pg_catalog.int4'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","textsend"](pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'textsend',
    args: ['pg_catalog.text'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tidsend"](pg_catalog.tid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tidsend',
    args: ['pg_catalog.tid'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","time_send"](pg_catalog."time")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'time_send',
    args: ['pg_catalog."time"'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","timestamp_send"](pg_catalog."timestamp")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'timestamp_send',
    args: ['pg_catalog."timestamp"'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","timestamptz_send"](pg_catalog.timestamptz)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'timestamptz_send',
    args: ['pg_catalog.timestamptz'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","timetz_send"](pg_catalog.timetz)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'timetz_send',
    args: ['pg_catalog.timetz'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsquerysend"](pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsquerysend',
    args: ['pg_catalog.tsquery'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsvectorsend"](pg_catalog.tsvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsvectorsend',
    args: ['pg_catalog.tsvector'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","txid_snapshot_send"](pg_catalog.txid_snapshot)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'txid_snapshot_send',
    args: ['pg_catalog.txid_snapshot'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","unknownsend"](pg_catalog.unknown)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'unknownsend',
    args: ['pg_catalog.unknown'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","uuid_send"](pg_catalog.uuid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'uuid_send',
    args: ['pg_catalog.uuid'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","varbit"](pg_catalog.varbit,pg_catalog.int4,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'varbit',
    args: ['pg_catalog.varbit', 'pg_catalog.int4', 'pg_catalog.bool'],
    result: 'pg_catalog.varbit',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","varbit_send"](pg_catalog.varbit)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'varbit_send',
    args: ['pg_catalog.varbit'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","varbitcmp"](pg_catalog.varbit,pg_catalog.varbit)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'varbitcmp',
    args: ['pg_catalog.varbit', 'pg_catalog.varbit'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","varbiteq"](pg_catalog.varbit,pg_catalog.varbit)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'varbiteq',
    args: ['pg_catalog.varbit', 'pg_catalog.varbit'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","varbitge"](pg_catalog.varbit,pg_catalog.varbit)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'varbitge',
    args: ['pg_catalog.varbit', 'pg_catalog.varbit'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","varbitgt"](pg_catalog.varbit,pg_catalog.varbit)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'varbitgt',
    args: ['pg_catalog.varbit', 'pg_catalog.varbit'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","varbitle"](pg_catalog.varbit,pg_catalog.varbit)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'varbitle',
    args: ['pg_catalog.varbit', 'pg_catalog.varbit'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","varbitlt"](pg_catalog.varbit,pg_catalog.varbit)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'varbitlt',
    args: ['pg_catalog.varbit', 'pg_catalog.varbit'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","varbitne"](pg_catalog.varbit,pg_catalog.varbit)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'varbitne',
    args: ['pg_catalog.varbit', 'pg_catalog.varbit'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","varcharsend"](pg_catalog."varchar")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'varcharsend',
    args: ['pg_catalog."varchar"'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","void_send"](pg_catalog.void)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'void_send',
    args: ['pg_catalog.void'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xid8send"](pg_catalog.xid8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xid8send',
    args: ['pg_catalog.xid8'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xidsend"](pg_catalog.xid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xidsend',
    args: ['pg_catalog.xid'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xml_send"](pg_catalog.xml)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xml_send',
    args: ['pg_catalog.xml'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'operator:["pg_catalog","!~~"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '!~~',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    left: 'pg_catalog.bytea',
    right: 'pg_catalog.bytea',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","#"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '#',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    left: 'pg_catalog."bit"',
    right: 'pg_catalog."bit"',
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","&"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    left: 'pg_catalog."bit"',
    right: 'pg_catalog."bit"',
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    left: 'pg_catalog."bit"',
    right: 'pg_catalog."bit"',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    left: 'pg_catalog.bytea',
    right: 'pg_catalog.bytea',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.varbit,pg_catalog.varbit)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    args: ['pg_catalog.varbit', 'pg_catalog.varbit'],
    left: 'pg_catalog.varbit',
    right: 'pg_catalog.varbit',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<<"](pg_catalog."bit",pg_catalog.int4)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<<',
    args: ['pg_catalog."bit"', 'pg_catalog.int4'],
    left: 'pg_catalog."bit"',
    right: 'pg_catalog.int4',
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    left: 'pg_catalog."bit"',
    right: 'pg_catalog."bit"',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    left: 'pg_catalog.bytea',
    right: 'pg_catalog.bytea',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.varbit,pg_catalog.varbit)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    args: ['pg_catalog.varbit', 'pg_catalog.varbit'],
    left: 'pg_catalog.varbit',
    right: 'pg_catalog.varbit',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    left: 'pg_catalog."bit"',
    right: 'pg_catalog."bit"',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    left: 'pg_catalog.bytea',
    right: 'pg_catalog.bytea',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.varbit,pg_catalog.varbit)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    args: ['pg_catalog.varbit', 'pg_catalog.varbit'],
    left: 'pg_catalog.varbit',
    right: 'pg_catalog.varbit',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    left: 'pg_catalog."bit"',
    right: 'pg_catalog."bit"',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    left: 'pg_catalog.bytea',
    right: 'pg_catalog.bytea',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.varbit,pg_catalog.varbit)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    args: ['pg_catalog.varbit', 'pg_catalog.varbit'],
    left: 'pg_catalog.varbit',
    right: 'pg_catalog.varbit',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    left: 'pg_catalog."bit"',
    right: 'pg_catalog."bit"',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    left: 'pg_catalog.bytea',
    right: 'pg_catalog.bytea',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.varbit,pg_catalog.varbit)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    args: ['pg_catalog.varbit', 'pg_catalog.varbit'],
    left: 'pg_catalog.varbit',
    right: 'pg_catalog.varbit',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    left: 'pg_catalog."bit"',
    right: 'pg_catalog."bit"',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    left: 'pg_catalog.bytea',
    right: 'pg_catalog.bytea',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.varbit,pg_catalog.varbit)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    args: ['pg_catalog.varbit', 'pg_catalog.varbit'],
    left: 'pg_catalog.varbit',
    right: 'pg_catalog.varbit',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">>"](pg_catalog."bit",pg_catalog.int4)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>>',
    args: ['pg_catalog."bit"', 'pg_catalog.int4'],
    left: 'pg_catalog."bit"',
    right: 'pg_catalog.int4',
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","|"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '|',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    left: 'pg_catalog."bit"',
    right: 'pg_catalog."bit"',
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","||"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '||',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    left: 'pg_catalog.bytea',
    right: 'pg_catalog.bytea',
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","||"](pg_catalog.varbit,pg_catalog.varbit)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '||',
    args: ['pg_catalog.varbit', 'pg_catalog.varbit'],
    left: 'pg_catalog.varbit',
    right: 'pg_catalog.varbit',
    result: 'pg_catalog.varbit',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","~"](,pg_catalog."bit")': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '~',
    args: ['pg_catalog."bit"'],
    left: null,
    right: 'pg_catalog."bit"',
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","~~"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '~~',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    left: 'pg_catalog.bytea',
    right: 'pg_catalog.bytea',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
} as const
