export const PG18_BINARY = {
  'function:["pg_catalog","anyarray_send"](pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'anyarray_send',
    rustName: 'sql__pg_catalog__anyarray_send__p0u2',
    args: ['pg_catalog.anyarray'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","anycompatiblearray_send"](pg_catalog.anycompatiblearray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'anycompatiblearray_send',
    rustName: 'sql__pg_catalog__anycompatiblearray_send__28wx',
    args: ['pg_catalog.anycompatiblearray'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_send"](pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_send',
    rustName: 'sql__pg_catalog__array_send__g245',
    args: ['pg_catalog.anyarray'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bit"](pg_catalog."bit",pg_catalog.int4,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bit',
    rustName: 'sql__pg_catalog__bit__eqck',
    args: ['pg_catalog."bit"', 'pg_catalog.int4', 'pg_catalog.bool'],
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bit"](pg_catalog.int4,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bit',
    rustName: 'sql__pg_catalog__bit__m5gi',
    args: ['pg_catalog.int4', 'pg_catalog.int4'],
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bit"](pg_catalog.int8,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bit',
    rustName: 'sql__pg_catalog__bit__1ahy',
    args: ['pg_catalog.int8', 'pg_catalog.int4'],
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bit_count"](pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bit_count',
    rustName: 'sql__pg_catalog__bit_count__fri1',
    args: ['pg_catalog."bit"'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bit_count"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bit_count',
    rustName: 'sql__pg_catalog__bit_count__u0pl',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bit_length"](pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bit_length',
    rustName: 'sql__pg_catalog__bit_length__e2i8',
    args: ['pg_catalog."bit"'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bit_length"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bit_length',
    rustName: 'sql__pg_catalog__bit_length__gryu',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bit_send"](pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bit_send',
    rustName: 'sql__pg_catalog__bit_send__1fyo',
    args: ['pg_catalog."bit"'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bitand"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bitand',
    rustName: 'sql__pg_catalog__bitand__mal6',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bitcat"](pg_catalog.varbit,pg_catalog.varbit)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bitcat',
    rustName: 'sql__pg_catalog__bitcat__t5mn',
    args: ['pg_catalog.varbit', 'pg_catalog.varbit'],
    result: 'pg_catalog.varbit',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bitcmp"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bitcmp',
    rustName: 'sql__pg_catalog__bitcmp__2r1v',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","biteq"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'biteq',
    rustName: 'sql__pg_catalog__biteq__320u',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bitge"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bitge',
    rustName: 'sql__pg_catalog__bitge__py56',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bitgt"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bitgt',
    rustName: 'sql__pg_catalog__bitgt__2srl',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bitle"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bitle',
    rustName: 'sql__pg_catalog__bitle__y0d7',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bitlt"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bitlt',
    rustName: 'sql__pg_catalog__bitlt__6ybn',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bitne"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bitne',
    rustName: 'sql__pg_catalog__bitne__xjg3',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bitnot"](pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bitnot',
    rustName: 'sql__pg_catalog__bitnot__xgta',
    args: ['pg_catalog."bit"'],
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bitor"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bitor',
    rustName: 'sql__pg_catalog__bitor__es93',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bitshiftleft"](pg_catalog."bit",pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bitshiftleft',
    rustName: 'sql__pg_catalog__bitshiftleft__qf9d',
    args: ['pg_catalog."bit"', 'pg_catalog.int4'],
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bitshiftright"](pg_catalog."bit",pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bitshiftright',
    rustName: 'sql__pg_catalog__bitshiftright__hgyn',
    args: ['pg_catalog."bit"', 'pg_catalog.int4'],
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bitxor"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bitxor',
    rustName: 'sql__pg_catalog__bitxor__al74',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","boolsend"](pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'boolsend',
    rustName: 'sql__pg_catalog__boolsend__oo82',
    args: ['pg_catalog.bool'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","box_send"](pg_catalog.box)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'box_send',
    rustName: 'sql__pg_catalog__box_send__gn94',
    args: ['pg_catalog.box'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bpcharsend"](pg_catalog.bpchar)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bpcharsend',
    rustName: 'sql__pg_catalog__bpcharsend__h9zn',
    args: ['pg_catalog.bpchar'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","brin_bloom_summary_send"](pg_catalog.pg_brin_bloom_summary)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'brin_bloom_summary_send',
    rustName: 'sql__pg_catalog__brin_bloom_summary_send__8bk7',
    args: ['pg_catalog.pg_brin_bloom_summary'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","brin_minmax_multi_summary_send"](pg_catalog.pg_brin_minmax_multi_summary)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'brin_minmax_multi_summary_send',
      rustName: 'sql__pg_catalog__brin_minmax_multi_summary_send__z258',
      args: ['pg_catalog.pg_brin_minmax_multi_summary'],
      result: 'pg_catalog.bytea',
      strict: true,
      volatility: 's',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","btrim"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'btrim',
    rustName: 'sql__pg_catalog__btrim__riux',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bytea"](pg_catalog.int2)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bytea',
    rustName: 'sql__pg_catalog__bytea__mcxl',
    args: ['pg_catalog.int2'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bytea"](pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bytea',
    rustName: 'sql__pg_catalog__bytea__4poi',
    args: ['pg_catalog.int4'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bytea"](pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bytea',
    rustName: 'sql__pg_catalog__bytea__0om8',
    args: ['pg_catalog.int8'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bytea_larger"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bytea_larger',
    rustName: 'sql__pg_catalog__bytea_larger__iqg1',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bytea_smaller"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bytea_smaller',
    rustName: 'sql__pg_catalog__bytea_smaller__iook',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","byteacat"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'byteacat',
    rustName: 'sql__pg_catalog__byteacat__zitv',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","byteacmp"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'byteacmp',
    rustName: 'sql__pg_catalog__byteacmp__2x4q',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","byteaeq"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'byteaeq',
    rustName: 'sql__pg_catalog__byteaeq__z0yh',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","byteage"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'byteage',
    rustName: 'sql__pg_catalog__byteage__paor',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","byteagt"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'byteagt',
    rustName: 'sql__pg_catalog__byteagt__221r',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","byteale"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'byteale',
    rustName: 'sql__pg_catalog__byteale__vi7d',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bytealike"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bytealike',
    rustName: 'sql__pg_catalog__bytealike__jhpm',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bytealt"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bytealt',
    rustName: 'sql__pg_catalog__bytealt__be6e',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","byteane"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'byteane',
    rustName: 'sql__pg_catalog__byteane__volo',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","byteanlike"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'byteanlike',
    rustName: 'sql__pg_catalog__byteanlike__qodo',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","byteasend"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'byteasend',
    rustName: 'sql__pg_catalog__byteasend__3q2t',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","cash_send"](pg_catalog.money)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'cash_send',
    rustName: 'sql__pg_catalog__cash_send__p2u1',
    args: ['pg_catalog.money'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","charsend"](pg_catalog."char")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'charsend',
    rustName: 'sql__pg_catalog__charsend__12ys',
    args: ['pg_catalog."char"'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","cidr_send"](pg_catalog.cidr)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'cidr_send',
    rustName: 'sql__pg_catalog__cidr_send__s007',
    args: ['pg_catalog.cidr'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","cidsend"](pg_catalog.cid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'cidsend',
    rustName: 'sql__pg_catalog__cidsend__7b3z',
    args: ['pg_catalog.cid'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","circle_send"](pg_catalog.circle)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'circle_send',
    rustName: 'sql__pg_catalog__circle_send__ff2a',
    args: ['pg_catalog.circle'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","convert"](pg_catalog.bytea,pg_catalog.name,pg_catalog.name)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'convert',
    rustName: 'sql__pg_catalog__convert__yh8x',
    args: ['pg_catalog.bytea', 'pg_catalog.name', 'pg_catalog.name'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","convert_from"](pg_catalog.bytea,pg_catalog.name)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'convert_from',
    rustName: 'sql__pg_catalog__convert_from__fszu',
    args: ['pg_catalog.bytea', 'pg_catalog.name'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","convert_to"](pg_catalog.text,pg_catalog.name)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'convert_to',
    rustName: 'sql__pg_catalog__convert_to__1hv1',
    args: ['pg_catalog.text', 'pg_catalog.name'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","crc32"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'crc32',
    rustName: 'sql__pg_catalog__crc32__0obw',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","crc32c"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'crc32c',
    rustName: 'sql__pg_catalog__crc32c__f1hu',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","date_send"](pg_catalog.date)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'date_send',
    rustName: 'sql__pg_catalog__date_send__i2tv',
    args: ['pg_catalog.date'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","decode"](pg_catalog.text,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'decode',
    rustName: 'sql__pg_catalog__decode__b6gt',
    args: ['pg_catalog.text', 'pg_catalog.text'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","encode"](pg_catalog.bytea,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'encode',
    rustName: 'sql__pg_catalog__encode__bvkp',
    args: ['pg_catalog.bytea', 'pg_catalog.text'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","enum_send"](pg_catalog.anyenum)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'enum_send',
    rustName: 'sql__pg_catalog__enum_send__k8qr',
    args: ['pg_catalog.anyenum'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float4send"](pg_catalog.float4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float4send',
    rustName: 'sql__pg_catalog__float4send__uk42',
    args: ['pg_catalog.float4'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8send"](pg_catalog.float8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8send',
    rustName: 'sql__pg_catalog__float8send__3bqt',
    args: ['pg_catalog.float8'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","get_bit"](pg_catalog."bit",pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'get_bit',
    rustName: 'sql__pg_catalog__get_bit__ygqy',
    args: ['pg_catalog."bit"', 'pg_catalog.int4'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","get_bit"](pg_catalog.bytea,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'get_bit',
    rustName: 'sql__pg_catalog__get_bit__thv7',
    args: ['pg_catalog.bytea', 'pg_catalog.int8'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","get_byte"](pg_catalog.bytea,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'get_byte',
    rustName: 'sql__pg_catalog__get_byte__48am',
    args: ['pg_catalog.bytea', 'pg_catalog.int4'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashbytea"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashbytea',
    rustName: 'sql__pg_catalog__hashbytea__mypt',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashbyteaextended"](pg_catalog.bytea,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashbyteaextended',
    rustName: 'sql__pg_catalog__hashbyteaextended__u1vz',
    args: ['pg_catalog.bytea', 'pg_catalog.int8'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","inet_send"](pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'inet_send',
    rustName: 'sql__pg_catalog__inet_send__z9ng',
    args: ['pg_catalog.inet'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int2"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int2',
    rustName: 'sql__pg_catalog__int2__hj0w',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.int2',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int2send"](pg_catalog.int2)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int2send',
    rustName: 'sql__pg_catalog__int2send__5wzj',
    args: ['pg_catalog.int2'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int2vectorsend"](pg_catalog.int2vector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int2vectorsend',
    rustName: 'sql__pg_catalog__int2vectorsend__4kiy',
    args: ['pg_catalog.int2vector'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int4"](pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int4',
    rustName: 'sql__pg_catalog__int4__lp2l',
    args: ['pg_catalog."bit"'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int4"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int4',
    rustName: 'sql__pg_catalog__int4__lvgc',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int4send"](pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int4send',
    rustName: 'sql__pg_catalog__int4send__fjzt',
    args: ['pg_catalog.int4'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int8"](pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int8',
    rustName: 'sql__pg_catalog__int8__09r6',
    args: ['pg_catalog."bit"'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int8"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int8',
    rustName: 'sql__pg_catalog__int8__ih14',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int8send"](pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int8send',
    rustName: 'sql__pg_catalog__int8send__pjz0',
    args: ['pg_catalog.int8'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","interval_send"](pg_catalog."interval")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'interval_send',
    rustName: 'sql__pg_catalog__interval_send__jxgl',
    args: ['pg_catalog."interval"'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_send"](pg_catalog."json")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_send',
    rustName: 'sql__pg_catalog__json_send__wrp3',
    args: ['pg_catalog."json"'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_send"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_send',
    rustName: 'sql__pg_catalog__jsonb_send__8nmo',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonpath_send"](pg_catalog.jsonpath)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonpath_send',
    rustName: 'sql__pg_catalog__jsonpath_send__hmew',
    args: ['pg_catalog.jsonpath'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","length"](pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'length',
    rustName: 'sql__pg_catalog__length__r5f9',
    args: ['pg_catalog."bit"'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","length"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'length',
    rustName: 'sql__pg_catalog__length__j2mn',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","length"](pg_catalog.bytea,pg_catalog.name)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'length',
    rustName: 'sql__pg_catalog__length__glip',
    args: ['pg_catalog.bytea', 'pg_catalog.name'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","like"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'like',
    rustName: 'sql__pg_catalog__like__9b5r',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","like_escape"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'like_escape',
    rustName: 'sql__pg_catalog__like_escape__hk4j',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","line_send"](pg_catalog.line)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'line_send',
    rustName: 'sql__pg_catalog__line_send__b5ct',
    args: ['pg_catalog.line'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","lo_get"](pg_catalog.oid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'lo_get',
    rustName: 'sql__pg_catalog__lo_get__7s9g',
    args: ['pg_catalog.oid'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","lo_get"](pg_catalog.oid,pg_catalog.int8,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'lo_get',
    rustName: 'sql__pg_catalog__lo_get__z40h',
    args: ['pg_catalog.oid', 'pg_catalog.int8', 'pg_catalog.int4'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","loread"](pg_catalog.int4,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'loread',
    rustName: 'sql__pg_catalog__loread__utwh',
    args: ['pg_catalog.int4', 'pg_catalog.int4'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","lowrite"](pg_catalog.int4,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'lowrite',
    rustName: 'sql__pg_catalog__lowrite__srz3',
    args: ['pg_catalog.int4', 'pg_catalog.bytea'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","lseg_send"](pg_catalog.lseg)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'lseg_send',
    rustName: 'sql__pg_catalog__lseg_send__kc2a',
    args: ['pg_catalog.lseg'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ltrim"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ltrim',
    rustName: 'sql__pg_catalog__ltrim__p5mp',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr8_send"](pg_catalog.macaddr8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr8_send',
    rustName: 'sql__pg_catalog__macaddr8_send__qten',
    args: ['pg_catalog.macaddr8'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr_send"](pg_catalog.macaddr)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr_send',
    rustName: 'sql__pg_catalog__macaddr_send__fk4p',
    args: ['pg_catalog.macaddr'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","md5"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'md5',
    rustName: 'sql__pg_catalog__md5__vpfl',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","multirange_send"](pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'multirange_send',
    rustName: 'sql__pg_catalog__multirange_send__awvx',
    args: ['pg_catalog.anymultirange'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","namesend"](pg_catalog.name)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'namesend',
    rustName: 'sql__pg_catalog__namesend__y7mk',
    args: ['pg_catalog.name'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","notlike"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'notlike',
    rustName: 'sql__pg_catalog__notlike__cy7a',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","numeric_send"](pg_catalog."numeric")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'numeric_send',
    rustName: 'sql__pg_catalog__numeric_send__3mnb',
    args: ['pg_catalog."numeric"'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","octet_length"](pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'octet_length',
    rustName: 'sql__pg_catalog__octet_length__acdm',
    args: ['pg_catalog."bit"'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","octet_length"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'octet_length',
    rustName: 'sql__pg_catalog__octet_length__eml7',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","oidsend"](pg_catalog.oid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'oidsend',
    rustName: 'sql__pg_catalog__oidsend__kq2v',
    args: ['pg_catalog.oid'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","oidvectorsend"](pg_catalog.oidvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'oidvectorsend',
    rustName: 'sql__pg_catalog__oidvectorsend__l5tl',
    args: ['pg_catalog.oidvector'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","overlay"](pg_catalog."bit",pg_catalog."bit",pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'overlay',
    rustName: 'sql__pg_catalog__overlay__dac4',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"', 'pg_catalog.int4'],
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","overlay"](pg_catalog."bit",pg_catalog."bit",pg_catalog.int4,pg_catalog.int4)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'overlay',
      rustName: 'sql__pg_catalog__overlay__moi0',
      args: ['pg_catalog."bit"', 'pg_catalog."bit"', 'pg_catalog.int4', 'pg_catalog.int4'],
      result: 'pg_catalog."bit"',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","overlay"](pg_catalog.bytea,pg_catalog.bytea,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'overlay',
    rustName: 'sql__pg_catalog__overlay__9neg',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea', 'pg_catalog.int4'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","overlay"](pg_catalog.bytea,pg_catalog.bytea,pg_catalog.int4,pg_catalog.int4)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'overlay',
      rustName: 'sql__pg_catalog__overlay__72ov',
      args: ['pg_catalog.bytea', 'pg_catalog.bytea', 'pg_catalog.int4', 'pg_catalog.int4'],
      result: 'pg_catalog.bytea',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","path_send"](pg_catalog.path)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'path_send',
    rustName: 'sql__pg_catalog__path_send__tszn',
    args: ['pg_catalog.path'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_ddl_command_send"](pg_catalog.pg_ddl_command)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_ddl_command_send',
    rustName: 'sql__pg_catalog__pg_ddl_command_send__n91o',
    args: ['pg_catalog.pg_ddl_command'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_dependencies_send"](pg_catalog.pg_dependencies)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_dependencies_send',
    rustName: 'sql__pg_catalog__pg_dependencies_send__8c66',
    args: ['pg_catalog.pg_dependencies'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_lsn_send"](pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lsn_send',
    rustName: 'sql__pg_catalog__pg_lsn_send__r284',
    args: ['pg_catalog.pg_lsn'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_mcv_list_send"](pg_catalog.pg_mcv_list)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_mcv_list_send',
    rustName: 'sql__pg_catalog__pg_mcv_list_send__qn2v',
    args: ['pg_catalog.pg_mcv_list'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_ndistinct_send"](pg_catalog.pg_ndistinct)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_ndistinct_send',
    rustName: 'sql__pg_catalog__pg_ndistinct_send__ofqt',
    args: ['pg_catalog.pg_ndistinct'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_node_tree_send"](pg_catalog.pg_node_tree)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_node_tree_send',
    rustName: 'sql__pg_catalog__pg_node_tree_send__h28l',
    args: ['pg_catalog.pg_node_tree'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_read_binary_file"](pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_read_binary_file',
    rustName: 'sql__pg_catalog__pg_read_binary_file__a3zx',
    args: ['pg_catalog.text'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_read_binary_file"](pg_catalog.text,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_read_binary_file',
    rustName: 'sql__pg_catalog__pg_read_binary_file__4yia',
    args: ['pg_catalog.text', 'pg_catalog.bool'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_read_binary_file"](pg_catalog.text,pg_catalog.int8,pg_catalog.int8)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'pg_read_binary_file',
      rustName: 'sql__pg_catalog__pg_read_binary_file__rm7n',
      args: ['pg_catalog.text', 'pg_catalog.int8', 'pg_catalog.int8'],
      result: 'pg_catalog.bytea',
      strict: true,
      volatility: 'v',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","pg_read_binary_file"](pg_catalog.text,pg_catalog.int8,pg_catalog.int8,pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'pg_read_binary_file',
      rustName: 'sql__pg_catalog__pg_read_binary_file__bq8m',
      args: ['pg_catalog.text', 'pg_catalog.int8', 'pg_catalog.int8', 'pg_catalog.bool'],
      result: 'pg_catalog.bytea',
      strict: true,
      volatility: 'v',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","pg_snapshot_send"](pg_catalog.pg_snapshot)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_snapshot_send',
    rustName: 'sql__pg_catalog__pg_snapshot_send__ux8s',
    args: ['pg_catalog.pg_snapshot'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","point_send"](pg_catalog.point)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'point_send',
    rustName: 'sql__pg_catalog__point_send__kuoa',
    args: ['pg_catalog.point'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","poly_send"](pg_catalog.polygon)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'poly_send',
    rustName: 'sql__pg_catalog__poly_send__38c4',
    args: ['pg_catalog.polygon'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","position"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'position',
    rustName: 'sql__pg_catalog__position__93b9',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","position"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'position',
    rustName: 'sql__pg_catalog__position__9w14',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_send"](pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_send',
    rustName: 'sql__pg_catalog__range_send__b1w5',
    args: ['pg_catalog.anyrange'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","record_send"](pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'record_send',
    rustName: 'sql__pg_catalog__record_send__yv22',
    args: ['pg_catalog.record'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regclasssend"](pg_catalog.regclass)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'regclasssend',
    rustName: 'sql__pg_catalog__regclasssend__c6c0',
    args: ['pg_catalog.regclass'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regcollationsend"](pg_catalog.regcollation)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'regcollationsend',
    rustName: 'sql__pg_catalog__regcollationsend__4bem',
    args: ['pg_catalog.regcollation'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regconfigsend"](pg_catalog.regconfig)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'regconfigsend',
    rustName: 'sql__pg_catalog__regconfigsend__db3d',
    args: ['pg_catalog.regconfig'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regdictionarysend"](pg_catalog.regdictionary)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'regdictionarysend',
    rustName: 'sql__pg_catalog__regdictionarysend__ok9z',
    args: ['pg_catalog.regdictionary'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regnamespacesend"](pg_catalog.regnamespace)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'regnamespacesend',
    rustName: 'sql__pg_catalog__regnamespacesend__jpj3',
    args: ['pg_catalog.regnamespace'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regoperatorsend"](pg_catalog.regoperator)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'regoperatorsend',
    rustName: 'sql__pg_catalog__regoperatorsend__vsu1',
    args: ['pg_catalog.regoperator'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regopersend"](pg_catalog.regoper)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'regopersend',
    rustName: 'sql__pg_catalog__regopersend__4lv2',
    args: ['pg_catalog.regoper'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regproceduresend"](pg_catalog.regprocedure)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'regproceduresend',
    rustName: 'sql__pg_catalog__regproceduresend__txe7',
    args: ['pg_catalog.regprocedure'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regprocsend"](pg_catalog.regproc)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'regprocsend',
    rustName: 'sql__pg_catalog__regprocsend__lxet',
    args: ['pg_catalog.regproc'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regrolesend"](pg_catalog.regrole)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'regrolesend',
    rustName: 'sql__pg_catalog__regrolesend__a3kd',
    args: ['pg_catalog.regrole'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","regtypesend"](pg_catalog.regtype)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'regtypesend',
    rustName: 'sql__pg_catalog__regtypesend__42nl',
    args: ['pg_catalog.regtype'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","reverse"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'reverse',
    rustName: 'sql__pg_catalog__reverse__w0od',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","rtrim"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'rtrim',
    rustName: 'sql__pg_catalog__rtrim__33rv',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","set_bit"](pg_catalog."bit",pg_catalog.int4,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'set_bit',
    rustName: 'sql__pg_catalog__set_bit__2mfa',
    args: ['pg_catalog."bit"', 'pg_catalog.int4', 'pg_catalog.int4'],
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","set_bit"](pg_catalog.bytea,pg_catalog.int8,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'set_bit',
    rustName: 'sql__pg_catalog__set_bit__06f4',
    args: ['pg_catalog.bytea', 'pg_catalog.int8', 'pg_catalog.int4'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","set_byte"](pg_catalog.bytea,pg_catalog.int4,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'set_byte',
    rustName: 'sql__pg_catalog__set_byte__8mtw',
    args: ['pg_catalog.bytea', 'pg_catalog.int4', 'pg_catalog.int4'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","sha224"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'sha224',
    rustName: 'sql__pg_catalog__sha224__s7oo',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","sha256"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'sha256',
    rustName: 'sql__pg_catalog__sha256__19zu',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","sha384"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'sha384',
    rustName: 'sql__pg_catalog__sha384__41g6',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","sha512"](pg_catalog.bytea)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'sha512',
    rustName: 'sql__pg_catalog__sha512__si49',
    args: ['pg_catalog.bytea'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","substr"](pg_catalog.bytea,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'substr',
    rustName: 'sql__pg_catalog__substr__xbdy',
    args: ['pg_catalog.bytea', 'pg_catalog.int4'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","substr"](pg_catalog.bytea,pg_catalog.int4,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'substr',
    rustName: 'sql__pg_catalog__substr__jkup',
    args: ['pg_catalog.bytea', 'pg_catalog.int4', 'pg_catalog.int4'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","substring"](pg_catalog."bit",pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'substring',
    rustName: 'sql__pg_catalog__substring__dfdi',
    args: ['pg_catalog."bit"', 'pg_catalog.int4'],
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","substring"](pg_catalog."bit",pg_catalog.int4,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'substring',
    rustName: 'sql__pg_catalog__substring__pr1e',
    args: ['pg_catalog."bit"', 'pg_catalog.int4', 'pg_catalog.int4'],
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","substring"](pg_catalog.bytea,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'substring',
    rustName: 'sql__pg_catalog__substring__2f07',
    args: ['pg_catalog.bytea', 'pg_catalog.int4'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","substring"](pg_catalog.bytea,pg_catalog.int4,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'substring',
    rustName: 'sql__pg_catalog__substring__b44k',
    args: ['pg_catalog.bytea', 'pg_catalog.int4', 'pg_catalog.int4'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","textsend"](pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'textsend',
    rustName: 'sql__pg_catalog__textsend__mgfj',
    args: ['pg_catalog.text'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tidsend"](pg_catalog.tid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tidsend',
    rustName: 'sql__pg_catalog__tidsend__o4ql',
    args: ['pg_catalog.tid'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","time_send"](pg_catalog."time")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'time_send',
    rustName: 'sql__pg_catalog__time_send__0qc6',
    args: ['pg_catalog."time"'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","timestamp_send"](pg_catalog."timestamp")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'timestamp_send',
    rustName: 'sql__pg_catalog__timestamp_send__3syx',
    args: ['pg_catalog."timestamp"'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","timestamptz_send"](pg_catalog.timestamptz)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'timestamptz_send',
    rustName: 'sql__pg_catalog__timestamptz_send__jyu1',
    args: ['pg_catalog.timestamptz'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","timetz_send"](pg_catalog.timetz)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'timetz_send',
    rustName: 'sql__pg_catalog__timetz_send__r9py',
    args: ['pg_catalog.timetz'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsquerysend"](pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsquerysend',
    rustName: 'sql__pg_catalog__tsquerysend__0660',
    args: ['pg_catalog.tsquery'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsvectorsend"](pg_catalog.tsvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsvectorsend',
    rustName: 'sql__pg_catalog__tsvectorsend__37x7',
    args: ['pg_catalog.tsvector'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","txid_snapshot_send"](pg_catalog.txid_snapshot)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'txid_snapshot_send',
    rustName: 'sql__pg_catalog__txid_snapshot_send__bjde',
    args: ['pg_catalog.txid_snapshot'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","unknownsend"](pg_catalog.unknown)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'unknownsend',
    rustName: 'sql__pg_catalog__unknownsend__n105',
    args: ['pg_catalog.unknown'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","uuid_send"](pg_catalog.uuid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'uuid_send',
    rustName: 'sql__pg_catalog__uuid_send__32nf',
    args: ['pg_catalog.uuid'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","varbit"](pg_catalog.varbit,pg_catalog.int4,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'varbit',
    rustName: 'sql__pg_catalog__varbit__7ap7',
    args: ['pg_catalog.varbit', 'pg_catalog.int4', 'pg_catalog.bool'],
    result: 'pg_catalog.varbit',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","varbit_send"](pg_catalog.varbit)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'varbit_send',
    rustName: 'sql__pg_catalog__varbit_send__yt0j',
    args: ['pg_catalog.varbit'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","varbitcmp"](pg_catalog.varbit,pg_catalog.varbit)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'varbitcmp',
    rustName: 'sql__pg_catalog__varbitcmp__vqwo',
    args: ['pg_catalog.varbit', 'pg_catalog.varbit'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","varbiteq"](pg_catalog.varbit,pg_catalog.varbit)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'varbiteq',
    rustName: 'sql__pg_catalog__varbiteq__d8r9',
    args: ['pg_catalog.varbit', 'pg_catalog.varbit'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","varbitge"](pg_catalog.varbit,pg_catalog.varbit)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'varbitge',
    rustName: 'sql__pg_catalog__varbitge__3izz',
    args: ['pg_catalog.varbit', 'pg_catalog.varbit'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","varbitgt"](pg_catalog.varbit,pg_catalog.varbit)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'varbitgt',
    rustName: 'sql__pg_catalog__varbitgt__31v4',
    args: ['pg_catalog.varbit', 'pg_catalog.varbit'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","varbitle"](pg_catalog.varbit,pg_catalog.varbit)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'varbitle',
    rustName: 'sql__pg_catalog__varbitle__42o0',
    args: ['pg_catalog.varbit', 'pg_catalog.varbit'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","varbitlt"](pg_catalog.varbit,pg_catalog.varbit)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'varbitlt',
    rustName: 'sql__pg_catalog__varbitlt__xsv2',
    args: ['pg_catalog.varbit', 'pg_catalog.varbit'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","varbitne"](pg_catalog.varbit,pg_catalog.varbit)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'varbitne',
    rustName: 'sql__pg_catalog__varbitne__sbck',
    args: ['pg_catalog.varbit', 'pg_catalog.varbit'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","varcharsend"](pg_catalog."varchar")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'varcharsend',
    rustName: 'sql__pg_catalog__varcharsend__jov8',
    args: ['pg_catalog."varchar"'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","void_send"](pg_catalog.void)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'void_send',
    rustName: 'sql__pg_catalog__void_send__3zwt',
    args: ['pg_catalog.void'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xid8send"](pg_catalog.xid8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xid8send',
    rustName: 'sql__pg_catalog__xid8send__iu1c',
    args: ['pg_catalog.xid8'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xidsend"](pg_catalog.xid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xidsend',
    rustName: 'sql__pg_catalog__xidsend__ca8a',
    args: ['pg_catalog.xid'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xml_send"](pg_catalog.xml)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xml_send',
    rustName: 'sql__pg_catalog__xml_send__uur7',
    args: ['pg_catalog.xml'],
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'operator:["pg_catalog","!~~"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '!~~',
    implementation: 'function:["pg_catalog","byteanlike"](pg_catalog.bytea,pg_catalog.bytea)',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    left: 'pg_catalog.bytea',
    right: 'pg_catalog.bytea',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","#"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '#',
    implementation: 'function:["pg_catalog","bitxor"](pg_catalog."bit",pg_catalog."bit")',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    left: 'pg_catalog."bit"',
    right: 'pg_catalog."bit"',
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","&"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&',
    implementation: 'function:["pg_catalog","bitand"](pg_catalog."bit",pg_catalog."bit")',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    left: 'pg_catalog."bit"',
    right: 'pg_catalog."bit"',
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    implementation: 'function:["pg_catalog","bitlt"](pg_catalog."bit",pg_catalog."bit")',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    left: 'pg_catalog."bit"',
    right: 'pg_catalog."bit"',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    implementation: 'function:["pg_catalog","bytealt"](pg_catalog.bytea,pg_catalog.bytea)',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    left: 'pg_catalog.bytea',
    right: 'pg_catalog.bytea',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.varbit,pg_catalog.varbit)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    implementation: 'function:["pg_catalog","varbitlt"](pg_catalog.varbit,pg_catalog.varbit)',
    args: ['pg_catalog.varbit', 'pg_catalog.varbit'],
    left: 'pg_catalog.varbit',
    right: 'pg_catalog.varbit',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<<"](pg_catalog."bit",pg_catalog.int4)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<<',
    implementation: 'function:["pg_catalog","bitshiftleft"](pg_catalog."bit",pg_catalog.int4)',
    args: ['pg_catalog."bit"', 'pg_catalog.int4'],
    left: 'pg_catalog."bit"',
    right: 'pg_catalog.int4',
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    implementation: 'function:["pg_catalog","bitle"](pg_catalog."bit",pg_catalog."bit")',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    left: 'pg_catalog."bit"',
    right: 'pg_catalog."bit"',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    implementation: 'function:["pg_catalog","byteale"](pg_catalog.bytea,pg_catalog.bytea)',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    left: 'pg_catalog.bytea',
    right: 'pg_catalog.bytea',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.varbit,pg_catalog.varbit)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    implementation: 'function:["pg_catalog","varbitle"](pg_catalog.varbit,pg_catalog.varbit)',
    args: ['pg_catalog.varbit', 'pg_catalog.varbit'],
    left: 'pg_catalog.varbit',
    right: 'pg_catalog.varbit',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    implementation: 'function:["pg_catalog","bitne"](pg_catalog."bit",pg_catalog."bit")',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    left: 'pg_catalog."bit"',
    right: 'pg_catalog."bit"',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    implementation: 'function:["pg_catalog","byteane"](pg_catalog.bytea,pg_catalog.bytea)',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    left: 'pg_catalog.bytea',
    right: 'pg_catalog.bytea',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.varbit,pg_catalog.varbit)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    implementation: 'function:["pg_catalog","varbitne"](pg_catalog.varbit,pg_catalog.varbit)',
    args: ['pg_catalog.varbit', 'pg_catalog.varbit'],
    left: 'pg_catalog.varbit',
    right: 'pg_catalog.varbit',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    implementation: 'function:["pg_catalog","biteq"](pg_catalog."bit",pg_catalog."bit")',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    left: 'pg_catalog."bit"',
    right: 'pg_catalog."bit"',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    implementation: 'function:["pg_catalog","byteaeq"](pg_catalog.bytea,pg_catalog.bytea)',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    left: 'pg_catalog.bytea',
    right: 'pg_catalog.bytea',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.varbit,pg_catalog.varbit)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    implementation: 'function:["pg_catalog","varbiteq"](pg_catalog.varbit,pg_catalog.varbit)',
    args: ['pg_catalog.varbit', 'pg_catalog.varbit'],
    left: 'pg_catalog.varbit',
    right: 'pg_catalog.varbit',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    implementation: 'function:["pg_catalog","bitgt"](pg_catalog."bit",pg_catalog."bit")',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    left: 'pg_catalog."bit"',
    right: 'pg_catalog."bit"',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    implementation: 'function:["pg_catalog","byteagt"](pg_catalog.bytea,pg_catalog.bytea)',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    left: 'pg_catalog.bytea',
    right: 'pg_catalog.bytea',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.varbit,pg_catalog.varbit)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    implementation: 'function:["pg_catalog","varbitgt"](pg_catalog.varbit,pg_catalog.varbit)',
    args: ['pg_catalog.varbit', 'pg_catalog.varbit'],
    left: 'pg_catalog.varbit',
    right: 'pg_catalog.varbit',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    implementation: 'function:["pg_catalog","bitge"](pg_catalog."bit",pg_catalog."bit")',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    left: 'pg_catalog."bit"',
    right: 'pg_catalog."bit"',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    implementation: 'function:["pg_catalog","byteage"](pg_catalog.bytea,pg_catalog.bytea)',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    left: 'pg_catalog.bytea',
    right: 'pg_catalog.bytea',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.varbit,pg_catalog.varbit)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    implementation: 'function:["pg_catalog","varbitge"](pg_catalog.varbit,pg_catalog.varbit)',
    args: ['pg_catalog.varbit', 'pg_catalog.varbit'],
    left: 'pg_catalog.varbit',
    right: 'pg_catalog.varbit',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">>"](pg_catalog."bit",pg_catalog.int4)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>>',
    implementation: 'function:["pg_catalog","bitshiftright"](pg_catalog."bit",pg_catalog.int4)',
    args: ['pg_catalog."bit"', 'pg_catalog.int4'],
    left: 'pg_catalog."bit"',
    right: 'pg_catalog.int4',
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","|"](pg_catalog."bit",pg_catalog."bit")': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '|',
    implementation: 'function:["pg_catalog","bitor"](pg_catalog."bit",pg_catalog."bit")',
    args: ['pg_catalog."bit"', 'pg_catalog."bit"'],
    left: 'pg_catalog."bit"',
    right: 'pg_catalog."bit"',
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","||"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '||',
    implementation: 'function:["pg_catalog","byteacat"](pg_catalog.bytea,pg_catalog.bytea)',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    left: 'pg_catalog.bytea',
    right: 'pg_catalog.bytea',
    result: 'pg_catalog.bytea',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","||"](pg_catalog.varbit,pg_catalog.varbit)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '||',
    implementation: 'function:["pg_catalog","bitcat"](pg_catalog.varbit,pg_catalog.varbit)',
    args: ['pg_catalog.varbit', 'pg_catalog.varbit'],
    left: 'pg_catalog.varbit',
    right: 'pg_catalog.varbit',
    result: 'pg_catalog.varbit',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","~"](,pg_catalog."bit")': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '~',
    implementation: 'function:["pg_catalog","bitnot"](pg_catalog."bit")',
    args: ['pg_catalog."bit"'],
    left: null,
    right: 'pg_catalog."bit"',
    result: 'pg_catalog."bit"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","~~"](pg_catalog.bytea,pg_catalog.bytea)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '~~',
    implementation: 'function:["pg_catalog","bytealike"](pg_catalog.bytea,pg_catalog.bytea)',
    args: ['pg_catalog.bytea', 'pg_catalog.bytea'],
    left: 'pg_catalog.bytea',
    right: 'pg_catalog.bytea',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
} as const
