export const PG18_BOOLEAN = {
  'function:["pg_catalog","booland_statefunc"](pg_catalog.bool,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'booland_statefunc',
    args: ['pg_catalog.bool', 'pg_catalog.bool'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","booleq"](pg_catalog.bool,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'booleq',
    args: ['pg_catalog.bool', 'pg_catalog.bool'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","boolge"](pg_catalog.bool,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'boolge',
    args: ['pg_catalog.bool', 'pg_catalog.bool'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","boolgt"](pg_catalog.bool,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'boolgt',
    args: ['pg_catalog.bool', 'pg_catalog.bool'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","boolle"](pg_catalog.bool,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'boolle',
    args: ['pg_catalog.bool', 'pg_catalog.bool'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","boollt"](pg_catalog.bool,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'boollt',
    args: ['pg_catalog.bool', 'pg_catalog.bool'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","boolne"](pg_catalog.bool,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'boolne',
    args: ['pg_catalog.bool', 'pg_catalog.bool'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","boolor_statefunc"](pg_catalog.bool,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'boolor_statefunc',
    args: ['pg_catalog.bool', 'pg_catalog.bool'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_is_in_recovery"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_is_in_recovery',
    args: [],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_is_wal_replay_paused"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_is_wal_replay_paused',
    args: [],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_jit_available"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_jit_available',
    args: [],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_numa_available"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_numa_available',
    args: [],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_reload_conf"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_reload_conf',
    args: [],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_replication_origin_session_is_setup"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_replication_origin_session_is_setup',
    args: [],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_rotate_logfile"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_rotate_logfile',
    args: [],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'operator:["pg_catalog","<"](pg_catalog.bool,pg_catalog.bool)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    args: ['pg_catalog.bool', 'pg_catalog.bool'],
    left: 'pg_catalog.bool',
    right: 'pg_catalog.bool',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.bool,pg_catalog.bool)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    args: ['pg_catalog.bool', 'pg_catalog.bool'],
    left: 'pg_catalog.bool',
    right: 'pg_catalog.bool',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.bool,pg_catalog.bool)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    args: ['pg_catalog.bool', 'pg_catalog.bool'],
    left: 'pg_catalog.bool',
    right: 'pg_catalog.bool',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.bool,pg_catalog.bool)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    args: ['pg_catalog.bool', 'pg_catalog.bool'],
    left: 'pg_catalog.bool',
    right: 'pg_catalog.bool',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.bool,pg_catalog.bool)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    args: ['pg_catalog.bool', 'pg_catalog.bool'],
    left: 'pg_catalog.bool',
    right: 'pg_catalog.bool',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.bool,pg_catalog.bool)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    args: ['pg_catalog.bool', 'pg_catalog.bool'],
    left: 'pg_catalog.bool',
    right: 'pg_catalog.bool',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
} as const
