export const PG18_BOOLEAN = {
  'function:["pg_catalog","booland_statefunc"](pg_catalog.bool,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'booland_statefunc',
    rustName: 'sql__pg_catalog__booland_statefunc__dxg8',
    args: ['pg_catalog.bool', 'pg_catalog.bool'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","booleq"](pg_catalog.bool,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'booleq',
    rustName: 'sql__pg_catalog__booleq__y6qu',
    args: ['pg_catalog.bool', 'pg_catalog.bool'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","boolge"](pg_catalog.bool,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'boolge',
    rustName: 'sql__pg_catalog__boolge__gviq',
    args: ['pg_catalog.bool', 'pg_catalog.bool'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","boolgt"](pg_catalog.bool,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'boolgt',
    rustName: 'sql__pg_catalog__boolgt__6vb2',
    args: ['pg_catalog.bool', 'pg_catalog.bool'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","boolle"](pg_catalog.bool,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'boolle',
    rustName: 'sql__pg_catalog__boolle__0cme',
    args: ['pg_catalog.bool', 'pg_catalog.bool'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","boollt"](pg_catalog.bool,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'boollt',
    rustName: 'sql__pg_catalog__boollt__cgkk',
    args: ['pg_catalog.bool', 'pg_catalog.bool'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","boolne"](pg_catalog.bool,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'boolne',
    rustName: 'sql__pg_catalog__boolne__zlce',
    args: ['pg_catalog.bool', 'pg_catalog.bool'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","boolor_statefunc"](pg_catalog.bool,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'boolor_statefunc',
    rustName: 'sql__pg_catalog__boolor_statefunc__1p3g',
    args: ['pg_catalog.bool', 'pg_catalog.bool'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_is_in_recovery"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_is_in_recovery',
    rustName: 'sql__pg_catalog__pg_is_in_recovery__j20d',
    args: [],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_is_wal_replay_paused"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_is_wal_replay_paused',
    rustName: 'sql__pg_catalog__pg_is_wal_replay_paused__9zdn',
    args: [],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_jit_available"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_jit_available',
    rustName: 'sql__pg_catalog__pg_jit_available__a2c1',
    args: [],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_numa_available"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_numa_available',
    rustName: 'sql__pg_catalog__pg_numa_available__jrqt',
    args: [],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_reload_conf"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_reload_conf',
    rustName: 'sql__pg_catalog__pg_reload_conf__bgf9',
    args: [],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_replication_origin_session_is_setup"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_replication_origin_session_is_setup',
    rustName: 'sql__pg_catalog__pg_replication_origin_session_is_setup__r6bt',
    args: [],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_rotate_logfile"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_rotate_logfile',
    rustName: 'sql__pg_catalog__pg_rotate_logfile__3am0',
    args: [],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'operator:["pg_catalog","<"](pg_catalog.bool,pg_catalog.bool)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    implementation: 'function:["pg_catalog","boollt"](pg_catalog.bool,pg_catalog.bool)',
    args: ['pg_catalog.bool', 'pg_catalog.bool'],
    left: 'pg_catalog.bool',
    right: 'pg_catalog.bool',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.bool,pg_catalog.bool)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    implementation: 'function:["pg_catalog","boolle"](pg_catalog.bool,pg_catalog.bool)',
    args: ['pg_catalog.bool', 'pg_catalog.bool'],
    left: 'pg_catalog.bool',
    right: 'pg_catalog.bool',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.bool,pg_catalog.bool)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    implementation: 'function:["pg_catalog","boolne"](pg_catalog.bool,pg_catalog.bool)',
    args: ['pg_catalog.bool', 'pg_catalog.bool'],
    left: 'pg_catalog.bool',
    right: 'pg_catalog.bool',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.bool,pg_catalog.bool)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    implementation: 'function:["pg_catalog","booleq"](pg_catalog.bool,pg_catalog.bool)',
    args: ['pg_catalog.bool', 'pg_catalog.bool'],
    left: 'pg_catalog.bool',
    right: 'pg_catalog.bool',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.bool,pg_catalog.bool)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    implementation: 'function:["pg_catalog","boolgt"](pg_catalog.bool,pg_catalog.bool)',
    args: ['pg_catalog.bool', 'pg_catalog.bool'],
    left: 'pg_catalog.bool',
    right: 'pg_catalog.bool',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.bool,pg_catalog.bool)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    implementation: 'function:["pg_catalog","boolge"](pg_catalog.bool,pg_catalog.bool)',
    args: ['pg_catalog.bool', 'pg_catalog.bool'],
    left: 'pg_catalog.bool',
    right: 'pg_catalog.bool',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
} as const
