export const PG18_BUILTIN_CASTS = {
  '["pg_catalog.\\"bit\\"","pg_catalog.\\"bit\\""]': {
    source: 'pg_catalog."bit"',
    target: 'pg_catalog."bit"',
    implementation:
      'function:["pg_catalog","bit"](pg_catalog."bit",pg_catalog.int4,pg_catalog.bool)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.\\"bit\\"","pg_catalog.int4"]': {
    source: 'pg_catalog."bit"',
    target: 'pg_catalog.int4',
    implementation: 'function:["pg_catalog","int4"](pg_catalog."bit")',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.\\"bit\\"","pg_catalog.int8"]': {
    source: 'pg_catalog."bit"',
    target: 'pg_catalog.int8',
    implementation: 'function:["pg_catalog","int8"](pg_catalog."bit")',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.\\"bit\\"","pg_catalog.varbit"]': {
    source: 'pg_catalog."bit"',
    target: 'pg_catalog.varbit',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.\\"char\\"","pg_catalog.\\"varchar\\""]': {
    source: 'pg_catalog."char"',
    target: 'pg_catalog."varchar"',
    implementation: 'function:["pg_catalog","text"](pg_catalog."char")',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.\\"char\\"","pg_catalog.bpchar"]': {
    source: 'pg_catalog."char"',
    target: 'pg_catalog.bpchar',
    implementation: 'function:["pg_catalog","bpchar"](pg_catalog."char")',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.\\"char\\"","pg_catalog.int4"]': {
    source: 'pg_catalog."char"',
    target: 'pg_catalog.int4',
    implementation: 'function:["pg_catalog","int4"](pg_catalog."char")',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.\\"char\\"","pg_catalog.text"]': {
    source: 'pg_catalog."char"',
    target: 'pg_catalog.text',
    implementation: 'function:["pg_catalog","text"](pg_catalog."char")',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.\\"interval\\"","pg_catalog.\\"interval\\""]': {
    source: 'pg_catalog."interval"',
    target: 'pg_catalog."interval"',
    implementation: 'function:["pg_catalog","interval"](pg_catalog."interval",pg_catalog.int4)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.\\"interval\\"","pg_catalog.\\"time\\""]': {
    source: 'pg_catalog."interval"',
    target: 'pg_catalog."time"',
    implementation: 'function:["pg_catalog","time"](pg_catalog."interval")',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.\\"json\\"","pg_catalog.jsonb"]': {
    source: 'pg_catalog."json"',
    target: 'pg_catalog.jsonb',
    implementation: null,
    context: 'a',
    method: 'i',
  },
  '["pg_catalog.\\"numeric\\"","pg_catalog.\\"numeric\\""]': {
    source: 'pg_catalog."numeric"',
    target: 'pg_catalog."numeric"',
    implementation: 'function:["pg_catalog","numeric"](pg_catalog."numeric",pg_catalog.int4)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.\\"numeric\\"","pg_catalog.float4"]': {
    source: 'pg_catalog."numeric"',
    target: 'pg_catalog.float4',
    implementation: 'function:["pg_catalog","float4"](pg_catalog."numeric")',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.\\"numeric\\"","pg_catalog.float8"]': {
    source: 'pg_catalog."numeric"',
    target: 'pg_catalog.float8',
    implementation: 'function:["pg_catalog","float8"](pg_catalog."numeric")',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.\\"numeric\\"","pg_catalog.int2"]': {
    source: 'pg_catalog."numeric"',
    target: 'pg_catalog.int2',
    implementation: 'function:["pg_catalog","int2"](pg_catalog."numeric")',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.\\"numeric\\"","pg_catalog.int4"]': {
    source: 'pg_catalog."numeric"',
    target: 'pg_catalog.int4',
    implementation: 'function:["pg_catalog","int4"](pg_catalog."numeric")',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.\\"numeric\\"","pg_catalog.int8"]': {
    source: 'pg_catalog."numeric"',
    target: 'pg_catalog.int8',
    implementation: 'function:["pg_catalog","int8"](pg_catalog."numeric")',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.\\"numeric\\"","pg_catalog.money"]': {
    source: 'pg_catalog."numeric"',
    target: 'pg_catalog.money',
    implementation: 'function:["pg_catalog","money"](pg_catalog."numeric")',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.\\"time\\"","pg_catalog.\\"interval\\""]': {
    source: 'pg_catalog."time"',
    target: 'pg_catalog."interval"',
    implementation: 'function:["pg_catalog","interval"](pg_catalog."time")',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.\\"time\\"","pg_catalog.\\"time\\""]': {
    source: 'pg_catalog."time"',
    target: 'pg_catalog."time"',
    implementation: 'function:["pg_catalog","time"](pg_catalog."time",pg_catalog.int4)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.\\"time\\"","pg_catalog.timetz"]': {
    source: 'pg_catalog."time"',
    target: 'pg_catalog.timetz',
    implementation: 'function:["pg_catalog","timetz"](pg_catalog."time")',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.\\"timestamp\\"","pg_catalog.\\"time\\""]': {
    source: 'pg_catalog."timestamp"',
    target: 'pg_catalog."time"',
    implementation: 'function:["pg_catalog","time"](pg_catalog."timestamp")',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.\\"timestamp\\"","pg_catalog.\\"timestamp\\""]': {
    source: 'pg_catalog."timestamp"',
    target: 'pg_catalog."timestamp"',
    implementation: 'function:["pg_catalog","timestamp"](pg_catalog."timestamp",pg_catalog.int4)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.\\"timestamp\\"","pg_catalog.date"]': {
    source: 'pg_catalog."timestamp"',
    target: 'pg_catalog.date',
    implementation: 'function:["pg_catalog","date"](pg_catalog."timestamp")',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.\\"timestamp\\"","pg_catalog.timestamptz"]': {
    source: 'pg_catalog."timestamp"',
    target: 'pg_catalog.timestamptz',
    implementation: 'function:["pg_catalog","timestamptz"](pg_catalog."timestamp")',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.\\"varchar\\"","pg_catalog.\\"char\\""]': {
    source: 'pg_catalog."varchar"',
    target: 'pg_catalog."char"',
    implementation: 'function:["pg_catalog","char"](pg_catalog.text)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.\\"varchar\\"","pg_catalog.\\"varchar\\""]': {
    source: 'pg_catalog."varchar"',
    target: 'pg_catalog."varchar"',
    implementation:
      'function:["pg_catalog","varchar"](pg_catalog."varchar",pg_catalog.int4,pg_catalog.bool)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.\\"varchar\\"","pg_catalog.bpchar"]': {
    source: 'pg_catalog."varchar"',
    target: 'pg_catalog.bpchar',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.\\"varchar\\"","pg_catalog.name"]': {
    source: 'pg_catalog."varchar"',
    target: 'pg_catalog.name',
    implementation: 'function:["pg_catalog","name"](pg_catalog."varchar")',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.\\"varchar\\"","pg_catalog.regclass"]': {
    source: 'pg_catalog."varchar"',
    target: 'pg_catalog.regclass',
    implementation: 'function:["pg_catalog","regclass"](pg_catalog.text)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.\\"varchar\\"","pg_catalog.text"]': {
    source: 'pg_catalog."varchar"',
    target: 'pg_catalog.text',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.\\"varchar\\"","pg_catalog.xml"]': {
    source: 'pg_catalog."varchar"',
    target: 'pg_catalog.xml',
    implementation: 'function:["pg_catalog","xml"](pg_catalog.text)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.bool","pg_catalog.\\"varchar\\""]': {
    source: 'pg_catalog.bool',
    target: 'pg_catalog."varchar"',
    implementation: 'function:["pg_catalog","text"](pg_catalog.bool)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.bool","pg_catalog.bpchar"]': {
    source: 'pg_catalog.bool',
    target: 'pg_catalog.bpchar',
    implementation: 'function:["pg_catalog","text"](pg_catalog.bool)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.bool","pg_catalog.int4"]': {
    source: 'pg_catalog.bool',
    target: 'pg_catalog.int4',
    implementation: 'function:["pg_catalog","int4"](pg_catalog.bool)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.bool","pg_catalog.text"]': {
    source: 'pg_catalog.bool',
    target: 'pg_catalog.text',
    implementation: 'function:["pg_catalog","text"](pg_catalog.bool)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.box","pg_catalog.circle"]': {
    source: 'pg_catalog.box',
    target: 'pg_catalog.circle',
    implementation: 'function:["pg_catalog","circle"](pg_catalog.box)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.box","pg_catalog.lseg"]': {
    source: 'pg_catalog.box',
    target: 'pg_catalog.lseg',
    implementation: 'function:["pg_catalog","lseg"](pg_catalog.box)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.box","pg_catalog.point"]': {
    source: 'pg_catalog.box',
    target: 'pg_catalog.point',
    implementation: 'function:["pg_catalog","point"](pg_catalog.box)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.box","pg_catalog.polygon"]': {
    source: 'pg_catalog.box',
    target: 'pg_catalog.polygon',
    implementation: 'function:["pg_catalog","polygon"](pg_catalog.box)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.bpchar","pg_catalog.\\"char\\""]': {
    source: 'pg_catalog.bpchar',
    target: 'pg_catalog."char"',
    implementation: 'function:["pg_catalog","char"](pg_catalog.text)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.bpchar","pg_catalog.\\"varchar\\""]': {
    source: 'pg_catalog.bpchar',
    target: 'pg_catalog."varchar"',
    implementation: 'function:["pg_catalog","text"](pg_catalog.bpchar)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.bpchar","pg_catalog.bpchar"]': {
    source: 'pg_catalog.bpchar',
    target: 'pg_catalog.bpchar',
    implementation:
      'function:["pg_catalog","bpchar"](pg_catalog.bpchar,pg_catalog.int4,pg_catalog.bool)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.bpchar","pg_catalog.name"]': {
    source: 'pg_catalog.bpchar',
    target: 'pg_catalog.name',
    implementation: 'function:["pg_catalog","name"](pg_catalog.bpchar)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.bpchar","pg_catalog.text"]': {
    source: 'pg_catalog.bpchar',
    target: 'pg_catalog.text',
    implementation: 'function:["pg_catalog","text"](pg_catalog.bpchar)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.bpchar","pg_catalog.xml"]': {
    source: 'pg_catalog.bpchar',
    target: 'pg_catalog.xml',
    implementation: 'function:["pg_catalog","xml"](pg_catalog.text)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.bytea","pg_catalog.int2"]': {
    source: 'pg_catalog.bytea',
    target: 'pg_catalog.int2',
    implementation: 'function:["pg_catalog","int2"](pg_catalog.bytea)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.bytea","pg_catalog.int4"]': {
    source: 'pg_catalog.bytea',
    target: 'pg_catalog.int4',
    implementation: 'function:["pg_catalog","int4"](pg_catalog.bytea)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.bytea","pg_catalog.int8"]': {
    source: 'pg_catalog.bytea',
    target: 'pg_catalog.int8',
    implementation: 'function:["pg_catalog","int8"](pg_catalog.bytea)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.cidr","pg_catalog.\\"varchar\\""]': {
    source: 'pg_catalog.cidr',
    target: 'pg_catalog."varchar"',
    implementation: 'function:["pg_catalog","text"](pg_catalog.inet)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.cidr","pg_catalog.bpchar"]': {
    source: 'pg_catalog.cidr',
    target: 'pg_catalog.bpchar',
    implementation: 'function:["pg_catalog","text"](pg_catalog.inet)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.cidr","pg_catalog.inet"]': {
    source: 'pg_catalog.cidr',
    target: 'pg_catalog.inet',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.cidr","pg_catalog.text"]': {
    source: 'pg_catalog.cidr',
    target: 'pg_catalog.text',
    implementation: 'function:["pg_catalog","text"](pg_catalog.inet)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.circle","pg_catalog.box"]': {
    source: 'pg_catalog.circle',
    target: 'pg_catalog.box',
    implementation: 'function:["pg_catalog","box"](pg_catalog.circle)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.circle","pg_catalog.point"]': {
    source: 'pg_catalog.circle',
    target: 'pg_catalog.point',
    implementation: 'function:["pg_catalog","point"](pg_catalog.circle)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.circle","pg_catalog.polygon"]': {
    source: 'pg_catalog.circle',
    target: 'pg_catalog.polygon',
    implementation: 'function:["pg_catalog","polygon"](pg_catalog.circle)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.date","pg_catalog.\\"timestamp\\""]': {
    source: 'pg_catalog.date',
    target: 'pg_catalog."timestamp"',
    implementation: 'function:["pg_catalog","timestamp"](pg_catalog.date)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.date","pg_catalog.timestamptz"]': {
    source: 'pg_catalog.date',
    target: 'pg_catalog.timestamptz',
    implementation: 'function:["pg_catalog","timestamptz"](pg_catalog.date)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.daterange","pg_catalog.datemultirange"]': {
    source: 'pg_catalog.daterange',
    target: 'pg_catalog.datemultirange',
    implementation: 'function:["pg_catalog","datemultirange"](pg_catalog.daterange)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.float4","pg_catalog.\\"numeric\\""]': {
    source: 'pg_catalog.float4',
    target: 'pg_catalog."numeric"',
    implementation: 'function:["pg_catalog","numeric"](pg_catalog.float4)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.float4","pg_catalog.float8"]': {
    source: 'pg_catalog.float4',
    target: 'pg_catalog.float8',
    implementation: 'function:["pg_catalog","float8"](pg_catalog.float4)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.float4","pg_catalog.int2"]': {
    source: 'pg_catalog.float4',
    target: 'pg_catalog.int2',
    implementation: 'function:["pg_catalog","int2"](pg_catalog.float4)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.float4","pg_catalog.int4"]': {
    source: 'pg_catalog.float4',
    target: 'pg_catalog.int4',
    implementation: 'function:["pg_catalog","int4"](pg_catalog.float4)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.float4","pg_catalog.int8"]': {
    source: 'pg_catalog.float4',
    target: 'pg_catalog.int8',
    implementation: 'function:["pg_catalog","int8"](pg_catalog.float4)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.float8","pg_catalog.\\"numeric\\""]': {
    source: 'pg_catalog.float8',
    target: 'pg_catalog."numeric"',
    implementation: 'function:["pg_catalog","numeric"](pg_catalog.float8)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.float8","pg_catalog.float4"]': {
    source: 'pg_catalog.float8',
    target: 'pg_catalog.float4',
    implementation: 'function:["pg_catalog","float4"](pg_catalog.float8)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.float8","pg_catalog.int2"]': {
    source: 'pg_catalog.float8',
    target: 'pg_catalog.int2',
    implementation: 'function:["pg_catalog","int2"](pg_catalog.float8)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.float8","pg_catalog.int4"]': {
    source: 'pg_catalog.float8',
    target: 'pg_catalog.int4',
    implementation: 'function:["pg_catalog","int4"](pg_catalog.float8)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.float8","pg_catalog.int8"]': {
    source: 'pg_catalog.float8',
    target: 'pg_catalog.int8',
    implementation: 'function:["pg_catalog","int8"](pg_catalog.float8)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.inet","pg_catalog.\\"varchar\\""]': {
    source: 'pg_catalog.inet',
    target: 'pg_catalog."varchar"',
    implementation: 'function:["pg_catalog","text"](pg_catalog.inet)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.inet","pg_catalog.bpchar"]': {
    source: 'pg_catalog.inet',
    target: 'pg_catalog.bpchar',
    implementation: 'function:["pg_catalog","text"](pg_catalog.inet)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.inet","pg_catalog.cidr"]': {
    source: 'pg_catalog.inet',
    target: 'pg_catalog.cidr',
    implementation: 'function:["pg_catalog","cidr"](pg_catalog.inet)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.inet","pg_catalog.text"]': {
    source: 'pg_catalog.inet',
    target: 'pg_catalog.text',
    implementation: 'function:["pg_catalog","text"](pg_catalog.inet)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.int2","pg_catalog.\\"numeric\\""]': {
    source: 'pg_catalog.int2',
    target: 'pg_catalog."numeric"',
    implementation: 'function:["pg_catalog","numeric"](pg_catalog.int2)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int2","pg_catalog.bytea"]': {
    source: 'pg_catalog.int2',
    target: 'pg_catalog.bytea',
    implementation: 'function:["pg_catalog","bytea"](pg_catalog.int2)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.int2","pg_catalog.float4"]': {
    source: 'pg_catalog.int2',
    target: 'pg_catalog.float4',
    implementation: 'function:["pg_catalog","float4"](pg_catalog.int2)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int2","pg_catalog.float8"]': {
    source: 'pg_catalog.int2',
    target: 'pg_catalog.float8',
    implementation: 'function:["pg_catalog","float8"](pg_catalog.int2)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int2","pg_catalog.int4"]': {
    source: 'pg_catalog.int2',
    target: 'pg_catalog.int4',
    implementation: 'function:["pg_catalog","int4"](pg_catalog.int2)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int2","pg_catalog.int8"]': {
    source: 'pg_catalog.int2',
    target: 'pg_catalog.int8',
    implementation: 'function:["pg_catalog","int8"](pg_catalog.int2)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int2","pg_catalog.oid"]': {
    source: 'pg_catalog.int2',
    target: 'pg_catalog.oid',
    implementation: 'function:["pg_catalog","int4"](pg_catalog.int2)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int2","pg_catalog.regclass"]': {
    source: 'pg_catalog.int2',
    target: 'pg_catalog.regclass',
    implementation: 'function:["pg_catalog","int4"](pg_catalog.int2)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int2","pg_catalog.regcollation"]': {
    source: 'pg_catalog.int2',
    target: 'pg_catalog.regcollation',
    implementation: 'function:["pg_catalog","int4"](pg_catalog.int2)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int2","pg_catalog.regconfig"]': {
    source: 'pg_catalog.int2',
    target: 'pg_catalog.regconfig',
    implementation: 'function:["pg_catalog","int4"](pg_catalog.int2)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int2","pg_catalog.regdictionary"]': {
    source: 'pg_catalog.int2',
    target: 'pg_catalog.regdictionary',
    implementation: 'function:["pg_catalog","int4"](pg_catalog.int2)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int2","pg_catalog.regnamespace"]': {
    source: 'pg_catalog.int2',
    target: 'pg_catalog.regnamespace',
    implementation: 'function:["pg_catalog","int4"](pg_catalog.int2)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int2","pg_catalog.regoper"]': {
    source: 'pg_catalog.int2',
    target: 'pg_catalog.regoper',
    implementation: 'function:["pg_catalog","int4"](pg_catalog.int2)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int2","pg_catalog.regoperator"]': {
    source: 'pg_catalog.int2',
    target: 'pg_catalog.regoperator',
    implementation: 'function:["pg_catalog","int4"](pg_catalog.int2)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int2","pg_catalog.regproc"]': {
    source: 'pg_catalog.int2',
    target: 'pg_catalog.regproc',
    implementation: 'function:["pg_catalog","int4"](pg_catalog.int2)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int2","pg_catalog.regprocedure"]': {
    source: 'pg_catalog.int2',
    target: 'pg_catalog.regprocedure',
    implementation: 'function:["pg_catalog","int4"](pg_catalog.int2)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int2","pg_catalog.regrole"]': {
    source: 'pg_catalog.int2',
    target: 'pg_catalog.regrole',
    implementation: 'function:["pg_catalog","int4"](pg_catalog.int2)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int2","pg_catalog.regtype"]': {
    source: 'pg_catalog.int2',
    target: 'pg_catalog.regtype',
    implementation: 'function:["pg_catalog","int4"](pg_catalog.int2)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int4","pg_catalog.\\"bit\\""]': {
    source: 'pg_catalog.int4',
    target: 'pg_catalog."bit"',
    implementation: 'function:["pg_catalog","bit"](pg_catalog.int4,pg_catalog.int4)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.int4","pg_catalog.\\"char\\""]': {
    source: 'pg_catalog.int4',
    target: 'pg_catalog."char"',
    implementation: 'function:["pg_catalog","char"](pg_catalog.int4)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.int4","pg_catalog.\\"numeric\\""]': {
    source: 'pg_catalog.int4',
    target: 'pg_catalog."numeric"',
    implementation: 'function:["pg_catalog","numeric"](pg_catalog.int4)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int4","pg_catalog.bool"]': {
    source: 'pg_catalog.int4',
    target: 'pg_catalog.bool',
    implementation: 'function:["pg_catalog","bool"](pg_catalog.int4)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.int4","pg_catalog.bytea"]': {
    source: 'pg_catalog.int4',
    target: 'pg_catalog.bytea',
    implementation: 'function:["pg_catalog","bytea"](pg_catalog.int4)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.int4","pg_catalog.float4"]': {
    source: 'pg_catalog.int4',
    target: 'pg_catalog.float4',
    implementation: 'function:["pg_catalog","float4"](pg_catalog.int4)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int4","pg_catalog.float8"]': {
    source: 'pg_catalog.int4',
    target: 'pg_catalog.float8',
    implementation: 'function:["pg_catalog","float8"](pg_catalog.int4)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int4","pg_catalog.int2"]': {
    source: 'pg_catalog.int4',
    target: 'pg_catalog.int2',
    implementation: 'function:["pg_catalog","int2"](pg_catalog.int4)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.int4","pg_catalog.int8"]': {
    source: 'pg_catalog.int4',
    target: 'pg_catalog.int8',
    implementation: 'function:["pg_catalog","int8"](pg_catalog.int4)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int4","pg_catalog.money"]': {
    source: 'pg_catalog.int4',
    target: 'pg_catalog.money',
    implementation: 'function:["pg_catalog","money"](pg_catalog.int4)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.int4","pg_catalog.oid"]': {
    source: 'pg_catalog.int4',
    target: 'pg_catalog.oid',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.int4","pg_catalog.regclass"]': {
    source: 'pg_catalog.int4',
    target: 'pg_catalog.regclass',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.int4","pg_catalog.regcollation"]': {
    source: 'pg_catalog.int4',
    target: 'pg_catalog.regcollation',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.int4","pg_catalog.regconfig"]': {
    source: 'pg_catalog.int4',
    target: 'pg_catalog.regconfig',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.int4","pg_catalog.regdictionary"]': {
    source: 'pg_catalog.int4',
    target: 'pg_catalog.regdictionary',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.int4","pg_catalog.regnamespace"]': {
    source: 'pg_catalog.int4',
    target: 'pg_catalog.regnamespace',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.int4","pg_catalog.regoper"]': {
    source: 'pg_catalog.int4',
    target: 'pg_catalog.regoper',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.int4","pg_catalog.regoperator"]': {
    source: 'pg_catalog.int4',
    target: 'pg_catalog.regoperator',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.int4","pg_catalog.regproc"]': {
    source: 'pg_catalog.int4',
    target: 'pg_catalog.regproc',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.int4","pg_catalog.regprocedure"]': {
    source: 'pg_catalog.int4',
    target: 'pg_catalog.regprocedure',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.int4","pg_catalog.regrole"]': {
    source: 'pg_catalog.int4',
    target: 'pg_catalog.regrole',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.int4","pg_catalog.regtype"]': {
    source: 'pg_catalog.int4',
    target: 'pg_catalog.regtype',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.int4range","pg_catalog.int4multirange"]': {
    source: 'pg_catalog.int4range',
    target: 'pg_catalog.int4multirange',
    implementation: 'function:["pg_catalog","int4multirange"](pg_catalog.int4range)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.int8","pg_catalog.\\"bit\\""]': {
    source: 'pg_catalog.int8',
    target: 'pg_catalog."bit"',
    implementation: 'function:["pg_catalog","bit"](pg_catalog.int8,pg_catalog.int4)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.int8","pg_catalog.\\"numeric\\""]': {
    source: 'pg_catalog.int8',
    target: 'pg_catalog."numeric"',
    implementation: 'function:["pg_catalog","numeric"](pg_catalog.int8)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int8","pg_catalog.bytea"]': {
    source: 'pg_catalog.int8',
    target: 'pg_catalog.bytea',
    implementation: 'function:["pg_catalog","bytea"](pg_catalog.int8)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.int8","pg_catalog.float4"]': {
    source: 'pg_catalog.int8',
    target: 'pg_catalog.float4',
    implementation: 'function:["pg_catalog","float4"](pg_catalog.int8)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int8","pg_catalog.float8"]': {
    source: 'pg_catalog.int8',
    target: 'pg_catalog.float8',
    implementation: 'function:["pg_catalog","float8"](pg_catalog.int8)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int8","pg_catalog.int2"]': {
    source: 'pg_catalog.int8',
    target: 'pg_catalog.int2',
    implementation: 'function:["pg_catalog","int2"](pg_catalog.int8)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.int8","pg_catalog.int4"]': {
    source: 'pg_catalog.int8',
    target: 'pg_catalog.int4',
    implementation: 'function:["pg_catalog","int4"](pg_catalog.int8)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.int8","pg_catalog.money"]': {
    source: 'pg_catalog.int8',
    target: 'pg_catalog.money',
    implementation: 'function:["pg_catalog","money"](pg_catalog.int8)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.int8","pg_catalog.oid"]': {
    source: 'pg_catalog.int8',
    target: 'pg_catalog.oid',
    implementation: 'function:["pg_catalog","oid"](pg_catalog.int8)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int8","pg_catalog.regclass"]': {
    source: 'pg_catalog.int8',
    target: 'pg_catalog.regclass',
    implementation: 'function:["pg_catalog","oid"](pg_catalog.int8)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int8","pg_catalog.regcollation"]': {
    source: 'pg_catalog.int8',
    target: 'pg_catalog.regcollation',
    implementation: 'function:["pg_catalog","oid"](pg_catalog.int8)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int8","pg_catalog.regconfig"]': {
    source: 'pg_catalog.int8',
    target: 'pg_catalog.regconfig',
    implementation: 'function:["pg_catalog","oid"](pg_catalog.int8)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int8","pg_catalog.regdictionary"]': {
    source: 'pg_catalog.int8',
    target: 'pg_catalog.regdictionary',
    implementation: 'function:["pg_catalog","oid"](pg_catalog.int8)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int8","pg_catalog.regnamespace"]': {
    source: 'pg_catalog.int8',
    target: 'pg_catalog.regnamespace',
    implementation: 'function:["pg_catalog","oid"](pg_catalog.int8)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int8","pg_catalog.regoper"]': {
    source: 'pg_catalog.int8',
    target: 'pg_catalog.regoper',
    implementation: 'function:["pg_catalog","oid"](pg_catalog.int8)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int8","pg_catalog.regoperator"]': {
    source: 'pg_catalog.int8',
    target: 'pg_catalog.regoperator',
    implementation: 'function:["pg_catalog","oid"](pg_catalog.int8)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int8","pg_catalog.regproc"]': {
    source: 'pg_catalog.int8',
    target: 'pg_catalog.regproc',
    implementation: 'function:["pg_catalog","oid"](pg_catalog.int8)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int8","pg_catalog.regprocedure"]': {
    source: 'pg_catalog.int8',
    target: 'pg_catalog.regprocedure',
    implementation: 'function:["pg_catalog","oid"](pg_catalog.int8)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int8","pg_catalog.regrole"]': {
    source: 'pg_catalog.int8',
    target: 'pg_catalog.regrole',
    implementation: 'function:["pg_catalog","oid"](pg_catalog.int8)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int8","pg_catalog.regtype"]': {
    source: 'pg_catalog.int8',
    target: 'pg_catalog.regtype',
    implementation: 'function:["pg_catalog","oid"](pg_catalog.int8)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.int8range","pg_catalog.int8multirange"]': {
    source: 'pg_catalog.int8range',
    target: 'pg_catalog.int8multirange',
    implementation: 'function:["pg_catalog","int8multirange"](pg_catalog.int8range)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.jsonb","pg_catalog.\\"json\\""]': {
    source: 'pg_catalog.jsonb',
    target: 'pg_catalog."json"',
    implementation: null,
    context: 'a',
    method: 'i',
  },
  '["pg_catalog.jsonb","pg_catalog.\\"numeric\\""]': {
    source: 'pg_catalog.jsonb',
    target: 'pg_catalog."numeric"',
    implementation: 'function:["pg_catalog","numeric"](pg_catalog.jsonb)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.jsonb","pg_catalog.bool"]': {
    source: 'pg_catalog.jsonb',
    target: 'pg_catalog.bool',
    implementation: 'function:["pg_catalog","bool"](pg_catalog.jsonb)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.jsonb","pg_catalog.float4"]': {
    source: 'pg_catalog.jsonb',
    target: 'pg_catalog.float4',
    implementation: 'function:["pg_catalog","float4"](pg_catalog.jsonb)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.jsonb","pg_catalog.float8"]': {
    source: 'pg_catalog.jsonb',
    target: 'pg_catalog.float8',
    implementation: 'function:["pg_catalog","float8"](pg_catalog.jsonb)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.jsonb","pg_catalog.int2"]': {
    source: 'pg_catalog.jsonb',
    target: 'pg_catalog.int2',
    implementation: 'function:["pg_catalog","int2"](pg_catalog.jsonb)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.jsonb","pg_catalog.int4"]': {
    source: 'pg_catalog.jsonb',
    target: 'pg_catalog.int4',
    implementation: 'function:["pg_catalog","int4"](pg_catalog.jsonb)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.jsonb","pg_catalog.int8"]': {
    source: 'pg_catalog.jsonb',
    target: 'pg_catalog.int8',
    implementation: 'function:["pg_catalog","int8"](pg_catalog.jsonb)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.lseg","pg_catalog.point"]': {
    source: 'pg_catalog.lseg',
    target: 'pg_catalog.point',
    implementation: 'function:["pg_catalog","point"](pg_catalog.lseg)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.macaddr","pg_catalog.macaddr8"]': {
    source: 'pg_catalog.macaddr',
    target: 'pg_catalog.macaddr8',
    implementation: 'function:["pg_catalog","macaddr8"](pg_catalog.macaddr)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.macaddr8","pg_catalog.macaddr"]': {
    source: 'pg_catalog.macaddr8',
    target: 'pg_catalog.macaddr',
    implementation: 'function:["pg_catalog","macaddr"](pg_catalog.macaddr8)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.money","pg_catalog.\\"numeric\\""]': {
    source: 'pg_catalog.money',
    target: 'pg_catalog."numeric"',
    implementation: 'function:["pg_catalog","numeric"](pg_catalog.money)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.name","pg_catalog.\\"varchar\\""]': {
    source: 'pg_catalog.name',
    target: 'pg_catalog."varchar"',
    implementation: 'function:["pg_catalog","varchar"](pg_catalog.name)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.name","pg_catalog.bpchar"]': {
    source: 'pg_catalog.name',
    target: 'pg_catalog.bpchar',
    implementation: 'function:["pg_catalog","bpchar"](pg_catalog.name)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.name","pg_catalog.text"]': {
    source: 'pg_catalog.name',
    target: 'pg_catalog.text',
    implementation: 'function:["pg_catalog","text"](pg_catalog.name)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.numrange","pg_catalog.nummultirange"]': {
    source: 'pg_catalog.numrange',
    target: 'pg_catalog.nummultirange',
    implementation: 'function:["pg_catalog","nummultirange"](pg_catalog.numrange)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.oid","pg_catalog.int4"]': {
    source: 'pg_catalog.oid',
    target: 'pg_catalog.int4',
    implementation: null,
    context: 'a',
    method: 'b',
  },
  '["pg_catalog.oid","pg_catalog.int8"]': {
    source: 'pg_catalog.oid',
    target: 'pg_catalog.int8',
    implementation: 'function:["pg_catalog","int8"](pg_catalog.oid)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.oid","pg_catalog.regclass"]': {
    source: 'pg_catalog.oid',
    target: 'pg_catalog.regclass',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.oid","pg_catalog.regcollation"]': {
    source: 'pg_catalog.oid',
    target: 'pg_catalog.regcollation',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.oid","pg_catalog.regconfig"]': {
    source: 'pg_catalog.oid',
    target: 'pg_catalog.regconfig',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.oid","pg_catalog.regdictionary"]': {
    source: 'pg_catalog.oid',
    target: 'pg_catalog.regdictionary',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.oid","pg_catalog.regnamespace"]': {
    source: 'pg_catalog.oid',
    target: 'pg_catalog.regnamespace',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.oid","pg_catalog.regoper"]': {
    source: 'pg_catalog.oid',
    target: 'pg_catalog.regoper',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.oid","pg_catalog.regoperator"]': {
    source: 'pg_catalog.oid',
    target: 'pg_catalog.regoperator',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.oid","pg_catalog.regproc"]': {
    source: 'pg_catalog.oid',
    target: 'pg_catalog.regproc',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.oid","pg_catalog.regprocedure"]': {
    source: 'pg_catalog.oid',
    target: 'pg_catalog.regprocedure',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.oid","pg_catalog.regrole"]': {
    source: 'pg_catalog.oid',
    target: 'pg_catalog.regrole',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.oid","pg_catalog.regtype"]': {
    source: 'pg_catalog.oid',
    target: 'pg_catalog.regtype',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.path","pg_catalog.polygon"]': {
    source: 'pg_catalog.path',
    target: 'pg_catalog.polygon',
    implementation: 'function:["pg_catalog","polygon"](pg_catalog.path)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.pg_dependencies","pg_catalog.bytea"]': {
    source: 'pg_catalog.pg_dependencies',
    target: 'pg_catalog.bytea',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.pg_dependencies","pg_catalog.text"]': {
    source: 'pg_catalog.pg_dependencies',
    target: 'pg_catalog.text',
    implementation: null,
    context: 'i',
    method: 'i',
  },
  '["pg_catalog.pg_mcv_list","pg_catalog.bytea"]': {
    source: 'pg_catalog.pg_mcv_list',
    target: 'pg_catalog.bytea',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.pg_mcv_list","pg_catalog.text"]': {
    source: 'pg_catalog.pg_mcv_list',
    target: 'pg_catalog.text',
    implementation: null,
    context: 'i',
    method: 'i',
  },
  '["pg_catalog.pg_ndistinct","pg_catalog.bytea"]': {
    source: 'pg_catalog.pg_ndistinct',
    target: 'pg_catalog.bytea',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.pg_ndistinct","pg_catalog.text"]': {
    source: 'pg_catalog.pg_ndistinct',
    target: 'pg_catalog.text',
    implementation: null,
    context: 'i',
    method: 'i',
  },
  '["pg_catalog.pg_node_tree","pg_catalog.text"]': {
    source: 'pg_catalog.pg_node_tree',
    target: 'pg_catalog.text',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.point","pg_catalog.box"]': {
    source: 'pg_catalog.point',
    target: 'pg_catalog.box',
    implementation: 'function:["pg_catalog","box"](pg_catalog.point)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.polygon","pg_catalog.box"]': {
    source: 'pg_catalog.polygon',
    target: 'pg_catalog.box',
    implementation: 'function:["pg_catalog","box"](pg_catalog.polygon)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.polygon","pg_catalog.circle"]': {
    source: 'pg_catalog.polygon',
    target: 'pg_catalog.circle',
    implementation: 'function:["pg_catalog","circle"](pg_catalog.polygon)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.polygon","pg_catalog.path"]': {
    source: 'pg_catalog.polygon',
    target: 'pg_catalog.path',
    implementation: 'function:["pg_catalog","path"](pg_catalog.polygon)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.polygon","pg_catalog.point"]': {
    source: 'pg_catalog.polygon',
    target: 'pg_catalog.point',
    implementation: 'function:["pg_catalog","point"](pg_catalog.polygon)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.regclass","pg_catalog.int4"]': {
    source: 'pg_catalog.regclass',
    target: 'pg_catalog.int4',
    implementation: null,
    context: 'a',
    method: 'b',
  },
  '["pg_catalog.regclass","pg_catalog.int8"]': {
    source: 'pg_catalog.regclass',
    target: 'pg_catalog.int8',
    implementation: 'function:["pg_catalog","int8"](pg_catalog.oid)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.regclass","pg_catalog.oid"]': {
    source: 'pg_catalog.regclass',
    target: 'pg_catalog.oid',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.regcollation","pg_catalog.int4"]': {
    source: 'pg_catalog.regcollation',
    target: 'pg_catalog.int4',
    implementation: null,
    context: 'a',
    method: 'b',
  },
  '["pg_catalog.regcollation","pg_catalog.int8"]': {
    source: 'pg_catalog.regcollation',
    target: 'pg_catalog.int8',
    implementation: 'function:["pg_catalog","int8"](pg_catalog.oid)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.regcollation","pg_catalog.oid"]': {
    source: 'pg_catalog.regcollation',
    target: 'pg_catalog.oid',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.regconfig","pg_catalog.int4"]': {
    source: 'pg_catalog.regconfig',
    target: 'pg_catalog.int4',
    implementation: null,
    context: 'a',
    method: 'b',
  },
  '["pg_catalog.regconfig","pg_catalog.int8"]': {
    source: 'pg_catalog.regconfig',
    target: 'pg_catalog.int8',
    implementation: 'function:["pg_catalog","int8"](pg_catalog.oid)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.regconfig","pg_catalog.oid"]': {
    source: 'pg_catalog.regconfig',
    target: 'pg_catalog.oid',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.regdictionary","pg_catalog.int4"]': {
    source: 'pg_catalog.regdictionary',
    target: 'pg_catalog.int4',
    implementation: null,
    context: 'a',
    method: 'b',
  },
  '["pg_catalog.regdictionary","pg_catalog.int8"]': {
    source: 'pg_catalog.regdictionary',
    target: 'pg_catalog.int8',
    implementation: 'function:["pg_catalog","int8"](pg_catalog.oid)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.regdictionary","pg_catalog.oid"]': {
    source: 'pg_catalog.regdictionary',
    target: 'pg_catalog.oid',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.regnamespace","pg_catalog.int4"]': {
    source: 'pg_catalog.regnamespace',
    target: 'pg_catalog.int4',
    implementation: null,
    context: 'a',
    method: 'b',
  },
  '["pg_catalog.regnamespace","pg_catalog.int8"]': {
    source: 'pg_catalog.regnamespace',
    target: 'pg_catalog.int8',
    implementation: 'function:["pg_catalog","int8"](pg_catalog.oid)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.regnamespace","pg_catalog.oid"]': {
    source: 'pg_catalog.regnamespace',
    target: 'pg_catalog.oid',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.regoper","pg_catalog.int4"]': {
    source: 'pg_catalog.regoper',
    target: 'pg_catalog.int4',
    implementation: null,
    context: 'a',
    method: 'b',
  },
  '["pg_catalog.regoper","pg_catalog.int8"]': {
    source: 'pg_catalog.regoper',
    target: 'pg_catalog.int8',
    implementation: 'function:["pg_catalog","int8"](pg_catalog.oid)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.regoper","pg_catalog.oid"]': {
    source: 'pg_catalog.regoper',
    target: 'pg_catalog.oid',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.regoper","pg_catalog.regoperator"]': {
    source: 'pg_catalog.regoper',
    target: 'pg_catalog.regoperator',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.regoperator","pg_catalog.int4"]': {
    source: 'pg_catalog.regoperator',
    target: 'pg_catalog.int4',
    implementation: null,
    context: 'a',
    method: 'b',
  },
  '["pg_catalog.regoperator","pg_catalog.int8"]': {
    source: 'pg_catalog.regoperator',
    target: 'pg_catalog.int8',
    implementation: 'function:["pg_catalog","int8"](pg_catalog.oid)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.regoperator","pg_catalog.oid"]': {
    source: 'pg_catalog.regoperator',
    target: 'pg_catalog.oid',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.regoperator","pg_catalog.regoper"]': {
    source: 'pg_catalog.regoperator',
    target: 'pg_catalog.regoper',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.regproc","pg_catalog.int4"]': {
    source: 'pg_catalog.regproc',
    target: 'pg_catalog.int4',
    implementation: null,
    context: 'a',
    method: 'b',
  },
  '["pg_catalog.regproc","pg_catalog.int8"]': {
    source: 'pg_catalog.regproc',
    target: 'pg_catalog.int8',
    implementation: 'function:["pg_catalog","int8"](pg_catalog.oid)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.regproc","pg_catalog.oid"]': {
    source: 'pg_catalog.regproc',
    target: 'pg_catalog.oid',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.regproc","pg_catalog.regprocedure"]': {
    source: 'pg_catalog.regproc',
    target: 'pg_catalog.regprocedure',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.regprocedure","pg_catalog.int4"]': {
    source: 'pg_catalog.regprocedure',
    target: 'pg_catalog.int4',
    implementation: null,
    context: 'a',
    method: 'b',
  },
  '["pg_catalog.regprocedure","pg_catalog.int8"]': {
    source: 'pg_catalog.regprocedure',
    target: 'pg_catalog.int8',
    implementation: 'function:["pg_catalog","int8"](pg_catalog.oid)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.regprocedure","pg_catalog.oid"]': {
    source: 'pg_catalog.regprocedure',
    target: 'pg_catalog.oid',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.regprocedure","pg_catalog.regproc"]': {
    source: 'pg_catalog.regprocedure',
    target: 'pg_catalog.regproc',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.regrole","pg_catalog.int4"]': {
    source: 'pg_catalog.regrole',
    target: 'pg_catalog.int4',
    implementation: null,
    context: 'a',
    method: 'b',
  },
  '["pg_catalog.regrole","pg_catalog.int8"]': {
    source: 'pg_catalog.regrole',
    target: 'pg_catalog.int8',
    implementation: 'function:["pg_catalog","int8"](pg_catalog.oid)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.regrole","pg_catalog.oid"]': {
    source: 'pg_catalog.regrole',
    target: 'pg_catalog.oid',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.regtype","pg_catalog.int4"]': {
    source: 'pg_catalog.regtype',
    target: 'pg_catalog.int4',
    implementation: null,
    context: 'a',
    method: 'b',
  },
  '["pg_catalog.regtype","pg_catalog.int8"]': {
    source: 'pg_catalog.regtype',
    target: 'pg_catalog.int8',
    implementation: 'function:["pg_catalog","int8"](pg_catalog.oid)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.regtype","pg_catalog.oid"]': {
    source: 'pg_catalog.regtype',
    target: 'pg_catalog.oid',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.text","pg_catalog.\\"char\\""]': {
    source: 'pg_catalog.text',
    target: 'pg_catalog."char"',
    implementation: 'function:["pg_catalog","char"](pg_catalog.text)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.text","pg_catalog.\\"varchar\\""]': {
    source: 'pg_catalog.text',
    target: 'pg_catalog."varchar"',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.text","pg_catalog.bpchar"]': {
    source: 'pg_catalog.text',
    target: 'pg_catalog.bpchar',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.text","pg_catalog.name"]': {
    source: 'pg_catalog.text',
    target: 'pg_catalog.name',
    implementation: 'function:["pg_catalog","name"](pg_catalog.text)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.text","pg_catalog.regclass"]': {
    source: 'pg_catalog.text',
    target: 'pg_catalog.regclass',
    implementation: 'function:["pg_catalog","regclass"](pg_catalog.text)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.text","pg_catalog.xml"]': {
    source: 'pg_catalog.text',
    target: 'pg_catalog.xml',
    implementation: 'function:["pg_catalog","xml"](pg_catalog.text)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.timestamptz","pg_catalog.\\"time\\""]': {
    source: 'pg_catalog.timestamptz',
    target: 'pg_catalog."time"',
    implementation: 'function:["pg_catalog","time"](pg_catalog.timestamptz)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.timestamptz","pg_catalog.\\"timestamp\\""]': {
    source: 'pg_catalog.timestamptz',
    target: 'pg_catalog."timestamp"',
    implementation: 'function:["pg_catalog","timestamp"](pg_catalog.timestamptz)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.timestamptz","pg_catalog.date"]': {
    source: 'pg_catalog.timestamptz',
    target: 'pg_catalog.date',
    implementation: 'function:["pg_catalog","date"](pg_catalog.timestamptz)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.timestamptz","pg_catalog.timestamptz"]': {
    source: 'pg_catalog.timestamptz',
    target: 'pg_catalog.timestamptz',
    implementation: 'function:["pg_catalog","timestamptz"](pg_catalog.timestamptz,pg_catalog.int4)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.timestamptz","pg_catalog.timetz"]': {
    source: 'pg_catalog.timestamptz',
    target: 'pg_catalog.timetz',
    implementation: 'function:["pg_catalog","timetz"](pg_catalog.timestamptz)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.timetz","pg_catalog.\\"time\\""]': {
    source: 'pg_catalog.timetz',
    target: 'pg_catalog."time"',
    implementation: 'function:["pg_catalog","time"](pg_catalog.timetz)',
    context: 'a',
    method: 'f',
  },
  '["pg_catalog.timetz","pg_catalog.timetz"]': {
    source: 'pg_catalog.timetz',
    target: 'pg_catalog.timetz',
    implementation: 'function:["pg_catalog","timetz"](pg_catalog.timetz,pg_catalog.int4)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.tsrange","pg_catalog.tsmultirange"]': {
    source: 'pg_catalog.tsrange',
    target: 'pg_catalog.tsmultirange',
    implementation: 'function:["pg_catalog","tsmultirange"](pg_catalog.tsrange)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.tstzrange","pg_catalog.tstzmultirange"]': {
    source: 'pg_catalog.tstzrange',
    target: 'pg_catalog.tstzmultirange',
    implementation: 'function:["pg_catalog","tstzmultirange"](pg_catalog.tstzrange)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.varbit","pg_catalog.\\"bit\\""]': {
    source: 'pg_catalog.varbit',
    target: 'pg_catalog."bit"',
    implementation: null,
    context: 'i',
    method: 'b',
  },
  '["pg_catalog.varbit","pg_catalog.varbit"]': {
    source: 'pg_catalog.varbit',
    target: 'pg_catalog.varbit',
    implementation:
      'function:["pg_catalog","varbit"](pg_catalog.varbit,pg_catalog.int4,pg_catalog.bool)',
    context: 'i',
    method: 'f',
  },
  '["pg_catalog.xid8","pg_catalog.xid"]': {
    source: 'pg_catalog.xid8',
    target: 'pg_catalog.xid',
    implementation: 'function:["pg_catalog","xid"](pg_catalog.xid8)',
    context: 'e',
    method: 'f',
  },
  '["pg_catalog.xml","pg_catalog.\\"varchar\\""]': {
    source: 'pg_catalog.xml',
    target: 'pg_catalog."varchar"',
    implementation: null,
    context: 'a',
    method: 'b',
  },
  '["pg_catalog.xml","pg_catalog.bpchar"]': {
    source: 'pg_catalog.xml',
    target: 'pg_catalog.bpchar',
    implementation: null,
    context: 'a',
    method: 'b',
  },
  '["pg_catalog.xml","pg_catalog.text"]': {
    source: 'pg_catalog.xml',
    target: 'pg_catalog.text',
    implementation: null,
    context: 'a',
    method: 'b',
  },
} as const
