export const PG18_GENERIC = {
  'function:["pg_catalog","any_value_transfn"](pg_catalog.anyelement,pg_catalog.anyelement)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'any_value_transfn',
    args: ['pg_catalog.anyelement', 'pg_catalog.anyelement'],
    result: 'pg_catalog.anyelement',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","btrecordcmp"](pg_catalog.record,pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'btrecordcmp',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","btrecordimagecmp"](pg_catalog.record,pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'btrecordimagecmp',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","concat"](pg_catalog."any")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'concat',
    args: ['pg_catalog."any"'],
    result: 'pg_catalog.text',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: 'pg_catalog."any"',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","enum_cmp"](pg_catalog.anyenum,pg_catalog.anyenum)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'enum_cmp',
    args: ['pg_catalog.anyenum', 'pg_catalog.anyenum'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","enum_eq"](pg_catalog.anyenum,pg_catalog.anyenum)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'enum_eq',
    args: ['pg_catalog.anyenum', 'pg_catalog.anyenum'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","enum_first"](pg_catalog.anyenum)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'enum_first',
    args: ['pg_catalog.anyenum'],
    result: 'pg_catalog.anyenum',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","enum_ge"](pg_catalog.anyenum,pg_catalog.anyenum)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'enum_ge',
    args: ['pg_catalog.anyenum', 'pg_catalog.anyenum'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","enum_gt"](pg_catalog.anyenum,pg_catalog.anyenum)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'enum_gt',
    args: ['pg_catalog.anyenum', 'pg_catalog.anyenum'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","enum_larger"](pg_catalog.anyenum,pg_catalog.anyenum)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'enum_larger',
    args: ['pg_catalog.anyenum', 'pg_catalog.anyenum'],
    result: 'pg_catalog.anyenum',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","enum_last"](pg_catalog.anyenum)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'enum_last',
    args: ['pg_catalog.anyenum'],
    result: 'pg_catalog.anyenum',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","enum_le"](pg_catalog.anyenum,pg_catalog.anyenum)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'enum_le',
    args: ['pg_catalog.anyenum', 'pg_catalog.anyenum'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","enum_lt"](pg_catalog.anyenum,pg_catalog.anyenum)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'enum_lt',
    args: ['pg_catalog.anyenum', 'pg_catalog.anyenum'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","enum_ne"](pg_catalog.anyenum,pg_catalog.anyenum)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'enum_ne',
    args: ['pg_catalog.anyenum', 'pg_catalog.anyenum'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","enum_smaller"](pg_catalog.anyenum,pg_catalog.anyenum)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'enum_smaller',
    args: ['pg_catalog.anyenum', 'pg_catalog.anyenum'],
    result: 'pg_catalog.anyenum',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hash_record"](pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hash_record',
    args: ['pg_catalog.record'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashenum"](pg_catalog.anyenum)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashenum',
    args: ['pg_catalog.anyenum'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","num_nonnulls"](pg_catalog."any")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'num_nonnulls',
    args: ['pg_catalog."any"'],
    result: 'pg_catalog.int4',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: 'pg_catalog."any"',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","num_nulls"](pg_catalog."any")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'num_nulls',
    args: ['pg_catalog."any"'],
    result: 'pg_catalog.int4',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: 'pg_catalog."any"',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_available_extension_versions"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_available_extension_versions',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_available_extensions"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_available_extensions',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_available_wal_summaries"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_available_wal_summaries',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_backup_stop"](pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_backup_stop',
    args: ['pg_catalog.bool'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 1,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_collation_for"](pg_catalog."any")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_collation_for',
    args: ['pg_catalog."any"'],
    result: 'pg_catalog.text',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_column_compression"](pg_catalog."any")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_column_compression',
    args: ['pg_catalog."any"'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_column_size"](pg_catalog."any")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_column_size',
    args: ['pg_catalog."any"'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_config"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_config',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_control_checkpoint"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_control_checkpoint',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_control_init"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_control_init',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_control_recovery"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_control_recovery',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_control_system"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_control_system',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_cursor"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_cursor',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_event_trigger_ddl_commands"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_event_trigger_ddl_commands',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_event_trigger_dropped_objects"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_event_trigger_dropped_objects',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_get_aios"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_get_aios',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_get_backend_memory_contexts"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_get_backend_memory_contexts',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_get_catalog_foreign_keys"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_get_catalog_foreign_keys',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_get_keywords"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_get_keywords',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_get_loaded_modules"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_get_loaded_modules',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_get_replication_slots"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_get_replication_slots',
    args: [],
    result: 'pg_catalog.record',
    strict: false,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_get_shmem_allocations"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_get_shmem_allocations',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_get_shmem_allocations_numa"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_get_shmem_allocations_numa',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_get_wait_events"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_get_wait_events',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_get_wal_resource_managers"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_get_wal_resource_managers',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_get_wal_summarizer_state"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_get_wal_summarizer_state',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_hba_file_rules"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_hba_file_rules',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_ident_file_mappings"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_ident_file_mappings',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_last_committed_xact"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_last_committed_xact',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_lock_status"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lock_status',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_ls_archive_statusdir"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_ls_archive_statusdir',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_ls_logdir"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_ls_logdir',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_ls_logicalmapdir"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_ls_logicalmapdir',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_ls_logicalsnapdir"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_ls_logicalsnapdir',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_ls_summariesdir"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_ls_summariesdir',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_ls_tmpdir"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_ls_tmpdir',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_ls_waldir"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_ls_waldir',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_mcv_list_items"](pg_catalog.pg_mcv_list)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_mcv_list_items',
    args: ['pg_catalog.pg_mcv_list'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_prepared_statement"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_prepared_statement',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_prepared_xact"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_prepared_xact',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_restore_attribute_stats"](pg_catalog."any")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_restore_attribute_stats',
    args: ['pg_catalog."any"'],
    result: 'pg_catalog.bool',
    strict: false,
    volatility: 'v',
    returnsSet: false,
    variadic: 'pg_catalog."any"',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_restore_relation_stats"](pg_catalog."any")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_restore_relation_stats',
    args: ['pg_catalog."any"'],
    result: 'pg_catalog.bool',
    strict: false,
    volatility: 'v',
    returnsSet: false,
    variadic: 'pg_catalog."any"',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_show_all_file_settings"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_show_all_file_settings',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_show_all_settings"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_show_all_settings',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_show_replication_origin_status"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_show_replication_origin_status',
    args: [],
    result: 'pg_catalog.record',
    strict: false,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_stat_get_archiver"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_stat_get_archiver',
    args: [],
    result: 'pg_catalog.record',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_stat_get_io"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_stat_get_io',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_stat_get_recovery_prefetch"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_stat_get_recovery_prefetch',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_stat_get_slru"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_stat_get_slru',
    args: [],
    result: 'pg_catalog.record',
    strict: false,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_stat_get_wal"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_stat_get_wal',
    args: [],
    result: 'pg_catalog.record',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_stat_get_wal_receiver"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_stat_get_wal_receiver',
    args: [],
    result: 'pg_catalog.record',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_stat_get_wal_senders"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_stat_get_wal_senders',
    args: [],
    result: 'pg_catalog.record',
    strict: false,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_timezone_abbrevs_abbrevs"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_timezone_abbrevs_abbrevs',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_timezone_abbrevs_zone"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_timezone_abbrevs_zone',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_timezone_names"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_timezone_names',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","quote_literal"](pg_catalog.anyelement)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'quote_literal',
    args: ['pg_catalog.anyelement'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","quote_nullable"](pg_catalog.anyelement)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'quote_nullable',
    args: ['pg_catalog.anyelement'],
    result: 'pg_catalog.text',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","record_eq"](pg_catalog.record,pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'record_eq',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","record_ge"](pg_catalog.record,pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'record_ge',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","record_gt"](pg_catalog.record,pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'record_gt',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","record_image_eq"](pg_catalog.record,pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'record_image_eq',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","record_image_ge"](pg_catalog.record,pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'record_image_ge',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","record_image_gt"](pg_catalog.record,pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'record_image_gt',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","record_image_le"](pg_catalog.record,pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'record_image_le',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","record_image_lt"](pg_catalog.record,pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'record_image_lt',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","record_image_ne"](pg_catalog.record,pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'record_image_ne',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","record_larger"](pg_catalog.record,pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'record_larger',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","record_le"](pg_catalog.record,pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'record_le',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","record_lt"](pg_catalog.record,pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'record_lt',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","record_ne"](pg_catalog.record,pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'record_ne',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","record_smaller"](pg_catalog.record,pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'record_smaller',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'operator:["pg_catalog","*<"](pg_catalog.record,pg_catalog.record)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '*<',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    left: 'pg_catalog.record',
    right: 'pg_catalog.record',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","*<="](pg_catalog.record,pg_catalog.record)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '*<=',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    left: 'pg_catalog.record',
    right: 'pg_catalog.record',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","*<>"](pg_catalog.record,pg_catalog.record)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '*<>',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    left: 'pg_catalog.record',
    right: 'pg_catalog.record',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","*="](pg_catalog.record,pg_catalog.record)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '*=',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    left: 'pg_catalog.record',
    right: 'pg_catalog.record',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","*>"](pg_catalog.record,pg_catalog.record)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '*>',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    left: 'pg_catalog.record',
    right: 'pg_catalog.record',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","*>="](pg_catalog.record,pg_catalog.record)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '*>=',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    left: 'pg_catalog.record',
    right: 'pg_catalog.record',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.anyenum,pg_catalog.anyenum)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    args: ['pg_catalog.anyenum', 'pg_catalog.anyenum'],
    left: 'pg_catalog.anyenum',
    right: 'pg_catalog.anyenum',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.record,pg_catalog.record)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    left: 'pg_catalog.record',
    right: 'pg_catalog.record',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.anyenum,pg_catalog.anyenum)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    args: ['pg_catalog.anyenum', 'pg_catalog.anyenum'],
    left: 'pg_catalog.anyenum',
    right: 'pg_catalog.anyenum',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.record,pg_catalog.record)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    left: 'pg_catalog.record',
    right: 'pg_catalog.record',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.anyenum,pg_catalog.anyenum)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    args: ['pg_catalog.anyenum', 'pg_catalog.anyenum'],
    left: 'pg_catalog.anyenum',
    right: 'pg_catalog.anyenum',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.record,pg_catalog.record)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    left: 'pg_catalog.record',
    right: 'pg_catalog.record',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.anyenum,pg_catalog.anyenum)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    args: ['pg_catalog.anyenum', 'pg_catalog.anyenum'],
    left: 'pg_catalog.anyenum',
    right: 'pg_catalog.anyenum',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.record,pg_catalog.record)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    left: 'pg_catalog.record',
    right: 'pg_catalog.record',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.anyenum,pg_catalog.anyenum)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    args: ['pg_catalog.anyenum', 'pg_catalog.anyenum'],
    left: 'pg_catalog.anyenum',
    right: 'pg_catalog.anyenum',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.record,pg_catalog.record)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    left: 'pg_catalog.record',
    right: 'pg_catalog.record',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.anyenum,pg_catalog.anyenum)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    args: ['pg_catalog.anyenum', 'pg_catalog.anyenum'],
    left: 'pg_catalog.anyenum',
    right: 'pg_catalog.anyenum',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.record,pg_catalog.record)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    left: 'pg_catalog.record',
    right: 'pg_catalog.record',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
} as const
