export const PG18_GENERIC = {
  'function:["pg_catalog","any_value_transfn"](pg_catalog.anyelement,pg_catalog.anyelement)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'any_value_transfn',
    rustName: 'sql__pg_catalog__any_value_transfn__8dki',
    args: ['pg_catalog.anyelement', 'pg_catalog.anyelement'],
    result: 'pg_catalog.anyelement',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","btrecordcmp"](pg_catalog.record,pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'btrecordcmp',
    rustName: 'sql__pg_catalog__btrecordcmp__m4or',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","btrecordimagecmp"](pg_catalog.record,pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'btrecordimagecmp',
    rustName: 'sql__pg_catalog__btrecordimagecmp__nom7',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","concat"](pg_catalog."any")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'concat',
    rustName: 'sql__pg_catalog__concat__ca4i',
    args: ['pg_catalog."any"'],
    result: 'pg_catalog.text',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: 'pg_catalog."any"',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","enum_cmp"](pg_catalog.anyenum,pg_catalog.anyenum)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'enum_cmp',
    rustName: 'sql__pg_catalog__enum_cmp__hjt6',
    args: ['pg_catalog.anyenum', 'pg_catalog.anyenum'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","enum_eq"](pg_catalog.anyenum,pg_catalog.anyenum)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'enum_eq',
    rustName: 'sql__pg_catalog__enum_eq__w63e',
    args: ['pg_catalog.anyenum', 'pg_catalog.anyenum'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","enum_first"](pg_catalog.anyenum)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'enum_first',
    rustName: 'sql__pg_catalog__enum_first__e14q',
    args: ['pg_catalog.anyenum'],
    result: 'pg_catalog.anyenum',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","enum_ge"](pg_catalog.anyenum,pg_catalog.anyenum)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'enum_ge',
    rustName: 'sql__pg_catalog__enum_ge__0b8h',
    args: ['pg_catalog.anyenum', 'pg_catalog.anyenum'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","enum_gt"](pg_catalog.anyenum,pg_catalog.anyenum)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'enum_gt',
    rustName: 'sql__pg_catalog__enum_gt__1jsh',
    args: ['pg_catalog.anyenum', 'pg_catalog.anyenum'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","enum_larger"](pg_catalog.anyenum,pg_catalog.anyenum)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'enum_larger',
    rustName: 'sql__pg_catalog__enum_larger__em2s',
    args: ['pg_catalog.anyenum', 'pg_catalog.anyenum'],
    result: 'pg_catalog.anyenum',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","enum_last"](pg_catalog.anyenum)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'enum_last',
    rustName: 'sql__pg_catalog__enum_last__73mc',
    args: ['pg_catalog.anyenum'],
    result: 'pg_catalog.anyenum',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","enum_le"](pg_catalog.anyenum,pg_catalog.anyenum)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'enum_le',
    rustName: 'sql__pg_catalog__enum_le__xl1v',
    args: ['pg_catalog.anyenum', 'pg_catalog.anyenum'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","enum_lt"](pg_catalog.anyenum,pg_catalog.anyenum)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'enum_lt',
    rustName: 'sql__pg_catalog__enum_lt__5af2',
    args: ['pg_catalog.anyenum', 'pg_catalog.anyenum'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","enum_ne"](pg_catalog.anyenum,pg_catalog.anyenum)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'enum_ne',
    rustName: 'sql__pg_catalog__enum_ne__tph2',
    args: ['pg_catalog.anyenum', 'pg_catalog.anyenum'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","enum_smaller"](pg_catalog.anyenum,pg_catalog.anyenum)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'enum_smaller',
    rustName: 'sql__pg_catalog__enum_smaller__whhx',
    args: ['pg_catalog.anyenum', 'pg_catalog.anyenum'],
    result: 'pg_catalog.anyenum',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hash_record"](pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hash_record',
    rustName: 'sql__pg_catalog__hash_record__5xrm',
    args: ['pg_catalog.record'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashenum"](pg_catalog.anyenum)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashenum',
    rustName: 'sql__pg_catalog__hashenum__z4zk',
    args: ['pg_catalog.anyenum'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","num_nonnulls"](pg_catalog."any")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'num_nonnulls',
    rustName: 'sql__pg_catalog__num_nonnulls__y0jf',
    args: ['pg_catalog."any"'],
    result: 'pg_catalog.int4',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: 'pg_catalog."any"',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","num_nulls"](pg_catalog."any")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'num_nulls',
    rustName: 'sql__pg_catalog__num_nulls__jx40',
    args: ['pg_catalog."any"'],
    result: 'pg_catalog.int4',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: 'pg_catalog."any"',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_available_extension_versions"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_available_extension_versions',
    rustName: 'sql__pg_catalog__pg_available_extension_versions__laum',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_available_extensions"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_available_extensions',
    rustName: 'sql__pg_catalog__pg_available_extensions__wkle',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_available_wal_summaries"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_available_wal_summaries',
    rustName: 'sql__pg_catalog__pg_available_wal_summaries__wthp',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_backup_stop"](pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_backup_stop',
    rustName: 'sql__pg_catalog__pg_backup_stop__cdmh',
    args: ['pg_catalog.bool'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 1,
    defaultArguments: 'true',
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_collation_for"](pg_catalog."any")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_collation_for',
    rustName: 'sql__pg_catalog__pg_collation_for__808q',
    args: ['pg_catalog."any"'],
    result: 'pg_catalog.text',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_column_compression"](pg_catalog."any")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_column_compression',
    rustName: 'sql__pg_catalog__pg_column_compression__rbpo',
    args: ['pg_catalog."any"'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_column_size"](pg_catalog."any")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_column_size',
    rustName: 'sql__pg_catalog__pg_column_size__5z69',
    args: ['pg_catalog."any"'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_config"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_config',
    rustName: 'sql__pg_catalog__pg_config__48jv',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_control_checkpoint"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_control_checkpoint',
    rustName: 'sql__pg_catalog__pg_control_checkpoint__w95x',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_control_init"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_control_init',
    rustName: 'sql__pg_catalog__pg_control_init__8ojz',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_control_recovery"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_control_recovery',
    rustName: 'sql__pg_catalog__pg_control_recovery__rpwn',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_control_system"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_control_system',
    rustName: 'sql__pg_catalog__pg_control_system__zg4s',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_cursor"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_cursor',
    rustName: 'sql__pg_catalog__pg_cursor__did9',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_event_trigger_ddl_commands"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_event_trigger_ddl_commands',
    rustName: 'sql__pg_catalog__pg_event_trigger_ddl_commands__izlx',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_event_trigger_dropped_objects"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_event_trigger_dropped_objects',
    rustName: 'sql__pg_catalog__pg_event_trigger_dropped_objects__1mun',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_get_aios"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_get_aios',
    rustName: 'sql__pg_catalog__pg_get_aios__bvc9',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_get_backend_memory_contexts"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_get_backend_memory_contexts',
    rustName: 'sql__pg_catalog__pg_get_backend_memory_contexts__cicy',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_get_catalog_foreign_keys"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_get_catalog_foreign_keys',
    rustName: 'sql__pg_catalog__pg_get_catalog_foreign_keys__oytl',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_get_keywords"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_get_keywords',
    rustName: 'sql__pg_catalog__pg_get_keywords__kfzt',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_get_loaded_modules"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_get_loaded_modules',
    rustName: 'sql__pg_catalog__pg_get_loaded_modules__vu13',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_get_replication_slots"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_get_replication_slots',
    rustName: 'sql__pg_catalog__pg_get_replication_slots__dn51',
    args: [],
    result: 'pg_catalog.record',
    strict: false,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_get_shmem_allocations"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_get_shmem_allocations',
    rustName: 'sql__pg_catalog__pg_get_shmem_allocations__q07d',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_get_shmem_allocations_numa"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_get_shmem_allocations_numa',
    rustName: 'sql__pg_catalog__pg_get_shmem_allocations_numa__v0mu',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_get_wait_events"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_get_wait_events',
    rustName: 'sql__pg_catalog__pg_get_wait_events__eb5j',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_get_wal_resource_managers"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_get_wal_resource_managers',
    rustName: 'sql__pg_catalog__pg_get_wal_resource_managers__qlvz',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_get_wal_summarizer_state"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_get_wal_summarizer_state',
    rustName: 'sql__pg_catalog__pg_get_wal_summarizer_state__c2gy',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_hba_file_rules"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_hba_file_rules',
    rustName: 'sql__pg_catalog__pg_hba_file_rules__0ipf',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_ident_file_mappings"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_ident_file_mappings',
    rustName: 'sql__pg_catalog__pg_ident_file_mappings__t65r',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_last_committed_xact"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_last_committed_xact',
    rustName: 'sql__pg_catalog__pg_last_committed_xact__oqp1',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_lock_status"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lock_status',
    rustName: 'sql__pg_catalog__pg_lock_status__da6b',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_ls_archive_statusdir"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_ls_archive_statusdir',
    rustName: 'sql__pg_catalog__pg_ls_archive_statusdir__raw0',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_ls_logdir"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_ls_logdir',
    rustName: 'sql__pg_catalog__pg_ls_logdir__152z',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_ls_logicalmapdir"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_ls_logicalmapdir',
    rustName: 'sql__pg_catalog__pg_ls_logicalmapdir__55m6',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_ls_logicalsnapdir"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_ls_logicalsnapdir',
    rustName: 'sql__pg_catalog__pg_ls_logicalsnapdir__i5b8',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_ls_summariesdir"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_ls_summariesdir',
    rustName: 'sql__pg_catalog__pg_ls_summariesdir__rr6c',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_ls_tmpdir"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_ls_tmpdir',
    rustName: 'sql__pg_catalog__pg_ls_tmpdir__fu4l',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_ls_waldir"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_ls_waldir',
    rustName: 'sql__pg_catalog__pg_ls_waldir__s3ld',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_mcv_list_items"](pg_catalog.pg_mcv_list)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_mcv_list_items',
    rustName: 'sql__pg_catalog__pg_mcv_list_items__cc14',
    args: ['pg_catalog.pg_mcv_list'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_prepared_statement"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_prepared_statement',
    rustName: 'sql__pg_catalog__pg_prepared_statement__xagl',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_prepared_xact"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_prepared_xact',
    rustName: 'sql__pg_catalog__pg_prepared_xact__j5v2',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_restore_attribute_stats"](pg_catalog."any")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_restore_attribute_stats',
    rustName: 'sql__pg_catalog__pg_restore_attribute_stats__9upu',
    args: ['pg_catalog."any"'],
    result: 'pg_catalog.bool',
    strict: false,
    volatility: 'v',
    returnsSet: false,
    variadic: 'pg_catalog."any"',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_restore_relation_stats"](pg_catalog."any")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_restore_relation_stats',
    rustName: 'sql__pg_catalog__pg_restore_relation_stats__npym',
    args: ['pg_catalog."any"'],
    result: 'pg_catalog.bool',
    strict: false,
    volatility: 'v',
    returnsSet: false,
    variadic: 'pg_catalog."any"',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_show_all_file_settings"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_show_all_file_settings',
    rustName: 'sql__pg_catalog__pg_show_all_file_settings__g5hv',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_show_all_settings"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_show_all_settings',
    rustName: 'sql__pg_catalog__pg_show_all_settings__206x',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_show_replication_origin_status"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_show_replication_origin_status',
    rustName: 'sql__pg_catalog__pg_show_replication_origin_status__nb1h',
    args: [],
    result: 'pg_catalog.record',
    strict: false,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_stat_get_archiver"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_stat_get_archiver',
    rustName: 'sql__pg_catalog__pg_stat_get_archiver__uzxx',
    args: [],
    result: 'pg_catalog.record',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_stat_get_io"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_stat_get_io',
    rustName: 'sql__pg_catalog__pg_stat_get_io__iqs4',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_stat_get_recovery_prefetch"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_stat_get_recovery_prefetch',
    rustName: 'sql__pg_catalog__pg_stat_get_recovery_prefetch__js6w',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_stat_get_slru"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_stat_get_slru',
    rustName: 'sql__pg_catalog__pg_stat_get_slru__067h',
    args: [],
    result: 'pg_catalog.record',
    strict: false,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_stat_get_wal"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_stat_get_wal',
    rustName: 'sql__pg_catalog__pg_stat_get_wal__s9tz',
    args: [],
    result: 'pg_catalog.record',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_stat_get_wal_receiver"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_stat_get_wal_receiver',
    rustName: 'sql__pg_catalog__pg_stat_get_wal_receiver__bq17',
    args: [],
    result: 'pg_catalog.record',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_stat_get_wal_senders"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_stat_get_wal_senders',
    rustName: 'sql__pg_catalog__pg_stat_get_wal_senders__tn4b',
    args: [],
    result: 'pg_catalog.record',
    strict: false,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_timezone_abbrevs_abbrevs"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_timezone_abbrevs_abbrevs',
    rustName: 'sql__pg_catalog__pg_timezone_abbrevs_abbrevs__r3hv',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_timezone_abbrevs_zone"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_timezone_abbrevs_zone',
    rustName: 'sql__pg_catalog__pg_timezone_abbrevs_zone__43xw',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_timezone_names"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_timezone_names',
    rustName: 'sql__pg_catalog__pg_timezone_names__5qpj',
    args: [],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","quote_literal"](pg_catalog.anyelement)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'quote_literal',
    rustName: 'sql__pg_catalog__quote_literal__i1gy',
    args: ['pg_catalog.anyelement'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","quote_nullable"](pg_catalog.anyelement)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'quote_nullable',
    rustName: 'sql__pg_catalog__quote_nullable__x3ga',
    args: ['pg_catalog.anyelement'],
    result: 'pg_catalog.text',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","record_eq"](pg_catalog.record,pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'record_eq',
    rustName: 'sql__pg_catalog__record_eq__rc7m',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","record_ge"](pg_catalog.record,pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'record_ge',
    rustName: 'sql__pg_catalog__record_ge__69vm',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","record_gt"](pg_catalog.record,pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'record_gt',
    rustName: 'sql__pg_catalog__record_gt__3rut',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","record_image_eq"](pg_catalog.record,pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'record_image_eq',
    rustName: 'sql__pg_catalog__record_image_eq__nr9y',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","record_image_ge"](pg_catalog.record,pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'record_image_ge',
    rustName: 'sql__pg_catalog__record_image_ge__2xz4',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","record_image_gt"](pg_catalog.record,pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'record_image_gt',
    rustName: 'sql__pg_catalog__record_image_gt__m168',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","record_image_le"](pg_catalog.record,pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'record_image_le',
    rustName: 'sql__pg_catalog__record_image_le__xsxq',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","record_image_lt"](pg_catalog.record,pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'record_image_lt',
    rustName: 'sql__pg_catalog__record_image_lt__3euz',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","record_image_ne"](pg_catalog.record,pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'record_image_ne',
    rustName: 'sql__pg_catalog__record_image_ne__hekg',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","record_larger"](pg_catalog.record,pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'record_larger',
    rustName: 'sql__pg_catalog__record_larger__hldj',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","record_le"](pg_catalog.record,pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'record_le',
    rustName: 'sql__pg_catalog__record_le__xg5r',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","record_lt"](pg_catalog.record,pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'record_lt',
    rustName: 'sql__pg_catalog__record_lt__393p',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","record_ne"](pg_catalog.record,pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'record_ne',
    rustName: 'sql__pg_catalog__record_ne__dmf7',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","record_smaller"](pg_catalog.record,pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'record_smaller',
    rustName: 'sql__pg_catalog__record_smaller__870l',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'operator:["pg_catalog","*<"](pg_catalog.record,pg_catalog.record)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '*<',
    implementation:
      'function:["pg_catalog","record_image_lt"](pg_catalog.record,pg_catalog.record)',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    left: 'pg_catalog.record',
    right: 'pg_catalog.record',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","*<="](pg_catalog.record,pg_catalog.record)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '*<=',
    implementation:
      'function:["pg_catalog","record_image_le"](pg_catalog.record,pg_catalog.record)',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    left: 'pg_catalog.record',
    right: 'pg_catalog.record',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","*<>"](pg_catalog.record,pg_catalog.record)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '*<>',
    implementation:
      'function:["pg_catalog","record_image_ne"](pg_catalog.record,pg_catalog.record)',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    left: 'pg_catalog.record',
    right: 'pg_catalog.record',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","*="](pg_catalog.record,pg_catalog.record)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '*=',
    implementation:
      'function:["pg_catalog","record_image_eq"](pg_catalog.record,pg_catalog.record)',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    left: 'pg_catalog.record',
    right: 'pg_catalog.record',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","*>"](pg_catalog.record,pg_catalog.record)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '*>',
    implementation:
      'function:["pg_catalog","record_image_gt"](pg_catalog.record,pg_catalog.record)',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    left: 'pg_catalog.record',
    right: 'pg_catalog.record',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","*>="](pg_catalog.record,pg_catalog.record)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '*>=',
    implementation:
      'function:["pg_catalog","record_image_ge"](pg_catalog.record,pg_catalog.record)',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    left: 'pg_catalog.record',
    right: 'pg_catalog.record',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.anyenum,pg_catalog.anyenum)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    implementation: 'function:["pg_catalog","enum_lt"](pg_catalog.anyenum,pg_catalog.anyenum)',
    args: ['pg_catalog.anyenum', 'pg_catalog.anyenum'],
    left: 'pg_catalog.anyenum',
    right: 'pg_catalog.anyenum',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.record,pg_catalog.record)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    implementation: 'function:["pg_catalog","record_lt"](pg_catalog.record,pg_catalog.record)',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    left: 'pg_catalog.record',
    right: 'pg_catalog.record',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.anyenum,pg_catalog.anyenum)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    implementation: 'function:["pg_catalog","enum_le"](pg_catalog.anyenum,pg_catalog.anyenum)',
    args: ['pg_catalog.anyenum', 'pg_catalog.anyenum'],
    left: 'pg_catalog.anyenum',
    right: 'pg_catalog.anyenum',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.record,pg_catalog.record)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    implementation: 'function:["pg_catalog","record_le"](pg_catalog.record,pg_catalog.record)',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    left: 'pg_catalog.record',
    right: 'pg_catalog.record',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.anyenum,pg_catalog.anyenum)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    implementation: 'function:["pg_catalog","enum_ne"](pg_catalog.anyenum,pg_catalog.anyenum)',
    args: ['pg_catalog.anyenum', 'pg_catalog.anyenum'],
    left: 'pg_catalog.anyenum',
    right: 'pg_catalog.anyenum',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.record,pg_catalog.record)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    implementation: 'function:["pg_catalog","record_ne"](pg_catalog.record,pg_catalog.record)',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    left: 'pg_catalog.record',
    right: 'pg_catalog.record',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.anyenum,pg_catalog.anyenum)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    implementation: 'function:["pg_catalog","enum_eq"](pg_catalog.anyenum,pg_catalog.anyenum)',
    args: ['pg_catalog.anyenum', 'pg_catalog.anyenum'],
    left: 'pg_catalog.anyenum',
    right: 'pg_catalog.anyenum',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.record,pg_catalog.record)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    implementation: 'function:["pg_catalog","record_eq"](pg_catalog.record,pg_catalog.record)',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    left: 'pg_catalog.record',
    right: 'pg_catalog.record',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.anyenum,pg_catalog.anyenum)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    implementation: 'function:["pg_catalog","enum_gt"](pg_catalog.anyenum,pg_catalog.anyenum)',
    args: ['pg_catalog.anyenum', 'pg_catalog.anyenum'],
    left: 'pg_catalog.anyenum',
    right: 'pg_catalog.anyenum',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.record,pg_catalog.record)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    implementation: 'function:["pg_catalog","record_gt"](pg_catalog.record,pg_catalog.record)',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    left: 'pg_catalog.record',
    right: 'pg_catalog.record',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.anyenum,pg_catalog.anyenum)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    implementation: 'function:["pg_catalog","enum_ge"](pg_catalog.anyenum,pg_catalog.anyenum)',
    args: ['pg_catalog.anyenum', 'pg_catalog.anyenum'],
    left: 'pg_catalog.anyenum',
    right: 'pg_catalog.anyenum',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.record,pg_catalog.record)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    implementation: 'function:["pg_catalog","record_ge"](pg_catalog.record,pg_catalog.record)',
    args: ['pg_catalog.record', 'pg_catalog.record'],
    left: 'pg_catalog.record',
    right: 'pg_catalog.record',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
} as const
