export const PG18_JSON = {
  'function:["pg_catalog","array_to_json"](pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_to_json',
    args: ['pg_catalog.anyarray'],
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_to_json"](pg_catalog.anyarray,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_to_json',
    args: ['pg_catalog.anyarray', 'pg_catalog.bool'],
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bool"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bool',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float4"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float4',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.float4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int2"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int2',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.int2',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int4"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int4',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int8"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int8',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_array_element"](pg_catalog."json",pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_array_element',
    args: ['pg_catalog."json"', 'pg_catalog.int4'],
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_array_element_text"](pg_catalog."json",pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_array_element_text',
    args: ['pg_catalog."json"', 'pg_catalog.int4'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_array_elements"](pg_catalog."json")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_array_elements',
    args: ['pg_catalog."json"'],
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_array_elements_text"](pg_catalog."json")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_array_elements_text',
    args: ['pg_catalog."json"'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_array_length"](pg_catalog."json")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_array_length',
    args: ['pg_catalog."json"'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_build_array"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_build_array',
    args: [],
    result: 'pg_catalog."json"',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_build_array"](pg_catalog."any")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_build_array',
    args: ['pg_catalog."any"'],
    result: 'pg_catalog."json"',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: 'pg_catalog."any"',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_build_object"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_build_object',
    args: [],
    result: 'pg_catalog."json"',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_build_object"](pg_catalog."any")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_build_object',
    args: ['pg_catalog."any"'],
    result: 'pg_catalog."json"',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: 'pg_catalog."any"',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_each"](pg_catalog."json")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_each',
    args: ['pg_catalog."json"'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_each_text"](pg_catalog."json")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_each_text',
    args: ['pg_catalog."json"'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_extract_path"](pg_catalog."json",pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_extract_path',
    args: ['pg_catalog."json"', 'pg_catalog._text'],
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: 'pg_catalog.text',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_extract_path_text"](pg_catalog."json",pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_extract_path_text',
    args: ['pg_catalog."json"', 'pg_catalog._text'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: 'pg_catalog.text',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_object"](pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_object',
    args: ['pg_catalog._text'],
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_object"](pg_catalog._text,pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_object',
    args: ['pg_catalog._text', 'pg_catalog._text'],
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_object_field"](pg_catalog."json",pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_object_field',
    args: ['pg_catalog."json"', 'pg_catalog.text'],
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_object_field_text"](pg_catalog."json",pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_object_field_text',
    args: ['pg_catalog."json"', 'pg_catalog.text'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_object_keys"](pg_catalog."json")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_object_keys',
    args: ['pg_catalog."json"'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_populate_record"](pg_catalog.anyelement,pg_catalog."json",pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'json_populate_record',
      args: ['pg_catalog.anyelement', 'pg_catalog."json"', 'pg_catalog.bool'],
      result: 'pg_catalog.anyelement',
      strict: false,
      volatility: 's',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 1,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","json_populate_recordset"](pg_catalog.anyelement,pg_catalog."json",pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'json_populate_recordset',
      args: ['pg_catalog.anyelement', 'pg_catalog."json"', 'pg_catalog.bool'],
      result: 'pg_catalog.anyelement',
      strict: false,
      volatility: 's',
      returnsSet: true,
      variadic: null,
      numArgDefaults: 1,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","json_strip_nulls"](pg_catalog."json",pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_strip_nulls',
    args: ['pg_catalog."json"', 'pg_catalog.bool'],
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 1,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_to_record"](pg_catalog."json")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_to_record',
    args: ['pg_catalog."json"'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_to_recordset"](pg_catalog."json")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_to_recordset',
    args: ['pg_catalog."json"'],
    result: 'pg_catalog.record',
    strict: false,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_typeof"](pg_catalog."json")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_typeof',
    args: ['pg_catalog."json"'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_array_element"](pg_catalog.jsonb,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_array_element',
    args: ['pg_catalog.jsonb', 'pg_catalog.int4'],
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_array_element_text"](pg_catalog.jsonb,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_array_element_text',
    args: ['pg_catalog.jsonb', 'pg_catalog.int4'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_array_elements"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_array_elements',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_array_elements_text"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_array_elements_text',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_array_length"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_array_length',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_build_array"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_build_array',
    args: [],
    result: 'pg_catalog.jsonb',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_build_array"](pg_catalog."any")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_build_array',
    args: ['pg_catalog."any"'],
    result: 'pg_catalog.jsonb',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: 'pg_catalog."any"',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_build_object"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_build_object',
    args: [],
    result: 'pg_catalog.jsonb',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_build_object"](pg_catalog."any")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_build_object',
    args: ['pg_catalog."any"'],
    result: 'pg_catalog.jsonb',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: 'pg_catalog."any"',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_cmp"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_cmp',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_concat"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_concat',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_contained"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_contained',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_contains"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_contains',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_delete"](pg_catalog.jsonb,pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_delete',
    args: ['pg_catalog.jsonb', 'pg_catalog._text'],
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: 'pg_catalog.text',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_delete"](pg_catalog.jsonb,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_delete',
    args: ['pg_catalog.jsonb', 'pg_catalog.int4'],
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_delete"](pg_catalog.jsonb,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_delete',
    args: ['pg_catalog.jsonb', 'pg_catalog.text'],
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_delete_path"](pg_catalog.jsonb,pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_delete_path',
    args: ['pg_catalog.jsonb', 'pg_catalog._text'],
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_each"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_each',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_each_text"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_each_text',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_eq"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_eq',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_exists"](pg_catalog.jsonb,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_exists',
    args: ['pg_catalog.jsonb', 'pg_catalog.text'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_exists_all"](pg_catalog.jsonb,pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_exists_all',
    args: ['pg_catalog.jsonb', 'pg_catalog._text'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_exists_any"](pg_catalog.jsonb,pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_exists_any',
    args: ['pg_catalog.jsonb', 'pg_catalog._text'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_extract_path"](pg_catalog.jsonb,pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_extract_path',
    args: ['pg_catalog.jsonb', 'pg_catalog._text'],
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: 'pg_catalog.text',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_extract_path_text"](pg_catalog.jsonb,pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_extract_path_text',
    args: ['pg_catalog.jsonb', 'pg_catalog._text'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: 'pg_catalog.text',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_ge"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_ge',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_gt"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_gt',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_hash"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_hash',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_hash_extended"](pg_catalog.jsonb,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_hash_extended',
    args: ['pg_catalog.jsonb', 'pg_catalog.int8'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_insert"](pg_catalog.jsonb,pg_catalog._text,pg_catalog.jsonb,pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'jsonb_insert',
      args: ['pg_catalog.jsonb', 'pg_catalog._text', 'pg_catalog.jsonb', 'pg_catalog.bool'],
      result: 'pg_catalog.jsonb',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 1,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","jsonb_le"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_le',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_lt"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_lt',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_ne"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_ne',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_object"](pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_object',
    args: ['pg_catalog._text'],
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_object"](pg_catalog._text,pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_object',
    args: ['pg_catalog._text', 'pg_catalog._text'],
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_object_field"](pg_catalog.jsonb,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_object_field',
    args: ['pg_catalog.jsonb', 'pg_catalog.text'],
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_object_field_text"](pg_catalog.jsonb,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_object_field_text',
    args: ['pg_catalog.jsonb', 'pg_catalog.text'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_object_keys"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_object_keys',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_path_exists"](pg_catalog.jsonb,pg_catalog.jsonpath,pg_catalog.jsonb,pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'jsonb_path_exists',
      args: ['pg_catalog.jsonb', 'pg_catalog.jsonpath', 'pg_catalog.jsonb', 'pg_catalog.bool'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 2,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","jsonb_path_exists_opr"](pg_catalog.jsonb,pg_catalog.jsonpath)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_path_exists_opr',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonpath'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_path_exists_tz"](pg_catalog.jsonb,pg_catalog.jsonpath,pg_catalog.jsonb,pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'jsonb_path_exists_tz',
      args: ['pg_catalog.jsonb', 'pg_catalog.jsonpath', 'pg_catalog.jsonb', 'pg_catalog.bool'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 's',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 2,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","jsonb_path_match"](pg_catalog.jsonb,pg_catalog.jsonpath,pg_catalog.jsonb,pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'jsonb_path_match',
      args: ['pg_catalog.jsonb', 'pg_catalog.jsonpath', 'pg_catalog.jsonb', 'pg_catalog.bool'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 2,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","jsonb_path_match_opr"](pg_catalog.jsonb,pg_catalog.jsonpath)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_path_match_opr',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonpath'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_path_match_tz"](pg_catalog.jsonb,pg_catalog.jsonpath,pg_catalog.jsonb,pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'jsonb_path_match_tz',
      args: ['pg_catalog.jsonb', 'pg_catalog.jsonpath', 'pg_catalog.jsonb', 'pg_catalog.bool'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 's',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 2,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","jsonb_path_query"](pg_catalog.jsonb,pg_catalog.jsonpath,pg_catalog.jsonb,pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'jsonb_path_query',
      args: ['pg_catalog.jsonb', 'pg_catalog.jsonpath', 'pg_catalog.jsonb', 'pg_catalog.bool'],
      result: 'pg_catalog.jsonb',
      strict: true,
      volatility: 'i',
      returnsSet: true,
      variadic: null,
      numArgDefaults: 2,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","jsonb_path_query_array"](pg_catalog.jsonb,pg_catalog.jsonpath,pg_catalog.jsonb,pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'jsonb_path_query_array',
      args: ['pg_catalog.jsonb', 'pg_catalog.jsonpath', 'pg_catalog.jsonb', 'pg_catalog.bool'],
      result: 'pg_catalog.jsonb',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 2,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","jsonb_path_query_array_tz"](pg_catalog.jsonb,pg_catalog.jsonpath,pg_catalog.jsonb,pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'jsonb_path_query_array_tz',
      args: ['pg_catalog.jsonb', 'pg_catalog.jsonpath', 'pg_catalog.jsonb', 'pg_catalog.bool'],
      result: 'pg_catalog.jsonb',
      strict: true,
      volatility: 's',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 2,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","jsonb_path_query_first"](pg_catalog.jsonb,pg_catalog.jsonpath,pg_catalog.jsonb,pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'jsonb_path_query_first',
      args: ['pg_catalog.jsonb', 'pg_catalog.jsonpath', 'pg_catalog.jsonb', 'pg_catalog.bool'],
      result: 'pg_catalog.jsonb',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 2,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","jsonb_path_query_first_tz"](pg_catalog.jsonb,pg_catalog.jsonpath,pg_catalog.jsonb,pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'jsonb_path_query_first_tz',
      args: ['pg_catalog.jsonb', 'pg_catalog.jsonpath', 'pg_catalog.jsonb', 'pg_catalog.bool'],
      result: 'pg_catalog.jsonb',
      strict: true,
      volatility: 's',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 2,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","jsonb_path_query_tz"](pg_catalog.jsonb,pg_catalog.jsonpath,pg_catalog.jsonb,pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'jsonb_path_query_tz',
      args: ['pg_catalog.jsonb', 'pg_catalog.jsonpath', 'pg_catalog.jsonb', 'pg_catalog.bool'],
      result: 'pg_catalog.jsonb',
      strict: true,
      volatility: 's',
      returnsSet: true,
      variadic: null,
      numArgDefaults: 2,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","jsonb_populate_record"](pg_catalog.anyelement,pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_populate_record',
    args: ['pg_catalog.anyelement', 'pg_catalog.jsonb'],
    result: 'pg_catalog.anyelement',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_populate_record_valid"](pg_catalog.anyelement,pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_populate_record_valid',
    args: ['pg_catalog.anyelement', 'pg_catalog.jsonb'],
    result: 'pg_catalog.bool',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_populate_recordset"](pg_catalog.anyelement,pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_populate_recordset',
    args: ['pg_catalog.anyelement', 'pg_catalog.jsonb'],
    result: 'pg_catalog.anyelement',
    strict: false,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_pretty"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_pretty',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_set"](pg_catalog.jsonb,pg_catalog._text,pg_catalog.jsonb,pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'jsonb_set',
      args: ['pg_catalog.jsonb', 'pg_catalog._text', 'pg_catalog.jsonb', 'pg_catalog.bool'],
      result: 'pg_catalog.jsonb',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 1,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","jsonb_set_lax"](pg_catalog.jsonb,pg_catalog._text,pg_catalog.jsonb,pg_catalog.bool,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'jsonb_set_lax',
      args: [
        'pg_catalog.jsonb',
        'pg_catalog._text',
        'pg_catalog.jsonb',
        'pg_catalog.bool',
        'pg_catalog.text',
      ],
      result: 'pg_catalog.jsonb',
      strict: false,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 2,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","jsonb_strip_nulls"](pg_catalog.jsonb,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_strip_nulls',
    args: ['pg_catalog.jsonb', 'pg_catalog.bool'],
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 1,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_to_record"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_to_record',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_to_recordset"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_to_recordset',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.record',
    strict: false,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_typeof"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_typeof',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","numeric"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'numeric',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog."numeric"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","row_to_json"](pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'row_to_json',
    args: ['pg_catalog.record'],
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","row_to_json"](pg_catalog.record,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'row_to_json',
    args: ['pg_catalog.record', 'pg_catalog.bool'],
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","to_json"](pg_catalog.anyelement)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'to_json',
    args: ['pg_catalog.anyelement'],
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","to_jsonb"](pg_catalog.anyelement)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'to_jsonb',
    args: ['pg_catalog.anyelement'],
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_headline"](pg_catalog."json",pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_headline',
    args: ['pg_catalog."json"', 'pg_catalog.tsquery'],
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_headline"](pg_catalog."json",pg_catalog.tsquery,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_headline',
    args: ['pg_catalog."json"', 'pg_catalog.tsquery', 'pg_catalog.text'],
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_headline"](pg_catalog.jsonb,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_headline',
    args: ['pg_catalog.jsonb', 'pg_catalog.tsquery'],
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_headline"](pg_catalog.jsonb,pg_catalog.tsquery,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_headline',
    args: ['pg_catalog.jsonb', 'pg_catalog.tsquery', 'pg_catalog.text'],
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_headline"](pg_catalog.regconfig,pg_catalog."json",pg_catalog.tsquery)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'ts_headline',
      args: ['pg_catalog.regconfig', 'pg_catalog."json"', 'pg_catalog.tsquery'],
      result: 'pg_catalog."json"',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","ts_headline"](pg_catalog.regconfig,pg_catalog."json",pg_catalog.tsquery,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'ts_headline',
      args: ['pg_catalog.regconfig', 'pg_catalog."json"', 'pg_catalog.tsquery', 'pg_catalog.text'],
      result: 'pg_catalog."json"',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","ts_headline"](pg_catalog.regconfig,pg_catalog.jsonb,pg_catalog.tsquery)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'ts_headline',
      args: ['pg_catalog.regconfig', 'pg_catalog.jsonb', 'pg_catalog.tsquery'],
      result: 'pg_catalog.jsonb',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","ts_headline"](pg_catalog.regconfig,pg_catalog.jsonb,pg_catalog.tsquery,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'ts_headline',
      args: ['pg_catalog.regconfig', 'pg_catalog.jsonb', 'pg_catalog.tsquery', 'pg_catalog.text'],
      result: 'pg_catalog.jsonb',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'operator:["pg_catalog","#-"](pg_catalog.jsonb,pg_catalog._text)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '#-',
    args: ['pg_catalog.jsonb', 'pg_catalog._text'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog._text',
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","#>"](pg_catalog."json",pg_catalog._text)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '#>',
    args: ['pg_catalog."json"', 'pg_catalog._text'],
    left: 'pg_catalog."json"',
    right: 'pg_catalog._text',
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","#>"](pg_catalog.jsonb,pg_catalog._text)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '#>',
    args: ['pg_catalog.jsonb', 'pg_catalog._text'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog._text',
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","#>>"](pg_catalog."json",pg_catalog._text)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '#>>',
    args: ['pg_catalog."json"', 'pg_catalog._text'],
    left: 'pg_catalog."json"',
    right: 'pg_catalog._text',
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","#>>"](pg_catalog.jsonb,pg_catalog._text)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '#>>',
    args: ['pg_catalog.jsonb', 'pg_catalog._text'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog._text',
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","-"](pg_catalog.jsonb,pg_catalog._text)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '-',
    args: ['pg_catalog.jsonb', 'pg_catalog._text'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog._text',
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","-"](pg_catalog.jsonb,pg_catalog.int4)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '-',
    args: ['pg_catalog.jsonb', 'pg_catalog.int4'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.int4',
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","-"](pg_catalog.jsonb,pg_catalog.text)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '-',
    args: ['pg_catalog.jsonb', 'pg_catalog.text'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.text',
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","->"](pg_catalog."json",pg_catalog.int4)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '->',
    args: ['pg_catalog."json"', 'pg_catalog.int4'],
    left: 'pg_catalog."json"',
    right: 'pg_catalog.int4',
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","->"](pg_catalog."json",pg_catalog.text)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '->',
    args: ['pg_catalog."json"', 'pg_catalog.text'],
    left: 'pg_catalog."json"',
    right: 'pg_catalog.text',
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","->"](pg_catalog.jsonb,pg_catalog.int4)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '->',
    args: ['pg_catalog.jsonb', 'pg_catalog.int4'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.int4',
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","->"](pg_catalog.jsonb,pg_catalog.text)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '->',
    args: ['pg_catalog.jsonb', 'pg_catalog.text'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.text',
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","->>"](pg_catalog."json",pg_catalog.int4)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '->>',
    args: ['pg_catalog."json"', 'pg_catalog.int4'],
    left: 'pg_catalog."json"',
    right: 'pg_catalog.int4',
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","->>"](pg_catalog."json",pg_catalog.text)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '->>',
    args: ['pg_catalog."json"', 'pg_catalog.text'],
    left: 'pg_catalog."json"',
    right: 'pg_catalog.text',
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","->>"](pg_catalog.jsonb,pg_catalog.int4)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '->>',
    args: ['pg_catalog.jsonb', 'pg_catalog.int4'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.int4',
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","->>"](pg_catalog.jsonb,pg_catalog.text)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '->>',
    args: ['pg_catalog.jsonb', 'pg_catalog.text'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.text',
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.jsonb',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.jsonb',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.jsonb',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<@"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<@',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.jsonb',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.jsonb',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.jsonb',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.jsonb',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","?"](pg_catalog.jsonb,pg_catalog.text)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '?',
    args: ['pg_catalog.jsonb', 'pg_catalog.text'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.text',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","?&"](pg_catalog.jsonb,pg_catalog._text)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '?&',
    args: ['pg_catalog.jsonb', 'pg_catalog._text'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog._text',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","?|"](pg_catalog.jsonb,pg_catalog._text)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '?|',
    args: ['pg_catalog.jsonb', 'pg_catalog._text'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog._text',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","@>"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@>',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.jsonb',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","@?"](pg_catalog.jsonb,pg_catalog.jsonpath)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@?',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonpath'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.jsonpath',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","@@"](pg_catalog.jsonb,pg_catalog.jsonpath)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@@',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonpath'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.jsonpath',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","||"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '||',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.jsonb',
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
} as const
