export const PG18_JSON = {
  'function:["pg_catalog","array_to_json"](pg_catalog.anyarray)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_to_json',
    rustName: 'sql__pg_catalog__array_to_json__sjq7',
    args: ['pg_catalog.anyarray'],
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","array_to_json"](pg_catalog.anyarray,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_to_json',
    rustName: 'sql__pg_catalog__array_to_json__fydb',
    args: ['pg_catalog.anyarray', 'pg_catalog.bool'],
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","bool"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bool',
    rustName: 'sql__pg_catalog__bool__k8bw',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float4"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float4',
    rustName: 'sql__pg_catalog__float4__jqx8',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.float4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","float8"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'float8',
    rustName: 'sql__pg_catalog__float8__ncq4',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.float8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int2"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int2',
    rustName: 'sql__pg_catalog__int2__0vdl',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.int2',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int4"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int4',
    rustName: 'sql__pg_catalog__int4__cjcd',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int8"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int8',
    rustName: 'sql__pg_catalog__int8__8pbn',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_array_element"](pg_catalog."json",pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_array_element',
    rustName: 'sql__pg_catalog__json_array_element__8yh4',
    args: ['pg_catalog."json"', 'pg_catalog.int4'],
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_array_element_text"](pg_catalog."json",pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_array_element_text',
    rustName: 'sql__pg_catalog__json_array_element_text__t2sr',
    args: ['pg_catalog."json"', 'pg_catalog.int4'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_array_elements"](pg_catalog."json")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_array_elements',
    rustName: 'sql__pg_catalog__json_array_elements__ktub',
    args: ['pg_catalog."json"'],
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_array_elements_text"](pg_catalog."json")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_array_elements_text',
    rustName: 'sql__pg_catalog__json_array_elements_text__q7d2',
    args: ['pg_catalog."json"'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_array_length"](pg_catalog."json")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_array_length',
    rustName: 'sql__pg_catalog__json_array_length__97pw',
    args: ['pg_catalog."json"'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_build_array"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_build_array',
    rustName: 'sql__pg_catalog__json_build_array__3khl',
    args: [],
    result: 'pg_catalog."json"',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_build_array"](pg_catalog."any")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_build_array',
    rustName: 'sql__pg_catalog__json_build_array__gme1',
    args: ['pg_catalog."any"'],
    result: 'pg_catalog."json"',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: 'pg_catalog."any"',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_build_object"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_build_object',
    rustName: 'sql__pg_catalog__json_build_object__nqz6',
    args: [],
    result: 'pg_catalog."json"',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_build_object"](pg_catalog."any")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_build_object',
    rustName: 'sql__pg_catalog__json_build_object__qfmu',
    args: ['pg_catalog."any"'],
    result: 'pg_catalog."json"',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: 'pg_catalog."any"',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_each"](pg_catalog."json")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_each',
    rustName: 'sql__pg_catalog__json_each__k0kb',
    args: ['pg_catalog."json"'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_each_text"](pg_catalog."json")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_each_text',
    rustName: 'sql__pg_catalog__json_each_text__w5u2',
    args: ['pg_catalog."json"'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_extract_path"](pg_catalog."json",pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_extract_path',
    rustName: 'sql__pg_catalog__json_extract_path__adkn',
    args: ['pg_catalog."json"', 'pg_catalog._text'],
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: 'pg_catalog.text',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_extract_path_text"](pg_catalog."json",pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_extract_path_text',
    rustName: 'sql__pg_catalog__json_extract_path_text__v3oi',
    args: ['pg_catalog."json"', 'pg_catalog._text'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: 'pg_catalog.text',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_object"](pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_object',
    rustName: 'sql__pg_catalog__json_object__fm30',
    args: ['pg_catalog._text'],
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_object"](pg_catalog._text,pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_object',
    rustName: 'sql__pg_catalog__json_object__katl',
    args: ['pg_catalog._text', 'pg_catalog._text'],
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_object_field"](pg_catalog."json",pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_object_field',
    rustName: 'sql__pg_catalog__json_object_field__ubt9',
    args: ['pg_catalog."json"', 'pg_catalog.text'],
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_object_field_text"](pg_catalog."json",pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_object_field_text',
    rustName: 'sql__pg_catalog__json_object_field_text__zdkt',
    args: ['pg_catalog."json"', 'pg_catalog.text'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_object_keys"](pg_catalog."json")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_object_keys',
    rustName: 'sql__pg_catalog__json_object_keys__el0w',
    args: ['pg_catalog."json"'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_populate_record"](pg_catalog.anyelement,pg_catalog."json",pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'json_populate_record',
      rustName: 'sql__pg_catalog__json_populate_record__qo9b',
      args: ['pg_catalog.anyelement', 'pg_catalog."json"', 'pg_catalog.bool'],
      result: 'pg_catalog.anyelement',
      strict: false,
      volatility: 's',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 1,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","json_populate_recordset"](pg_catalog.anyelement,pg_catalog."json",pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'json_populate_recordset',
      rustName: 'sql__pg_catalog__json_populate_recordset__drkx',
      args: ['pg_catalog.anyelement', 'pg_catalog."json"', 'pg_catalog.bool'],
      result: 'pg_catalog.anyelement',
      strict: false,
      volatility: 's',
      returnsSet: true,
      variadic: null,
      numArgDefaults: 1,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","json_strip_nulls"](pg_catalog."json",pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_strip_nulls',
    rustName: 'sql__pg_catalog__json_strip_nulls__z8vm',
    args: ['pg_catalog."json"', 'pg_catalog.bool'],
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 1,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_to_record"](pg_catalog."json")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_to_record',
    rustName: 'sql__pg_catalog__json_to_record__112o',
    args: ['pg_catalog."json"'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_to_recordset"](pg_catalog."json")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_to_recordset',
    rustName: 'sql__pg_catalog__json_to_recordset__43ye',
    args: ['pg_catalog."json"'],
    result: 'pg_catalog.record',
    strict: false,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_typeof"](pg_catalog."json")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_typeof',
    rustName: 'sql__pg_catalog__json_typeof__vzgr',
    args: ['pg_catalog."json"'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_array_element"](pg_catalog.jsonb,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_array_element',
    rustName: 'sql__pg_catalog__jsonb_array_element__08oi',
    args: ['pg_catalog.jsonb', 'pg_catalog.int4'],
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_array_element_text"](pg_catalog.jsonb,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_array_element_text',
    rustName: 'sql__pg_catalog__jsonb_array_element_text__83ql',
    args: ['pg_catalog.jsonb', 'pg_catalog.int4'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_array_elements"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_array_elements',
    rustName: 'sql__pg_catalog__jsonb_array_elements__3v6o',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_array_elements_text"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_array_elements_text',
    rustName: 'sql__pg_catalog__jsonb_array_elements_text__kafm',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_array_length"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_array_length',
    rustName: 'sql__pg_catalog__jsonb_array_length__1gng',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_build_array"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_build_array',
    rustName: 'sql__pg_catalog__jsonb_build_array__o9ke',
    args: [],
    result: 'pg_catalog.jsonb',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_build_array"](pg_catalog."any")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_build_array',
    rustName: 'sql__pg_catalog__jsonb_build_array__gfm5',
    args: ['pg_catalog."any"'],
    result: 'pg_catalog.jsonb',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: 'pg_catalog."any"',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_build_object"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_build_object',
    rustName: 'sql__pg_catalog__jsonb_build_object__a8ms',
    args: [],
    result: 'pg_catalog.jsonb',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_build_object"](pg_catalog."any")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_build_object',
    rustName: 'sql__pg_catalog__jsonb_build_object__8qt7',
    args: ['pg_catalog."any"'],
    result: 'pg_catalog.jsonb',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: 'pg_catalog."any"',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_cmp"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_cmp',
    rustName: 'sql__pg_catalog__jsonb_cmp__n2cx',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_concat"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_concat',
    rustName: 'sql__pg_catalog__jsonb_concat__j7e0',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_contained"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_contained',
    rustName: 'sql__pg_catalog__jsonb_contained__3itb',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_contains"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_contains',
    rustName: 'sql__pg_catalog__jsonb_contains__x4n2',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_delete"](pg_catalog.jsonb,pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_delete',
    rustName: 'sql__pg_catalog__jsonb_delete__11uh',
    args: ['pg_catalog.jsonb', 'pg_catalog._text'],
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: 'pg_catalog.text',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_delete"](pg_catalog.jsonb,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_delete',
    rustName: 'sql__pg_catalog__jsonb_delete__btgy',
    args: ['pg_catalog.jsonb', 'pg_catalog.int4'],
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_delete"](pg_catalog.jsonb,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_delete',
    rustName: 'sql__pg_catalog__jsonb_delete__cow2',
    args: ['pg_catalog.jsonb', 'pg_catalog.text'],
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_delete_path"](pg_catalog.jsonb,pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_delete_path',
    rustName: 'sql__pg_catalog__jsonb_delete_path__1ziq',
    args: ['pg_catalog.jsonb', 'pg_catalog._text'],
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_each"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_each',
    rustName: 'sql__pg_catalog__jsonb_each__8dcc',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_each_text"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_each_text',
    rustName: 'sql__pg_catalog__jsonb_each_text__3u6j',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_eq"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_eq',
    rustName: 'sql__pg_catalog__jsonb_eq__tfah',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_exists"](pg_catalog.jsonb,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_exists',
    rustName: 'sql__pg_catalog__jsonb_exists__f8f8',
    args: ['pg_catalog.jsonb', 'pg_catalog.text'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_exists_all"](pg_catalog.jsonb,pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_exists_all',
    rustName: 'sql__pg_catalog__jsonb_exists_all__x510',
    args: ['pg_catalog.jsonb', 'pg_catalog._text'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_exists_any"](pg_catalog.jsonb,pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_exists_any',
    rustName: 'sql__pg_catalog__jsonb_exists_any__p8z3',
    args: ['pg_catalog.jsonb', 'pg_catalog._text'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_extract_path"](pg_catalog.jsonb,pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_extract_path',
    rustName: 'sql__pg_catalog__jsonb_extract_path__6gn0',
    args: ['pg_catalog.jsonb', 'pg_catalog._text'],
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: 'pg_catalog.text',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_extract_path_text"](pg_catalog.jsonb,pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_extract_path_text',
    rustName: 'sql__pg_catalog__jsonb_extract_path_text__w3ff',
    args: ['pg_catalog.jsonb', 'pg_catalog._text'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: 'pg_catalog.text',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_ge"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_ge',
    rustName: 'sql__pg_catalog__jsonb_ge__ymoh',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_gt"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_gt',
    rustName: 'sql__pg_catalog__jsonb_gt__ogc1',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_hash"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_hash',
    rustName: 'sql__pg_catalog__jsonb_hash__qo2a',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_hash_extended"](pg_catalog.jsonb,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_hash_extended',
    rustName: 'sql__pg_catalog__jsonb_hash_extended__h75l',
    args: ['pg_catalog.jsonb', 'pg_catalog.int8'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_insert"](pg_catalog.jsonb,pg_catalog._text,pg_catalog.jsonb,pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'jsonb_insert',
      rustName: 'sql__pg_catalog__jsonb_insert__j3iu',
      args: ['pg_catalog.jsonb', 'pg_catalog._text', 'pg_catalog.jsonb', 'pg_catalog.bool'],
      result: 'pg_catalog.jsonb',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 1,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","jsonb_le"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_le',
    rustName: 'sql__pg_catalog__jsonb_le__mrjw',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_lt"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_lt',
    rustName: 'sql__pg_catalog__jsonb_lt__tn76',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_ne"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_ne',
    rustName: 'sql__pg_catalog__jsonb_ne__79zi',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_object"](pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_object',
    rustName: 'sql__pg_catalog__jsonb_object__4dkp',
    args: ['pg_catalog._text'],
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_object"](pg_catalog._text,pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_object',
    rustName: 'sql__pg_catalog__jsonb_object__tmdc',
    args: ['pg_catalog._text', 'pg_catalog._text'],
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_object_field"](pg_catalog.jsonb,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_object_field',
    rustName: 'sql__pg_catalog__jsonb_object_field__4uf3',
    args: ['pg_catalog.jsonb', 'pg_catalog.text'],
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_object_field_text"](pg_catalog.jsonb,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_object_field_text',
    rustName: 'sql__pg_catalog__jsonb_object_field_text__jpuz',
    args: ['pg_catalog.jsonb', 'pg_catalog.text'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_object_keys"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_object_keys',
    rustName: 'sql__pg_catalog__jsonb_object_keys__syuc',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_path_exists"](pg_catalog.jsonb,pg_catalog.jsonpath,pg_catalog.jsonb,pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'jsonb_path_exists',
      rustName: 'sql__pg_catalog__jsonb_path_exists__81t5',
      args: ['pg_catalog.jsonb', 'pg_catalog.jsonpath', 'pg_catalog.jsonb', 'pg_catalog.bool'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 2,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","jsonb_path_exists_opr"](pg_catalog.jsonb,pg_catalog.jsonpath)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_path_exists_opr',
    rustName: 'sql__pg_catalog__jsonb_path_exists_opr__8snd',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonpath'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_path_exists_tz"](pg_catalog.jsonb,pg_catalog.jsonpath,pg_catalog.jsonb,pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'jsonb_path_exists_tz',
      rustName: 'sql__pg_catalog__jsonb_path_exists_tz__46e9',
      args: ['pg_catalog.jsonb', 'pg_catalog.jsonpath', 'pg_catalog.jsonb', 'pg_catalog.bool'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 's',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 2,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","jsonb_path_match"](pg_catalog.jsonb,pg_catalog.jsonpath,pg_catalog.jsonb,pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'jsonb_path_match',
      rustName: 'sql__pg_catalog__jsonb_path_match__421e',
      args: ['pg_catalog.jsonb', 'pg_catalog.jsonpath', 'pg_catalog.jsonb', 'pg_catalog.bool'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 2,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","jsonb_path_match_opr"](pg_catalog.jsonb,pg_catalog.jsonpath)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_path_match_opr',
    rustName: 'sql__pg_catalog__jsonb_path_match_opr__juo6',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonpath'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_path_match_tz"](pg_catalog.jsonb,pg_catalog.jsonpath,pg_catalog.jsonb,pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'jsonb_path_match_tz',
      rustName: 'sql__pg_catalog__jsonb_path_match_tz__dd2q',
      args: ['pg_catalog.jsonb', 'pg_catalog.jsonpath', 'pg_catalog.jsonb', 'pg_catalog.bool'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 's',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 2,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","jsonb_path_query"](pg_catalog.jsonb,pg_catalog.jsonpath,pg_catalog.jsonb,pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'jsonb_path_query',
      rustName: 'sql__pg_catalog__jsonb_path_query__9imj',
      args: ['pg_catalog.jsonb', 'pg_catalog.jsonpath', 'pg_catalog.jsonb', 'pg_catalog.bool'],
      result: 'pg_catalog.jsonb',
      strict: true,
      volatility: 'i',
      returnsSet: true,
      variadic: null,
      numArgDefaults: 2,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","jsonb_path_query_array"](pg_catalog.jsonb,pg_catalog.jsonpath,pg_catalog.jsonb,pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'jsonb_path_query_array',
      rustName: 'sql__pg_catalog__jsonb_path_query_array__qidf',
      args: ['pg_catalog.jsonb', 'pg_catalog.jsonpath', 'pg_catalog.jsonb', 'pg_catalog.bool'],
      result: 'pg_catalog.jsonb',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 2,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","jsonb_path_query_array_tz"](pg_catalog.jsonb,pg_catalog.jsonpath,pg_catalog.jsonb,pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'jsonb_path_query_array_tz',
      rustName: 'sql__pg_catalog__jsonb_path_query_array_tz__qy5e',
      args: ['pg_catalog.jsonb', 'pg_catalog.jsonpath', 'pg_catalog.jsonb', 'pg_catalog.bool'],
      result: 'pg_catalog.jsonb',
      strict: true,
      volatility: 's',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 2,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","jsonb_path_query_first"](pg_catalog.jsonb,pg_catalog.jsonpath,pg_catalog.jsonb,pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'jsonb_path_query_first',
      rustName: 'sql__pg_catalog__jsonb_path_query_first__w0y6',
      args: ['pg_catalog.jsonb', 'pg_catalog.jsonpath', 'pg_catalog.jsonb', 'pg_catalog.bool'],
      result: 'pg_catalog.jsonb',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 2,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","jsonb_path_query_first_tz"](pg_catalog.jsonb,pg_catalog.jsonpath,pg_catalog.jsonb,pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'jsonb_path_query_first_tz',
      rustName: 'sql__pg_catalog__jsonb_path_query_first_tz__55ep',
      args: ['pg_catalog.jsonb', 'pg_catalog.jsonpath', 'pg_catalog.jsonb', 'pg_catalog.bool'],
      result: 'pg_catalog.jsonb',
      strict: true,
      volatility: 's',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 2,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","jsonb_path_query_tz"](pg_catalog.jsonb,pg_catalog.jsonpath,pg_catalog.jsonb,pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'jsonb_path_query_tz',
      rustName: 'sql__pg_catalog__jsonb_path_query_tz__z223',
      args: ['pg_catalog.jsonb', 'pg_catalog.jsonpath', 'pg_catalog.jsonb', 'pg_catalog.bool'],
      result: 'pg_catalog.jsonb',
      strict: true,
      volatility: 's',
      returnsSet: true,
      variadic: null,
      numArgDefaults: 2,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","jsonb_populate_record"](pg_catalog.anyelement,pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_populate_record',
    rustName: 'sql__pg_catalog__jsonb_populate_record__f6m5',
    args: ['pg_catalog.anyelement', 'pg_catalog.jsonb'],
    result: 'pg_catalog.anyelement',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_populate_record_valid"](pg_catalog.anyelement,pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_populate_record_valid',
    rustName: 'sql__pg_catalog__jsonb_populate_record_valid__rd7k',
    args: ['pg_catalog.anyelement', 'pg_catalog.jsonb'],
    result: 'pg_catalog.bool',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_populate_recordset"](pg_catalog.anyelement,pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_populate_recordset',
    rustName: 'sql__pg_catalog__jsonb_populate_recordset__a4te',
    args: ['pg_catalog.anyelement', 'pg_catalog.jsonb'],
    result: 'pg_catalog.anyelement',
    strict: false,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_pretty"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_pretty',
    rustName: 'sql__pg_catalog__jsonb_pretty__gz4i',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_set"](pg_catalog.jsonb,pg_catalog._text,pg_catalog.jsonb,pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'jsonb_set',
      rustName: 'sql__pg_catalog__jsonb_set__6ysq',
      args: ['pg_catalog.jsonb', 'pg_catalog._text', 'pg_catalog.jsonb', 'pg_catalog.bool'],
      result: 'pg_catalog.jsonb',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 1,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","jsonb_set_lax"](pg_catalog.jsonb,pg_catalog._text,pg_catalog.jsonb,pg_catalog.bool,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'jsonb_set_lax',
      rustName: 'sql__pg_catalog__jsonb_set_lax__lecq',
      args: [
        'pg_catalog.jsonb',
        'pg_catalog._text',
        'pg_catalog.jsonb',
        'pg_catalog.bool',
        'pg_catalog.text',
      ],
      result: 'pg_catalog.jsonb',
      strict: false,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 2,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","jsonb_strip_nulls"](pg_catalog.jsonb,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_strip_nulls',
    rustName: 'sql__pg_catalog__jsonb_strip_nulls__ruwp',
    args: ['pg_catalog.jsonb', 'pg_catalog.bool'],
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 1,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_to_record"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_to_record',
    rustName: 'sql__pg_catalog__jsonb_to_record__8kup',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_to_recordset"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_to_recordset',
    rustName: 'sql__pg_catalog__jsonb_to_recordset__z64u',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.record',
    strict: false,
    volatility: 's',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_typeof"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_typeof',
    rustName: 'sql__pg_catalog__jsonb_typeof__68xu',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","numeric"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'numeric',
    rustName: 'sql__pg_catalog__numeric__unkz',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog."numeric"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","row_to_json"](pg_catalog.record)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'row_to_json',
    rustName: 'sql__pg_catalog__row_to_json__99i2',
    args: ['pg_catalog.record'],
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","row_to_json"](pg_catalog.record,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'row_to_json',
    rustName: 'sql__pg_catalog__row_to_json__djs5',
    args: ['pg_catalog.record', 'pg_catalog.bool'],
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","to_json"](pg_catalog.anyelement)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'to_json',
    rustName: 'sql__pg_catalog__to_json__25lg',
    args: ['pg_catalog.anyelement'],
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","to_jsonb"](pg_catalog.anyelement)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'to_jsonb',
    rustName: 'sql__pg_catalog__to_jsonb__9y7o',
    args: ['pg_catalog.anyelement'],
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_headline"](pg_catalog."json",pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_headline',
    rustName: 'sql__pg_catalog__ts_headline__mlbg',
    args: ['pg_catalog."json"', 'pg_catalog.tsquery'],
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_headline"](pg_catalog."json",pg_catalog.tsquery,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_headline',
    rustName: 'sql__pg_catalog__ts_headline__07ls',
    args: ['pg_catalog."json"', 'pg_catalog.tsquery', 'pg_catalog.text'],
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_headline"](pg_catalog.jsonb,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_headline',
    rustName: 'sql__pg_catalog__ts_headline__a0ls',
    args: ['pg_catalog.jsonb', 'pg_catalog.tsquery'],
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_headline"](pg_catalog.jsonb,pg_catalog.tsquery,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_headline',
    rustName: 'sql__pg_catalog__ts_headline__8pxp',
    args: ['pg_catalog.jsonb', 'pg_catalog.tsquery', 'pg_catalog.text'],
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_headline"](pg_catalog.regconfig,pg_catalog."json",pg_catalog.tsquery)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'ts_headline',
      rustName: 'sql__pg_catalog__ts_headline__hf2i',
      args: ['pg_catalog.regconfig', 'pg_catalog."json"', 'pg_catalog.tsquery'],
      result: 'pg_catalog."json"',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","ts_headline"](pg_catalog.regconfig,pg_catalog."json",pg_catalog.tsquery,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'ts_headline',
      rustName: 'sql__pg_catalog__ts_headline__xdbu',
      args: ['pg_catalog.regconfig', 'pg_catalog."json"', 'pg_catalog.tsquery', 'pg_catalog.text'],
      result: 'pg_catalog."json"',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","ts_headline"](pg_catalog.regconfig,pg_catalog.jsonb,pg_catalog.tsquery)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'ts_headline',
      rustName: 'sql__pg_catalog__ts_headline__ycci',
      args: ['pg_catalog.regconfig', 'pg_catalog.jsonb', 'pg_catalog.tsquery'],
      result: 'pg_catalog.jsonb',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","ts_headline"](pg_catalog.regconfig,pg_catalog.jsonb,pg_catalog.tsquery,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'ts_headline',
      rustName: 'sql__pg_catalog__ts_headline__hgic',
      args: ['pg_catalog.regconfig', 'pg_catalog.jsonb', 'pg_catalog.tsquery', 'pg_catalog.text'],
      result: 'pg_catalog.jsonb',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'operator:["pg_catalog","#-"](pg_catalog.jsonb,pg_catalog._text)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '#-',
    implementation:
      'function:["pg_catalog","jsonb_delete_path"](pg_catalog.jsonb,pg_catalog._text)',
    args: ['pg_catalog.jsonb', 'pg_catalog._text'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog._text',
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","#>"](pg_catalog."json",pg_catalog._text)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '#>',
    implementation:
      'function:["pg_catalog","json_extract_path"](pg_catalog."json",pg_catalog._text)',
    args: ['pg_catalog."json"', 'pg_catalog._text'],
    left: 'pg_catalog."json"',
    right: 'pg_catalog._text',
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","#>"](pg_catalog.jsonb,pg_catalog._text)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '#>',
    implementation:
      'function:["pg_catalog","jsonb_extract_path"](pg_catalog.jsonb,pg_catalog._text)',
    args: ['pg_catalog.jsonb', 'pg_catalog._text'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog._text',
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","#>>"](pg_catalog."json",pg_catalog._text)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '#>>',
    implementation:
      'function:["pg_catalog","json_extract_path_text"](pg_catalog."json",pg_catalog._text)',
    args: ['pg_catalog."json"', 'pg_catalog._text'],
    left: 'pg_catalog."json"',
    right: 'pg_catalog._text',
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","#>>"](pg_catalog.jsonb,pg_catalog._text)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '#>>',
    implementation:
      'function:["pg_catalog","jsonb_extract_path_text"](pg_catalog.jsonb,pg_catalog._text)',
    args: ['pg_catalog.jsonb', 'pg_catalog._text'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog._text',
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","-"](pg_catalog.jsonb,pg_catalog._text)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '-',
    implementation: 'function:["pg_catalog","jsonb_delete"](pg_catalog.jsonb,pg_catalog._text)',
    args: ['pg_catalog.jsonb', 'pg_catalog._text'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog._text',
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","-"](pg_catalog.jsonb,pg_catalog.int4)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '-',
    implementation: 'function:["pg_catalog","jsonb_delete"](pg_catalog.jsonb,pg_catalog.int4)',
    args: ['pg_catalog.jsonb', 'pg_catalog.int4'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.int4',
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","-"](pg_catalog.jsonb,pg_catalog.text)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '-',
    implementation: 'function:["pg_catalog","jsonb_delete"](pg_catalog.jsonb,pg_catalog.text)',
    args: ['pg_catalog.jsonb', 'pg_catalog.text'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.text',
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","->"](pg_catalog."json",pg_catalog.int4)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '->',
    implementation:
      'function:["pg_catalog","json_array_element"](pg_catalog."json",pg_catalog.int4)',
    args: ['pg_catalog."json"', 'pg_catalog.int4'],
    left: 'pg_catalog."json"',
    right: 'pg_catalog.int4',
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","->"](pg_catalog."json",pg_catalog.text)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '->',
    implementation:
      'function:["pg_catalog","json_object_field"](pg_catalog."json",pg_catalog.text)',
    args: ['pg_catalog."json"', 'pg_catalog.text'],
    left: 'pg_catalog."json"',
    right: 'pg_catalog.text',
    result: 'pg_catalog."json"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","->"](pg_catalog.jsonb,pg_catalog.int4)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '->',
    implementation:
      'function:["pg_catalog","jsonb_array_element"](pg_catalog.jsonb,pg_catalog.int4)',
    args: ['pg_catalog.jsonb', 'pg_catalog.int4'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.int4',
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","->"](pg_catalog.jsonb,pg_catalog.text)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '->',
    implementation:
      'function:["pg_catalog","jsonb_object_field"](pg_catalog.jsonb,pg_catalog.text)',
    args: ['pg_catalog.jsonb', 'pg_catalog.text'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.text',
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","->>"](pg_catalog."json",pg_catalog.int4)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '->>',
    implementation:
      'function:["pg_catalog","json_array_element_text"](pg_catalog."json",pg_catalog.int4)',
    args: ['pg_catalog."json"', 'pg_catalog.int4'],
    left: 'pg_catalog."json"',
    right: 'pg_catalog.int4',
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","->>"](pg_catalog."json",pg_catalog.text)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '->>',
    implementation:
      'function:["pg_catalog","json_object_field_text"](pg_catalog."json",pg_catalog.text)',
    args: ['pg_catalog."json"', 'pg_catalog.text'],
    left: 'pg_catalog."json"',
    right: 'pg_catalog.text',
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","->>"](pg_catalog.jsonb,pg_catalog.int4)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '->>',
    implementation:
      'function:["pg_catalog","jsonb_array_element_text"](pg_catalog.jsonb,pg_catalog.int4)',
    args: ['pg_catalog.jsonb', 'pg_catalog.int4'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.int4',
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","->>"](pg_catalog.jsonb,pg_catalog.text)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '->>',
    implementation:
      'function:["pg_catalog","jsonb_object_field_text"](pg_catalog.jsonb,pg_catalog.text)',
    args: ['pg_catalog.jsonb', 'pg_catalog.text'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.text',
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    implementation: 'function:["pg_catalog","jsonb_lt"](pg_catalog.jsonb,pg_catalog.jsonb)',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.jsonb',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    implementation: 'function:["pg_catalog","jsonb_le"](pg_catalog.jsonb,pg_catalog.jsonb)',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.jsonb',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    implementation: 'function:["pg_catalog","jsonb_ne"](pg_catalog.jsonb,pg_catalog.jsonb)',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.jsonb',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<@"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<@',
    implementation: 'function:["pg_catalog","jsonb_contained"](pg_catalog.jsonb,pg_catalog.jsonb)',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.jsonb',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    implementation: 'function:["pg_catalog","jsonb_eq"](pg_catalog.jsonb,pg_catalog.jsonb)',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.jsonb',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    implementation: 'function:["pg_catalog","jsonb_gt"](pg_catalog.jsonb,pg_catalog.jsonb)',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.jsonb',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    implementation: 'function:["pg_catalog","jsonb_ge"](pg_catalog.jsonb,pg_catalog.jsonb)',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.jsonb',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","?"](pg_catalog.jsonb,pg_catalog.text)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '?',
    implementation: 'function:["pg_catalog","jsonb_exists"](pg_catalog.jsonb,pg_catalog.text)',
    args: ['pg_catalog.jsonb', 'pg_catalog.text'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.text',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","?&"](pg_catalog.jsonb,pg_catalog._text)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '?&',
    implementation: 'function:["pg_catalog","jsonb_exists_all"](pg_catalog.jsonb,pg_catalog._text)',
    args: ['pg_catalog.jsonb', 'pg_catalog._text'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog._text',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","?|"](pg_catalog.jsonb,pg_catalog._text)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '?|',
    implementation: 'function:["pg_catalog","jsonb_exists_any"](pg_catalog.jsonb,pg_catalog._text)',
    args: ['pg_catalog.jsonb', 'pg_catalog._text'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog._text',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","@>"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@>',
    implementation: 'function:["pg_catalog","jsonb_contains"](pg_catalog.jsonb,pg_catalog.jsonb)',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.jsonb',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","@?"](pg_catalog.jsonb,pg_catalog.jsonpath)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@?',
    implementation:
      'function:["pg_catalog","jsonb_path_exists_opr"](pg_catalog.jsonb,pg_catalog.jsonpath)',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonpath'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.jsonpath',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","@@"](pg_catalog.jsonb,pg_catalog.jsonpath)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@@',
    implementation:
      'function:["pg_catalog","jsonb_path_match_opr"](pg_catalog.jsonb,pg_catalog.jsonpath)',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonpath'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.jsonpath',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","||"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '||',
    implementation: 'function:["pg_catalog","jsonb_concat"](pg_catalog.jsonb,pg_catalog.jsonb)',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    left: 'pg_catalog.jsonb',
    right: 'pg_catalog.jsonb',
    result: 'pg_catalog.jsonb',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
} as const
