export const PG18_NETWORK = {
  'function:["pg_catalog","abbrev"](pg_catalog.cidr)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'abbrev',
    rustName: 'sql__pg_catalog__abbrev__5tby',
    args: ['pg_catalog.cidr'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","abbrev"](pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'abbrev',
    rustName: 'sql__pg_catalog__abbrev__xdee',
    args: ['pg_catalog.inet'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","broadcast"](pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'broadcast',
    rustName: 'sql__pg_catalog__broadcast__ilgu',
    args: ['pg_catalog.inet'],
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","cidr"](pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'cidr',
    rustName: 'sql__pg_catalog__cidr__6idb',
    args: ['pg_catalog.inet'],
    result: 'pg_catalog.cidr',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","family"](pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'family',
    rustName: 'sql__pg_catalog__family__2lcf',
    args: ['pg_catalog.inet'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashinet"](pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashinet',
    rustName: 'sql__pg_catalog__hashinet__fhly',
    args: ['pg_catalog.inet'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashinetextended"](pg_catalog.inet,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashinetextended',
    rustName: 'sql__pg_catalog__hashinetextended__n7xh',
    args: ['pg_catalog.inet', 'pg_catalog.int8'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashmacaddr"](pg_catalog.macaddr)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashmacaddr',
    rustName: 'sql__pg_catalog__hashmacaddr__ih2y',
    args: ['pg_catalog.macaddr'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashmacaddr8"](pg_catalog.macaddr8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashmacaddr8',
    rustName: 'sql__pg_catalog__hashmacaddr8__72kw',
    args: ['pg_catalog.macaddr8'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashmacaddr8extended"](pg_catalog.macaddr8,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashmacaddr8extended',
    rustName: 'sql__pg_catalog__hashmacaddr8extended__63o8',
    args: ['pg_catalog.macaddr8', 'pg_catalog.int8'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashmacaddrextended"](pg_catalog.macaddr,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashmacaddrextended',
    rustName: 'sql__pg_catalog__hashmacaddrextended__94rh',
    args: ['pg_catalog.macaddr', 'pg_catalog.int8'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","host"](pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'host',
    rustName: 'sql__pg_catalog__host__h4jb',
    args: ['pg_catalog.inet'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hostmask"](pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hostmask',
    rustName: 'sql__pg_catalog__hostmask__vz12',
    args: ['pg_catalog.inet'],
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","inet_client_addr"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'inet_client_addr',
    rustName: 'sql__pg_catalog__inet_client_addr__j4vm',
    args: [],
    result: 'pg_catalog.inet',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","inet_merge"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'inet_merge',
    rustName: 'sql__pg_catalog__inet_merge__iflm',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.cidr',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","inet_same_family"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'inet_same_family',
    rustName: 'sql__pg_catalog__inet_same_family__ogv6',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","inet_server_addr"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'inet_server_addr',
    rustName: 'sql__pg_catalog__inet_server_addr__fj25',
    args: [],
    result: 'pg_catalog.inet',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","inetand"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'inetand',
    rustName: 'sql__pg_catalog__inetand__qxb6',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","inetmi"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'inetmi',
    rustName: 'sql__pg_catalog__inetmi__jocm',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","inetmi_int8"](pg_catalog.inet,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'inetmi_int8',
    rustName: 'sql__pg_catalog__inetmi_int8__z4fj',
    args: ['pg_catalog.inet', 'pg_catalog.int8'],
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","inetnot"](pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'inetnot',
    rustName: 'sql__pg_catalog__inetnot__8bow',
    args: ['pg_catalog.inet'],
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","inetor"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'inetor',
    rustName: 'sql__pg_catalog__inetor__kw39',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","inetpl"](pg_catalog.inet,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'inetpl',
    rustName: 'sql__pg_catalog__inetpl__eu7x',
    args: ['pg_catalog.inet', 'pg_catalog.int8'],
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int8pl_inet"](pg_catalog.int8,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int8pl_inet',
    rustName: 'sql__pg_catalog__int8pl_inet__3uh7',
    args: ['pg_catalog.int8', 'pg_catalog.inet'],
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr"](pg_catalog.macaddr8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr',
    rustName: 'sql__pg_catalog__macaddr__xnt6',
    args: ['pg_catalog.macaddr8'],
    result: 'pg_catalog.macaddr',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr8"](pg_catalog.macaddr)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr8',
    rustName: 'sql__pg_catalog__macaddr8__ta7j',
    args: ['pg_catalog.macaddr'],
    result: 'pg_catalog.macaddr8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr8_and"](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr8_and',
    rustName: 'sql__pg_catalog__macaddr8_and__ceah',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    result: 'pg_catalog.macaddr8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr8_cmp"](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr8_cmp',
    rustName: 'sql__pg_catalog__macaddr8_cmp__id7f',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr8_eq"](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr8_eq',
    rustName: 'sql__pg_catalog__macaddr8_eq__wy3p',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr8_ge"](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr8_ge',
    rustName: 'sql__pg_catalog__macaddr8_ge__054u',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr8_gt"](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr8_gt',
    rustName: 'sql__pg_catalog__macaddr8_gt__o95h',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr8_le"](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr8_le',
    rustName: 'sql__pg_catalog__macaddr8_le__dmol',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr8_lt"](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr8_lt',
    rustName: 'sql__pg_catalog__macaddr8_lt__5tsr',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr8_ne"](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr8_ne',
    rustName: 'sql__pg_catalog__macaddr8_ne__j20a',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr8_not"](pg_catalog.macaddr8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr8_not',
    rustName: 'sql__pg_catalog__macaddr8_not__ufi9',
    args: ['pg_catalog.macaddr8'],
    result: 'pg_catalog.macaddr8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr8_or"](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr8_or',
    rustName: 'sql__pg_catalog__macaddr8_or__6kdp',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    result: 'pg_catalog.macaddr8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr8_set7bit"](pg_catalog.macaddr8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr8_set7bit',
    rustName: 'sql__pg_catalog__macaddr8_set7bit__2kgh',
    args: ['pg_catalog.macaddr8'],
    result: 'pg_catalog.macaddr8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr_and"](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr_and',
    rustName: 'sql__pg_catalog__macaddr_and__ky45',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    result: 'pg_catalog.macaddr',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr_cmp"](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr_cmp',
    rustName: 'sql__pg_catalog__macaddr_cmp__jv7y',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr_eq"](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr_eq',
    rustName: 'sql__pg_catalog__macaddr_eq__uthl',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr_ge"](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr_ge',
    rustName: 'sql__pg_catalog__macaddr_ge__iuvk',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr_gt"](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr_gt',
    rustName: 'sql__pg_catalog__macaddr_gt__4kss',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr_le"](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr_le',
    rustName: 'sql__pg_catalog__macaddr_le__6qq0',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr_lt"](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr_lt',
    rustName: 'sql__pg_catalog__macaddr_lt__8vk5',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr_ne"](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr_ne',
    rustName: 'sql__pg_catalog__macaddr_ne__etmb',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr_not"](pg_catalog.macaddr)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr_not',
    rustName: 'sql__pg_catalog__macaddr_not__4gjk',
    args: ['pg_catalog.macaddr'],
    result: 'pg_catalog.macaddr',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr_or"](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr_or',
    rustName: 'sql__pg_catalog__macaddr_or__wqx0',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    result: 'pg_catalog.macaddr',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","masklen"](pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'masklen',
    rustName: 'sql__pg_catalog__masklen__kk20',
    args: ['pg_catalog.inet'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","netmask"](pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'netmask',
    rustName: 'sql__pg_catalog__netmask__bt5i',
    args: ['pg_catalog.inet'],
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","network"](pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'network',
    rustName: 'sql__pg_catalog__network__o215',
    args: ['pg_catalog.inet'],
    result: 'pg_catalog.cidr',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","network_cmp"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'network_cmp',
    rustName: 'sql__pg_catalog__network_cmp__7dun',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","network_eq"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'network_eq',
    rustName: 'sql__pg_catalog__network_eq__i7hn',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","network_ge"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'network_ge',
    rustName: 'sql__pg_catalog__network_ge__q7pc',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","network_gt"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'network_gt',
    rustName: 'sql__pg_catalog__network_gt__i6x7',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","network_larger"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'network_larger',
    rustName: 'sql__pg_catalog__network_larger__wb5u',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","network_le"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'network_le',
    rustName: 'sql__pg_catalog__network_le__n61s',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","network_lt"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'network_lt',
    rustName: 'sql__pg_catalog__network_lt__0kbr',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","network_ne"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'network_ne',
    rustName: 'sql__pg_catalog__network_ne__vmql',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","network_overlap"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'network_overlap',
    rustName: 'sql__pg_catalog__network_overlap__zbdv',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","network_smaller"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'network_smaller',
    rustName: 'sql__pg_catalog__network_smaller__nmw8',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","network_sub"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'network_sub',
    rustName: 'sql__pg_catalog__network_sub__y7j2',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","network_subeq"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'network_subeq',
    rustName: 'sql__pg_catalog__network_subeq__9psu',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","network_sup"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'network_sup',
    rustName: 'sql__pg_catalog__network_sup__1zu4',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","network_supeq"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'network_supeq',
    rustName: 'sql__pg_catalog__network_supeq__utj6',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_stat_get_backend_client_addr"](pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_stat_get_backend_client_addr',
    rustName: 'sql__pg_catalog__pg_stat_get_backend_client_addr__x97t',
    args: ['pg_catalog.int4'],
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","set_masklen"](pg_catalog.cidr,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'set_masklen',
    rustName: 'sql__pg_catalog__set_masklen__00t7',
    args: ['pg_catalog.cidr', 'pg_catalog.int4'],
    result: 'pg_catalog.cidr',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","set_masklen"](pg_catalog.inet,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'set_masklen',
    rustName: 'sql__pg_catalog__set_masklen__a6b0',
    args: ['pg_catalog.inet', 'pg_catalog.int4'],
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","text"](pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'text',
    rustName: 'sql__pg_catalog__text__99pc',
    args: ['pg_catalog.inet'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","trunc"](pg_catalog.macaddr)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'trunc',
    rustName: 'sql__pg_catalog__trunc__bgg8',
    args: ['pg_catalog.macaddr'],
    result: 'pg_catalog.macaddr',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","trunc"](pg_catalog.macaddr8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'trunc',
    rustName: 'sql__pg_catalog__trunc__y4rb',
    args: ['pg_catalog.macaddr8'],
    result: 'pg_catalog.macaddr8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'operator:["pg_catalog","&"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&',
    implementation: 'function:["pg_catalog","inetand"](pg_catalog.inet,pg_catalog.inet)',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    left: 'pg_catalog.inet',
    right: 'pg_catalog.inet',
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","&"](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&',
    implementation: 'function:["pg_catalog","macaddr_and"](pg_catalog.macaddr,pg_catalog.macaddr)',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    left: 'pg_catalog.macaddr',
    right: 'pg_catalog.macaddr',
    result: 'pg_catalog.macaddr',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","&"](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&',
    implementation:
      'function:["pg_catalog","macaddr8_and"](pg_catalog.macaddr8,pg_catalog.macaddr8)',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    left: 'pg_catalog.macaddr8',
    right: 'pg_catalog.macaddr8',
    result: 'pg_catalog.macaddr8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","&&"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&&',
    implementation: 'function:["pg_catalog","network_overlap"](pg_catalog.inet,pg_catalog.inet)',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    left: 'pg_catalog.inet',
    right: 'pg_catalog.inet',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","+"](pg_catalog.inet,pg_catalog.int8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '+',
    implementation: 'function:["pg_catalog","inetpl"](pg_catalog.inet,pg_catalog.int8)',
    args: ['pg_catalog.inet', 'pg_catalog.int8'],
    left: 'pg_catalog.inet',
    right: 'pg_catalog.int8',
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","+"](pg_catalog.int8,pg_catalog.inet)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '+',
    implementation: 'function:["pg_catalog","int8pl_inet"](pg_catalog.int8,pg_catalog.inet)',
    args: ['pg_catalog.int8', 'pg_catalog.inet'],
    left: 'pg_catalog.int8',
    right: 'pg_catalog.inet',
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","-"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '-',
    implementation: 'function:["pg_catalog","inetmi"](pg_catalog.inet,pg_catalog.inet)',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    left: 'pg_catalog.inet',
    right: 'pg_catalog.inet',
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","-"](pg_catalog.inet,pg_catalog.int8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '-',
    implementation: 'function:["pg_catalog","inetmi_int8"](pg_catalog.inet,pg_catalog.int8)',
    args: ['pg_catalog.inet', 'pg_catalog.int8'],
    left: 'pg_catalog.inet',
    right: 'pg_catalog.int8',
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    implementation: 'function:["pg_catalog","network_lt"](pg_catalog.inet,pg_catalog.inet)',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    left: 'pg_catalog.inet',
    right: 'pg_catalog.inet',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    implementation: 'function:["pg_catalog","macaddr_lt"](pg_catalog.macaddr,pg_catalog.macaddr)',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    left: 'pg_catalog.macaddr',
    right: 'pg_catalog.macaddr',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    implementation:
      'function:["pg_catalog","macaddr8_lt"](pg_catalog.macaddr8,pg_catalog.macaddr8)',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    left: 'pg_catalog.macaddr8',
    right: 'pg_catalog.macaddr8',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<<"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<<',
    implementation: 'function:["pg_catalog","network_sub"](pg_catalog.inet,pg_catalog.inet)',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    left: 'pg_catalog.inet',
    right: 'pg_catalog.inet',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<<="](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<<=',
    implementation: 'function:["pg_catalog","network_subeq"](pg_catalog.inet,pg_catalog.inet)',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    left: 'pg_catalog.inet',
    right: 'pg_catalog.inet',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    implementation: 'function:["pg_catalog","network_le"](pg_catalog.inet,pg_catalog.inet)',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    left: 'pg_catalog.inet',
    right: 'pg_catalog.inet',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    implementation: 'function:["pg_catalog","macaddr_le"](pg_catalog.macaddr,pg_catalog.macaddr)',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    left: 'pg_catalog.macaddr',
    right: 'pg_catalog.macaddr',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    implementation:
      'function:["pg_catalog","macaddr8_le"](pg_catalog.macaddr8,pg_catalog.macaddr8)',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    left: 'pg_catalog.macaddr8',
    right: 'pg_catalog.macaddr8',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    implementation: 'function:["pg_catalog","network_ne"](pg_catalog.inet,pg_catalog.inet)',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    left: 'pg_catalog.inet',
    right: 'pg_catalog.inet',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    implementation: 'function:["pg_catalog","macaddr_ne"](pg_catalog.macaddr,pg_catalog.macaddr)',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    left: 'pg_catalog.macaddr',
    right: 'pg_catalog.macaddr',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    implementation:
      'function:["pg_catalog","macaddr8_ne"](pg_catalog.macaddr8,pg_catalog.macaddr8)',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    left: 'pg_catalog.macaddr8',
    right: 'pg_catalog.macaddr8',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    implementation: 'function:["pg_catalog","network_eq"](pg_catalog.inet,pg_catalog.inet)',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    left: 'pg_catalog.inet',
    right: 'pg_catalog.inet',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    implementation: 'function:["pg_catalog","macaddr_eq"](pg_catalog.macaddr,pg_catalog.macaddr)',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    left: 'pg_catalog.macaddr',
    right: 'pg_catalog.macaddr',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    implementation:
      'function:["pg_catalog","macaddr8_eq"](pg_catalog.macaddr8,pg_catalog.macaddr8)',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    left: 'pg_catalog.macaddr8',
    right: 'pg_catalog.macaddr8',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    implementation: 'function:["pg_catalog","network_gt"](pg_catalog.inet,pg_catalog.inet)',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    left: 'pg_catalog.inet',
    right: 'pg_catalog.inet',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    implementation: 'function:["pg_catalog","macaddr_gt"](pg_catalog.macaddr,pg_catalog.macaddr)',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    left: 'pg_catalog.macaddr',
    right: 'pg_catalog.macaddr',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    implementation:
      'function:["pg_catalog","macaddr8_gt"](pg_catalog.macaddr8,pg_catalog.macaddr8)',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    left: 'pg_catalog.macaddr8',
    right: 'pg_catalog.macaddr8',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    implementation: 'function:["pg_catalog","network_ge"](pg_catalog.inet,pg_catalog.inet)',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    left: 'pg_catalog.inet',
    right: 'pg_catalog.inet',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    implementation: 'function:["pg_catalog","macaddr_ge"](pg_catalog.macaddr,pg_catalog.macaddr)',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    left: 'pg_catalog.macaddr',
    right: 'pg_catalog.macaddr',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    implementation:
      'function:["pg_catalog","macaddr8_ge"](pg_catalog.macaddr8,pg_catalog.macaddr8)',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    left: 'pg_catalog.macaddr8',
    right: 'pg_catalog.macaddr8',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">>"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>>',
    implementation: 'function:["pg_catalog","network_sup"](pg_catalog.inet,pg_catalog.inet)',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    left: 'pg_catalog.inet',
    right: 'pg_catalog.inet',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">>="](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>>=',
    implementation: 'function:["pg_catalog","network_supeq"](pg_catalog.inet,pg_catalog.inet)',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    left: 'pg_catalog.inet',
    right: 'pg_catalog.inet',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","|"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '|',
    implementation: 'function:["pg_catalog","inetor"](pg_catalog.inet,pg_catalog.inet)',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    left: 'pg_catalog.inet',
    right: 'pg_catalog.inet',
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","|"](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '|',
    implementation: 'function:["pg_catalog","macaddr_or"](pg_catalog.macaddr,pg_catalog.macaddr)',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    left: 'pg_catalog.macaddr',
    right: 'pg_catalog.macaddr',
    result: 'pg_catalog.macaddr',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","|"](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '|',
    implementation:
      'function:["pg_catalog","macaddr8_or"](pg_catalog.macaddr8,pg_catalog.macaddr8)',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    left: 'pg_catalog.macaddr8',
    right: 'pg_catalog.macaddr8',
    result: 'pg_catalog.macaddr8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","~"](,pg_catalog.inet)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '~',
    implementation: 'function:["pg_catalog","inetnot"](pg_catalog.inet)',
    args: ['pg_catalog.inet'],
    left: null,
    right: 'pg_catalog.inet',
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","~"](,pg_catalog.macaddr)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '~',
    implementation: 'function:["pg_catalog","macaddr_not"](pg_catalog.macaddr)',
    args: ['pg_catalog.macaddr'],
    left: null,
    right: 'pg_catalog.macaddr',
    result: 'pg_catalog.macaddr',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","~"](,pg_catalog.macaddr8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '~',
    implementation: 'function:["pg_catalog","macaddr8_not"](pg_catalog.macaddr8)',
    args: ['pg_catalog.macaddr8'],
    left: null,
    right: 'pg_catalog.macaddr8',
    result: 'pg_catalog.macaddr8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
} as const
