export const PG18_NETWORK = {
  'function:["pg_catalog","abbrev"](pg_catalog.cidr)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'abbrev',
    args: ['pg_catalog.cidr'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","abbrev"](pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'abbrev',
    args: ['pg_catalog.inet'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","broadcast"](pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'broadcast',
    args: ['pg_catalog.inet'],
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","cidr"](pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'cidr',
    args: ['pg_catalog.inet'],
    result: 'pg_catalog.cidr',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","family"](pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'family',
    args: ['pg_catalog.inet'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashinet"](pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashinet',
    args: ['pg_catalog.inet'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashinetextended"](pg_catalog.inet,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashinetextended',
    args: ['pg_catalog.inet', 'pg_catalog.int8'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashmacaddr"](pg_catalog.macaddr)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashmacaddr',
    args: ['pg_catalog.macaddr'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashmacaddr8"](pg_catalog.macaddr8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashmacaddr8',
    args: ['pg_catalog.macaddr8'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashmacaddr8extended"](pg_catalog.macaddr8,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashmacaddr8extended',
    args: ['pg_catalog.macaddr8', 'pg_catalog.int8'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashmacaddrextended"](pg_catalog.macaddr,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashmacaddrextended',
    args: ['pg_catalog.macaddr', 'pg_catalog.int8'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","host"](pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'host',
    args: ['pg_catalog.inet'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hostmask"](pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hostmask',
    args: ['pg_catalog.inet'],
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","inet_client_addr"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'inet_client_addr',
    args: [],
    result: 'pg_catalog.inet',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","inet_merge"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'inet_merge',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.cidr',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","inet_same_family"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'inet_same_family',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","inet_server_addr"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'inet_server_addr',
    args: [],
    result: 'pg_catalog.inet',
    strict: false,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","inetand"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'inetand',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","inetmi"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'inetmi',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","inetmi_int8"](pg_catalog.inet,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'inetmi_int8',
    args: ['pg_catalog.inet', 'pg_catalog.int8'],
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","inetnot"](pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'inetnot',
    args: ['pg_catalog.inet'],
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","inetor"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'inetor',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","inetpl"](pg_catalog.inet,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'inetpl',
    args: ['pg_catalog.inet', 'pg_catalog.int8'],
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int8pl_inet"](pg_catalog.int8,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int8pl_inet',
    args: ['pg_catalog.int8', 'pg_catalog.inet'],
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr"](pg_catalog.macaddr8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr',
    args: ['pg_catalog.macaddr8'],
    result: 'pg_catalog.macaddr',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr8"](pg_catalog.macaddr)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr8',
    args: ['pg_catalog.macaddr'],
    result: 'pg_catalog.macaddr8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr8_and"](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr8_and',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    result: 'pg_catalog.macaddr8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr8_cmp"](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr8_cmp',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr8_eq"](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr8_eq',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr8_ge"](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr8_ge',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr8_gt"](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr8_gt',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr8_le"](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr8_le',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr8_lt"](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr8_lt',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr8_ne"](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr8_ne',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr8_not"](pg_catalog.macaddr8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr8_not',
    args: ['pg_catalog.macaddr8'],
    result: 'pg_catalog.macaddr8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr8_or"](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr8_or',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    result: 'pg_catalog.macaddr8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr8_set7bit"](pg_catalog.macaddr8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr8_set7bit',
    args: ['pg_catalog.macaddr8'],
    result: 'pg_catalog.macaddr8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr_and"](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr_and',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    result: 'pg_catalog.macaddr',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr_cmp"](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr_cmp',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr_eq"](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr_eq',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr_ge"](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr_ge',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr_gt"](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr_gt',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr_le"](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr_le',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr_lt"](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr_lt',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr_ne"](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr_ne',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr_not"](pg_catalog.macaddr)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr_not',
    args: ['pg_catalog.macaddr'],
    result: 'pg_catalog.macaddr',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","macaddr_or"](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'macaddr_or',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    result: 'pg_catalog.macaddr',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","masklen"](pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'masklen',
    args: ['pg_catalog.inet'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","netmask"](pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'netmask',
    args: ['pg_catalog.inet'],
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","network"](pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'network',
    args: ['pg_catalog.inet'],
    result: 'pg_catalog.cidr',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","network_cmp"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'network_cmp',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","network_eq"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'network_eq',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","network_ge"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'network_ge',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","network_gt"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'network_gt',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","network_larger"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'network_larger',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","network_le"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'network_le',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","network_lt"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'network_lt',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","network_ne"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'network_ne',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","network_overlap"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'network_overlap',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","network_smaller"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'network_smaller',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","network_sub"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'network_sub',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","network_subeq"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'network_subeq',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","network_sup"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'network_sup',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","network_supeq"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'network_supeq',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_stat_get_backend_client_addr"](pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_stat_get_backend_client_addr',
    args: ['pg_catalog.int4'],
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","set_masklen"](pg_catalog.cidr,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'set_masklen',
    args: ['pg_catalog.cidr', 'pg_catalog.int4'],
    result: 'pg_catalog.cidr',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","set_masklen"](pg_catalog.inet,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'set_masklen',
    args: ['pg_catalog.inet', 'pg_catalog.int4'],
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","text"](pg_catalog.inet)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'text',
    args: ['pg_catalog.inet'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","trunc"](pg_catalog.macaddr)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'trunc',
    args: ['pg_catalog.macaddr'],
    result: 'pg_catalog.macaddr',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","trunc"](pg_catalog.macaddr8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'trunc',
    args: ['pg_catalog.macaddr8'],
    result: 'pg_catalog.macaddr8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'operator:["pg_catalog","&"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    left: 'pg_catalog.inet',
    right: 'pg_catalog.inet',
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","&"](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    left: 'pg_catalog.macaddr',
    right: 'pg_catalog.macaddr',
    result: 'pg_catalog.macaddr',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","&"](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    left: 'pg_catalog.macaddr8',
    right: 'pg_catalog.macaddr8',
    result: 'pg_catalog.macaddr8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","&&"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&&',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    left: 'pg_catalog.inet',
    right: 'pg_catalog.inet',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","+"](pg_catalog.inet,pg_catalog.int8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '+',
    args: ['pg_catalog.inet', 'pg_catalog.int8'],
    left: 'pg_catalog.inet',
    right: 'pg_catalog.int8',
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","+"](pg_catalog.int8,pg_catalog.inet)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '+',
    args: ['pg_catalog.int8', 'pg_catalog.inet'],
    left: 'pg_catalog.int8',
    right: 'pg_catalog.inet',
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","-"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '-',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    left: 'pg_catalog.inet',
    right: 'pg_catalog.inet',
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","-"](pg_catalog.inet,pg_catalog.int8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '-',
    args: ['pg_catalog.inet', 'pg_catalog.int8'],
    left: 'pg_catalog.inet',
    right: 'pg_catalog.int8',
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    left: 'pg_catalog.inet',
    right: 'pg_catalog.inet',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    left: 'pg_catalog.macaddr',
    right: 'pg_catalog.macaddr',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    left: 'pg_catalog.macaddr8',
    right: 'pg_catalog.macaddr8',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<<"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<<',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    left: 'pg_catalog.inet',
    right: 'pg_catalog.inet',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<<="](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<<=',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    left: 'pg_catalog.inet',
    right: 'pg_catalog.inet',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    left: 'pg_catalog.inet',
    right: 'pg_catalog.inet',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    left: 'pg_catalog.macaddr',
    right: 'pg_catalog.macaddr',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    left: 'pg_catalog.macaddr8',
    right: 'pg_catalog.macaddr8',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    left: 'pg_catalog.inet',
    right: 'pg_catalog.inet',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    left: 'pg_catalog.macaddr',
    right: 'pg_catalog.macaddr',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    left: 'pg_catalog.macaddr8',
    right: 'pg_catalog.macaddr8',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    left: 'pg_catalog.inet',
    right: 'pg_catalog.inet',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    left: 'pg_catalog.macaddr',
    right: 'pg_catalog.macaddr',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    left: 'pg_catalog.macaddr8',
    right: 'pg_catalog.macaddr8',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    left: 'pg_catalog.inet',
    right: 'pg_catalog.inet',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    left: 'pg_catalog.macaddr',
    right: 'pg_catalog.macaddr',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    left: 'pg_catalog.macaddr8',
    right: 'pg_catalog.macaddr8',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    left: 'pg_catalog.inet',
    right: 'pg_catalog.inet',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    left: 'pg_catalog.macaddr',
    right: 'pg_catalog.macaddr',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    left: 'pg_catalog.macaddr8',
    right: 'pg_catalog.macaddr8',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">>"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>>',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    left: 'pg_catalog.inet',
    right: 'pg_catalog.inet',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">>="](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>>=',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    left: 'pg_catalog.inet',
    right: 'pg_catalog.inet',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","|"](pg_catalog.inet,pg_catalog.inet)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '|',
    args: ['pg_catalog.inet', 'pg_catalog.inet'],
    left: 'pg_catalog.inet',
    right: 'pg_catalog.inet',
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","|"](pg_catalog.macaddr,pg_catalog.macaddr)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '|',
    args: ['pg_catalog.macaddr', 'pg_catalog.macaddr'],
    left: 'pg_catalog.macaddr',
    right: 'pg_catalog.macaddr',
    result: 'pg_catalog.macaddr',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","|"](pg_catalog.macaddr8,pg_catalog.macaddr8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '|',
    args: ['pg_catalog.macaddr8', 'pg_catalog.macaddr8'],
    left: 'pg_catalog.macaddr8',
    right: 'pg_catalog.macaddr8',
    result: 'pg_catalog.macaddr8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","~"](,pg_catalog.inet)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '~',
    args: ['pg_catalog.inet'],
    left: null,
    right: 'pg_catalog.inet',
    result: 'pg_catalog.inet',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","~"](,pg_catalog.macaddr)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '~',
    args: ['pg_catalog.macaddr'],
    left: null,
    right: 'pg_catalog.macaddr',
    result: 'pg_catalog.macaddr',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","~"](,pg_catalog.macaddr8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '~',
    args: ['pg_catalog.macaddr8'],
    left: null,
    right: 'pg_catalog.macaddr8',
    result: 'pg_catalog.macaddr8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
} as const
