export const PG18_RANGES = {
  'function:["pg_catalog","datemultirange"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'datemultirange',
    rustName: 'sql__pg_catalog__datemultirange__qjle',
    args: [],
    result: 'pg_catalog.datemultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","datemultirange"](pg_catalog._daterange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'datemultirange',
    rustName: 'sql__pg_catalog__datemultirange__jpar',
    args: ['pg_catalog._daterange'],
    result: 'pg_catalog.datemultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: 'pg_catalog.daterange',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","datemultirange"](pg_catalog.daterange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'datemultirange',
    rustName: 'sql__pg_catalog__datemultirange__mwip',
    args: ['pg_catalog.daterange'],
    result: 'pg_catalog.datemultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","daterange"](pg_catalog.date,pg_catalog.date)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'daterange',
    rustName: 'sql__pg_catalog__daterange__xa2w',
    args: ['pg_catalog.date', 'pg_catalog.date'],
    result: 'pg_catalog.daterange',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","daterange"](pg_catalog.date,pg_catalog.date,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'daterange',
    rustName: 'sql__pg_catalog__daterange__z15e',
    args: ['pg_catalog.date', 'pg_catalog.date', 'pg_catalog.text'],
    result: 'pg_catalog.daterange',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","daterange_canonical"](pg_catalog.daterange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'daterange_canonical',
    rustName: 'sql__pg_catalog__daterange_canonical__wxsu',
    args: ['pg_catalog.daterange'],
    result: 'pg_catalog.daterange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","elem_contained_by_multirange"](pg_catalog.anyelement,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'elem_contained_by_multirange',
      rustName: 'sql__pg_catalog__elem_contained_by_multirange__1fqy',
      args: ['pg_catalog.anyelement', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","elem_contained_by_range"](pg_catalog.anyelement,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'elem_contained_by_range',
    rustName: 'sql__pg_catalog__elem_contained_by_range__wkbk',
    args: ['pg_catalog.anyelement', 'pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hash_multirange"](pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hash_multirange',
    rustName: 'sql__pg_catalog__hash_multirange__603b',
    args: ['pg_catalog.anymultirange'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hash_multirange_extended"](pg_catalog.anymultirange,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hash_multirange_extended',
    rustName: 'sql__pg_catalog__hash_multirange_extended__coup',
    args: ['pg_catalog.anymultirange', 'pg_catalog.int8'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hash_range"](pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hash_range',
    rustName: 'sql__pg_catalog__hash_range__ov3e',
    args: ['pg_catalog.anyrange'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hash_range_extended"](pg_catalog.anyrange,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hash_range_extended',
    rustName: 'sql__pg_catalog__hash_range_extended__axg0',
    args: ['pg_catalog.anyrange', 'pg_catalog.int8'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int4multirange"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int4multirange',
    rustName: 'sql__pg_catalog__int4multirange__qvfa',
    args: [],
    result: 'pg_catalog.int4multirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int4multirange"](pg_catalog._int4range)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int4multirange',
    rustName: 'sql__pg_catalog__int4multirange__809e',
    args: ['pg_catalog._int4range'],
    result: 'pg_catalog.int4multirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: 'pg_catalog.int4range',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int4multirange"](pg_catalog.int4range)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int4multirange',
    rustName: 'sql__pg_catalog__int4multirange__weie',
    args: ['pg_catalog.int4range'],
    result: 'pg_catalog.int4multirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int4range"](pg_catalog.int4,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int4range',
    rustName: 'sql__pg_catalog__int4range__h2la',
    args: ['pg_catalog.int4', 'pg_catalog.int4'],
    result: 'pg_catalog.int4range',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int4range"](pg_catalog.int4,pg_catalog.int4,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int4range',
    rustName: 'sql__pg_catalog__int4range__dl1b',
    args: ['pg_catalog.int4', 'pg_catalog.int4', 'pg_catalog.text'],
    result: 'pg_catalog.int4range',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int4range_canonical"](pg_catalog.int4range)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int4range_canonical',
    rustName: 'sql__pg_catalog__int4range_canonical__rxi1',
    args: ['pg_catalog.int4range'],
    result: 'pg_catalog.int4range',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int8multirange"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int8multirange',
    rustName: 'sql__pg_catalog__int8multirange__djko',
    args: [],
    result: 'pg_catalog.int8multirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int8multirange"](pg_catalog._int8range)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int8multirange',
    rustName: 'sql__pg_catalog__int8multirange__x1sx',
    args: ['pg_catalog._int8range'],
    result: 'pg_catalog.int8multirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: 'pg_catalog.int8range',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int8multirange"](pg_catalog.int8range)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int8multirange',
    rustName: 'sql__pg_catalog__int8multirange__jzn4',
    args: ['pg_catalog.int8range'],
    result: 'pg_catalog.int8multirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int8range"](pg_catalog.int8,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int8range',
    rustName: 'sql__pg_catalog__int8range__p6bp',
    args: ['pg_catalog.int8', 'pg_catalog.int8'],
    result: 'pg_catalog.int8range',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int8range"](pg_catalog.int8,pg_catalog.int8,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int8range',
    rustName: 'sql__pg_catalog__int8range__k46i',
    args: ['pg_catalog.int8', 'pg_catalog.int8', 'pg_catalog.text'],
    result: 'pg_catalog.int8range',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int8range_canonical"](pg_catalog.int8range)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int8range_canonical',
    rustName: 'sql__pg_catalog__int8range_canonical__wenu',
    args: ['pg_catalog.int8range'],
    result: 'pg_catalog.int8range',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","isempty"](pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'isempty',
    rustName: 'sql__pg_catalog__isempty__t80p',
    args: ['pg_catalog.anymultirange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","isempty"](pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'isempty',
    rustName: 'sql__pg_catalog__isempty__86tf',
    args: ['pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","lower"](pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'lower',
    rustName: 'sql__pg_catalog__lower__eyri',
    args: ['pg_catalog.anymultirange'],
    result: 'pg_catalog.anyelement',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","lower"](pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'lower',
    rustName: 'sql__pg_catalog__lower__ny7i',
    args: ['pg_catalog.anyrange'],
    result: 'pg_catalog.anyelement',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","lower_inc"](pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'lower_inc',
    rustName: 'sql__pg_catalog__lower_inc__0qlg',
    args: ['pg_catalog.anymultirange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","lower_inc"](pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'lower_inc',
    rustName: 'sql__pg_catalog__lower_inc__9bur',
    args: ['pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","lower_inf"](pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'lower_inf',
    rustName: 'sql__pg_catalog__lower_inf__8sw0',
    args: ['pg_catalog.anymultirange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","lower_inf"](pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'lower_inf',
    rustName: 'sql__pg_catalog__lower_inf__wo5x',
    args: ['pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","multirange"](pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'multirange',
    rustName: 'sql__pg_catalog__multirange__ng1w',
    args: ['pg_catalog.anyrange'],
    result: 'pg_catalog.anymultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","multirange_adjacent_multirange"](pg_catalog.anymultirange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_adjacent_multirange',
      rustName: 'sql__pg_catalog__multirange_adjacent_multirange__volo',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_adjacent_range"](pg_catalog.anymultirange,pg_catalog.anyrange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_adjacent_range',
      rustName: 'sql__pg_catalog__multirange_adjacent_range__z75g',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anyrange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_after_multirange"](pg_catalog.anymultirange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_after_multirange',
      rustName: 'sql__pg_catalog__multirange_after_multirange__nrvn',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_after_range"](pg_catalog.anymultirange,pg_catalog.anyrange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_after_range',
      rustName: 'sql__pg_catalog__multirange_after_range__r05j',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anyrange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_before_multirange"](pg_catalog.anymultirange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_before_multirange',
      rustName: 'sql__pg_catalog__multirange_before_multirange__8hjl',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_before_range"](pg_catalog.anymultirange,pg_catalog.anyrange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_before_range',
      rustName: 'sql__pg_catalog__multirange_before_range__5v34',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anyrange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_cmp"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'multirange_cmp',
    rustName: 'sql__pg_catalog__multirange_cmp__mafd',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","multirange_contained_by_multirange"](pg_catalog.anymultirange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_contained_by_multirange',
      rustName: 'sql__pg_catalog__multirange_contained_by_multirange__9c9u',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_contained_by_range"](pg_catalog.anymultirange,pg_catalog.anyrange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_contained_by_range',
      rustName: 'sql__pg_catalog__multirange_contained_by_range__muhz',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anyrange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_contains_elem"](pg_catalog.anymultirange,pg_catalog.anyelement)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_contains_elem',
      rustName: 'sql__pg_catalog__multirange_contains_elem__aq4j',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anyelement'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_contains_multirange"](pg_catalog.anymultirange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_contains_multirange',
      rustName: 'sql__pg_catalog__multirange_contains_multirange__xn5h',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_contains_range"](pg_catalog.anymultirange,pg_catalog.anyrange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_contains_range',
      rustName: 'sql__pg_catalog__multirange_contains_range__bpqf',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anyrange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_eq"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'multirange_eq',
    rustName: 'sql__pg_catalog__multirange_eq__9xy5',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","multirange_ge"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'multirange_ge',
    rustName: 'sql__pg_catalog__multirange_ge__m1wr',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","multirange_gt"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'multirange_gt',
    rustName: 'sql__pg_catalog__multirange_gt__3xub',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","multirange_intersect"](pg_catalog.anymultirange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_intersect',
      rustName: 'sql__pg_catalog__multirange_intersect__ezyb',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.anymultirange',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_intersect_agg_transfn"](pg_catalog.anymultirange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_intersect_agg_transfn',
      rustName: 'sql__pg_catalog__multirange_intersect_agg_transfn__7333',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.anymultirange',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_le"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'multirange_le',
    rustName: 'sql__pg_catalog__multirange_le__3kuk',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","multirange_lt"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'multirange_lt',
    rustName: 'sql__pg_catalog__multirange_lt__8rid',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","multirange_minus"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'multirange_minus',
    rustName: 'sql__pg_catalog__multirange_minus__8qbr',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    result: 'pg_catalog.anymultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","multirange_ne"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'multirange_ne',
    rustName: 'sql__pg_catalog__multirange_ne__fjyh',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","multirange_overlaps_multirange"](pg_catalog.anymultirange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_overlaps_multirange',
      rustName: 'sql__pg_catalog__multirange_overlaps_multirange__93jh',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_overlaps_range"](pg_catalog.anymultirange,pg_catalog.anyrange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_overlaps_range',
      rustName: 'sql__pg_catalog__multirange_overlaps_range__lju4',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anyrange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_overleft_multirange"](pg_catalog.anymultirange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_overleft_multirange',
      rustName: 'sql__pg_catalog__multirange_overleft_multirange__lj1m',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_overleft_range"](pg_catalog.anymultirange,pg_catalog.anyrange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_overleft_range',
      rustName: 'sql__pg_catalog__multirange_overleft_range__q948',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anyrange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_overright_multirange"](pg_catalog.anymultirange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_overright_multirange',
      rustName: 'sql__pg_catalog__multirange_overright_multirange__20d6',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_overright_range"](pg_catalog.anymultirange,pg_catalog.anyrange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_overright_range',
      rustName: 'sql__pg_catalog__multirange_overright_range__j24k',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anyrange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_union"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'multirange_union',
    rustName: 'sql__pg_catalog__multirange_union__3oae',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    result: 'pg_catalog.anymultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","nummultirange"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'nummultirange',
    rustName: 'sql__pg_catalog__nummultirange__qnke',
    args: [],
    result: 'pg_catalog.nummultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","nummultirange"](pg_catalog._numrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'nummultirange',
    rustName: 'sql__pg_catalog__nummultirange__voqt',
    args: ['pg_catalog._numrange'],
    result: 'pg_catalog.nummultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: 'pg_catalog.numrange',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","nummultirange"](pg_catalog.numrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'nummultirange',
    rustName: 'sql__pg_catalog__nummultirange__88ec',
    args: ['pg_catalog.numrange'],
    result: 'pg_catalog.nummultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","numrange"](pg_catalog."numeric",pg_catalog."numeric")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'numrange',
    rustName: 'sql__pg_catalog__numrange__eag6',
    args: ['pg_catalog."numeric"', 'pg_catalog."numeric"'],
    result: 'pg_catalog.numrange',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","numrange"](pg_catalog."numeric",pg_catalog."numeric",pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'numrange',
    rustName: 'sql__pg_catalog__numrange__8ziy',
    args: ['pg_catalog."numeric"', 'pg_catalog."numeric"', 'pg_catalog.text'],
    result: 'pg_catalog.numrange',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_adjacent"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_adjacent',
    rustName: 'sql__pg_catalog__range_adjacent__03u0',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_adjacent_multirange"](pg_catalog.anyrange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'range_adjacent_multirange',
      rustName: 'sql__pg_catalog__range_adjacent_multirange__8wks',
      args: ['pg_catalog.anyrange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","range_after"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_after',
    rustName: 'sql__pg_catalog__range_after__5pak',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_after_multirange"](pg_catalog.anyrange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'range_after_multirange',
      rustName: 'sql__pg_catalog__range_after_multirange__5u82',
      args: ['pg_catalog.anyrange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","range_before"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_before',
    rustName: 'sql__pg_catalog__range_before__z0g8',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_before_multirange"](pg_catalog.anyrange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'range_before_multirange',
      rustName: 'sql__pg_catalog__range_before_multirange__eaoa',
      args: ['pg_catalog.anyrange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","range_cmp"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_cmp',
    rustName: 'sql__pg_catalog__range_cmp__8jgl',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_contained_by"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_contained_by',
    rustName: 'sql__pg_catalog__range_contained_by__ok2x',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_contained_by_multirange"](pg_catalog.anyrange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'range_contained_by_multirange',
      rustName: 'sql__pg_catalog__range_contained_by_multirange__oyeg',
      args: ['pg_catalog.anyrange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","range_contains"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_contains',
    rustName: 'sql__pg_catalog__range_contains__ut37',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_contains_elem"](pg_catalog.anyrange,pg_catalog.anyelement)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_contains_elem',
    rustName: 'sql__pg_catalog__range_contains_elem__wtfe',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyelement'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_contains_multirange"](pg_catalog.anyrange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'range_contains_multirange',
      rustName: 'sql__pg_catalog__range_contains_multirange__n92i',
      args: ['pg_catalog.anyrange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","range_eq"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_eq',
    rustName: 'sql__pg_catalog__range_eq__loxq',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_ge"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_ge',
    rustName: 'sql__pg_catalog__range_ge__i2f0',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_gt"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_gt',
    rustName: 'sql__pg_catalog__range_gt__943z',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_intersect"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_intersect',
    rustName: 'sql__pg_catalog__range_intersect__4pce',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.anyrange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_intersect_agg_transfn"](pg_catalog.anyrange,pg_catalog.anyrange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'range_intersect_agg_transfn',
      rustName: 'sql__pg_catalog__range_intersect_agg_transfn__gcvb',
      args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
      result: 'pg_catalog.anyrange',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","range_le"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_le',
    rustName: 'sql__pg_catalog__range_le__ur15',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_lt"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_lt',
    rustName: 'sql__pg_catalog__range_lt__t1sv',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_merge"](pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_merge',
    rustName: 'sql__pg_catalog__range_merge__f619',
    args: ['pg_catalog.anymultirange'],
    result: 'pg_catalog.anyrange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_merge"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_merge',
    rustName: 'sql__pg_catalog__range_merge__b43r',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.anyrange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_minus"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_minus',
    rustName: 'sql__pg_catalog__range_minus__f67g',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.anyrange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_ne"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_ne',
    rustName: 'sql__pg_catalog__range_ne__mzkw',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_overlaps"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_overlaps',
    rustName: 'sql__pg_catalog__range_overlaps__38jd',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_overlaps_multirange"](pg_catalog.anyrange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'range_overlaps_multirange',
      rustName: 'sql__pg_catalog__range_overlaps_multirange__5sb2',
      args: ['pg_catalog.anyrange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","range_overleft"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_overleft',
    rustName: 'sql__pg_catalog__range_overleft__8k1o',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_overleft_multirange"](pg_catalog.anyrange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'range_overleft_multirange',
      rustName: 'sql__pg_catalog__range_overleft_multirange__zjel',
      args: ['pg_catalog.anyrange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","range_overright"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_overright',
    rustName: 'sql__pg_catalog__range_overright__rl1q',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_overright_multirange"](pg_catalog.anyrange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'range_overright_multirange',
      rustName: 'sql__pg_catalog__range_overright_multirange__c1uw',
      args: ['pg_catalog.anyrange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","range_union"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_union',
    rustName: 'sql__pg_catalog__range_union__8koj',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.anyrange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsmultirange"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsmultirange',
    rustName: 'sql__pg_catalog__tsmultirange__bmb3',
    args: [],
    result: 'pg_catalog.tsmultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsmultirange"](pg_catalog._tsrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsmultirange',
    rustName: 'sql__pg_catalog__tsmultirange__pp1p',
    args: ['pg_catalog._tsrange'],
    result: 'pg_catalog.tsmultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: 'pg_catalog.tsrange',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsmultirange"](pg_catalog.tsrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsmultirange',
    rustName: 'sql__pg_catalog__tsmultirange__kuha',
    args: ['pg_catalog.tsrange'],
    result: 'pg_catalog.tsmultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsrange"](pg_catalog."timestamp",pg_catalog."timestamp")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsrange',
    rustName: 'sql__pg_catalog__tsrange__u3gz',
    args: ['pg_catalog."timestamp"', 'pg_catalog."timestamp"'],
    result: 'pg_catalog.tsrange',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsrange"](pg_catalog."timestamp",pg_catalog."timestamp",pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'tsrange',
      rustName: 'sql__pg_catalog__tsrange__rglb',
      args: ['pg_catalog."timestamp"', 'pg_catalog."timestamp"', 'pg_catalog.text'],
      result: 'pg_catalog.tsrange',
      strict: false,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","tstzmultirange"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tstzmultirange',
    rustName: 'sql__pg_catalog__tstzmultirange__3xsg',
    args: [],
    result: 'pg_catalog.tstzmultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tstzmultirange"](pg_catalog._tstzrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tstzmultirange',
    rustName: 'sql__pg_catalog__tstzmultirange__hkj9',
    args: ['pg_catalog._tstzrange'],
    result: 'pg_catalog.tstzmultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: 'pg_catalog.tstzrange',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tstzmultirange"](pg_catalog.tstzrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tstzmultirange',
    rustName: 'sql__pg_catalog__tstzmultirange__z001',
    args: ['pg_catalog.tstzrange'],
    result: 'pg_catalog.tstzmultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tstzrange"](pg_catalog.timestamptz,pg_catalog.timestamptz)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tstzrange',
    rustName: 'sql__pg_catalog__tstzrange__2y9m',
    args: ['pg_catalog.timestamptz', 'pg_catalog.timestamptz'],
    result: 'pg_catalog.tstzrange',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tstzrange"](pg_catalog.timestamptz,pg_catalog.timestamptz,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'tstzrange',
      rustName: 'sql__pg_catalog__tstzrange__zuff',
      args: ['pg_catalog.timestamptz', 'pg_catalog.timestamptz', 'pg_catalog.text'],
      result: 'pg_catalog.tstzrange',
      strict: false,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","unnest"](pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'unnest',
    rustName: 'sql__pg_catalog__unnest__9069',
    args: ['pg_catalog.anymultirange'],
    result: 'pg_catalog.anyrange',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","upper"](pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'upper',
    rustName: 'sql__pg_catalog__upper__8wv4',
    args: ['pg_catalog.anymultirange'],
    result: 'pg_catalog.anyelement',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","upper"](pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'upper',
    rustName: 'sql__pg_catalog__upper__4y0a',
    args: ['pg_catalog.anyrange'],
    result: 'pg_catalog.anyelement',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","upper_inc"](pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'upper_inc',
    rustName: 'sql__pg_catalog__upper_inc__aqou',
    args: ['pg_catalog.anymultirange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","upper_inc"](pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'upper_inc',
    rustName: 'sql__pg_catalog__upper_inc__vwy8',
    args: ['pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","upper_inf"](pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'upper_inf',
    rustName: 'sql__pg_catalog__upper_inf__2edg',
    args: ['pg_catalog.anymultirange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","upper_inf"](pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'upper_inf',
    rustName: 'sql__pg_catalog__upper_inf__51cc',
    args: ['pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'operator:["pg_catalog","&&"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&&',
    implementation:
      'function:["pg_catalog","multirange_overlaps_multirange"](pg_catalog.anymultirange,pg_catalog.anymultirange)',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","&&"](pg_catalog.anymultirange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&&',
    implementation:
      'function:["pg_catalog","multirange_overlaps_range"](pg_catalog.anymultirange,pg_catalog.anyrange)',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","&&"](pg_catalog.anyrange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&&',
    implementation:
      'function:["pg_catalog","range_overlaps_multirange"](pg_catalog.anyrange,pg_catalog.anymultirange)',
    args: ['pg_catalog.anyrange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","&&"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&&',
    implementation:
      'function:["pg_catalog","range_overlaps"](pg_catalog.anyrange,pg_catalog.anyrange)',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","&<"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&<',
    implementation:
      'function:["pg_catalog","multirange_overleft_multirange"](pg_catalog.anymultirange,pg_catalog.anymultirange)',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","&<"](pg_catalog.anymultirange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&<',
    implementation:
      'function:["pg_catalog","multirange_overleft_range"](pg_catalog.anymultirange,pg_catalog.anyrange)',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","&<"](pg_catalog.anyrange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&<',
    implementation:
      'function:["pg_catalog","range_overleft_multirange"](pg_catalog.anyrange,pg_catalog.anymultirange)',
    args: ['pg_catalog.anyrange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","&<"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&<',
    implementation:
      'function:["pg_catalog","range_overleft"](pg_catalog.anyrange,pg_catalog.anyrange)',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","&>"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&>',
    implementation:
      'function:["pg_catalog","multirange_overright_multirange"](pg_catalog.anymultirange,pg_catalog.anymultirange)',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","&>"](pg_catalog.anymultirange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&>',
    implementation:
      'function:["pg_catalog","multirange_overright_range"](pg_catalog.anymultirange,pg_catalog.anyrange)',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","&>"](pg_catalog.anyrange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&>',
    implementation:
      'function:["pg_catalog","range_overright_multirange"](pg_catalog.anyrange,pg_catalog.anymultirange)',
    args: ['pg_catalog.anyrange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","&>"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&>',
    implementation:
      'function:["pg_catalog","range_overright"](pg_catalog.anyrange,pg_catalog.anyrange)',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","*"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '*',
    implementation:
      'function:["pg_catalog","multirange_intersect"](pg_catalog.anymultirange,pg_catalog.anymultirange)',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.anymultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","*"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '*',
    implementation:
      'function:["pg_catalog","range_intersect"](pg_catalog.anyrange,pg_catalog.anyrange)',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.anyrange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","+"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '+',
    implementation:
      'function:["pg_catalog","multirange_union"](pg_catalog.anymultirange,pg_catalog.anymultirange)',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.anymultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","+"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '+',
    implementation:
      'function:["pg_catalog","range_union"](pg_catalog.anyrange,pg_catalog.anyrange)',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.anyrange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","-"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '-',
    implementation:
      'function:["pg_catalog","multirange_minus"](pg_catalog.anymultirange,pg_catalog.anymultirange)',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.anymultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","-"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '-',
    implementation:
      'function:["pg_catalog","range_minus"](pg_catalog.anyrange,pg_catalog.anyrange)',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.anyrange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","-|-"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '-|-',
    implementation:
      'function:["pg_catalog","multirange_adjacent_multirange"](pg_catalog.anymultirange,pg_catalog.anymultirange)',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","-|-"](pg_catalog.anymultirange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '-|-',
    implementation:
      'function:["pg_catalog","multirange_adjacent_range"](pg_catalog.anymultirange,pg_catalog.anyrange)',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","-|-"](pg_catalog.anyrange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '-|-',
    implementation:
      'function:["pg_catalog","range_adjacent_multirange"](pg_catalog.anyrange,pg_catalog.anymultirange)',
    args: ['pg_catalog.anyrange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","-|-"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '-|-',
    implementation:
      'function:["pg_catalog","range_adjacent"](pg_catalog.anyrange,pg_catalog.anyrange)',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    implementation:
      'function:["pg_catalog","multirange_lt"](pg_catalog.anymultirange,pg_catalog.anymultirange)',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    implementation: 'function:["pg_catalog","range_lt"](pg_catalog.anyrange,pg_catalog.anyrange)',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<<"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<<',
    implementation:
      'function:["pg_catalog","multirange_before_multirange"](pg_catalog.anymultirange,pg_catalog.anymultirange)',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<<"](pg_catalog.anymultirange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<<',
    implementation:
      'function:["pg_catalog","multirange_before_range"](pg_catalog.anymultirange,pg_catalog.anyrange)',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<<"](pg_catalog.anyrange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<<',
    implementation:
      'function:["pg_catalog","range_before_multirange"](pg_catalog.anyrange,pg_catalog.anymultirange)',
    args: ['pg_catalog.anyrange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<<"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<<',
    implementation:
      'function:["pg_catalog","range_before"](pg_catalog.anyrange,pg_catalog.anyrange)',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    implementation:
      'function:["pg_catalog","multirange_le"](pg_catalog.anymultirange,pg_catalog.anymultirange)',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    implementation: 'function:["pg_catalog","range_le"](pg_catalog.anyrange,pg_catalog.anyrange)',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    implementation:
      'function:["pg_catalog","multirange_ne"](pg_catalog.anymultirange,pg_catalog.anymultirange)',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    implementation: 'function:["pg_catalog","range_ne"](pg_catalog.anyrange,pg_catalog.anyrange)',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<@"](pg_catalog.anyelement,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<@',
    implementation:
      'function:["pg_catalog","elem_contained_by_multirange"](pg_catalog.anyelement,pg_catalog.anymultirange)',
    args: ['pg_catalog.anyelement', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anyelement',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<@"](pg_catalog.anyelement,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<@',
    implementation:
      'function:["pg_catalog","elem_contained_by_range"](pg_catalog.anyelement,pg_catalog.anyrange)',
    args: ['pg_catalog.anyelement', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyelement',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<@"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<@',
    implementation:
      'function:["pg_catalog","multirange_contained_by_multirange"](pg_catalog.anymultirange,pg_catalog.anymultirange)',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<@"](pg_catalog.anymultirange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<@',
    implementation:
      'function:["pg_catalog","multirange_contained_by_range"](pg_catalog.anymultirange,pg_catalog.anyrange)',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<@"](pg_catalog.anyrange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<@',
    implementation:
      'function:["pg_catalog","range_contained_by_multirange"](pg_catalog.anyrange,pg_catalog.anymultirange)',
    args: ['pg_catalog.anyrange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<@"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<@',
    implementation:
      'function:["pg_catalog","range_contained_by"](pg_catalog.anyrange,pg_catalog.anyrange)',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    implementation:
      'function:["pg_catalog","multirange_eq"](pg_catalog.anymultirange,pg_catalog.anymultirange)',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    implementation: 'function:["pg_catalog","range_eq"](pg_catalog.anyrange,pg_catalog.anyrange)',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    implementation:
      'function:["pg_catalog","multirange_gt"](pg_catalog.anymultirange,pg_catalog.anymultirange)',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    implementation: 'function:["pg_catalog","range_gt"](pg_catalog.anyrange,pg_catalog.anyrange)',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    implementation:
      'function:["pg_catalog","multirange_ge"](pg_catalog.anymultirange,pg_catalog.anymultirange)',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    implementation: 'function:["pg_catalog","range_ge"](pg_catalog.anyrange,pg_catalog.anyrange)',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">>"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>>',
    implementation:
      'function:["pg_catalog","multirange_after_multirange"](pg_catalog.anymultirange,pg_catalog.anymultirange)',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">>"](pg_catalog.anymultirange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>>',
    implementation:
      'function:["pg_catalog","multirange_after_range"](pg_catalog.anymultirange,pg_catalog.anyrange)',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">>"](pg_catalog.anyrange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>>',
    implementation:
      'function:["pg_catalog","range_after_multirange"](pg_catalog.anyrange,pg_catalog.anymultirange)',
    args: ['pg_catalog.anyrange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">>"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>>',
    implementation:
      'function:["pg_catalog","range_after"](pg_catalog.anyrange,pg_catalog.anyrange)',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","@>"](pg_catalog.anymultirange,pg_catalog.anyelement)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@>',
    implementation:
      'function:["pg_catalog","multirange_contains_elem"](pg_catalog.anymultirange,pg_catalog.anyelement)',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anyelement'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anyelement',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","@>"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@>',
    implementation:
      'function:["pg_catalog","multirange_contains_multirange"](pg_catalog.anymultirange,pg_catalog.anymultirange)',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","@>"](pg_catalog.anymultirange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@>',
    implementation:
      'function:["pg_catalog","multirange_contains_range"](pg_catalog.anymultirange,pg_catalog.anyrange)',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","@>"](pg_catalog.anyrange,pg_catalog.anyelement)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@>',
    implementation:
      'function:["pg_catalog","range_contains_elem"](pg_catalog.anyrange,pg_catalog.anyelement)',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyelement'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyelement',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","@>"](pg_catalog.anyrange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@>',
    implementation:
      'function:["pg_catalog","range_contains_multirange"](pg_catalog.anyrange,pg_catalog.anymultirange)',
    args: ['pg_catalog.anyrange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","@>"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@>',
    implementation:
      'function:["pg_catalog","range_contains"](pg_catalog.anyrange,pg_catalog.anyrange)',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
} as const
