export const PG18_RANGES = {
  'function:["pg_catalog","datemultirange"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'datemultirange',
    args: [],
    result: 'pg_catalog.datemultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","datemultirange"](pg_catalog._daterange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'datemultirange',
    args: ['pg_catalog._daterange'],
    result: 'pg_catalog.datemultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: 'pg_catalog.daterange',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","datemultirange"](pg_catalog.daterange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'datemultirange',
    args: ['pg_catalog.daterange'],
    result: 'pg_catalog.datemultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","daterange"](pg_catalog.date,pg_catalog.date)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'daterange',
    args: ['pg_catalog.date', 'pg_catalog.date'],
    result: 'pg_catalog.daterange',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","daterange"](pg_catalog.date,pg_catalog.date,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'daterange',
    args: ['pg_catalog.date', 'pg_catalog.date', 'pg_catalog.text'],
    result: 'pg_catalog.daterange',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","daterange_canonical"](pg_catalog.daterange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'daterange_canonical',
    args: ['pg_catalog.daterange'],
    result: 'pg_catalog.daterange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","elem_contained_by_multirange"](pg_catalog.anyelement,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'elem_contained_by_multirange',
      args: ['pg_catalog.anyelement', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","elem_contained_by_range"](pg_catalog.anyelement,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'elem_contained_by_range',
    args: ['pg_catalog.anyelement', 'pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hash_multirange"](pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hash_multirange',
    args: ['pg_catalog.anymultirange'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hash_multirange_extended"](pg_catalog.anymultirange,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hash_multirange_extended',
    args: ['pg_catalog.anymultirange', 'pg_catalog.int8'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hash_range"](pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hash_range',
    args: ['pg_catalog.anyrange'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hash_range_extended"](pg_catalog.anyrange,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hash_range_extended',
    args: ['pg_catalog.anyrange', 'pg_catalog.int8'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int4multirange"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int4multirange',
    args: [],
    result: 'pg_catalog.int4multirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int4multirange"](pg_catalog._int4range)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int4multirange',
    args: ['pg_catalog._int4range'],
    result: 'pg_catalog.int4multirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: 'pg_catalog.int4range',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int4multirange"](pg_catalog.int4range)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int4multirange',
    args: ['pg_catalog.int4range'],
    result: 'pg_catalog.int4multirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int4range"](pg_catalog.int4,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int4range',
    args: ['pg_catalog.int4', 'pg_catalog.int4'],
    result: 'pg_catalog.int4range',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int4range"](pg_catalog.int4,pg_catalog.int4,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int4range',
    args: ['pg_catalog.int4', 'pg_catalog.int4', 'pg_catalog.text'],
    result: 'pg_catalog.int4range',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int4range_canonical"](pg_catalog.int4range)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int4range_canonical',
    args: ['pg_catalog.int4range'],
    result: 'pg_catalog.int4range',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int8multirange"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int8multirange',
    args: [],
    result: 'pg_catalog.int8multirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int8multirange"](pg_catalog._int8range)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int8multirange',
    args: ['pg_catalog._int8range'],
    result: 'pg_catalog.int8multirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: 'pg_catalog.int8range',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int8multirange"](pg_catalog.int8range)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int8multirange',
    args: ['pg_catalog.int8range'],
    result: 'pg_catalog.int8multirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int8range"](pg_catalog.int8,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int8range',
    args: ['pg_catalog.int8', 'pg_catalog.int8'],
    result: 'pg_catalog.int8range',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int8range"](pg_catalog.int8,pg_catalog.int8,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int8range',
    args: ['pg_catalog.int8', 'pg_catalog.int8', 'pg_catalog.text'],
    result: 'pg_catalog.int8range',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","int8range_canonical"](pg_catalog.int8range)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'int8range_canonical',
    args: ['pg_catalog.int8range'],
    result: 'pg_catalog.int8range',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","isempty"](pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'isempty',
    args: ['pg_catalog.anymultirange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","isempty"](pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'isempty',
    args: ['pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","lower"](pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'lower',
    args: ['pg_catalog.anymultirange'],
    result: 'pg_catalog.anyelement',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","lower"](pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'lower',
    args: ['pg_catalog.anyrange'],
    result: 'pg_catalog.anyelement',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","lower_inc"](pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'lower_inc',
    args: ['pg_catalog.anymultirange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","lower_inc"](pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'lower_inc',
    args: ['pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","lower_inf"](pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'lower_inf',
    args: ['pg_catalog.anymultirange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","lower_inf"](pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'lower_inf',
    args: ['pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","multirange"](pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'multirange',
    args: ['pg_catalog.anyrange'],
    result: 'pg_catalog.anymultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","multirange_adjacent_multirange"](pg_catalog.anymultirange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_adjacent_multirange',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_adjacent_range"](pg_catalog.anymultirange,pg_catalog.anyrange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_adjacent_range',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anyrange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_after_multirange"](pg_catalog.anymultirange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_after_multirange',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_after_range"](pg_catalog.anymultirange,pg_catalog.anyrange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_after_range',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anyrange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_before_multirange"](pg_catalog.anymultirange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_before_multirange',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_before_range"](pg_catalog.anymultirange,pg_catalog.anyrange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_before_range',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anyrange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_cmp"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'multirange_cmp',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","multirange_contained_by_multirange"](pg_catalog.anymultirange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_contained_by_multirange',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_contained_by_range"](pg_catalog.anymultirange,pg_catalog.anyrange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_contained_by_range',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anyrange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_contains_elem"](pg_catalog.anymultirange,pg_catalog.anyelement)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_contains_elem',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anyelement'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_contains_multirange"](pg_catalog.anymultirange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_contains_multirange',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_contains_range"](pg_catalog.anymultirange,pg_catalog.anyrange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_contains_range',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anyrange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_eq"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'multirange_eq',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","multirange_ge"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'multirange_ge',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","multirange_gt"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'multirange_gt',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","multirange_intersect"](pg_catalog.anymultirange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_intersect',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.anymultirange',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_intersect_agg_transfn"](pg_catalog.anymultirange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_intersect_agg_transfn',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.anymultirange',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_le"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'multirange_le',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","multirange_lt"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'multirange_lt',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","multirange_minus"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'multirange_minus',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    result: 'pg_catalog.anymultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","multirange_ne"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'multirange_ne',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","multirange_overlaps_multirange"](pg_catalog.anymultirange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_overlaps_multirange',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_overlaps_range"](pg_catalog.anymultirange,pg_catalog.anyrange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_overlaps_range',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anyrange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_overleft_multirange"](pg_catalog.anymultirange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_overleft_multirange',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_overleft_range"](pg_catalog.anymultirange,pg_catalog.anyrange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_overleft_range',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anyrange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_overright_multirange"](pg_catalog.anymultirange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_overright_multirange',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_overright_range"](pg_catalog.anymultirange,pg_catalog.anyrange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'multirange_overright_range',
      args: ['pg_catalog.anymultirange', 'pg_catalog.anyrange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","multirange_union"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'multirange_union',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    result: 'pg_catalog.anymultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","nummultirange"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'nummultirange',
    args: [],
    result: 'pg_catalog.nummultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","nummultirange"](pg_catalog._numrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'nummultirange',
    args: ['pg_catalog._numrange'],
    result: 'pg_catalog.nummultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: 'pg_catalog.numrange',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","nummultirange"](pg_catalog.numrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'nummultirange',
    args: ['pg_catalog.numrange'],
    result: 'pg_catalog.nummultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","numrange"](pg_catalog."numeric",pg_catalog."numeric")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'numrange',
    args: ['pg_catalog."numeric"', 'pg_catalog."numeric"'],
    result: 'pg_catalog.numrange',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","numrange"](pg_catalog."numeric",pg_catalog."numeric",pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'numrange',
    args: ['pg_catalog."numeric"', 'pg_catalog."numeric"', 'pg_catalog.text'],
    result: 'pg_catalog.numrange',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_adjacent"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_adjacent',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_adjacent_multirange"](pg_catalog.anyrange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'range_adjacent_multirange',
      args: ['pg_catalog.anyrange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","range_after"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_after',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_after_multirange"](pg_catalog.anyrange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'range_after_multirange',
      args: ['pg_catalog.anyrange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","range_before"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_before',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_before_multirange"](pg_catalog.anyrange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'range_before_multirange',
      args: ['pg_catalog.anyrange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","range_cmp"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_cmp',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_contained_by"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_contained_by',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_contained_by_multirange"](pg_catalog.anyrange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'range_contained_by_multirange',
      args: ['pg_catalog.anyrange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","range_contains"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_contains',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_contains_elem"](pg_catalog.anyrange,pg_catalog.anyelement)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_contains_elem',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyelement'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_contains_multirange"](pg_catalog.anyrange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'range_contains_multirange',
      args: ['pg_catalog.anyrange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","range_eq"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_eq',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_ge"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_ge',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_gt"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_gt',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_intersect"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_intersect',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.anyrange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_intersect_agg_transfn"](pg_catalog.anyrange,pg_catalog.anyrange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'range_intersect_agg_transfn',
      args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
      result: 'pg_catalog.anyrange',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","range_le"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_le',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_lt"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_lt',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_merge"](pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_merge',
    args: ['pg_catalog.anymultirange'],
    result: 'pg_catalog.anyrange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_merge"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_merge',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.anyrange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_minus"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_minus',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.anyrange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_ne"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_ne',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_overlaps"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_overlaps',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_overlaps_multirange"](pg_catalog.anyrange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'range_overlaps_multirange',
      args: ['pg_catalog.anyrange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","range_overleft"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_overleft',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_overleft_multirange"](pg_catalog.anyrange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'range_overleft_multirange',
      args: ['pg_catalog.anyrange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","range_overright"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_overright',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","range_overright_multirange"](pg_catalog.anyrange,pg_catalog.anymultirange)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'range_overright_multirange',
      args: ['pg_catalog.anyrange', 'pg_catalog.anymultirange'],
      result: 'pg_catalog.bool',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","range_union"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'range_union',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    result: 'pg_catalog.anyrange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsmultirange"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsmultirange',
    args: [],
    result: 'pg_catalog.tsmultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsmultirange"](pg_catalog._tsrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsmultirange',
    args: ['pg_catalog._tsrange'],
    result: 'pg_catalog.tsmultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: 'pg_catalog.tsrange',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsmultirange"](pg_catalog.tsrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsmultirange',
    args: ['pg_catalog.tsrange'],
    result: 'pg_catalog.tsmultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsrange"](pg_catalog."timestamp",pg_catalog."timestamp")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsrange',
    args: ['pg_catalog."timestamp"', 'pg_catalog."timestamp"'],
    result: 'pg_catalog.tsrange',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsrange"](pg_catalog."timestamp",pg_catalog."timestamp",pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'tsrange',
      args: ['pg_catalog."timestamp"', 'pg_catalog."timestamp"', 'pg_catalog.text'],
      result: 'pg_catalog.tsrange',
      strict: false,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","tstzmultirange"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tstzmultirange',
    args: [],
    result: 'pg_catalog.tstzmultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tstzmultirange"](pg_catalog._tstzrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tstzmultirange',
    args: ['pg_catalog._tstzrange'],
    result: 'pg_catalog.tstzmultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: 'pg_catalog.tstzrange',
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tstzmultirange"](pg_catalog.tstzrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tstzmultirange',
    args: ['pg_catalog.tstzrange'],
    result: 'pg_catalog.tstzmultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tstzrange"](pg_catalog.timestamptz,pg_catalog.timestamptz)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tstzrange',
    args: ['pg_catalog.timestamptz', 'pg_catalog.timestamptz'],
    result: 'pg_catalog.tstzrange',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tstzrange"](pg_catalog.timestamptz,pg_catalog.timestamptz,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'tstzrange',
      args: ['pg_catalog.timestamptz', 'pg_catalog.timestamptz', 'pg_catalog.text'],
      result: 'pg_catalog.tstzrange',
      strict: false,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","unnest"](pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'unnest',
    args: ['pg_catalog.anymultirange'],
    result: 'pg_catalog.anyrange',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","upper"](pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'upper',
    args: ['pg_catalog.anymultirange'],
    result: 'pg_catalog.anyelement',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","upper"](pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'upper',
    args: ['pg_catalog.anyrange'],
    result: 'pg_catalog.anyelement',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","upper_inc"](pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'upper_inc',
    args: ['pg_catalog.anymultirange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","upper_inc"](pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'upper_inc',
    args: ['pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","upper_inf"](pg_catalog.anymultirange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'upper_inf',
    args: ['pg_catalog.anymultirange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","upper_inf"](pg_catalog.anyrange)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'upper_inf',
    args: ['pg_catalog.anyrange'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'operator:["pg_catalog","&&"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&&',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","&&"](pg_catalog.anymultirange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&&',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","&&"](pg_catalog.anyrange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&&',
    args: ['pg_catalog.anyrange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","&&"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&&',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","&<"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&<',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","&<"](pg_catalog.anymultirange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&<',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","&<"](pg_catalog.anyrange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&<',
    args: ['pg_catalog.anyrange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","&<"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&<',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","&>"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&>',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","&>"](pg_catalog.anymultirange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&>',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","&>"](pg_catalog.anyrange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&>',
    args: ['pg_catalog.anyrange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","&>"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&>',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","*"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '*',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.anymultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","*"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '*',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.anyrange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","+"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '+',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.anymultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","+"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '+',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.anyrange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","-"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '-',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.anymultirange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","-"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '-',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.anyrange',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","-|-"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '-|-',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","-|-"](pg_catalog.anymultirange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '-|-',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","-|-"](pg_catalog.anyrange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '-|-',
    args: ['pg_catalog.anyrange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","-|-"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '-|-',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<<"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<<',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<<"](pg_catalog.anymultirange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<<',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<<"](pg_catalog.anyrange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<<',
    args: ['pg_catalog.anyrange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<<"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<<',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<@"](pg_catalog.anyelement,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<@',
    args: ['pg_catalog.anyelement', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anyelement',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<@"](pg_catalog.anyelement,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<@',
    args: ['pg_catalog.anyelement', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyelement',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<@"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<@',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<@"](pg_catalog.anymultirange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<@',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<@"](pg_catalog.anyrange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<@',
    args: ['pg_catalog.anyrange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<@"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<@',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">>"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>>',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">>"](pg_catalog.anymultirange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>>',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">>"](pg_catalog.anyrange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>>',
    args: ['pg_catalog.anyrange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">>"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>>',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","@>"](pg_catalog.anymultirange,pg_catalog.anyelement)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@>',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anyelement'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anyelement',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","@>"](pg_catalog.anymultirange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@>',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","@>"](pg_catalog.anymultirange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@>',
    args: ['pg_catalog.anymultirange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anymultirange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","@>"](pg_catalog.anyrange,pg_catalog.anyelement)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@>',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyelement'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyelement',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","@>"](pg_catalog.anyrange,pg_catalog.anymultirange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@>',
    args: ['pg_catalog.anyrange', 'pg_catalog.anymultirange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anymultirange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","@>"](pg_catalog.anyrange,pg_catalog.anyrange)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@>',
    args: ['pg_catalog.anyrange', 'pg_catalog.anyrange'],
    left: 'pg_catalog.anyrange',
    right: 'pg_catalog.anyrange',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
} as const
