export const PG18_TEXT_SEARCH = {
  'function:["pg_catalog","array_to_tsvector"](pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_to_tsvector',
    rustName: 'sql__pg_catalog__array_to_tsvector__y8ia',
    args: ['pg_catalog._text'],
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_to_tsvector"](pg_catalog."json",pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_to_tsvector',
    rustName: 'sql__pg_catalog__json_to_tsvector__jl7e',
    args: ['pg_catalog."json"', 'pg_catalog.jsonb'],
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_to_tsvector"](pg_catalog.regconfig,pg_catalog."json",pg_catalog.jsonb)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'json_to_tsvector',
      rustName: 'sql__pg_catalog__json_to_tsvector__1l9c',
      args: ['pg_catalog.regconfig', 'pg_catalog."json"', 'pg_catalog.jsonb'],
      result: 'pg_catalog.tsvector',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","jsonb_to_tsvector"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_to_tsvector',
    rustName: 'sql__pg_catalog__jsonb_to_tsvector__g0su',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_to_tsvector"](pg_catalog.regconfig,pg_catalog.jsonb,pg_catalog.jsonb)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'jsonb_to_tsvector',
      rustName: 'sql__pg_catalog__jsonb_to_tsvector__u1wn',
      args: ['pg_catalog.regconfig', 'pg_catalog.jsonb', 'pg_catalog.jsonb'],
      result: 'pg_catalog.tsvector',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","length"](pg_catalog.tsvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'length',
    rustName: 'sql__pg_catalog__length__grcw',
    args: ['pg_catalog.tsvector'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","numnode"](pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'numnode',
    rustName: 'sql__pg_catalog__numnode__7bkv',
    args: ['pg_catalog.tsquery'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","phraseto_tsquery"](pg_catalog.regconfig,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'phraseto_tsquery',
    rustName: 'sql__pg_catalog__phraseto_tsquery__uk9z',
    args: ['pg_catalog.regconfig', 'pg_catalog.text'],
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","phraseto_tsquery"](pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'phraseto_tsquery',
    rustName: 'sql__pg_catalog__phraseto_tsquery__kz6o',
    args: ['pg_catalog.text'],
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","plainto_tsquery"](pg_catalog.regconfig,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'plainto_tsquery',
    rustName: 'sql__pg_catalog__plainto_tsquery__c30q',
    args: ['pg_catalog.regconfig', 'pg_catalog.text'],
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","plainto_tsquery"](pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'plainto_tsquery',
    rustName: 'sql__pg_catalog__plainto_tsquery__1yb3',
    args: ['pg_catalog.text'],
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","querytree"](pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'querytree',
    rustName: 'sql__pg_catalog__querytree__8aj6',
    args: ['pg_catalog.tsquery'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","setweight"](pg_catalog.tsvector,pg_catalog."char")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'setweight',
    rustName: 'sql__pg_catalog__setweight__hza4',
    args: ['pg_catalog.tsvector', 'pg_catalog."char"'],
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","setweight"](pg_catalog.tsvector,pg_catalog."char",pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'setweight',
    rustName: 'sql__pg_catalog__setweight__ozd9',
    args: ['pg_catalog.tsvector', 'pg_catalog."char"', 'pg_catalog._text'],
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","strip"](pg_catalog.tsvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'strip',
    rustName: 'sql__pg_catalog__strip__3rdv',
    args: ['pg_catalog.tsvector'],
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","to_tsquery"](pg_catalog.regconfig,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'to_tsquery',
    rustName: 'sql__pg_catalog__to_tsquery__faqh',
    args: ['pg_catalog.regconfig', 'pg_catalog.text'],
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","to_tsquery"](pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'to_tsquery',
    rustName: 'sql__pg_catalog__to_tsquery__imje',
    args: ['pg_catalog.text'],
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","to_tsvector"](pg_catalog."json")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'to_tsvector',
    rustName: 'sql__pg_catalog__to_tsvector__72ti',
    args: ['pg_catalog."json"'],
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","to_tsvector"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'to_tsvector',
    rustName: 'sql__pg_catalog__to_tsvector__1kti',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","to_tsvector"](pg_catalog.regconfig,pg_catalog."json")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'to_tsvector',
    rustName: 'sql__pg_catalog__to_tsvector__72kw',
    args: ['pg_catalog.regconfig', 'pg_catalog."json"'],
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","to_tsvector"](pg_catalog.regconfig,pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'to_tsvector',
    rustName: 'sql__pg_catalog__to_tsvector__zsmh',
    args: ['pg_catalog.regconfig', 'pg_catalog.jsonb'],
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","to_tsvector"](pg_catalog.regconfig,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'to_tsvector',
    rustName: 'sql__pg_catalog__to_tsvector__669y',
    args: ['pg_catalog.regconfig', 'pg_catalog.text'],
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","to_tsvector"](pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'to_tsvector',
    rustName: 'sql__pg_catalog__to_tsvector__g0bj',
    args: ['pg_catalog.text'],
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_delete"](pg_catalog.tsvector,pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_delete',
    rustName: 'sql__pg_catalog__ts_delete__ytqn',
    args: ['pg_catalog.tsvector', 'pg_catalog._text'],
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_delete"](pg_catalog.tsvector,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_delete',
    rustName: 'sql__pg_catalog__ts_delete__y2kd',
    args: ['pg_catalog.tsvector', 'pg_catalog.text'],
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_filter"](pg_catalog.tsvector,pg_catalog._char)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_filter',
    rustName: 'sql__pg_catalog__ts_filter__82l1',
    args: ['pg_catalog.tsvector', 'pg_catalog._char'],
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_headline"](pg_catalog.text,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_headline',
    rustName: 'sql__pg_catalog__ts_headline__kx2h',
    args: ['pg_catalog.text', 'pg_catalog.tsquery'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_headline"](pg_catalog.text,pg_catalog.tsquery,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_headline',
    rustName: 'sql__pg_catalog__ts_headline__f0qo',
    args: ['pg_catalog.text', 'pg_catalog.tsquery', 'pg_catalog.text'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_match_qv"](pg_catalog.tsquery,pg_catalog.tsvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_match_qv',
    rustName: 'sql__pg_catalog__ts_match_qv__ib1m',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsvector'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_match_tq"](pg_catalog.text,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_match_tq',
    rustName: 'sql__pg_catalog__ts_match_tq__9lfe',
    args: ['pg_catalog.text', 'pg_catalog.tsquery'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_match_vq"](pg_catalog.tsvector,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_match_vq',
    rustName: 'sql__pg_catalog__ts_match_vq__53kf',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsquery'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_rank"](pg_catalog.tsvector,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_rank',
    rustName: 'sql__pg_catalog__ts_rank__fite',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsquery'],
    result: 'pg_catalog.float4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_rank"](pg_catalog.tsvector,pg_catalog.tsquery,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_rank',
    rustName: 'sql__pg_catalog__ts_rank__d2j5',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsquery', 'pg_catalog.int4'],
    result: 'pg_catalog.float4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_rank_cd"](pg_catalog.tsvector,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_rank_cd',
    rustName: 'sql__pg_catalog__ts_rank_cd__rycu',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsquery'],
    result: 'pg_catalog.float4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_rank_cd"](pg_catalog.tsvector,pg_catalog.tsquery,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_rank_cd',
    rustName: 'sql__pg_catalog__ts_rank_cd__tqso',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsquery', 'pg_catalog.int4'],
    result: 'pg_catalog.float4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_rewrite"](pg_catalog.tsquery,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_rewrite',
    rustName: 'sql__pg_catalog__ts_rewrite__7nov',
    args: ['pg_catalog.tsquery', 'pg_catalog.text'],
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_rewrite"](pg_catalog.tsquery,pg_catalog.tsquery,pg_catalog.tsquery)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'ts_rewrite',
      rustName: 'sql__pg_catalog__ts_rewrite__2hpb',
      args: ['pg_catalog.tsquery', 'pg_catalog.tsquery', 'pg_catalog.tsquery'],
      result: 'pg_catalog.tsquery',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","tsq_mcontained"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsq_mcontained',
    rustName: 'sql__pg_catalog__tsq_mcontained__4g5m',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsq_mcontains"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsq_mcontains',
    rustName: 'sql__pg_catalog__tsq_mcontains__d21x',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsquery_and"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsquery_and',
    rustName: 'sql__pg_catalog__tsquery_and__zwff',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsquery_cmp"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsquery_cmp',
    rustName: 'sql__pg_catalog__tsquery_cmp__1oet',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsquery_eq"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsquery_eq',
    rustName: 'sql__pg_catalog__tsquery_eq__d4ao',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsquery_ge"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsquery_ge',
    rustName: 'sql__pg_catalog__tsquery_ge__0jdt',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsquery_gt"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsquery_gt',
    rustName: 'sql__pg_catalog__tsquery_gt__6cq7',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsquery_le"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsquery_le',
    rustName: 'sql__pg_catalog__tsquery_le__3i4m',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsquery_lt"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsquery_lt',
    rustName: 'sql__pg_catalog__tsquery_lt__zocf',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsquery_ne"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsquery_ne',
    rustName: 'sql__pg_catalog__tsquery_ne__2lq4',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsquery_not"](pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsquery_not',
    rustName: 'sql__pg_catalog__tsquery_not__5zwa',
    args: ['pg_catalog.tsquery'],
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsquery_or"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsquery_or',
    rustName: 'sql__pg_catalog__tsquery_or__le7y',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsquery_phrase"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsquery_phrase',
    rustName: 'sql__pg_catalog__tsquery_phrase__gq2o',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsquery_phrase"](pg_catalog.tsquery,pg_catalog.tsquery,pg_catalog.int4)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'tsquery_phrase',
      rustName: 'sql__pg_catalog__tsquery_phrase__u1ck',
      args: ['pg_catalog.tsquery', 'pg_catalog.tsquery', 'pg_catalog.int4'],
      result: 'pg_catalog.tsquery',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","tsvector_cmp"](pg_catalog.tsvector,pg_catalog.tsvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsvector_cmp',
    rustName: 'sql__pg_catalog__tsvector_cmp__xinv',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsvector'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsvector_concat"](pg_catalog.tsvector,pg_catalog.tsvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsvector_concat',
    rustName: 'sql__pg_catalog__tsvector_concat__0ejl',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsvector'],
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsvector_eq"](pg_catalog.tsvector,pg_catalog.tsvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsvector_eq',
    rustName: 'sql__pg_catalog__tsvector_eq__aqk8',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsvector'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsvector_ge"](pg_catalog.tsvector,pg_catalog.tsvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsvector_ge',
    rustName: 'sql__pg_catalog__tsvector_ge__sjck',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsvector'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsvector_gt"](pg_catalog.tsvector,pg_catalog.tsvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsvector_gt',
    rustName: 'sql__pg_catalog__tsvector_gt__dorq',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsvector'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsvector_le"](pg_catalog.tsvector,pg_catalog.tsvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsvector_le',
    rustName: 'sql__pg_catalog__tsvector_le__7xey',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsvector'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsvector_lt"](pg_catalog.tsvector,pg_catalog.tsvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsvector_lt',
    rustName: 'sql__pg_catalog__tsvector_lt__6duo',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsvector'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsvector_ne"](pg_catalog.tsvector,pg_catalog.tsvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsvector_ne',
    rustName: 'sql__pg_catalog__tsvector_ne__v0j3',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsvector'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","unnest"](pg_catalog.tsvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'unnest',
    rustName: 'sql__pg_catalog__unnest__20ne',
    args: ['pg_catalog.tsvector'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","websearch_to_tsquery"](pg_catalog.regconfig,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'websearch_to_tsquery',
    rustName: 'sql__pg_catalog__websearch_to_tsquery__09a0',
    args: ['pg_catalog.regconfig', 'pg_catalog.text'],
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","websearch_to_tsquery"](pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'websearch_to_tsquery',
    rustName: 'sql__pg_catalog__websearch_to_tsquery__1qf6',
    args: ['pg_catalog.text'],
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'operator:["pg_catalog","!!"](,pg_catalog.tsquery)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '!!',
    implementation: 'function:["pg_catalog","tsquery_not"](pg_catalog.tsquery)',
    args: ['pg_catalog.tsquery'],
    left: null,
    right: 'pg_catalog.tsquery',
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","&&"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&&',
    implementation: 'function:["pg_catalog","tsquery_and"](pg_catalog.tsquery,pg_catalog.tsquery)',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    left: 'pg_catalog.tsquery',
    right: 'pg_catalog.tsquery',
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    implementation: 'function:["pg_catalog","tsquery_lt"](pg_catalog.tsquery,pg_catalog.tsquery)',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    left: 'pg_catalog.tsquery',
    right: 'pg_catalog.tsquery',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.tsvector,pg_catalog.tsvector)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    implementation:
      'function:["pg_catalog","tsvector_lt"](pg_catalog.tsvector,pg_catalog.tsvector)',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsvector'],
    left: 'pg_catalog.tsvector',
    right: 'pg_catalog.tsvector',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<->"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<->',
    implementation:
      'function:["pg_catalog","tsquery_phrase"](pg_catalog.tsquery,pg_catalog.tsquery)',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    left: 'pg_catalog.tsquery',
    right: 'pg_catalog.tsquery',
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    implementation: 'function:["pg_catalog","tsquery_le"](pg_catalog.tsquery,pg_catalog.tsquery)',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    left: 'pg_catalog.tsquery',
    right: 'pg_catalog.tsquery',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.tsvector,pg_catalog.tsvector)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    implementation:
      'function:["pg_catalog","tsvector_le"](pg_catalog.tsvector,pg_catalog.tsvector)',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsvector'],
    left: 'pg_catalog.tsvector',
    right: 'pg_catalog.tsvector',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    implementation: 'function:["pg_catalog","tsquery_ne"](pg_catalog.tsquery,pg_catalog.tsquery)',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    left: 'pg_catalog.tsquery',
    right: 'pg_catalog.tsquery',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.tsvector,pg_catalog.tsvector)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    implementation:
      'function:["pg_catalog","tsvector_ne"](pg_catalog.tsvector,pg_catalog.tsvector)',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsvector'],
    left: 'pg_catalog.tsvector',
    right: 'pg_catalog.tsvector',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<@"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<@',
    implementation:
      'function:["pg_catalog","tsq_mcontained"](pg_catalog.tsquery,pg_catalog.tsquery)',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    left: 'pg_catalog.tsquery',
    right: 'pg_catalog.tsquery',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    implementation: 'function:["pg_catalog","tsquery_eq"](pg_catalog.tsquery,pg_catalog.tsquery)',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    left: 'pg_catalog.tsquery',
    right: 'pg_catalog.tsquery',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.tsvector,pg_catalog.tsvector)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    implementation:
      'function:["pg_catalog","tsvector_eq"](pg_catalog.tsvector,pg_catalog.tsvector)',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsvector'],
    left: 'pg_catalog.tsvector',
    right: 'pg_catalog.tsvector',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    implementation: 'function:["pg_catalog","tsquery_gt"](pg_catalog.tsquery,pg_catalog.tsquery)',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    left: 'pg_catalog.tsquery',
    right: 'pg_catalog.tsquery',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.tsvector,pg_catalog.tsvector)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    implementation:
      'function:["pg_catalog","tsvector_gt"](pg_catalog.tsvector,pg_catalog.tsvector)',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsvector'],
    left: 'pg_catalog.tsvector',
    right: 'pg_catalog.tsvector',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    implementation: 'function:["pg_catalog","tsquery_ge"](pg_catalog.tsquery,pg_catalog.tsquery)',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    left: 'pg_catalog.tsquery',
    right: 'pg_catalog.tsquery',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.tsvector,pg_catalog.tsvector)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    implementation:
      'function:["pg_catalog","tsvector_ge"](pg_catalog.tsvector,pg_catalog.tsvector)',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsvector'],
    left: 'pg_catalog.tsvector',
    right: 'pg_catalog.tsvector',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","@>"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@>',
    implementation:
      'function:["pg_catalog","tsq_mcontains"](pg_catalog.tsquery,pg_catalog.tsquery)',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    left: 'pg_catalog.tsquery',
    right: 'pg_catalog.tsquery',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","@@"](pg_catalog.text,pg_catalog.tsquery)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@@',
    implementation: 'function:["pg_catalog","ts_match_tq"](pg_catalog.text,pg_catalog.tsquery)',
    args: ['pg_catalog.text', 'pg_catalog.tsquery'],
    left: 'pg_catalog.text',
    right: 'pg_catalog.tsquery',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 's',
    returnsSet: false,
  },
  'operator:["pg_catalog","@@"](pg_catalog.tsquery,pg_catalog.tsvector)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@@',
    implementation: 'function:["pg_catalog","ts_match_qv"](pg_catalog.tsquery,pg_catalog.tsvector)',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsvector'],
    left: 'pg_catalog.tsquery',
    right: 'pg_catalog.tsvector',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","@@"](pg_catalog.tsvector,pg_catalog.tsquery)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@@',
    implementation: 'function:["pg_catalog","ts_match_vq"](pg_catalog.tsvector,pg_catalog.tsquery)',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsquery'],
    left: 'pg_catalog.tsvector',
    right: 'pg_catalog.tsquery',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","@@@"](pg_catalog.tsquery,pg_catalog.tsvector)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@@@',
    implementation: 'function:["pg_catalog","ts_match_qv"](pg_catalog.tsquery,pg_catalog.tsvector)',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsvector'],
    left: 'pg_catalog.tsquery',
    right: 'pg_catalog.tsvector',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","@@@"](pg_catalog.tsvector,pg_catalog.tsquery)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@@@',
    implementation: 'function:["pg_catalog","ts_match_vq"](pg_catalog.tsvector,pg_catalog.tsquery)',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsquery'],
    left: 'pg_catalog.tsvector',
    right: 'pg_catalog.tsquery',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","||"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '||',
    implementation: 'function:["pg_catalog","tsquery_or"](pg_catalog.tsquery,pg_catalog.tsquery)',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    left: 'pg_catalog.tsquery',
    right: 'pg_catalog.tsquery',
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","||"](pg_catalog.tsvector,pg_catalog.tsvector)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '||',
    implementation:
      'function:["pg_catalog","tsvector_concat"](pg_catalog.tsvector,pg_catalog.tsvector)',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsvector'],
    left: 'pg_catalog.tsvector',
    right: 'pg_catalog.tsvector',
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
} as const
