export const PG18_TEXT_SEARCH = {
  'function:["pg_catalog","array_to_tsvector"](pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'array_to_tsvector',
    args: ['pg_catalog._text'],
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_to_tsvector"](pg_catalog."json",pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'json_to_tsvector',
    args: ['pg_catalog."json"', 'pg_catalog.jsonb'],
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","json_to_tsvector"](pg_catalog.regconfig,pg_catalog."json",pg_catalog.jsonb)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'json_to_tsvector',
      args: ['pg_catalog.regconfig', 'pg_catalog."json"', 'pg_catalog.jsonb'],
      result: 'pg_catalog.tsvector',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","jsonb_to_tsvector"](pg_catalog.jsonb,pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'jsonb_to_tsvector',
    args: ['pg_catalog.jsonb', 'pg_catalog.jsonb'],
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","jsonb_to_tsvector"](pg_catalog.regconfig,pg_catalog.jsonb,pg_catalog.jsonb)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'jsonb_to_tsvector',
      args: ['pg_catalog.regconfig', 'pg_catalog.jsonb', 'pg_catalog.jsonb'],
      result: 'pg_catalog.tsvector',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","length"](pg_catalog.tsvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'length',
    args: ['pg_catalog.tsvector'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","numnode"](pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'numnode',
    args: ['pg_catalog.tsquery'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","phraseto_tsquery"](pg_catalog.regconfig,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'phraseto_tsquery',
    args: ['pg_catalog.regconfig', 'pg_catalog.text'],
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","phraseto_tsquery"](pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'phraseto_tsquery',
    args: ['pg_catalog.text'],
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","plainto_tsquery"](pg_catalog.regconfig,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'plainto_tsquery',
    args: ['pg_catalog.regconfig', 'pg_catalog.text'],
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","plainto_tsquery"](pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'plainto_tsquery',
    args: ['pg_catalog.text'],
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","querytree"](pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'querytree',
    args: ['pg_catalog.tsquery'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","setweight"](pg_catalog.tsvector,pg_catalog."char")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'setweight',
    args: ['pg_catalog.tsvector', 'pg_catalog."char"'],
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","setweight"](pg_catalog.tsvector,pg_catalog."char",pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'setweight',
    args: ['pg_catalog.tsvector', 'pg_catalog."char"', 'pg_catalog._text'],
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","strip"](pg_catalog.tsvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'strip',
    args: ['pg_catalog.tsvector'],
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","to_tsquery"](pg_catalog.regconfig,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'to_tsquery',
    args: ['pg_catalog.regconfig', 'pg_catalog.text'],
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","to_tsquery"](pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'to_tsquery',
    args: ['pg_catalog.text'],
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","to_tsvector"](pg_catalog."json")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'to_tsvector',
    args: ['pg_catalog."json"'],
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","to_tsvector"](pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'to_tsvector',
    args: ['pg_catalog.jsonb'],
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","to_tsvector"](pg_catalog.regconfig,pg_catalog."json")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'to_tsvector',
    args: ['pg_catalog.regconfig', 'pg_catalog."json"'],
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","to_tsvector"](pg_catalog.regconfig,pg_catalog.jsonb)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'to_tsvector',
    args: ['pg_catalog.regconfig', 'pg_catalog.jsonb'],
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","to_tsvector"](pg_catalog.regconfig,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'to_tsvector',
    args: ['pg_catalog.regconfig', 'pg_catalog.text'],
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","to_tsvector"](pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'to_tsvector',
    args: ['pg_catalog.text'],
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_delete"](pg_catalog.tsvector,pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_delete',
    args: ['pg_catalog.tsvector', 'pg_catalog._text'],
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_delete"](pg_catalog.tsvector,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_delete',
    args: ['pg_catalog.tsvector', 'pg_catalog.text'],
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_filter"](pg_catalog.tsvector,pg_catalog._char)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_filter',
    args: ['pg_catalog.tsvector', 'pg_catalog._char'],
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_headline"](pg_catalog.text,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_headline',
    args: ['pg_catalog.text', 'pg_catalog.tsquery'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_headline"](pg_catalog.text,pg_catalog.tsquery,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_headline',
    args: ['pg_catalog.text', 'pg_catalog.tsquery', 'pg_catalog.text'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_match_qv"](pg_catalog.tsquery,pg_catalog.tsvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_match_qv',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsvector'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_match_tq"](pg_catalog.text,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_match_tq',
    args: ['pg_catalog.text', 'pg_catalog.tsquery'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_match_vq"](pg_catalog.tsvector,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_match_vq',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsquery'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_rank"](pg_catalog.tsvector,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_rank',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsquery'],
    result: 'pg_catalog.float4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_rank"](pg_catalog.tsvector,pg_catalog.tsquery,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_rank',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsquery', 'pg_catalog.int4'],
    result: 'pg_catalog.float4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_rank_cd"](pg_catalog.tsvector,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_rank_cd',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsquery'],
    result: 'pg_catalog.float4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_rank_cd"](pg_catalog.tsvector,pg_catalog.tsquery,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_rank_cd',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsquery', 'pg_catalog.int4'],
    result: 'pg_catalog.float4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_rewrite"](pg_catalog.tsquery,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'ts_rewrite',
    args: ['pg_catalog.tsquery', 'pg_catalog.text'],
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","ts_rewrite"](pg_catalog.tsquery,pg_catalog.tsquery,pg_catalog.tsquery)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'ts_rewrite',
      args: ['pg_catalog.tsquery', 'pg_catalog.tsquery', 'pg_catalog.tsquery'],
      result: 'pg_catalog.tsquery',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","tsq_mcontained"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsq_mcontained',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsq_mcontains"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsq_mcontains',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsquery_and"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsquery_and',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsquery_cmp"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsquery_cmp',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsquery_eq"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsquery_eq',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsquery_ge"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsquery_ge',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsquery_gt"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsquery_gt',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsquery_le"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsquery_le',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsquery_lt"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsquery_lt',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsquery_ne"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsquery_ne',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsquery_not"](pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsquery_not',
    args: ['pg_catalog.tsquery'],
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsquery_or"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsquery_or',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsquery_phrase"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsquery_phrase',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsquery_phrase"](pg_catalog.tsquery,pg_catalog.tsquery,pg_catalog.int4)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'tsquery_phrase',
      args: ['pg_catalog.tsquery', 'pg_catalog.tsquery', 'pg_catalog.int4'],
      result: 'pg_catalog.tsquery',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","tsvector_cmp"](pg_catalog.tsvector,pg_catalog.tsvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsvector_cmp',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsvector'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsvector_concat"](pg_catalog.tsvector,pg_catalog.tsvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsvector_concat',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsvector'],
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsvector_eq"](pg_catalog.tsvector,pg_catalog.tsvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsvector_eq',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsvector'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsvector_ge"](pg_catalog.tsvector,pg_catalog.tsvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsvector_ge',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsvector'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsvector_gt"](pg_catalog.tsvector,pg_catalog.tsvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsvector_gt',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsvector'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsvector_le"](pg_catalog.tsvector,pg_catalog.tsvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsvector_le',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsvector'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsvector_lt"](pg_catalog.tsvector,pg_catalog.tsvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsvector_lt',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsvector'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tsvector_ne"](pg_catalog.tsvector,pg_catalog.tsvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tsvector_ne',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsvector'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","unnest"](pg_catalog.tsvector)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'unnest',
    args: ['pg_catalog.tsvector'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","websearch_to_tsquery"](pg_catalog.regconfig,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'websearch_to_tsquery',
    args: ['pg_catalog.regconfig', 'pg_catalog.text'],
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","websearch_to_tsquery"](pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'websearch_to_tsquery',
    args: ['pg_catalog.text'],
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'operator:["pg_catalog","!!"](,pg_catalog.tsquery)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '!!',
    args: ['pg_catalog.tsquery'],
    left: null,
    right: 'pg_catalog.tsquery',
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","&&"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '&&',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    left: 'pg_catalog.tsquery',
    right: 'pg_catalog.tsquery',
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    left: 'pg_catalog.tsquery',
    right: 'pg_catalog.tsquery',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.tsvector,pg_catalog.tsvector)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsvector'],
    left: 'pg_catalog.tsvector',
    right: 'pg_catalog.tsvector',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<->"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<->',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    left: 'pg_catalog.tsquery',
    right: 'pg_catalog.tsquery',
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    left: 'pg_catalog.tsquery',
    right: 'pg_catalog.tsquery',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.tsvector,pg_catalog.tsvector)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsvector'],
    left: 'pg_catalog.tsvector',
    right: 'pg_catalog.tsvector',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    left: 'pg_catalog.tsquery',
    right: 'pg_catalog.tsquery',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.tsvector,pg_catalog.tsvector)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsvector'],
    left: 'pg_catalog.tsvector',
    right: 'pg_catalog.tsvector',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<@"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<@',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    left: 'pg_catalog.tsquery',
    right: 'pg_catalog.tsquery',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    left: 'pg_catalog.tsquery',
    right: 'pg_catalog.tsquery',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.tsvector,pg_catalog.tsvector)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsvector'],
    left: 'pg_catalog.tsvector',
    right: 'pg_catalog.tsvector',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    left: 'pg_catalog.tsquery',
    right: 'pg_catalog.tsquery',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.tsvector,pg_catalog.tsvector)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsvector'],
    left: 'pg_catalog.tsvector',
    right: 'pg_catalog.tsvector',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    left: 'pg_catalog.tsquery',
    right: 'pg_catalog.tsquery',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.tsvector,pg_catalog.tsvector)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsvector'],
    left: 'pg_catalog.tsvector',
    right: 'pg_catalog.tsvector',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","@>"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@>',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    left: 'pg_catalog.tsquery',
    right: 'pg_catalog.tsquery',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","@@"](pg_catalog.text,pg_catalog.tsquery)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@@',
    args: ['pg_catalog.text', 'pg_catalog.tsquery'],
    left: 'pg_catalog.text',
    right: 'pg_catalog.tsquery',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 's',
    returnsSet: false,
  },
  'operator:["pg_catalog","@@"](pg_catalog.tsquery,pg_catalog.tsvector)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@@',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsvector'],
    left: 'pg_catalog.tsquery',
    right: 'pg_catalog.tsvector',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","@@"](pg_catalog.tsvector,pg_catalog.tsquery)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@@',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsquery'],
    left: 'pg_catalog.tsvector',
    right: 'pg_catalog.tsquery',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","@@@"](pg_catalog.tsquery,pg_catalog.tsvector)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@@@',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsvector'],
    left: 'pg_catalog.tsquery',
    right: 'pg_catalog.tsvector',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","@@@"](pg_catalog.tsvector,pg_catalog.tsquery)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '@@@',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsquery'],
    left: 'pg_catalog.tsvector',
    right: 'pg_catalog.tsquery',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","||"](pg_catalog.tsquery,pg_catalog.tsquery)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '||',
    args: ['pg_catalog.tsquery', 'pg_catalog.tsquery'],
    left: 'pg_catalog.tsquery',
    right: 'pg_catalog.tsquery',
    result: 'pg_catalog.tsquery',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","||"](pg_catalog.tsvector,pg_catalog.tsvector)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '||',
    args: ['pg_catalog.tsvector', 'pg_catalog.tsvector'],
    left: 'pg_catalog.tsvector',
    right: 'pg_catalog.tsvector',
    result: 'pg_catalog.tsvector',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
} as const
