export const PG18_TRANSACTION = {
  'function:["pg_catalog","age"](pg_catalog.xid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'age',
    args: ['pg_catalog.xid'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","binary_upgrade_replorigin_advance"](pg_catalog.text,pg_catalog.pg_lsn)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'binary_upgrade_replorigin_advance',
      args: ['pg_catalog.text', 'pg_catalog.pg_lsn'],
      result: 'pg_catalog.void',
      strict: false,
      volatility: 'v',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","bttidcmp"](pg_catalog.tid,pg_catalog.tid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bttidcmp',
    args: ['pg_catalog.tid', 'pg_catalog.tid'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","cideq"](pg_catalog.cid,pg_catalog.cid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'cideq',
    args: ['pg_catalog.cid', 'pg_catalog.cid'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","currtid2"](pg_catalog.text,pg_catalog.tid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'currtid2',
    args: ['pg_catalog.text', 'pg_catalog.tid'],
    result: 'pg_catalog.tid',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashcid"](pg_catalog.cid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashcid',
    args: ['pg_catalog.cid'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashcidextended"](pg_catalog.cid,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashcidextended',
    args: ['pg_catalog.cid', 'pg_catalog.int8'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashtid"](pg_catalog.tid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashtid',
    args: ['pg_catalog.tid'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashtidextended"](pg_catalog.tid,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashtidextended',
    args: ['pg_catalog.tid', 'pg_catalog.int8'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashxid"](pg_catalog.xid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashxid',
    args: ['pg_catalog.xid'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashxid8"](pg_catalog.xid8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashxid8',
    args: ['pg_catalog.xid8'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashxid8extended"](pg_catalog.xid8,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashxid8extended',
    args: ['pg_catalog.xid8', 'pg_catalog.int8'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashxidextended"](pg_catalog.xid,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashxidextended',
    args: ['pg_catalog.xid', 'pg_catalog.int8'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","mxid_age"](pg_catalog.xid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'mxid_age',
    args: ['pg_catalog.xid'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","numeric_pl_pg_lsn"](pg_catalog."numeric",pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'numeric_pl_pg_lsn',
    args: ['pg_catalog."numeric"', 'pg_catalog.pg_lsn'],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_backup_start"](pg_catalog.text,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_backup_start',
    args: ['pg_catalog.text', 'pg_catalog.bool'],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 1,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_create_restore_point"](pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_create_restore_point',
    args: ['pg_catalog.text'],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_current_snapshot"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_current_snapshot',
    args: [],
    result: 'pg_catalog.pg_snapshot',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_current_wal_flush_lsn"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_current_wal_flush_lsn',
    args: [],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_current_wal_insert_lsn"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_current_wal_insert_lsn',
    args: [],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_current_wal_lsn"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_current_wal_lsn',
    args: [],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_current_xact_id"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_current_xact_id',
    args: [],
    result: 'pg_catalog.xid8',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_current_xact_id_if_assigned"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_current_xact_id_if_assigned',
    args: [],
    result: 'pg_catalog.xid8',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_get_multixact_members"](pg_catalog.xid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_get_multixact_members',
    args: ['pg_catalog.xid'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_last_wal_receive_lsn"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_last_wal_receive_lsn',
    args: [],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_last_wal_replay_lsn"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_last_wal_replay_lsn',
    args: [],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_log_standby_snapshot"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_log_standby_snapshot',
    args: [],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_logical_emit_message"](pg_catalog.bool,pg_catalog.text,pg_catalog.bytea,pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'pg_logical_emit_message',
      args: ['pg_catalog.bool', 'pg_catalog.text', 'pg_catalog.bytea', 'pg_catalog.bool'],
      result: 'pg_catalog.pg_lsn',
      strict: true,
      volatility: 'v',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 1,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","pg_logical_emit_message"](pg_catalog.bool,pg_catalog.text,pg_catalog.text,pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'pg_logical_emit_message',
      args: ['pg_catalog.bool', 'pg_catalog.text', 'pg_catalog.text', 'pg_catalog.bool'],
      result: 'pg_catalog.pg_lsn',
      strict: true,
      volatility: 'v',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 1,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","pg_logical_slot_get_binary_changes"](pg_catalog.name,pg_catalog.pg_lsn,pg_catalog.int4,pg_catalog._text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'pg_logical_slot_get_binary_changes',
      args: ['pg_catalog.name', 'pg_catalog.pg_lsn', 'pg_catalog.int4', 'pg_catalog._text'],
      result: 'pg_catalog.record',
      strict: false,
      volatility: 'v',
      returnsSet: true,
      variadic: 'pg_catalog.text',
      numArgDefaults: 1,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","pg_logical_slot_get_changes"](pg_catalog.name,pg_catalog.pg_lsn,pg_catalog.int4,pg_catalog._text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'pg_logical_slot_get_changes',
      args: ['pg_catalog.name', 'pg_catalog.pg_lsn', 'pg_catalog.int4', 'pg_catalog._text'],
      result: 'pg_catalog.record',
      strict: false,
      volatility: 'v',
      returnsSet: true,
      variadic: 'pg_catalog.text',
      numArgDefaults: 1,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","pg_logical_slot_peek_binary_changes"](pg_catalog.name,pg_catalog.pg_lsn,pg_catalog.int4,pg_catalog._text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'pg_logical_slot_peek_binary_changes',
      args: ['pg_catalog.name', 'pg_catalog.pg_lsn', 'pg_catalog.int4', 'pg_catalog._text'],
      result: 'pg_catalog.record',
      strict: false,
      volatility: 'v',
      returnsSet: true,
      variadic: 'pg_catalog.text',
      numArgDefaults: 1,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","pg_logical_slot_peek_changes"](pg_catalog.name,pg_catalog.pg_lsn,pg_catalog.int4,pg_catalog._text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'pg_logical_slot_peek_changes',
      args: ['pg_catalog.name', 'pg_catalog.pg_lsn', 'pg_catalog.int4', 'pg_catalog._text'],
      result: 'pg_catalog.record',
      strict: false,
      volatility: 'v',
      returnsSet: true,
      variadic: 'pg_catalog.text',
      numArgDefaults: 1,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","pg_lsn"](pg_catalog."numeric")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lsn',
    args: ['pg_catalog."numeric"'],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_lsn_cmp"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lsn_cmp',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_lsn_eq"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lsn_eq',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_lsn_ge"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lsn_ge',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_lsn_gt"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lsn_gt',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_lsn_hash"](pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lsn_hash',
    args: ['pg_catalog.pg_lsn'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_lsn_hash_extended"](pg_catalog.pg_lsn,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lsn_hash_extended',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.int8'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_lsn_larger"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lsn_larger',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_lsn_le"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lsn_le',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_lsn_lt"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lsn_lt',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_lsn_mi"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lsn_mi',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    result: 'pg_catalog."numeric"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_lsn_mii"](pg_catalog.pg_lsn,pg_catalog."numeric")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lsn_mii',
    args: ['pg_catalog.pg_lsn', 'pg_catalog."numeric"'],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_lsn_ne"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lsn_ne',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_lsn_pli"](pg_catalog.pg_lsn,pg_catalog."numeric")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lsn_pli',
    args: ['pg_catalog.pg_lsn', 'pg_catalog."numeric"'],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_lsn_smaller"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lsn_smaller',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_replication_origin_advance"](pg_catalog.text,pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_replication_origin_advance',
    args: ['pg_catalog.text', 'pg_catalog.pg_lsn'],
    result: 'pg_catalog.void',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_replication_origin_progress"](pg_catalog.text,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_replication_origin_progress',
    args: ['pg_catalog.text', 'pg_catalog.bool'],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_replication_origin_session_progress"](pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_replication_origin_session_progress',
    args: ['pg_catalog.bool'],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_replication_origin_xact_setup"](pg_catalog.pg_lsn,pg_catalog.timestamptz)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'pg_replication_origin_xact_setup',
      args: ['pg_catalog.pg_lsn', 'pg_catalog.timestamptz'],
      result: 'pg_catalog.void',
      strict: true,
      volatility: 'v',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","pg_replication_slot_advance"](pg_catalog.name,pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_replication_slot_advance',
    args: ['pg_catalog.name', 'pg_catalog.pg_lsn'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_snapshot_xip"](pg_catalog.pg_snapshot)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_snapshot_xip',
    args: ['pg_catalog.pg_snapshot'],
    result: 'pg_catalog.xid8',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_snapshot_xmax"](pg_catalog.pg_snapshot)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_snapshot_xmax',
    args: ['pg_catalog.pg_snapshot'],
    result: 'pg_catalog.xid8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_snapshot_xmin"](pg_catalog.pg_snapshot)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_snapshot_xmin',
    args: ['pg_catalog.pg_snapshot'],
    result: 'pg_catalog.xid8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_switch_wal"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_switch_wal',
    args: [],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_visible_in_snapshot"](pg_catalog.xid8,pg_catalog.pg_snapshot)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_visible_in_snapshot',
    args: ['pg_catalog.xid8', 'pg_catalog.pg_snapshot'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_wal_lsn_diff"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_wal_lsn_diff',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    result: 'pg_catalog."numeric"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_wal_summary_contents"](pg_catalog.int8,pg_catalog.pg_lsn,pg_catalog.pg_lsn)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'pg_wal_summary_contents',
      args: ['pg_catalog.int8', 'pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
      result: 'pg_catalog.record',
      strict: true,
      volatility: 'v',
      returnsSet: true,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","pg_walfile_name"](pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_walfile_name',
    args: ['pg_catalog.pg_lsn'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_walfile_name_offset"](pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_walfile_name_offset',
    args: ['pg_catalog.pg_lsn'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_xact_commit_timestamp_origin"](pg_catalog.xid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_xact_commit_timestamp_origin',
    args: ['pg_catalog.xid'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_xact_status"](pg_catalog.xid8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_xact_status',
    args: ['pg_catalog.xid8'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tideq"](pg_catalog.tid,pg_catalog.tid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tideq',
    args: ['pg_catalog.tid', 'pg_catalog.tid'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tidge"](pg_catalog.tid,pg_catalog.tid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tidge',
    args: ['pg_catalog.tid', 'pg_catalog.tid'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tidgt"](pg_catalog.tid,pg_catalog.tid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tidgt',
    args: ['pg_catalog.tid', 'pg_catalog.tid'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tidlarger"](pg_catalog.tid,pg_catalog.tid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tidlarger',
    args: ['pg_catalog.tid', 'pg_catalog.tid'],
    result: 'pg_catalog.tid',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tidle"](pg_catalog.tid,pg_catalog.tid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tidle',
    args: ['pg_catalog.tid', 'pg_catalog.tid'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tidlt"](pg_catalog.tid,pg_catalog.tid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tidlt',
    args: ['pg_catalog.tid', 'pg_catalog.tid'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tidne"](pg_catalog.tid,pg_catalog.tid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tidne',
    args: ['pg_catalog.tid', 'pg_catalog.tid'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tidsmaller"](pg_catalog.tid,pg_catalog.tid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tidsmaller',
    args: ['pg_catalog.tid', 'pg_catalog.tid'],
    result: 'pg_catalog.tid',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","txid_current_snapshot"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'txid_current_snapshot',
    args: [],
    result: 'pg_catalog.txid_snapshot',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","txid_snapshot_xip"](pg_catalog.txid_snapshot)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'txid_snapshot_xip',
    args: ['pg_catalog.txid_snapshot'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","txid_snapshot_xmax"](pg_catalog.txid_snapshot)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'txid_snapshot_xmax',
    args: ['pg_catalog.txid_snapshot'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","txid_snapshot_xmin"](pg_catalog.txid_snapshot)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'txid_snapshot_xmin',
    args: ['pg_catalog.txid_snapshot'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","txid_visible_in_snapshot"](pg_catalog.int8,pg_catalog.txid_snapshot)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'txid_visible_in_snapshot',
    args: ['pg_catalog.int8', 'pg_catalog.txid_snapshot'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xid"](pg_catalog.xid8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xid',
    args: ['pg_catalog.xid8'],
    result: 'pg_catalog.xid',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xid8_larger"](pg_catalog.xid8,pg_catalog.xid8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xid8_larger',
    args: ['pg_catalog.xid8', 'pg_catalog.xid8'],
    result: 'pg_catalog.xid8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xid8_smaller"](pg_catalog.xid8,pg_catalog.xid8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xid8_smaller',
    args: ['pg_catalog.xid8', 'pg_catalog.xid8'],
    result: 'pg_catalog.xid8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xid8cmp"](pg_catalog.xid8,pg_catalog.xid8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xid8cmp',
    args: ['pg_catalog.xid8', 'pg_catalog.xid8'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xid8eq"](pg_catalog.xid8,pg_catalog.xid8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xid8eq',
    args: ['pg_catalog.xid8', 'pg_catalog.xid8'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xid8ge"](pg_catalog.xid8,pg_catalog.xid8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xid8ge',
    args: ['pg_catalog.xid8', 'pg_catalog.xid8'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xid8gt"](pg_catalog.xid8,pg_catalog.xid8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xid8gt',
    args: ['pg_catalog.xid8', 'pg_catalog.xid8'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xid8le"](pg_catalog.xid8,pg_catalog.xid8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xid8le',
    args: ['pg_catalog.xid8', 'pg_catalog.xid8'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xid8lt"](pg_catalog.xid8,pg_catalog.xid8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xid8lt',
    args: ['pg_catalog.xid8', 'pg_catalog.xid8'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xid8ne"](pg_catalog.xid8,pg_catalog.xid8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xid8ne',
    args: ['pg_catalog.xid8', 'pg_catalog.xid8'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xideq"](pg_catalog.xid,pg_catalog.xid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xideq',
    args: ['pg_catalog.xid', 'pg_catalog.xid'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xideqint4"](pg_catalog.xid,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xideqint4',
    args: ['pg_catalog.xid', 'pg_catalog.int4'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xidneq"](pg_catalog.xid,pg_catalog.xid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xidneq',
    args: ['pg_catalog.xid', 'pg_catalog.xid'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xidneqint4"](pg_catalog.xid,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xidneqint4',
    args: ['pg_catalog.xid', 'pg_catalog.int4'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'operator:["pg_catalog","+"](pg_catalog."numeric",pg_catalog.pg_lsn)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '+',
    args: ['pg_catalog."numeric"', 'pg_catalog.pg_lsn'],
    left: 'pg_catalog."numeric"',
    right: 'pg_catalog.pg_lsn',
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","+"](pg_catalog.pg_lsn,pg_catalog."numeric")': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '+',
    args: ['pg_catalog.pg_lsn', 'pg_catalog."numeric"'],
    left: 'pg_catalog.pg_lsn',
    right: 'pg_catalog."numeric"',
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","-"](pg_catalog.pg_lsn,pg_catalog."numeric")': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '-',
    args: ['pg_catalog.pg_lsn', 'pg_catalog."numeric"'],
    left: 'pg_catalog.pg_lsn',
    right: 'pg_catalog."numeric"',
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","-"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '-',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    left: 'pg_catalog.pg_lsn',
    right: 'pg_catalog.pg_lsn',
    result: 'pg_catalog."numeric"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    left: 'pg_catalog.pg_lsn',
    right: 'pg_catalog.pg_lsn',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.tid,pg_catalog.tid)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    args: ['pg_catalog.tid', 'pg_catalog.tid'],
    left: 'pg_catalog.tid',
    right: 'pg_catalog.tid',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.xid8,pg_catalog.xid8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    args: ['pg_catalog.xid8', 'pg_catalog.xid8'],
    left: 'pg_catalog.xid8',
    right: 'pg_catalog.xid8',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    left: 'pg_catalog.pg_lsn',
    right: 'pg_catalog.pg_lsn',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.tid,pg_catalog.tid)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    args: ['pg_catalog.tid', 'pg_catalog.tid'],
    left: 'pg_catalog.tid',
    right: 'pg_catalog.tid',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.xid8,pg_catalog.xid8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    args: ['pg_catalog.xid8', 'pg_catalog.xid8'],
    left: 'pg_catalog.xid8',
    right: 'pg_catalog.xid8',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    left: 'pg_catalog.pg_lsn',
    right: 'pg_catalog.pg_lsn',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.tid,pg_catalog.tid)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    args: ['pg_catalog.tid', 'pg_catalog.tid'],
    left: 'pg_catalog.tid',
    right: 'pg_catalog.tid',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.xid,pg_catalog.int4)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    args: ['pg_catalog.xid', 'pg_catalog.int4'],
    left: 'pg_catalog.xid',
    right: 'pg_catalog.int4',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.xid,pg_catalog.xid)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    args: ['pg_catalog.xid', 'pg_catalog.xid'],
    left: 'pg_catalog.xid',
    right: 'pg_catalog.xid',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.xid8,pg_catalog.xid8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    args: ['pg_catalog.xid8', 'pg_catalog.xid8'],
    left: 'pg_catalog.xid8',
    right: 'pg_catalog.xid8',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.cid,pg_catalog.cid)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    args: ['pg_catalog.cid', 'pg_catalog.cid'],
    left: 'pg_catalog.cid',
    right: 'pg_catalog.cid',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    left: 'pg_catalog.pg_lsn',
    right: 'pg_catalog.pg_lsn',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.tid,pg_catalog.tid)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    args: ['pg_catalog.tid', 'pg_catalog.tid'],
    left: 'pg_catalog.tid',
    right: 'pg_catalog.tid',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.xid,pg_catalog.int4)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    args: ['pg_catalog.xid', 'pg_catalog.int4'],
    left: 'pg_catalog.xid',
    right: 'pg_catalog.int4',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.xid,pg_catalog.xid)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    args: ['pg_catalog.xid', 'pg_catalog.xid'],
    left: 'pg_catalog.xid',
    right: 'pg_catalog.xid',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.xid8,pg_catalog.xid8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    args: ['pg_catalog.xid8', 'pg_catalog.xid8'],
    left: 'pg_catalog.xid8',
    right: 'pg_catalog.xid8',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    left: 'pg_catalog.pg_lsn',
    right: 'pg_catalog.pg_lsn',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.tid,pg_catalog.tid)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    args: ['pg_catalog.tid', 'pg_catalog.tid'],
    left: 'pg_catalog.tid',
    right: 'pg_catalog.tid',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.xid8,pg_catalog.xid8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    args: ['pg_catalog.xid8', 'pg_catalog.xid8'],
    left: 'pg_catalog.xid8',
    right: 'pg_catalog.xid8',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    left: 'pg_catalog.pg_lsn',
    right: 'pg_catalog.pg_lsn',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.tid,pg_catalog.tid)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    args: ['pg_catalog.tid', 'pg_catalog.tid'],
    left: 'pg_catalog.tid',
    right: 'pg_catalog.tid',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.xid8,pg_catalog.xid8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    args: ['pg_catalog.xid8', 'pg_catalog.xid8'],
    left: 'pg_catalog.xid8',
    right: 'pg_catalog.xid8',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
} as const
