export const PG18_TRANSACTION = {
  'function:["pg_catalog","age"](pg_catalog.xid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'age',
    rustName: 'sql__pg_catalog__age__jzni',
    args: ['pg_catalog.xid'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","binary_upgrade_replorigin_advance"](pg_catalog.text,pg_catalog.pg_lsn)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'binary_upgrade_replorigin_advance',
      rustName: 'sql__pg_catalog__binary_upgrade_replorigin_advance__z3h6',
      args: ['pg_catalog.text', 'pg_catalog.pg_lsn'],
      result: 'pg_catalog.void',
      strict: false,
      volatility: 'v',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","bttidcmp"](pg_catalog.tid,pg_catalog.tid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'bttidcmp',
    rustName: 'sql__pg_catalog__bttidcmp__ak5t',
    args: ['pg_catalog.tid', 'pg_catalog.tid'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","cideq"](pg_catalog.cid,pg_catalog.cid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'cideq',
    rustName: 'sql__pg_catalog__cideq__cniv',
    args: ['pg_catalog.cid', 'pg_catalog.cid'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","currtid2"](pg_catalog.text,pg_catalog.tid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'currtid2',
    rustName: 'sql__pg_catalog__currtid2__57a0',
    args: ['pg_catalog.text', 'pg_catalog.tid'],
    result: 'pg_catalog.tid',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashcid"](pg_catalog.cid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashcid',
    rustName: 'sql__pg_catalog__hashcid__a8z6',
    args: ['pg_catalog.cid'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashcidextended"](pg_catalog.cid,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashcidextended',
    rustName: 'sql__pg_catalog__hashcidextended__eeef',
    args: ['pg_catalog.cid', 'pg_catalog.int8'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashtid"](pg_catalog.tid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashtid',
    rustName: 'sql__pg_catalog__hashtid__li7j',
    args: ['pg_catalog.tid'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashtidextended"](pg_catalog.tid,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashtidextended',
    rustName: 'sql__pg_catalog__hashtidextended__osxq',
    args: ['pg_catalog.tid', 'pg_catalog.int8'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashxid"](pg_catalog.xid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashxid',
    rustName: 'sql__pg_catalog__hashxid__5s1i',
    args: ['pg_catalog.xid'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashxid8"](pg_catalog.xid8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashxid8',
    rustName: 'sql__pg_catalog__hashxid8__l6u3',
    args: ['pg_catalog.xid8'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashxid8extended"](pg_catalog.xid8,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashxid8extended',
    rustName: 'sql__pg_catalog__hashxid8extended__h8is',
    args: ['pg_catalog.xid8', 'pg_catalog.int8'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","hashxidextended"](pg_catalog.xid,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'hashxidextended',
    rustName: 'sql__pg_catalog__hashxidextended__3a8s',
    args: ['pg_catalog.xid', 'pg_catalog.int8'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","mxid_age"](pg_catalog.xid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'mxid_age',
    rustName: 'sql__pg_catalog__mxid_age__c147',
    args: ['pg_catalog.xid'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","numeric_pl_pg_lsn"](pg_catalog."numeric",pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'numeric_pl_pg_lsn',
    rustName: 'sql__pg_catalog__numeric_pl_pg_lsn__jhoo',
    args: ['pg_catalog."numeric"', 'pg_catalog.pg_lsn'],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_backup_start"](pg_catalog.text,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_backup_start',
    rustName: 'sql__pg_catalog__pg_backup_start__vopy',
    args: ['pg_catalog.text', 'pg_catalog.bool'],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 1,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_create_restore_point"](pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_create_restore_point',
    rustName: 'sql__pg_catalog__pg_create_restore_point__mci8',
    args: ['pg_catalog.text'],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_current_snapshot"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_current_snapshot',
    rustName: 'sql__pg_catalog__pg_current_snapshot__6yqs',
    args: [],
    result: 'pg_catalog.pg_snapshot',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_current_wal_flush_lsn"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_current_wal_flush_lsn',
    rustName: 'sql__pg_catalog__pg_current_wal_flush_lsn__vsvq',
    args: [],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_current_wal_insert_lsn"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_current_wal_insert_lsn',
    rustName: 'sql__pg_catalog__pg_current_wal_insert_lsn__srlg',
    args: [],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_current_wal_lsn"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_current_wal_lsn',
    rustName: 'sql__pg_catalog__pg_current_wal_lsn__5heg',
    args: [],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_current_xact_id"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_current_xact_id',
    rustName: 'sql__pg_catalog__pg_current_xact_id__sncy',
    args: [],
    result: 'pg_catalog.xid8',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_current_xact_id_if_assigned"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_current_xact_id_if_assigned',
    rustName: 'sql__pg_catalog__pg_current_xact_id_if_assigned__8nvs',
    args: [],
    result: 'pg_catalog.xid8',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_get_multixact_members"](pg_catalog.xid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_get_multixact_members',
    rustName: 'sql__pg_catalog__pg_get_multixact_members__kqn1',
    args: ['pg_catalog.xid'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_last_wal_receive_lsn"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_last_wal_receive_lsn',
    rustName: 'sql__pg_catalog__pg_last_wal_receive_lsn__9rtk',
    args: [],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_last_wal_replay_lsn"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_last_wal_replay_lsn',
    rustName: 'sql__pg_catalog__pg_last_wal_replay_lsn__zvwg',
    args: [],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_log_standby_snapshot"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_log_standby_snapshot',
    rustName: 'sql__pg_catalog__pg_log_standby_snapshot__oa4p',
    args: [],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_logical_emit_message"](pg_catalog.bool,pg_catalog.text,pg_catalog.bytea,pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'pg_logical_emit_message',
      rustName: 'sql__pg_catalog__pg_logical_emit_message__oaec',
      args: ['pg_catalog.bool', 'pg_catalog.text', 'pg_catalog.bytea', 'pg_catalog.bool'],
      result: 'pg_catalog.pg_lsn',
      strict: true,
      volatility: 'v',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 1,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","pg_logical_emit_message"](pg_catalog.bool,pg_catalog.text,pg_catalog.text,pg_catalog.bool)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'pg_logical_emit_message',
      rustName: 'sql__pg_catalog__pg_logical_emit_message__fre8',
      args: ['pg_catalog.bool', 'pg_catalog.text', 'pg_catalog.text', 'pg_catalog.bool'],
      result: 'pg_catalog.pg_lsn',
      strict: true,
      volatility: 'v',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 1,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","pg_logical_slot_get_binary_changes"](pg_catalog.name,pg_catalog.pg_lsn,pg_catalog.int4,pg_catalog._text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'pg_logical_slot_get_binary_changes',
      rustName: 'sql__pg_catalog__pg_logical_slot_get_binary_changes__re57',
      args: ['pg_catalog.name', 'pg_catalog.pg_lsn', 'pg_catalog.int4', 'pg_catalog._text'],
      result: 'pg_catalog.record',
      strict: false,
      volatility: 'v',
      returnsSet: true,
      variadic: 'pg_catalog.text',
      numArgDefaults: 1,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","pg_logical_slot_get_changes"](pg_catalog.name,pg_catalog.pg_lsn,pg_catalog.int4,pg_catalog._text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'pg_logical_slot_get_changes',
      rustName: 'sql__pg_catalog__pg_logical_slot_get_changes__431p',
      args: ['pg_catalog.name', 'pg_catalog.pg_lsn', 'pg_catalog.int4', 'pg_catalog._text'],
      result: 'pg_catalog.record',
      strict: false,
      volatility: 'v',
      returnsSet: true,
      variadic: 'pg_catalog.text',
      numArgDefaults: 1,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","pg_logical_slot_peek_binary_changes"](pg_catalog.name,pg_catalog.pg_lsn,pg_catalog.int4,pg_catalog._text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'pg_logical_slot_peek_binary_changes',
      rustName: 'sql__pg_catalog__pg_logical_slot_peek_binary_changes__tmoq',
      args: ['pg_catalog.name', 'pg_catalog.pg_lsn', 'pg_catalog.int4', 'pg_catalog._text'],
      result: 'pg_catalog.record',
      strict: false,
      volatility: 'v',
      returnsSet: true,
      variadic: 'pg_catalog.text',
      numArgDefaults: 1,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","pg_logical_slot_peek_changes"](pg_catalog.name,pg_catalog.pg_lsn,pg_catalog.int4,pg_catalog._text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'pg_logical_slot_peek_changes',
      rustName: 'sql__pg_catalog__pg_logical_slot_peek_changes__kqtd',
      args: ['pg_catalog.name', 'pg_catalog.pg_lsn', 'pg_catalog.int4', 'pg_catalog._text'],
      result: 'pg_catalog.record',
      strict: false,
      volatility: 'v',
      returnsSet: true,
      variadic: 'pg_catalog.text',
      numArgDefaults: 1,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","pg_lsn"](pg_catalog."numeric")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lsn',
    rustName: 'sql__pg_catalog__pg_lsn__8qf1',
    args: ['pg_catalog."numeric"'],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_lsn_cmp"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lsn_cmp',
    rustName: 'sql__pg_catalog__pg_lsn_cmp__46uk',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_lsn_eq"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lsn_eq',
    rustName: 'sql__pg_catalog__pg_lsn_eq__isht',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_lsn_ge"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lsn_ge',
    rustName: 'sql__pg_catalog__pg_lsn_ge__fqvw',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_lsn_gt"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lsn_gt',
    rustName: 'sql__pg_catalog__pg_lsn_gt__hlz9',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_lsn_hash"](pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lsn_hash',
    rustName: 'sql__pg_catalog__pg_lsn_hash__f4fo',
    args: ['pg_catalog.pg_lsn'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_lsn_hash_extended"](pg_catalog.pg_lsn,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lsn_hash_extended',
    rustName: 'sql__pg_catalog__pg_lsn_hash_extended__mll2',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.int8'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_lsn_larger"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lsn_larger',
    rustName: 'sql__pg_catalog__pg_lsn_larger__u28j',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_lsn_le"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lsn_le',
    rustName: 'sql__pg_catalog__pg_lsn_le__gaq2',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_lsn_lt"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lsn_lt',
    rustName: 'sql__pg_catalog__pg_lsn_lt__autv',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_lsn_mi"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lsn_mi',
    rustName: 'sql__pg_catalog__pg_lsn_mi__f4h2',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    result: 'pg_catalog."numeric"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_lsn_mii"](pg_catalog.pg_lsn,pg_catalog."numeric")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lsn_mii',
    rustName: 'sql__pg_catalog__pg_lsn_mii__kdo3',
    args: ['pg_catalog.pg_lsn', 'pg_catalog."numeric"'],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_lsn_ne"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lsn_ne',
    rustName: 'sql__pg_catalog__pg_lsn_ne__cw52',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_lsn_pli"](pg_catalog.pg_lsn,pg_catalog."numeric")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lsn_pli',
    rustName: 'sql__pg_catalog__pg_lsn_pli__rpc5',
    args: ['pg_catalog.pg_lsn', 'pg_catalog."numeric"'],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_lsn_smaller"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_lsn_smaller',
    rustName: 'sql__pg_catalog__pg_lsn_smaller__txge',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_replication_origin_advance"](pg_catalog.text,pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_replication_origin_advance',
    rustName: 'sql__pg_catalog__pg_replication_origin_advance__gyac',
    args: ['pg_catalog.text', 'pg_catalog.pg_lsn'],
    result: 'pg_catalog.void',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_replication_origin_progress"](pg_catalog.text,pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_replication_origin_progress',
    rustName: 'sql__pg_catalog__pg_replication_origin_progress__ssuv',
    args: ['pg_catalog.text', 'pg_catalog.bool'],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_replication_origin_session_progress"](pg_catalog.bool)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_replication_origin_session_progress',
    rustName: 'sql__pg_catalog__pg_replication_origin_session_progress__85js',
    args: ['pg_catalog.bool'],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_replication_origin_xact_setup"](pg_catalog.pg_lsn,pg_catalog.timestamptz)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'pg_replication_origin_xact_setup',
      rustName: 'sql__pg_catalog__pg_replication_origin_xact_setup__3g5z',
      args: ['pg_catalog.pg_lsn', 'pg_catalog.timestamptz'],
      result: 'pg_catalog.void',
      strict: true,
      volatility: 'v',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","pg_replication_slot_advance"](pg_catalog.name,pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_replication_slot_advance',
    rustName: 'sql__pg_catalog__pg_replication_slot_advance__1pxt',
    args: ['pg_catalog.name', 'pg_catalog.pg_lsn'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_snapshot_xip"](pg_catalog.pg_snapshot)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_snapshot_xip',
    rustName: 'sql__pg_catalog__pg_snapshot_xip__1z84',
    args: ['pg_catalog.pg_snapshot'],
    result: 'pg_catalog.xid8',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_snapshot_xmax"](pg_catalog.pg_snapshot)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_snapshot_xmax',
    rustName: 'sql__pg_catalog__pg_snapshot_xmax__enpd',
    args: ['pg_catalog.pg_snapshot'],
    result: 'pg_catalog.xid8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_snapshot_xmin"](pg_catalog.pg_snapshot)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_snapshot_xmin',
    rustName: 'sql__pg_catalog__pg_snapshot_xmin__je8q',
    args: ['pg_catalog.pg_snapshot'],
    result: 'pg_catalog.xid8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_switch_wal"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_switch_wal',
    rustName: 'sql__pg_catalog__pg_switch_wal__xxg5',
    args: [],
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_visible_in_snapshot"](pg_catalog.xid8,pg_catalog.pg_snapshot)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_visible_in_snapshot',
    rustName: 'sql__pg_catalog__pg_visible_in_snapshot__5zx2',
    args: ['pg_catalog.xid8', 'pg_catalog.pg_snapshot'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_wal_lsn_diff"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_wal_lsn_diff',
    rustName: 'sql__pg_catalog__pg_wal_lsn_diff__secp',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    result: 'pg_catalog."numeric"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_wal_summary_contents"](pg_catalog.int8,pg_catalog.pg_lsn,pg_catalog.pg_lsn)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'pg_wal_summary_contents',
      rustName: 'sql__pg_catalog__pg_wal_summary_contents__8j84',
      args: ['pg_catalog.int8', 'pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
      result: 'pg_catalog.record',
      strict: true,
      volatility: 'v',
      returnsSet: true,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","pg_walfile_name"](pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_walfile_name',
    rustName: 'sql__pg_catalog__pg_walfile_name__ei2i',
    args: ['pg_catalog.pg_lsn'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_walfile_name_offset"](pg_catalog.pg_lsn)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_walfile_name_offset',
    rustName: 'sql__pg_catalog__pg_walfile_name_offset__xcoh',
    args: ['pg_catalog.pg_lsn'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_xact_commit_timestamp_origin"](pg_catalog.xid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_xact_commit_timestamp_origin',
    rustName: 'sql__pg_catalog__pg_xact_commit_timestamp_origin__ti6v',
    args: ['pg_catalog.xid'],
    result: 'pg_catalog.record',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","pg_xact_status"](pg_catalog.xid8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'pg_xact_status',
    rustName: 'sql__pg_catalog__pg_xact_status__q00n',
    args: ['pg_catalog.xid8'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tideq"](pg_catalog.tid,pg_catalog.tid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tideq',
    rustName: 'sql__pg_catalog__tideq__ba7v',
    args: ['pg_catalog.tid', 'pg_catalog.tid'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tidge"](pg_catalog.tid,pg_catalog.tid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tidge',
    rustName: 'sql__pg_catalog__tidge__3r7u',
    args: ['pg_catalog.tid', 'pg_catalog.tid'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tidgt"](pg_catalog.tid,pg_catalog.tid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tidgt',
    rustName: 'sql__pg_catalog__tidgt__2wvy',
    args: ['pg_catalog.tid', 'pg_catalog.tid'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tidlarger"](pg_catalog.tid,pg_catalog.tid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tidlarger',
    rustName: 'sql__pg_catalog__tidlarger__zk24',
    args: ['pg_catalog.tid', 'pg_catalog.tid'],
    result: 'pg_catalog.tid',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tidle"](pg_catalog.tid,pg_catalog.tid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tidle',
    rustName: 'sql__pg_catalog__tidle__ny8u',
    args: ['pg_catalog.tid', 'pg_catalog.tid'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tidlt"](pg_catalog.tid,pg_catalog.tid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tidlt',
    rustName: 'sql__pg_catalog__tidlt__am0j',
    args: ['pg_catalog.tid', 'pg_catalog.tid'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tidne"](pg_catalog.tid,pg_catalog.tid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tidne',
    rustName: 'sql__pg_catalog__tidne__wafx',
    args: ['pg_catalog.tid', 'pg_catalog.tid'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","tidsmaller"](pg_catalog.tid,pg_catalog.tid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'tidsmaller',
    rustName: 'sql__pg_catalog__tidsmaller__k6of',
    args: ['pg_catalog.tid', 'pg_catalog.tid'],
    result: 'pg_catalog.tid',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","txid_current_snapshot"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'txid_current_snapshot',
    rustName: 'sql__pg_catalog__txid_current_snapshot__ilay',
    args: [],
    result: 'pg_catalog.txid_snapshot',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","txid_snapshot_xip"](pg_catalog.txid_snapshot)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'txid_snapshot_xip',
    rustName: 'sql__pg_catalog__txid_snapshot_xip__y3br',
    args: ['pg_catalog.txid_snapshot'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: true,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","txid_snapshot_xmax"](pg_catalog.txid_snapshot)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'txid_snapshot_xmax',
    rustName: 'sql__pg_catalog__txid_snapshot_xmax__nuyq',
    args: ['pg_catalog.txid_snapshot'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","txid_snapshot_xmin"](pg_catalog.txid_snapshot)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'txid_snapshot_xmin',
    rustName: 'sql__pg_catalog__txid_snapshot_xmin__vg5z',
    args: ['pg_catalog.txid_snapshot'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","txid_visible_in_snapshot"](pg_catalog.int8,pg_catalog.txid_snapshot)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'txid_visible_in_snapshot',
    rustName: 'sql__pg_catalog__txid_visible_in_snapshot__1qno',
    args: ['pg_catalog.int8', 'pg_catalog.txid_snapshot'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xid"](pg_catalog.xid8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xid',
    rustName: 'sql__pg_catalog__xid__lwyo',
    args: ['pg_catalog.xid8'],
    result: 'pg_catalog.xid',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xid8_larger"](pg_catalog.xid8,pg_catalog.xid8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xid8_larger',
    rustName: 'sql__pg_catalog__xid8_larger__92s8',
    args: ['pg_catalog.xid8', 'pg_catalog.xid8'],
    result: 'pg_catalog.xid8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xid8_smaller"](pg_catalog.xid8,pg_catalog.xid8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xid8_smaller',
    rustName: 'sql__pg_catalog__xid8_smaller__ww2e',
    args: ['pg_catalog.xid8', 'pg_catalog.xid8'],
    result: 'pg_catalog.xid8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xid8cmp"](pg_catalog.xid8,pg_catalog.xid8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xid8cmp',
    rustName: 'sql__pg_catalog__xid8cmp__d6ry',
    args: ['pg_catalog.xid8', 'pg_catalog.xid8'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xid8eq"](pg_catalog.xid8,pg_catalog.xid8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xid8eq',
    rustName: 'sql__pg_catalog__xid8eq__swjx',
    args: ['pg_catalog.xid8', 'pg_catalog.xid8'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xid8ge"](pg_catalog.xid8,pg_catalog.xid8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xid8ge',
    rustName: 'sql__pg_catalog__xid8ge__41iy',
    args: ['pg_catalog.xid8', 'pg_catalog.xid8'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xid8gt"](pg_catalog.xid8,pg_catalog.xid8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xid8gt',
    rustName: 'sql__pg_catalog__xid8gt__1b0u',
    args: ['pg_catalog.xid8', 'pg_catalog.xid8'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xid8le"](pg_catalog.xid8,pg_catalog.xid8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xid8le',
    rustName: 'sql__pg_catalog__xid8le__pyad',
    args: ['pg_catalog.xid8', 'pg_catalog.xid8'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xid8lt"](pg_catalog.xid8,pg_catalog.xid8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xid8lt',
    rustName: 'sql__pg_catalog__xid8lt__zusi',
    args: ['pg_catalog.xid8', 'pg_catalog.xid8'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xid8ne"](pg_catalog.xid8,pg_catalog.xid8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xid8ne',
    rustName: 'sql__pg_catalog__xid8ne__cbvq',
    args: ['pg_catalog.xid8', 'pg_catalog.xid8'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xideq"](pg_catalog.xid,pg_catalog.xid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xideq',
    rustName: 'sql__pg_catalog__xideq__bmjv',
    args: ['pg_catalog.xid', 'pg_catalog.xid'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xideqint4"](pg_catalog.xid,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xideqint4',
    rustName: 'sql__pg_catalog__xideqint4__0glx',
    args: ['pg_catalog.xid', 'pg_catalog.int4'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xidneq"](pg_catalog.xid,pg_catalog.xid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xidneq',
    rustName: 'sql__pg_catalog__xidneq__5eig',
    args: ['pg_catalog.xid', 'pg_catalog.xid'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xidneqint4"](pg_catalog.xid,pg_catalog.int4)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xidneqint4',
    rustName: 'sql__pg_catalog__xidneqint4__27b3',
    args: ['pg_catalog.xid', 'pg_catalog.int4'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'operator:["pg_catalog","+"](pg_catalog."numeric",pg_catalog.pg_lsn)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '+',
    implementation:
      'function:["pg_catalog","numeric_pl_pg_lsn"](pg_catalog."numeric",pg_catalog.pg_lsn)',
    args: ['pg_catalog."numeric"', 'pg_catalog.pg_lsn'],
    left: 'pg_catalog."numeric"',
    right: 'pg_catalog.pg_lsn',
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","+"](pg_catalog.pg_lsn,pg_catalog."numeric")': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '+',
    implementation: 'function:["pg_catalog","pg_lsn_pli"](pg_catalog.pg_lsn,pg_catalog."numeric")',
    args: ['pg_catalog.pg_lsn', 'pg_catalog."numeric"'],
    left: 'pg_catalog.pg_lsn',
    right: 'pg_catalog."numeric"',
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","-"](pg_catalog.pg_lsn,pg_catalog."numeric")': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '-',
    implementation: 'function:["pg_catalog","pg_lsn_mii"](pg_catalog.pg_lsn,pg_catalog."numeric")',
    args: ['pg_catalog.pg_lsn', 'pg_catalog."numeric"'],
    left: 'pg_catalog.pg_lsn',
    right: 'pg_catalog."numeric"',
    result: 'pg_catalog.pg_lsn',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","-"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '-',
    implementation: 'function:["pg_catalog","pg_lsn_mi"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    left: 'pg_catalog.pg_lsn',
    right: 'pg_catalog.pg_lsn',
    result: 'pg_catalog."numeric"',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    implementation: 'function:["pg_catalog","pg_lsn_lt"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    left: 'pg_catalog.pg_lsn',
    right: 'pg_catalog.pg_lsn',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.tid,pg_catalog.tid)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    implementation: 'function:["pg_catalog","tidlt"](pg_catalog.tid,pg_catalog.tid)',
    args: ['pg_catalog.tid', 'pg_catalog.tid'],
    left: 'pg_catalog.tid',
    right: 'pg_catalog.tid',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<"](pg_catalog.xid8,pg_catalog.xid8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    implementation: 'function:["pg_catalog","xid8lt"](pg_catalog.xid8,pg_catalog.xid8)',
    args: ['pg_catalog.xid8', 'pg_catalog.xid8'],
    left: 'pg_catalog.xid8',
    right: 'pg_catalog.xid8',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    implementation: 'function:["pg_catalog","pg_lsn_le"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    left: 'pg_catalog.pg_lsn',
    right: 'pg_catalog.pg_lsn',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.tid,pg_catalog.tid)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    implementation: 'function:["pg_catalog","tidle"](pg_catalog.tid,pg_catalog.tid)',
    args: ['pg_catalog.tid', 'pg_catalog.tid'],
    left: 'pg_catalog.tid',
    right: 'pg_catalog.tid',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.xid8,pg_catalog.xid8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    implementation: 'function:["pg_catalog","xid8le"](pg_catalog.xid8,pg_catalog.xid8)',
    args: ['pg_catalog.xid8', 'pg_catalog.xid8'],
    left: 'pg_catalog.xid8',
    right: 'pg_catalog.xid8',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    implementation: 'function:["pg_catalog","pg_lsn_ne"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    left: 'pg_catalog.pg_lsn',
    right: 'pg_catalog.pg_lsn',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.tid,pg_catalog.tid)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    implementation: 'function:["pg_catalog","tidne"](pg_catalog.tid,pg_catalog.tid)',
    args: ['pg_catalog.tid', 'pg_catalog.tid'],
    left: 'pg_catalog.tid',
    right: 'pg_catalog.tid',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.xid,pg_catalog.int4)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    implementation: 'function:["pg_catalog","xidneqint4"](pg_catalog.xid,pg_catalog.int4)',
    args: ['pg_catalog.xid', 'pg_catalog.int4'],
    left: 'pg_catalog.xid',
    right: 'pg_catalog.int4',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.xid,pg_catalog.xid)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    implementation: 'function:["pg_catalog","xidneq"](pg_catalog.xid,pg_catalog.xid)',
    args: ['pg_catalog.xid', 'pg_catalog.xid'],
    left: 'pg_catalog.xid',
    right: 'pg_catalog.xid',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.xid8,pg_catalog.xid8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    implementation: 'function:["pg_catalog","xid8ne"](pg_catalog.xid8,pg_catalog.xid8)',
    args: ['pg_catalog.xid8', 'pg_catalog.xid8'],
    left: 'pg_catalog.xid8',
    right: 'pg_catalog.xid8',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.cid,pg_catalog.cid)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    implementation: 'function:["pg_catalog","cideq"](pg_catalog.cid,pg_catalog.cid)',
    args: ['pg_catalog.cid', 'pg_catalog.cid'],
    left: 'pg_catalog.cid',
    right: 'pg_catalog.cid',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    implementation: 'function:["pg_catalog","pg_lsn_eq"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    left: 'pg_catalog.pg_lsn',
    right: 'pg_catalog.pg_lsn',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.tid,pg_catalog.tid)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    implementation: 'function:["pg_catalog","tideq"](pg_catalog.tid,pg_catalog.tid)',
    args: ['pg_catalog.tid', 'pg_catalog.tid'],
    left: 'pg_catalog.tid',
    right: 'pg_catalog.tid',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.xid,pg_catalog.int4)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    implementation: 'function:["pg_catalog","xideqint4"](pg_catalog.xid,pg_catalog.int4)',
    args: ['pg_catalog.xid', 'pg_catalog.int4'],
    left: 'pg_catalog.xid',
    right: 'pg_catalog.int4',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.xid,pg_catalog.xid)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    implementation: 'function:["pg_catalog","xideq"](pg_catalog.xid,pg_catalog.xid)',
    args: ['pg_catalog.xid', 'pg_catalog.xid'],
    left: 'pg_catalog.xid',
    right: 'pg_catalog.xid',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.xid8,pg_catalog.xid8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    implementation: 'function:["pg_catalog","xid8eq"](pg_catalog.xid8,pg_catalog.xid8)',
    args: ['pg_catalog.xid8', 'pg_catalog.xid8'],
    left: 'pg_catalog.xid8',
    right: 'pg_catalog.xid8',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    implementation: 'function:["pg_catalog","pg_lsn_gt"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    left: 'pg_catalog.pg_lsn',
    right: 'pg_catalog.pg_lsn',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.tid,pg_catalog.tid)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    implementation: 'function:["pg_catalog","tidgt"](pg_catalog.tid,pg_catalog.tid)',
    args: ['pg_catalog.tid', 'pg_catalog.tid'],
    left: 'pg_catalog.tid',
    right: 'pg_catalog.tid',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.xid8,pg_catalog.xid8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    implementation: 'function:["pg_catalog","xid8gt"](pg_catalog.xid8,pg_catalog.xid8)',
    args: ['pg_catalog.xid8', 'pg_catalog.xid8'],
    left: 'pg_catalog.xid8',
    right: 'pg_catalog.xid8',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.pg_lsn,pg_catalog.pg_lsn)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    implementation: 'function:["pg_catalog","pg_lsn_ge"](pg_catalog.pg_lsn,pg_catalog.pg_lsn)',
    args: ['pg_catalog.pg_lsn', 'pg_catalog.pg_lsn'],
    left: 'pg_catalog.pg_lsn',
    right: 'pg_catalog.pg_lsn',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.tid,pg_catalog.tid)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    implementation: 'function:["pg_catalog","tidge"](pg_catalog.tid,pg_catalog.tid)',
    args: ['pg_catalog.tid', 'pg_catalog.tid'],
    left: 'pg_catalog.tid',
    right: 'pg_catalog.tid',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.xid8,pg_catalog.xid8)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    implementation: 'function:["pg_catalog","xid8ge"](pg_catalog.xid8,pg_catalog.xid8)',
    args: ['pg_catalog.xid8', 'pg_catalog.xid8'],
    left: 'pg_catalog.xid8',
    right: 'pg_catalog.xid8',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
} as const
