export const PG18_UUID = {
  'function:["pg_catalog","gen_random_uuid"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'gen_random_uuid',
    args: [],
    result: 'pg_catalog.uuid',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","uuid_cmp"](pg_catalog.uuid,pg_catalog.uuid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'uuid_cmp',
    args: ['pg_catalog.uuid', 'pg_catalog.uuid'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","uuid_eq"](pg_catalog.uuid,pg_catalog.uuid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'uuid_eq',
    args: ['pg_catalog.uuid', 'pg_catalog.uuid'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","uuid_extract_version"](pg_catalog.uuid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'uuid_extract_version',
    args: ['pg_catalog.uuid'],
    result: 'pg_catalog.int2',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","uuid_ge"](pg_catalog.uuid,pg_catalog.uuid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'uuid_ge',
    args: ['pg_catalog.uuid', 'pg_catalog.uuid'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","uuid_gt"](pg_catalog.uuid,pg_catalog.uuid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'uuid_gt',
    args: ['pg_catalog.uuid', 'pg_catalog.uuid'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","uuid_hash"](pg_catalog.uuid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'uuid_hash',
    args: ['pg_catalog.uuid'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","uuid_hash_extended"](pg_catalog.uuid,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'uuid_hash_extended',
    args: ['pg_catalog.uuid', 'pg_catalog.int8'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","uuid_le"](pg_catalog.uuid,pg_catalog.uuid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'uuid_le',
    args: ['pg_catalog.uuid', 'pg_catalog.uuid'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","uuid_lt"](pg_catalog.uuid,pg_catalog.uuid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'uuid_lt',
    args: ['pg_catalog.uuid', 'pg_catalog.uuid'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","uuid_ne"](pg_catalog.uuid,pg_catalog.uuid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'uuid_ne',
    args: ['pg_catalog.uuid', 'pg_catalog.uuid'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","uuidv4"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'uuidv4',
    args: [],
    result: 'pg_catalog.uuid',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","uuidv7"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'uuidv7',
    args: [],
    result: 'pg_catalog.uuid',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","uuidv7"](pg_catalog."interval")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'uuidv7',
    args: ['pg_catalog."interval"'],
    result: 'pg_catalog.uuid',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'operator:["pg_catalog","<"](pg_catalog.uuid,pg_catalog.uuid)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    args: ['pg_catalog.uuid', 'pg_catalog.uuid'],
    left: 'pg_catalog.uuid',
    right: 'pg_catalog.uuid',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.uuid,pg_catalog.uuid)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    args: ['pg_catalog.uuid', 'pg_catalog.uuid'],
    left: 'pg_catalog.uuid',
    right: 'pg_catalog.uuid',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.uuid,pg_catalog.uuid)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    args: ['pg_catalog.uuid', 'pg_catalog.uuid'],
    left: 'pg_catalog.uuid',
    right: 'pg_catalog.uuid',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.uuid,pg_catalog.uuid)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    args: ['pg_catalog.uuid', 'pg_catalog.uuid'],
    left: 'pg_catalog.uuid',
    right: 'pg_catalog.uuid',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.uuid,pg_catalog.uuid)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    args: ['pg_catalog.uuid', 'pg_catalog.uuid'],
    left: 'pg_catalog.uuid',
    right: 'pg_catalog.uuid',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.uuid,pg_catalog.uuid)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    args: ['pg_catalog.uuid', 'pg_catalog.uuid'],
    left: 'pg_catalog.uuid',
    right: 'pg_catalog.uuid',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
} as const
