export const PG18_UUID = {
  'function:["pg_catalog","gen_random_uuid"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'gen_random_uuid',
    rustName: 'sql__pg_catalog__gen_random_uuid__ouwn',
    args: [],
    result: 'pg_catalog.uuid',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","uuid_cmp"](pg_catalog.uuid,pg_catalog.uuid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'uuid_cmp',
    rustName: 'sql__pg_catalog__uuid_cmp__6t9k',
    args: ['pg_catalog.uuid', 'pg_catalog.uuid'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","uuid_eq"](pg_catalog.uuid,pg_catalog.uuid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'uuid_eq',
    rustName: 'sql__pg_catalog__uuid_eq__6czo',
    args: ['pg_catalog.uuid', 'pg_catalog.uuid'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","uuid_extract_version"](pg_catalog.uuid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'uuid_extract_version',
    rustName: 'sql__pg_catalog__uuid_extract_version__ydwe',
    args: ['pg_catalog.uuid'],
    result: 'pg_catalog.int2',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","uuid_ge"](pg_catalog.uuid,pg_catalog.uuid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'uuid_ge',
    rustName: 'sql__pg_catalog__uuid_ge__098n',
    args: ['pg_catalog.uuid', 'pg_catalog.uuid'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","uuid_gt"](pg_catalog.uuid,pg_catalog.uuid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'uuid_gt',
    rustName: 'sql__pg_catalog__uuid_gt__0fj1',
    args: ['pg_catalog.uuid', 'pg_catalog.uuid'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","uuid_hash"](pg_catalog.uuid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'uuid_hash',
    rustName: 'sql__pg_catalog__uuid_hash__8nnn',
    args: ['pg_catalog.uuid'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","uuid_hash_extended"](pg_catalog.uuid,pg_catalog.int8)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'uuid_hash_extended',
    rustName: 'sql__pg_catalog__uuid_hash_extended__i59z',
    args: ['pg_catalog.uuid', 'pg_catalog.int8'],
    result: 'pg_catalog.int8',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","uuid_le"](pg_catalog.uuid,pg_catalog.uuid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'uuid_le',
    rustName: 'sql__pg_catalog__uuid_le__g9j5',
    args: ['pg_catalog.uuid', 'pg_catalog.uuid'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","uuid_lt"](pg_catalog.uuid,pg_catalog.uuid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'uuid_lt',
    rustName: 'sql__pg_catalog__uuid_lt__50za',
    args: ['pg_catalog.uuid', 'pg_catalog.uuid'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","uuid_ne"](pg_catalog.uuid,pg_catalog.uuid)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'uuid_ne',
    rustName: 'sql__pg_catalog__uuid_ne__n2xp',
    args: ['pg_catalog.uuid', 'pg_catalog.uuid'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","uuidv4"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'uuidv4',
    rustName: 'sql__pg_catalog__uuidv4__3yo3',
    args: [],
    result: 'pg_catalog.uuid',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","uuidv7"]()': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'uuidv7',
    rustName: 'sql__pg_catalog__uuidv7__s79l',
    args: [],
    result: 'pg_catalog.uuid',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","uuidv7"](pg_catalog."interval")': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'uuidv7',
    rustName: 'sql__pg_catalog__uuidv7__l6f3',
    args: ['pg_catalog."interval"'],
    result: 'pg_catalog.uuid',
    strict: true,
    volatility: 'v',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'operator:["pg_catalog","<"](pg_catalog.uuid,pg_catalog.uuid)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<',
    implementation: 'function:["pg_catalog","uuid_lt"](pg_catalog.uuid,pg_catalog.uuid)',
    args: ['pg_catalog.uuid', 'pg_catalog.uuid'],
    left: 'pg_catalog.uuid',
    right: 'pg_catalog.uuid',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<="](pg_catalog.uuid,pg_catalog.uuid)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<=',
    implementation: 'function:["pg_catalog","uuid_le"](pg_catalog.uuid,pg_catalog.uuid)',
    args: ['pg_catalog.uuid', 'pg_catalog.uuid'],
    left: 'pg_catalog.uuid',
    right: 'pg_catalog.uuid',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","<>"](pg_catalog.uuid,pg_catalog.uuid)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '<>',
    implementation: 'function:["pg_catalog","uuid_ne"](pg_catalog.uuid,pg_catalog.uuid)',
    args: ['pg_catalog.uuid', 'pg_catalog.uuid'],
    left: 'pg_catalog.uuid',
    right: 'pg_catalog.uuid',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog","="](pg_catalog.uuid,pg_catalog.uuid)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '=',
    implementation: 'function:["pg_catalog","uuid_eq"](pg_catalog.uuid,pg_catalog.uuid)',
    args: ['pg_catalog.uuid', 'pg_catalog.uuid'],
    left: 'pg_catalog.uuid',
    right: 'pg_catalog.uuid',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">"](pg_catalog.uuid,pg_catalog.uuid)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>',
    implementation: 'function:["pg_catalog","uuid_gt"](pg_catalog.uuid,pg_catalog.uuid)',
    args: ['pg_catalog.uuid', 'pg_catalog.uuid'],
    left: 'pg_catalog.uuid',
    right: 'pg_catalog.uuid',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
  'operator:["pg_catalog",">="](pg_catalog.uuid,pg_catalog.uuid)': {
    kind: 'operator',
    schema: 'pg_catalog',
    name: '>=',
    implementation: 'function:["pg_catalog","uuid_ge"](pg_catalog.uuid,pg_catalog.uuid)',
    args: ['pg_catalog.uuid', 'pg_catalog.uuid'],
    left: 'pg_catalog.uuid',
    right: 'pg_catalog.uuid',
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
  },
} as const
