export const PG18_WINDOWS = {
  'window:["pg_catalog","cume_dist"]()': {
    kind: 'window',
    schema: 'pg_catalog',
    name: 'cume_dist',
    rustName: 'sql__pg_catalog__cume_dist__jrm1',
    args: [],
    result: 'pg_catalog.float8',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'window:["pg_catalog","dense_rank"]()': {
    kind: 'window',
    schema: 'pg_catalog',
    name: 'dense_rank',
    rustName: 'sql__pg_catalog__dense_rank__4so1',
    args: [],
    result: 'pg_catalog.int8',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'window:["pg_catalog","first_value"](pg_catalog.anyelement)': {
    kind: 'window',
    schema: 'pg_catalog',
    name: 'first_value',
    rustName: 'sql__pg_catalog__first_value__aer9',
    args: ['pg_catalog.anyelement'],
    result: 'pg_catalog.anyelement',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'window:["pg_catalog","lag"](pg_catalog.anycompatible,pg_catalog.int4,pg_catalog.anycompatible)':
    {
      kind: 'window',
      schema: 'pg_catalog',
      name: 'lag',
      rustName: 'sql__pg_catalog__lag__r195',
      args: ['pg_catalog.anycompatible', 'pg_catalog.int4', 'pg_catalog.anycompatible'],
      result: 'pg_catalog.anycompatible',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'window:["pg_catalog","lag"](pg_catalog.anyelement)': {
    kind: 'window',
    schema: 'pg_catalog',
    name: 'lag',
    rustName: 'sql__pg_catalog__lag__qtw2',
    args: ['pg_catalog.anyelement'],
    result: 'pg_catalog.anyelement',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'window:["pg_catalog","lag"](pg_catalog.anyelement,pg_catalog.int4)': {
    kind: 'window',
    schema: 'pg_catalog',
    name: 'lag',
    rustName: 'sql__pg_catalog__lag__evmw',
    args: ['pg_catalog.anyelement', 'pg_catalog.int4'],
    result: 'pg_catalog.anyelement',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'window:["pg_catalog","last_value"](pg_catalog.anyelement)': {
    kind: 'window',
    schema: 'pg_catalog',
    name: 'last_value',
    rustName: 'sql__pg_catalog__last_value__jqcz',
    args: ['pg_catalog.anyelement'],
    result: 'pg_catalog.anyelement',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'window:["pg_catalog","lead"](pg_catalog.anycompatible,pg_catalog.int4,pg_catalog.anycompatible)':
    {
      kind: 'window',
      schema: 'pg_catalog',
      name: 'lead',
      rustName: 'sql__pg_catalog__lead__e4ek',
      args: ['pg_catalog.anycompatible', 'pg_catalog.int4', 'pg_catalog.anycompatible'],
      result: 'pg_catalog.anycompatible',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'window:["pg_catalog","lead"](pg_catalog.anyelement)': {
    kind: 'window',
    schema: 'pg_catalog',
    name: 'lead',
    rustName: 'sql__pg_catalog__lead__l7w1',
    args: ['pg_catalog.anyelement'],
    result: 'pg_catalog.anyelement',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'window:["pg_catalog","lead"](pg_catalog.anyelement,pg_catalog.int4)': {
    kind: 'window',
    schema: 'pg_catalog',
    name: 'lead',
    rustName: 'sql__pg_catalog__lead__0jpw',
    args: ['pg_catalog.anyelement', 'pg_catalog.int4'],
    result: 'pg_catalog.anyelement',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'window:["pg_catalog","nth_value"](pg_catalog.anyelement,pg_catalog.int4)': {
    kind: 'window',
    schema: 'pg_catalog',
    name: 'nth_value',
    rustName: 'sql__pg_catalog__nth_value__frp7',
    args: ['pg_catalog.anyelement', 'pg_catalog.int4'],
    result: 'pg_catalog.anyelement',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'window:["pg_catalog","ntile"](pg_catalog.int4)': {
    kind: 'window',
    schema: 'pg_catalog',
    name: 'ntile',
    rustName: 'sql__pg_catalog__ntile__e6fn',
    args: ['pg_catalog.int4'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'window:["pg_catalog","percent_rank"]()': {
    kind: 'window',
    schema: 'pg_catalog',
    name: 'percent_rank',
    rustName: 'sql__pg_catalog__percent_rank__5ad8',
    args: [],
    result: 'pg_catalog.float8',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'window:["pg_catalog","rank"]()': {
    kind: 'window',
    schema: 'pg_catalog',
    name: 'rank',
    rustName: 'sql__pg_catalog__rank__24vo',
    args: [],
    result: 'pg_catalog.int8',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'window:["pg_catalog","row_number"]()': {
    kind: 'window',
    schema: 'pg_catalog',
    name: 'row_number',
    rustName: 'sql__pg_catalog__row_number__x3ew',
    args: [],
    result: 'pg_catalog.int8',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
} as const
