export const PG18_WINDOWS = {
  'window:["pg_catalog","cume_dist"]()': {
    kind: 'window',
    schema: 'pg_catalog',
    name: 'cume_dist',
    args: [],
    result: 'pg_catalog.float8',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'window:["pg_catalog","dense_rank"]()': {
    kind: 'window',
    schema: 'pg_catalog',
    name: 'dense_rank',
    args: [],
    result: 'pg_catalog.int8',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'window:["pg_catalog","first_value"](pg_catalog.anyelement)': {
    kind: 'window',
    schema: 'pg_catalog',
    name: 'first_value',
    args: ['pg_catalog.anyelement'],
    result: 'pg_catalog.anyelement',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'window:["pg_catalog","lag"](pg_catalog.anycompatible,pg_catalog.int4,pg_catalog.anycompatible)':
    {
      kind: 'window',
      schema: 'pg_catalog',
      name: 'lag',
      args: ['pg_catalog.anycompatible', 'pg_catalog.int4', 'pg_catalog.anycompatible'],
      result: 'pg_catalog.anycompatible',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'window:["pg_catalog","lag"](pg_catalog.anyelement)': {
    kind: 'window',
    schema: 'pg_catalog',
    name: 'lag',
    args: ['pg_catalog.anyelement'],
    result: 'pg_catalog.anyelement',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'window:["pg_catalog","lag"](pg_catalog.anyelement,pg_catalog.int4)': {
    kind: 'window',
    schema: 'pg_catalog',
    name: 'lag',
    args: ['pg_catalog.anyelement', 'pg_catalog.int4'],
    result: 'pg_catalog.anyelement',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'window:["pg_catalog","last_value"](pg_catalog.anyelement)': {
    kind: 'window',
    schema: 'pg_catalog',
    name: 'last_value',
    args: ['pg_catalog.anyelement'],
    result: 'pg_catalog.anyelement',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'window:["pg_catalog","lead"](pg_catalog.anycompatible,pg_catalog.int4,pg_catalog.anycompatible)':
    {
      kind: 'window',
      schema: 'pg_catalog',
      name: 'lead',
      args: ['pg_catalog.anycompatible', 'pg_catalog.int4', 'pg_catalog.anycompatible'],
      result: 'pg_catalog.anycompatible',
      strict: true,
      volatility: 'i',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'window:["pg_catalog","lead"](pg_catalog.anyelement)': {
    kind: 'window',
    schema: 'pg_catalog',
    name: 'lead',
    args: ['pg_catalog.anyelement'],
    result: 'pg_catalog.anyelement',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'window:["pg_catalog","lead"](pg_catalog.anyelement,pg_catalog.int4)': {
    kind: 'window',
    schema: 'pg_catalog',
    name: 'lead',
    args: ['pg_catalog.anyelement', 'pg_catalog.int4'],
    result: 'pg_catalog.anyelement',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'window:["pg_catalog","nth_value"](pg_catalog.anyelement,pg_catalog.int4)': {
    kind: 'window',
    schema: 'pg_catalog',
    name: 'nth_value',
    args: ['pg_catalog.anyelement', 'pg_catalog.int4'],
    result: 'pg_catalog.anyelement',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'window:["pg_catalog","ntile"](pg_catalog.int4)': {
    kind: 'window',
    schema: 'pg_catalog',
    name: 'ntile',
    args: ['pg_catalog.int4'],
    result: 'pg_catalog.int4',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'window:["pg_catalog","percent_rank"]()': {
    kind: 'window',
    schema: 'pg_catalog',
    name: 'percent_rank',
    args: [],
    result: 'pg_catalog.float8',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'window:["pg_catalog","rank"]()': {
    kind: 'window',
    schema: 'pg_catalog',
    name: 'rank',
    args: [],
    result: 'pg_catalog.int8',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'window:["pg_catalog","row_number"]()': {
    kind: 'window',
    schema: 'pg_catalog',
    name: 'row_number',
    args: [],
    result: 'pg_catalog.int8',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
} as const
