export const PG18_XML = {
  'function:["pg_catalog","cursor_to_xml"](pg_catalog.refcursor,pg_catalog.int4,pg_catalog.bool,pg_catalog.bool,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'cursor_to_xml',
      args: [
        'pg_catalog.refcursor',
        'pg_catalog.int4',
        'pg_catalog.bool',
        'pg_catalog.bool',
        'pg_catalog.text',
      ],
      result: 'pg_catalog.xml',
      strict: true,
      volatility: 'v',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","cursor_to_xmlschema"](pg_catalog.refcursor,pg_catalog.bool,pg_catalog.bool,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'cursor_to_xmlschema',
      args: ['pg_catalog.refcursor', 'pg_catalog.bool', 'pg_catalog.bool', 'pg_catalog.text'],
      result: 'pg_catalog.xml',
      strict: true,
      volatility: 'v',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","database_to_xml"](pg_catalog.bool,pg_catalog.bool,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'database_to_xml',
    args: ['pg_catalog.bool', 'pg_catalog.bool', 'pg_catalog.text'],
    result: 'pg_catalog.xml',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","database_to_xml_and_xmlschema"](pg_catalog.bool,pg_catalog.bool,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'database_to_xml_and_xmlschema',
      args: ['pg_catalog.bool', 'pg_catalog.bool', 'pg_catalog.text'],
      result: 'pg_catalog.xml',
      strict: true,
      volatility: 's',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","database_to_xmlschema"](pg_catalog.bool,pg_catalog.bool,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'database_to_xmlschema',
      args: ['pg_catalog.bool', 'pg_catalog.bool', 'pg_catalog.text'],
      result: 'pg_catalog.xml',
      strict: true,
      volatility: 's',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","query_to_xml"](pg_catalog.text,pg_catalog.bool,pg_catalog.bool,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'query_to_xml',
      args: ['pg_catalog.text', 'pg_catalog.bool', 'pg_catalog.bool', 'pg_catalog.text'],
      result: 'pg_catalog.xml',
      strict: true,
      volatility: 'v',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","query_to_xml_and_xmlschema"](pg_catalog.text,pg_catalog.bool,pg_catalog.bool,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'query_to_xml_and_xmlschema',
      args: ['pg_catalog.text', 'pg_catalog.bool', 'pg_catalog.bool', 'pg_catalog.text'],
      result: 'pg_catalog.xml',
      strict: true,
      volatility: 'v',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","query_to_xmlschema"](pg_catalog.text,pg_catalog.bool,pg_catalog.bool,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'query_to_xmlschema',
      args: ['pg_catalog.text', 'pg_catalog.bool', 'pg_catalog.bool', 'pg_catalog.text'],
      result: 'pg_catalog.xml',
      strict: true,
      volatility: 'v',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","schema_to_xml"](pg_catalog.name,pg_catalog.bool,pg_catalog.bool,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'schema_to_xml',
      args: ['pg_catalog.name', 'pg_catalog.bool', 'pg_catalog.bool', 'pg_catalog.text'],
      result: 'pg_catalog.xml',
      strict: true,
      volatility: 's',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","schema_to_xml_and_xmlschema"](pg_catalog.name,pg_catalog.bool,pg_catalog.bool,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'schema_to_xml_and_xmlschema',
      args: ['pg_catalog.name', 'pg_catalog.bool', 'pg_catalog.bool', 'pg_catalog.text'],
      result: 'pg_catalog.xml',
      strict: true,
      volatility: 's',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","schema_to_xmlschema"](pg_catalog.name,pg_catalog.bool,pg_catalog.bool,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'schema_to_xmlschema',
      args: ['pg_catalog.name', 'pg_catalog.bool', 'pg_catalog.bool', 'pg_catalog.text'],
      result: 'pg_catalog.xml',
      strict: true,
      volatility: 's',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","table_to_xml"](pg_catalog.regclass,pg_catalog.bool,pg_catalog.bool,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'table_to_xml',
      args: ['pg_catalog.regclass', 'pg_catalog.bool', 'pg_catalog.bool', 'pg_catalog.text'],
      result: 'pg_catalog.xml',
      strict: true,
      volatility: 's',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","table_to_xml_and_xmlschema"](pg_catalog.regclass,pg_catalog.bool,pg_catalog.bool,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'table_to_xml_and_xmlschema',
      args: ['pg_catalog.regclass', 'pg_catalog.bool', 'pg_catalog.bool', 'pg_catalog.text'],
      result: 'pg_catalog.xml',
      strict: true,
      volatility: 's',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","table_to_xmlschema"](pg_catalog.regclass,pg_catalog.bool,pg_catalog.bool,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'table_to_xmlschema',
      args: ['pg_catalog.regclass', 'pg_catalog.bool', 'pg_catalog.bool', 'pg_catalog.text'],
      result: 'pg_catalog.xml',
      strict: true,
      volatility: 's',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","text"](pg_catalog.xml)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'text',
    args: ['pg_catalog.xml'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xml"](pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xml',
    args: ['pg_catalog.text'],
    result: 'pg_catalog.xml',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xmlcomment"](pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xmlcomment',
    args: ['pg_catalog.text'],
    result: 'pg_catalog.xml',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xmlconcat2"](pg_catalog.xml,pg_catalog.xml)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xmlconcat2',
    args: ['pg_catalog.xml', 'pg_catalog.xml'],
    result: 'pg_catalog.xml',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xmlexists"](pg_catalog.text,pg_catalog.xml)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xmlexists',
    args: ['pg_catalog.text', 'pg_catalog.xml'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xmltext"](pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xmltext',
    args: ['pg_catalog.text'],
    result: 'pg_catalog.xml',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xmlvalidate"](pg_catalog.xml,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xmlvalidate',
    args: ['pg_catalog.xml', 'pg_catalog.text'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xpath_exists"](pg_catalog.text,pg_catalog.xml)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xpath_exists',
    args: ['pg_catalog.text', 'pg_catalog.xml'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xpath_exists"](pg_catalog.text,pg_catalog.xml,pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xpath_exists',
    args: ['pg_catalog.text', 'pg_catalog.xml', 'pg_catalog._text'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
} as const
