export const PG18_XML = {
  'function:["pg_catalog","cursor_to_xml"](pg_catalog.refcursor,pg_catalog.int4,pg_catalog.bool,pg_catalog.bool,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'cursor_to_xml',
      rustName: 'sql__pg_catalog__cursor_to_xml__c91d',
      args: [
        'pg_catalog.refcursor',
        'pg_catalog.int4',
        'pg_catalog.bool',
        'pg_catalog.bool',
        'pg_catalog.text',
      ],
      result: 'pg_catalog.xml',
      strict: true,
      volatility: 'v',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","cursor_to_xmlschema"](pg_catalog.refcursor,pg_catalog.bool,pg_catalog.bool,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'cursor_to_xmlschema',
      rustName: 'sql__pg_catalog__cursor_to_xmlschema__wun7',
      args: ['pg_catalog.refcursor', 'pg_catalog.bool', 'pg_catalog.bool', 'pg_catalog.text'],
      result: 'pg_catalog.xml',
      strict: true,
      volatility: 'v',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","database_to_xml"](pg_catalog.bool,pg_catalog.bool,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'database_to_xml',
    rustName: 'sql__pg_catalog__database_to_xml__luph',
    args: ['pg_catalog.bool', 'pg_catalog.bool', 'pg_catalog.text'],
    result: 'pg_catalog.xml',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","database_to_xml_and_xmlschema"](pg_catalog.bool,pg_catalog.bool,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'database_to_xml_and_xmlschema',
      rustName: 'sql__pg_catalog__database_to_xml_and_xmlschema__q9ta',
      args: ['pg_catalog.bool', 'pg_catalog.bool', 'pg_catalog.text'],
      result: 'pg_catalog.xml',
      strict: true,
      volatility: 's',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","database_to_xmlschema"](pg_catalog.bool,pg_catalog.bool,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'database_to_xmlschema',
      rustName: 'sql__pg_catalog__database_to_xmlschema__0n3f',
      args: ['pg_catalog.bool', 'pg_catalog.bool', 'pg_catalog.text'],
      result: 'pg_catalog.xml',
      strict: true,
      volatility: 's',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","query_to_xml"](pg_catalog.text,pg_catalog.bool,pg_catalog.bool,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'query_to_xml',
      rustName: 'sql__pg_catalog__query_to_xml__teqs',
      args: ['pg_catalog.text', 'pg_catalog.bool', 'pg_catalog.bool', 'pg_catalog.text'],
      result: 'pg_catalog.xml',
      strict: true,
      volatility: 'v',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","query_to_xml_and_xmlschema"](pg_catalog.text,pg_catalog.bool,pg_catalog.bool,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'query_to_xml_and_xmlschema',
      rustName: 'sql__pg_catalog__query_to_xml_and_xmlschema__8qwz',
      args: ['pg_catalog.text', 'pg_catalog.bool', 'pg_catalog.bool', 'pg_catalog.text'],
      result: 'pg_catalog.xml',
      strict: true,
      volatility: 'v',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","query_to_xmlschema"](pg_catalog.text,pg_catalog.bool,pg_catalog.bool,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'query_to_xmlschema',
      rustName: 'sql__pg_catalog__query_to_xmlschema__jz7t',
      args: ['pg_catalog.text', 'pg_catalog.bool', 'pg_catalog.bool', 'pg_catalog.text'],
      result: 'pg_catalog.xml',
      strict: true,
      volatility: 'v',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","schema_to_xml"](pg_catalog.name,pg_catalog.bool,pg_catalog.bool,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'schema_to_xml',
      rustName: 'sql__pg_catalog__schema_to_xml__jyvi',
      args: ['pg_catalog.name', 'pg_catalog.bool', 'pg_catalog.bool', 'pg_catalog.text'],
      result: 'pg_catalog.xml',
      strict: true,
      volatility: 's',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","schema_to_xml_and_xmlschema"](pg_catalog.name,pg_catalog.bool,pg_catalog.bool,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'schema_to_xml_and_xmlschema',
      rustName: 'sql__pg_catalog__schema_to_xml_and_xmlschema__noe6',
      args: ['pg_catalog.name', 'pg_catalog.bool', 'pg_catalog.bool', 'pg_catalog.text'],
      result: 'pg_catalog.xml',
      strict: true,
      volatility: 's',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","schema_to_xmlschema"](pg_catalog.name,pg_catalog.bool,pg_catalog.bool,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'schema_to_xmlschema',
      rustName: 'sql__pg_catalog__schema_to_xmlschema__6ksq',
      args: ['pg_catalog.name', 'pg_catalog.bool', 'pg_catalog.bool', 'pg_catalog.text'],
      result: 'pg_catalog.xml',
      strict: true,
      volatility: 's',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","table_to_xml"](pg_catalog.regclass,pg_catalog.bool,pg_catalog.bool,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'table_to_xml',
      rustName: 'sql__pg_catalog__table_to_xml__htv4',
      args: ['pg_catalog.regclass', 'pg_catalog.bool', 'pg_catalog.bool', 'pg_catalog.text'],
      result: 'pg_catalog.xml',
      strict: true,
      volatility: 's',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","table_to_xml_and_xmlschema"](pg_catalog.regclass,pg_catalog.bool,pg_catalog.bool,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'table_to_xml_and_xmlschema',
      rustName: 'sql__pg_catalog__table_to_xml_and_xmlschema__jo2d',
      args: ['pg_catalog.regclass', 'pg_catalog.bool', 'pg_catalog.bool', 'pg_catalog.text'],
      result: 'pg_catalog.xml',
      strict: true,
      volatility: 's',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","table_to_xmlschema"](pg_catalog.regclass,pg_catalog.bool,pg_catalog.bool,pg_catalog.text)':
    {
      kind: 'function',
      schema: 'pg_catalog',
      name: 'table_to_xmlschema',
      rustName: 'sql__pg_catalog__table_to_xmlschema__as2k',
      args: ['pg_catalog.regclass', 'pg_catalog.bool', 'pg_catalog.bool', 'pg_catalog.text'],
      result: 'pg_catalog.xml',
      strict: true,
      volatility: 's',
      returnsSet: false,
      variadic: null,
      numArgDefaults: 0,
      aggKind: null,
      numDirectArgs: null,
    },
  'function:["pg_catalog","text"](pg_catalog.xml)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'text',
    rustName: 'sql__pg_catalog__text__03xf',
    args: ['pg_catalog.xml'],
    result: 'pg_catalog.text',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xml"](pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xml',
    rustName: 'sql__pg_catalog__xml__8nn5',
    args: ['pg_catalog.text'],
    result: 'pg_catalog.xml',
    strict: true,
    volatility: 's',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xmlcomment"](pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xmlcomment',
    rustName: 'sql__pg_catalog__xmlcomment__8j57',
    args: ['pg_catalog.text'],
    result: 'pg_catalog.xml',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xmlconcat2"](pg_catalog.xml,pg_catalog.xml)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xmlconcat2',
    rustName: 'sql__pg_catalog__xmlconcat2__vnu3',
    args: ['pg_catalog.xml', 'pg_catalog.xml'],
    result: 'pg_catalog.xml',
    strict: false,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xmlexists"](pg_catalog.text,pg_catalog.xml)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xmlexists',
    rustName: 'sql__pg_catalog__xmlexists__3gat',
    args: ['pg_catalog.text', 'pg_catalog.xml'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xmltext"](pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xmltext',
    rustName: 'sql__pg_catalog__xmltext__a36t',
    args: ['pg_catalog.text'],
    result: 'pg_catalog.xml',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xmlvalidate"](pg_catalog.xml,pg_catalog.text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xmlvalidate',
    rustName: 'sql__pg_catalog__xmlvalidate__bvje',
    args: ['pg_catalog.xml', 'pg_catalog.text'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xpath_exists"](pg_catalog.text,pg_catalog.xml)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xpath_exists',
    rustName: 'sql__pg_catalog__xpath_exists__s9ul',
    args: ['pg_catalog.text', 'pg_catalog.xml'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
  'function:["pg_catalog","xpath_exists"](pg_catalog.text,pg_catalog.xml,pg_catalog._text)': {
    kind: 'function',
    schema: 'pg_catalog',
    name: 'xpath_exists',
    rustName: 'sql__pg_catalog__xpath_exists__1hns',
    args: ['pg_catalog.text', 'pg_catalog.xml', 'pg_catalog._text'],
    result: 'pg_catalog.bool',
    strict: true,
    volatility: 'i',
    returnsSet: false,
    variadic: null,
    numArgDefaults: 0,
    aggKind: null,
    numDirectArgs: null,
  },
} as const
