export const goArrayDependencies: Record<string, readonly string[]> = {
  SqlArray: ['SqlInteger'],
  arrayInput: ['SqlArray', 'SqlInteger'],
  arrayText: ['SqlArray', 'SqlText'],
  arrayCardinality: ['SqlArray', 'SqlInteger'],
  arrayNdims: ['SqlArray', 'SqlInteger'],
  arrayDims: ['SqlArray', 'SqlText'],
  arrayDimension: ['SqlArray', 'SqlInteger'],
  arrayLength: ['SqlArray', 'SqlInteger', 'arrayDimension'],
  arrayLower: ['SqlArray', 'SqlInteger', 'arrayDimension'],
  arrayUpper: ['SqlArray', 'SqlInteger', 'arrayDimension'],
  arrayCompare: ['SqlArray', 'SqlInteger'],
  arrayComparison: ['SqlArray', 'SqlBoolean', 'arrayCompare'],
  arrayLt: ['SqlArray', 'SqlBoolean', 'arrayComparison'],
  arrayLe: ['SqlArray', 'SqlBoolean', 'arrayComparison'],
  arrayGt: ['SqlArray', 'SqlBoolean', 'arrayComparison'],
  arrayGe: ['SqlArray', 'SqlBoolean', 'arrayComparison'],
  arrayEq: ['SqlArray', 'SqlBoolean'],
  arrayNe: ['SqlArray', 'SqlBoolean', 'arrayEq'],
  arrayContains: ['SqlArray', 'SqlBoolean'],
  arrayContained: ['SqlArray', 'SqlBoolean', 'arrayContains'],
  arrayOverlap: ['SqlArray', 'SqlBoolean'],
  arrayConcat: ['SqlArray'],
  arraySubscript: ['SqlArray', 'SqlInteger'],
  sqlIsNullArray: ['SqlArray', 'SqlBoolean'],
  sqlIsNotNullArray: ['SqlArray', 'SqlBoolean'],
  sqlCaseArray: ['SqlArray', 'SqlBoolean'],
  sqlCoalesceArray: ['SqlArray'],
}
