export const goArrayDependencies: Record<string, readonly string[]> = {
  SqlArray: ['SqlArrayElement'],
  SqlArrayElement: [],
  arrayElementInput: [
    'SqlArrayElement',
    'SqlInteger',
    'SqlFloat',
    'SqlDecimal',
    'SqlBoolean',
    'SqlText',
    'SqlUuid',
    'SqlEnum',
  ],
  arrayCoerceElement: [
    'SqlArrayElement',
    'arrayElementInput',
    'decimalFromInteger',
    'float4FromInteger',
    'float8FromInteger',
    'float4FromDecimal',
    'float8FromDecimal',
    'bpcharText',
  ],
  arrayCoerce: ['SqlArray', 'SqlArrayElement', 'arrayCoerceElement'],
  arrayElementText: [
    'SqlArrayElement',
    'SqlInteger',
    'SqlFloat',
    'SqlDecimal',
    'SqlBoolean',
    'SqlText',
    'SqlUuid',
    'SqlEnum',
    'sqlDecimalText',
    'uuidText',
  ],
  arrayElementCompare: [
    'SqlArrayElement',
    'SqlInteger',
    'SqlFloat',
    'SqlDecimal',
    'SqlBoolean',
    'SqlText',
    'SqlUuid',
    'SqlEnum',
    'sqlFloatCompare',
    'sqlDecimalCompare',
    'uuidCompare',
    'enumCompare',
  ],
  arrayInput: ['SqlArray', 'SqlArrayElement'],
  arrayText: ['SqlArray', 'SqlText', 'arrayElementText'],
  arrayCardinality: ['SqlArray', 'SqlInteger'],
  arrayNdims: ['SqlArray', 'SqlInteger'],
  arrayDims: ['SqlArray', 'SqlText'],
  arrayDimension: ['SqlArray', 'SqlInteger'],
  arrayLength: ['SqlArray', 'SqlInteger', 'arrayDimension'],
  arrayLower: ['SqlArray', 'SqlInteger', 'arrayDimension'],
  arrayUpper: ['SqlArray', 'SqlInteger', 'arrayDimension'],
  arrayCompare: ['SqlArray', 'SqlInteger', 'arrayElementCompare'],
  arrayComparison: ['SqlArray', 'SqlBoolean', 'arrayCompare'],
  arrayLt: ['SqlArray', 'SqlBoolean', 'arrayComparison'],
  arrayLe: ['SqlArray', 'SqlBoolean', 'arrayComparison'],
  arrayGt: ['SqlArray', 'SqlBoolean', 'arrayComparison'],
  arrayGe: ['SqlArray', 'SqlBoolean', 'arrayComparison'],
  arrayEq: ['SqlArray', 'SqlBoolean', 'arrayElementCompare'],
  arrayNe: ['SqlArray', 'SqlBoolean', 'arrayEq'],
  arrayContains: ['SqlArray', 'SqlBoolean', 'arrayElementCompare'],
  arrayContained: ['SqlArray', 'SqlBoolean', 'arrayContains'],
  arrayOverlap: ['SqlArray', 'SqlBoolean', 'arrayElementCompare'],
  arrayConcat: ['SqlArray'],
  arraySubscript: ['SqlArray', 'SqlArrayElement', 'SqlInteger'],
  arraySubscriptInteger: ['SqlArray', 'SqlInteger', 'arraySubscript'],
  arraySubscriptFloat: ['SqlArray', 'SqlInteger', 'SqlFloat', 'arraySubscript'],
  arraySubscriptDecimal: ['SqlArray', 'SqlInteger', 'SqlDecimal', 'arraySubscript'],
  arraySubscriptBoolean: ['SqlArray', 'SqlInteger', 'SqlBoolean', 'arraySubscript'],
  arraySubscriptText: ['SqlArray', 'SqlInteger', 'SqlText', 'arraySubscript'],
  arraySubscriptUuid: ['SqlArray', 'SqlInteger', 'SqlUuid', 'arraySubscript'],
  arraySubscriptEnum: ['SqlArray', 'SqlInteger', 'SqlEnum', 'arraySubscript'],
  arrayElementNotDistinct: ['SqlArrayElement', 'arrayElementCompare'],
  arrayAppend: ['SqlArray', 'SqlArrayElement'],
  arrayPrepend: ['SqlArray', 'SqlArrayElement'],
  arrayPosition: ['SqlArray', 'SqlArrayElement', 'SqlInteger', 'arrayPositionFrom'],
  arrayPositionStart: ['SqlArray', 'SqlArrayElement', 'SqlInteger', 'arrayPositionFrom'],
  arrayPositionFrom: ['SqlArray', 'SqlArrayElement', 'SqlInteger', 'arrayElementNotDistinct'],
  arrayPositions: [
    'SqlArray',
    'SqlArrayElement',
    'SqlInteger',
    'arrayElementNotDistinct',
    'arrayElementInput',
  ],
  arrayRemove: ['SqlArray', 'SqlArrayElement', 'arrayElementNotDistinct'],
  arrayReplace: ['SqlArray', 'SqlArrayElement', 'arrayElementNotDistinct'],
  arrayFill: ['SqlArray', 'SqlArrayElement', 'arrayFillInternal'],
  arrayFillBounds: ['SqlArray', 'SqlArrayElement', 'arrayFillInternal'],
  arrayFillInternal: ['SqlArray', 'SqlArrayElement', 'SqlInteger'],
  arrayTrim: ['SqlArray', 'SqlInteger'],
  arrayReverse: ['SqlArray', 'SqlArrayElement'],
  arraySort: ['SqlArray', 'SqlBoolean', 'arraySortInternal'],
  arraySortOrder: ['SqlArray', 'SqlBoolean', 'arraySortInternal'],
  arraySortNulls: ['SqlArray', 'SqlBoolean', 'arraySortInternal'],
  arraySortInternal: ['SqlArray', 'SqlArrayElement', 'SqlBoolean', 'arrayElementCompare'],
  arraySlice: ['SqlArray', 'SqlArrayElement', 'SqlInteger'],
  arrayAssign: ['SqlArray', 'SqlArrayElement', 'SqlInteger'],
  sqlIsNullArray: ['SqlArray', 'SqlBoolean'],
  sqlIsNotNullArray: ['SqlArray', 'SqlBoolean'],
  sqlCaseArray: ['SqlArray', 'SqlBoolean'],
  sqlCoalesceArray: ['SqlArray'],
}
