export const goArrayDependencies: Record<string, readonly string[]> = {
  SqlArray: ['SqlArrayElement'],
  SqlArrayElement: [],
  arrayElementInput: [
    'SqlArrayElement',
    'SqlInteger',
    'SqlFloat',
    'SqlDecimal',
    'SqlBoolean',
    'SqlText',
    'SqlUuid',
    'SqlEnum',
  ],
  arrayElementText: [
    'SqlArrayElement',
    'SqlInteger',
    'SqlFloat',
    'SqlDecimal',
    'SqlBoolean',
    'SqlText',
    'SqlUuid',
    'SqlEnum',
    'sqlDecimalText',
    'uuidText',
  ],
  arrayElementCompare: [
    'SqlArrayElement',
    'SqlInteger',
    'SqlFloat',
    'SqlDecimal',
    'SqlBoolean',
    'SqlText',
    'SqlUuid',
    'SqlEnum',
    'sqlFloatCompare',
    'sqlDecimalCompare',
    'uuidCompare',
    'enumCompare',
  ],
  arrayInput: ['SqlArray', 'SqlArrayElement'],
  arrayText: ['SqlArray', 'SqlText', 'arrayElementText'],
  arrayCardinality: ['SqlArray', 'SqlInteger'],
  arrayNdims: ['SqlArray', 'SqlInteger'],
  arrayDims: ['SqlArray', 'SqlText'],
  arrayDimension: ['SqlArray', 'SqlInteger'],
  arrayLength: ['SqlArray', 'SqlInteger', 'arrayDimension'],
  arrayLower: ['SqlArray', 'SqlInteger', 'arrayDimension'],
  arrayUpper: ['SqlArray', 'SqlInteger', 'arrayDimension'],
  arrayCompare: ['SqlArray', 'SqlInteger', 'arrayElementCompare'],
  arrayComparison: ['SqlArray', 'SqlBoolean', 'arrayCompare'],
  arrayLt: ['SqlArray', 'SqlBoolean', 'arrayComparison'],
  arrayLe: ['SqlArray', 'SqlBoolean', 'arrayComparison'],
  arrayGt: ['SqlArray', 'SqlBoolean', 'arrayComparison'],
  arrayGe: ['SqlArray', 'SqlBoolean', 'arrayComparison'],
  arrayEq: ['SqlArray', 'SqlBoolean', 'arrayElementCompare'],
  arrayNe: ['SqlArray', 'SqlBoolean', 'arrayEq'],
  arrayContains: ['SqlArray', 'SqlBoolean', 'arrayElementCompare'],
  arrayContained: ['SqlArray', 'SqlBoolean', 'arrayContains'],
  arrayOverlap: ['SqlArray', 'SqlBoolean', 'arrayElementCompare'],
  arrayConcat: ['SqlArray'],
  arraySubscript: ['SqlArray', 'SqlArrayElement', 'SqlInteger'],
  arraySubscriptInteger: ['SqlArray', 'SqlInteger', 'arraySubscript'],
  arraySubscriptFloat: ['SqlArray', 'SqlInteger', 'SqlFloat', 'arraySubscript'],
  arraySubscriptDecimal: ['SqlArray', 'SqlInteger', 'SqlDecimal', 'arraySubscript'],
  arraySubscriptBoolean: ['SqlArray', 'SqlInteger', 'SqlBoolean', 'arraySubscript'],
  arraySubscriptText: ['SqlArray', 'SqlInteger', 'SqlText', 'arraySubscript'],
  arraySubscriptUuid: ['SqlArray', 'SqlInteger', 'SqlUuid', 'arraySubscript'],
  arraySubscriptEnum: ['SqlArray', 'SqlInteger', 'SqlEnum', 'arraySubscript'],
  sqlIsNullArray: ['SqlArray', 'SqlBoolean'],
  sqlIsNotNullArray: ['SqlArray', 'SqlBoolean'],
  sqlCaseArray: ['SqlArray', 'SqlBoolean'],
  sqlCoalesceArray: ['SqlArray'],
}
