export const goBitDependencies: Record<string, readonly string[]> = {
  bitInput: ['SqlText'],
  bitPack: [],
  bitCompare: ['SqlInteger', 'SqlText', 'bitPack'],
  bitPredicate: ['SqlBoolean', 'SqlInteger', 'SqlText', 'bitCompare'],
  bitEq: ['SqlBoolean', 'SqlText', 'bitPredicate'],
  bitNe: ['SqlBoolean', 'SqlText', 'bitPredicate'],
  bitLt: ['SqlBoolean', 'SqlText', 'bitPredicate'],
  bitLe: ['SqlBoolean', 'SqlText', 'bitPredicate'],
  bitGt: ['SqlBoolean', 'SqlText', 'bitPredicate'],
  bitGe: ['SqlBoolean', 'SqlText', 'bitPredicate'],
  bitLength: ['SqlInteger', 'SqlText'],
  bitOctetLength: ['SqlInteger', 'SqlText'],
  bitCount: ['SqlInteger', 'SqlText'],
  bitSameWidth: [],
  bitCombine: ['SqlText', 'bitSameWidth'],
  bitAnd: ['SqlText', 'bitCombine'],
  bitOr: ['SqlText', 'bitCombine'],
  bitXor: ['SqlText', 'bitCombine'],
  bitNot: ['SqlText'],
  bitShift: ['SqlText', 'SqlInteger', 'repeatBit'],
  repeatBit: [],
  bitShiftLeft: ['SqlText', 'SqlInteger', 'bitShift'],
  bitShiftRight: ['SqlText', 'SqlInteger', 'bitShift'],
  bitCat: ['SqlText'],
  bitSubstring: [],
  bitSubstr: ['SqlText', 'SqlInteger', 'bitSubstring'],
  bitSubstrLength: ['SqlText', 'SqlInteger', 'bitSubstring'],
  bitOverlayLength: ['SqlText', 'SqlInteger', 'bitSubstring'],
  bitOverlay: ['SqlText', 'SqlInteger', 'bitOverlayLength', 'bitLength'],
  bitPosition: ['SqlInteger', 'SqlText'],
  bitGet: ['SqlInteger', 'SqlText'],
  bitSet: ['SqlText', 'SqlInteger'],
  bitTypmod: ['SqlText', 'SqlInteger', 'SqlBoolean', 'repeatBit'],
  varbitTypmod: ['SqlText', 'SqlInteger', 'SqlBoolean'],
  bitFromInt: ['SqlText', 'SqlInteger'],
  bitFromInt4: ['SqlText', 'SqlInteger', 'bitFromInt'],
  bitFromInt8: ['SqlText', 'SqlInteger', 'bitFromInt'],
  bitToInt: ['SqlInteger', 'SqlText'],
  bitToInt4: ['SqlInteger', 'SqlText', 'bitToInt'],
  bitToInt8: ['SqlInteger', 'SqlText', 'bitToInt'],
}
