export const goCheckDependencies: Record<string, readonly string[]> = {
  EvalBool: ['SqlBoolean'],
  evalBoolCertain: ['EvalBool'],
  evalBoolUncertain: ['EvalBool'],
  evalBoolNot: ['EvalBool'],
  evalBoolAnd: ['EvalBool', 'evalBoolCertain', 'evalBoolUncertain'],
  evalBoolOr: ['EvalBool', 'evalBoolCertain', 'evalBoolUncertain'],
  evalBoolCase: ['EvalBool', 'evalBoolUncertain'],
  evalBoolTest: ['EvalBool', 'evalBoolCertain'],
  evalBoolCompare: ['EvalBool', 'evalBoolCertain', 'evalBoolUncertain'],
  evalBoolRegex: ['EvalBool', 'SqlText', 'evalBoolCertain'],
  evalBoolRegexUnsupported: ['EvalBool', 'SqlText', 'evalBoolCertain', 'evalBoolUncertain'],
  evalBoolRegexInvalid: ['EvalBool', 'SqlText', 'evalBoolCertain'],
  evalBoolRegexAnalyze: [],
  evalBoolRegexDynamic: [
    'EvalBool',
    'SqlText',
    'evalBoolCertain',
    'evalBoolRegex',
    'evalBoolRegexUnsupported',
    'evalBoolRegexInvalid',
    'evalBoolRegexAnalyze',
  ],
  regexLikeFlags: [],
  evalBoolRegexInvalidFlags: ['EvalBool', 'SqlText', 'evalBoolCertain'],
  evalBoolRegexpLike: [
    'EvalBool',
    'SqlText',
    'evalBoolCertain',
    'evalBoolRegexDynamic',
    'regexLikeFlags',
  ],
}
