export const goCheckDependencies: Record<string, readonly string[]> = {
  regexEngineOptions: ['regexEngine'],
  evalBoolRegexEngine: [
    'regexEngineOptions',
    'EvalBool',
    'SqlText',
    'evalBoolCertain',
    'evalBoolUncertain',
  ],
  evalBoolRegexpLikeEngine: ['evalBoolRegexEngine', 'regexLikeFlags'],
  evalRegexCountEngine: [
    'regexEngineOptions',
    'regexLikeFlags',
    'EvalValue',
    'SqlInteger',
    'SqlText',
  ],
  EvalValue: [],
  EvalBool: ['EvalValue', 'SqlBoolean'],
  evalBoolFromValue: ['EvalBool', 'EvalValue'],
  evalValueFromBool: ['EvalBool', 'EvalValue'],
  evalBoolCertain: ['EvalBool'],
  evalBoolUncertain: ['EvalBool'],
  evalBoolNot: ['EvalBool'],
  evalBoolAnd: ['EvalBool', 'evalBoolCertain', 'evalBoolUncertain'],
  evalBoolOr: ['EvalBool', 'evalBoolCertain', 'evalBoolUncertain'],
  evalBoolCase: ['EvalBool', 'evalBoolUncertain'],
  evalBoolTest: ['EvalBool', 'evalBoolCertain'],
  evalBoolCompare: ['EvalBool', 'evalBoolCertain', 'evalBoolUncertain'],
  regexLikeFlags: [],
  evalBoolRegexInvalidFlags: ['EvalBool', 'SqlText', 'evalBoolCertain'],
}
