export const goDecimalMathDependencies: Record<string, readonly string[]> = {
  SqlDecimalMath: [],
  sqlDecimalMathRound: ['SqlDecimalMath'],
  sqlDecimalMathDigits: [],
  sqlDecimalMathWeight: ['sqlDecimalMathDigits'],
  sqlDecimalMathFromPairs: [],
  sqlDecimalMathAdd: ['SqlDecimalMath'],
  sqlDecimalMathMul: [
    'SqlDecimalMath',
    'sqlDecimalMathRound',
    'sqlDecimalMathDigits',
    'sqlDecimalMathFromPairs',
  ],
  sqlDecimalMathDiv: [
    'SqlDecimalMath',
    'sqlDecimalMathRound',
    'sqlDecimalMathDigits',
    'sqlDecimalMathFromPairs',
  ],
  sqlDecimalMathSqrt: ['SqlDecimalMath'],
  sqlDecimalMathFloat: [],
  sqlDecimalMathExp: [
    'SqlDecimalMath',
    'sqlDecimalMathRound',
    'sqlDecimalMathWeight',
    'sqlDecimalMathAdd',
    'sqlDecimalMathMul',
    'sqlDecimalMathDiv',
    'sqlDecimalMathFloat',
  ],
  sqlDecimalMathLnWeight: ['sqlDecimalMathDigits'],
  sqlDecimalMathLn: [
    'SqlDecimalMath',
    'sqlDecimalMathWeight',
    'sqlDecimalMathAdd',
    'sqlDecimalMathMul',
    'sqlDecimalMathDiv',
    'sqlDecimalMathSqrt',
  ],
  sqlDecimalMathScale: [],
  sqlDecimalMathPowerInt: [
    'SqlDecimalMath',
    'sqlDecimalMathRound',
    'sqlDecimalMathDigits',
    'sqlDecimalMathWeight',
    'sqlDecimalMathMul',
    'sqlDecimalMathDiv',
    'sqlDecimalMathScale',
  ],
  sqlDecimalMathPower: [
    'SqlDecimalMath',
    'sqlDecimalMathMul',
    'sqlDecimalMathFloat',
    'sqlDecimalMathExp',
    'sqlDecimalMathLnWeight',
    'sqlDecimalMathLn',
    'sqlDecimalMathScale',
    'sqlDecimalMathPowerInt',
  ],
  sqlDecimalMathUnary: [
    'SqlDecimalMath',
    'sqlDecimalMathWeight',
    'sqlDecimalMathSqrt',
    'sqlDecimalMathFloat',
    'sqlDecimalMathExp',
    'sqlDecimalMathLnWeight',
    'sqlDecimalMathLn',
    'sqlDecimalMathScale',
    'SqlDecimal',
    'sqlDecimalResult',
  ],
  decimalPower: [
    'SqlDecimalMath',
    'sqlDecimalMathPower',
    'SqlDecimal',
    'sqlDecimalResult',
    'sqlDecimalSign',
  ],
  decimalLog: [
    'SqlDecimalMath',
    'sqlDecimalMathDiv',
    'sqlDecimalMathLnWeight',
    'sqlDecimalMathLn',
    'sqlDecimalMathScale',
    'SqlDecimal',
    'sqlDecimalResult',
    'sqlDecimalSign',
  ],
  decimalSqrt: ['sqlDecimalMathUnary', 'SqlDecimal'],
  decimalExp: ['sqlDecimalMathUnary', 'SqlDecimal'],
  decimalLn: ['sqlDecimalMathUnary', 'SqlDecimal'],
  decimalLog10: ['decimalLog', 'SqlDecimal', 'sqlDecimalResult'],
}
