export const goDecimalDependencies: Record<string, readonly string[]> = {
  SqlDecimal: [],
  sqlDecimalResult: ['SqlDecimal'],
  sqlDecimalText: ['SqlDecimal'],
  decimalInput: ['sqlDecimalResult'],
  sqlDecimalSign: ['SqlDecimal'],
  sqlDecimalWeight: [],
  sqlDecimalBinary: ['sqlDecimalResult', 'sqlDecimalSign', 'sqlDecimalWeight'],
  sqlDecimalUnary: ['sqlDecimalResult', 'sqlDecimalSign'],
  sqlDecimalRound: ['sqlDecimalResult', 'SqlInteger'],
  decimalTypmod: ['sqlDecimalRound'],
  sqlDecimalCompare: ['SqlDecimal', 'SqlInteger'],
  sqlDecimalGcd: ['sqlDecimalResult'],
  decimalFromInteger: ['SqlInteger', 'sqlDecimalResult'],
  sqlDecimalFromFloat: ['SqlFloat', 'decimalInput'],
  sqlDecimalToInteger: ['SqlDecimal', 'SqlInteger'],
  sqlDecimalToFloat: ['SqlDecimal', 'SqlFloat'],
  decimalAdd: ['sqlDecimalBinary'],
  decimalSub: ['sqlDecimalBinary'],
  decimalMul: ['sqlDecimalBinary'],
  decimalDiv: ['sqlDecimalBinary'],
  decimalQuotient: ['sqlDecimalBinary'],
  decimalMod: ['sqlDecimalBinary'],
  decimalIdentity: ['sqlDecimalUnary'],
  decimalNeg: ['sqlDecimalUnary'],
  decimalAbs: ['sqlDecimalUnary'],
  decimalCeil: ['sqlDecimalUnary'],
  decimalFloor: ['sqlDecimalUnary'],
  decimalSign: ['sqlDecimalUnary'],
  decimalRound: ['sqlDecimalRound'],
  decimalTrunc: ['sqlDecimalRound'],
  decimalGcd: ['sqlDecimalGcd'],
  decimalLcm: ['sqlDecimalGcd'],
  decimalEq: ['sqlDecimalCompare', 'sqlComparisonResult'],
  decimalNe: ['sqlDecimalCompare', 'sqlComparisonResult'],
  decimalLt: ['sqlDecimalCompare', 'sqlComparisonResult'],
  decimalLe: ['sqlDecimalCompare', 'sqlComparisonResult'],
  decimalGt: ['sqlDecimalCompare', 'sqlComparisonResult'],
  decimalGe: ['sqlDecimalCompare', 'sqlComparisonResult'],
  int2FromDecimal: ['sqlDecimalToInteger'],
  int4FromDecimal: ['sqlDecimalToInteger'],
  int8FromDecimal: ['sqlDecimalToInteger'],
  decimalFromFloat4: ['sqlDecimalFromFloat'],
  float4FromDecimal: ['sqlDecimalToFloat'],
  decimalFromFloat8: ['sqlDecimalFromFloat'],
  float8FromDecimal: ['sqlDecimalToFloat'],
}
