import { go } from '../ast.js'
import type { GoExpression } from '../ast.js'
import type { CallableMetadata } from '../../../postgres/builtins/catalog.js'
import type {
  CallableEmitter,
  FunctionBindings,
  OperatorBindings,
} from '../../../sql-semantics/signatures.js'
import { PG18_NUMERIC } from '../../../postgres/builtins/numeric.generated.js'

function call<M extends CallableMetadata>(helper: string): CallableEmitter<M, GoExpression> {
  return {
    helpers: [helper],
    emit: (metadata, operands) => ({
      type: metadata.result,
      expression: go.call(
        go.ident(helper),
        operands.map((operand) => operand.expression),
      ),
    }),
  }
}

export const goFloatOperators = {
  'operator:["pg_catalog","^"](pg_catalog.float8,pg_catalog.float8)': call('float8Power'),
  'operator:["pg_catalog","+"](pg_catalog.float4,pg_catalog.float4)': call('float4Add'),
  'operator:["pg_catalog","+"](pg_catalog.float4,pg_catalog.float8)': call('float8Add'),
  'operator:["pg_catalog","+"](pg_catalog.float8,pg_catalog.float4)': call('float8Add'),
  'operator:["pg_catalog","+"](pg_catalog.float8,pg_catalog.float8)': call('float8Add'),
  'operator:["pg_catalog","-"](pg_catalog.float4,pg_catalog.float4)': call('float4Sub'),
  'operator:["pg_catalog","-"](pg_catalog.float4,pg_catalog.float8)': call('float8Sub'),
  'operator:["pg_catalog","-"](pg_catalog.float8,pg_catalog.float4)': call('float8Sub'),
  'operator:["pg_catalog","-"](pg_catalog.float8,pg_catalog.float8)': call('float8Sub'),
  'operator:["pg_catalog","*"](pg_catalog.float4,pg_catalog.float4)': call('float4Mul'),
  'operator:["pg_catalog","*"](pg_catalog.float4,pg_catalog.float8)': call('float8Mul'),
  'operator:["pg_catalog","*"](pg_catalog.float8,pg_catalog.float4)': call('float8Mul'),
  'operator:["pg_catalog","*"](pg_catalog.float8,pg_catalog.float8)': call('float8Mul'),
  'operator:["pg_catalog","/"](pg_catalog.float4,pg_catalog.float4)': call('float4Div'),
  'operator:["pg_catalog","/"](pg_catalog.float4,pg_catalog.float8)': call('float8Div'),
  'operator:["pg_catalog","/"](pg_catalog.float8,pg_catalog.float4)': call('float8Div'),
  'operator:["pg_catalog","/"](pg_catalog.float8,pg_catalog.float8)': call('float8Div'),
  'operator:["pg_catalog","="](pg_catalog.float4,pg_catalog.float4)': call('floatEq'),
  'operator:["pg_catalog","="](pg_catalog.float4,pg_catalog.float8)': call('floatEq'),
  'operator:["pg_catalog","="](pg_catalog.float8,pg_catalog.float4)': call('floatEq'),
  'operator:["pg_catalog","="](pg_catalog.float8,pg_catalog.float8)': call('floatEq'),
  'operator:["pg_catalog","<>"](pg_catalog.float4,pg_catalog.float4)': call('floatNe'),
  'operator:["pg_catalog","<>"](pg_catalog.float4,pg_catalog.float8)': call('floatNe'),
  'operator:["pg_catalog","<>"](pg_catalog.float8,pg_catalog.float4)': call('floatNe'),
  'operator:["pg_catalog","<>"](pg_catalog.float8,pg_catalog.float8)': call('floatNe'),
  'operator:["pg_catalog","<"](pg_catalog.float4,pg_catalog.float4)': call('floatLt'),
  'operator:["pg_catalog","<"](pg_catalog.float4,pg_catalog.float8)': call('floatLt'),
  'operator:["pg_catalog","<"](pg_catalog.float8,pg_catalog.float4)': call('floatLt'),
  'operator:["pg_catalog","<"](pg_catalog.float8,pg_catalog.float8)': call('floatLt'),
  'operator:["pg_catalog","<="](pg_catalog.float4,pg_catalog.float4)': call('floatLe'),
  'operator:["pg_catalog","<="](pg_catalog.float4,pg_catalog.float8)': call('floatLe'),
  'operator:["pg_catalog","<="](pg_catalog.float8,pg_catalog.float4)': call('floatLe'),
  'operator:["pg_catalog","<="](pg_catalog.float8,pg_catalog.float8)': call('floatLe'),
  'operator:["pg_catalog",">"](pg_catalog.float4,pg_catalog.float4)': call('floatGt'),
  'operator:["pg_catalog",">"](pg_catalog.float4,pg_catalog.float8)': call('floatGt'),
  'operator:["pg_catalog",">"](pg_catalog.float8,pg_catalog.float4)': call('floatGt'),
  'operator:["pg_catalog",">"](pg_catalog.float8,pg_catalog.float8)': call('floatGt'),
  'operator:["pg_catalog",">="](pg_catalog.float4,pg_catalog.float4)': call('floatGe'),
  'operator:["pg_catalog",">="](pg_catalog.float4,pg_catalog.float8)': call('floatGe'),
  'operator:["pg_catalog",">="](pg_catalog.float8,pg_catalog.float4)': call('floatGe'),
  'operator:["pg_catalog",">="](pg_catalog.float8,pg_catalog.float8)': call('floatGe'),
  'operator:["pg_catalog","-"](,pg_catalog.float4)': call('float4Neg'),
  'operator:["pg_catalog","+"](,pg_catalog.float4)': call('float4Identity'),
  'operator:["pg_catalog","@"](,pg_catalog.float4)': call('float4Abs'),
  'operator:["pg_catalog","-"](,pg_catalog.float8)': call('float8Neg'),
  'operator:["pg_catalog","+"](,pg_catalog.float8)': call('float8Identity'),
  'operator:["pg_catalog","@"](,pg_catalog.float8)': call('float8Abs'),
  'operator:["pg_catalog","|/"](,pg_catalog.float8)': call('float8Sqrt'),
  'operator:["pg_catalog","||/"](,pg_catalog.float8)': call('float8Cbrt'),
} satisfies OperatorBindings<typeof PG18_NUMERIC, GoExpression>

export const goFloatFunctions = {
  'function:["pg_catalog","power"](pg_catalog.float8,pg_catalog.float8)': call('float8Power'),
  'function:["pg_catalog","pow"](pg_catalog.float8,pg_catalog.float8)': call('float8Power'),
  'function:["pg_catalog","exp"](pg_catalog.float8)': call('float8Exp'),
  'function:["pg_catalog","ln"](pg_catalog.float8)': call('float8Ln'),
  'function:["pg_catalog","log"](pg_catalog.float8)': call('float8Log10'),
  'function:["pg_catalog","log10"](pg_catalog.float8)': call('float8Log10'),
  'function:["pg_catalog","width_bucket"](pg_catalog.float8,pg_catalog.float8,pg_catalog.float8,pg_catalog.int4)':
    call('float8WidthBucket'),
  'function:["pg_catalog","abs"](pg_catalog.float4)': call('float4Abs'),
  'function:["pg_catalog","float4"](pg_catalog.float8)': call('float4FromFloat8'),
  'function:["pg_catalog","float4"](pg_catalog.int2)': call('float4FromInteger'),
  'function:["pg_catalog","int2"](pg_catalog.float4)': call('int2FromFloat'),
  'function:["pg_catalog","float4"](pg_catalog.int4)': call('float4FromInteger'),
  'function:["pg_catalog","int4"](pg_catalog.float4)': call('int4FromFloat'),
  'function:["pg_catalog","float4"](pg_catalog.int8)': call('float4FromInteger'),
  'function:["pg_catalog","int8"](pg_catalog.float4)': call('int8FromFloat'),
  'function:["pg_catalog","abs"](pg_catalog.float8)': call('float8Abs'),
  'function:["pg_catalog","float8"](pg_catalog.float4)': call('float8FromFloat4'),
  'function:["pg_catalog","float8"](pg_catalog.int2)': call('float8FromInteger'),
  'function:["pg_catalog","int2"](pg_catalog.float8)': call('int2FromFloat'),
  'function:["pg_catalog","float8"](pg_catalog.int4)': call('float8FromInteger'),
  'function:["pg_catalog","int4"](pg_catalog.float8)': call('int4FromFloat'),
  'function:["pg_catalog","float8"](pg_catalog.int8)': call('float8FromInteger'),
  'function:["pg_catalog","int8"](pg_catalog.float8)': call('int8FromFloat'),
  'function:["pg_catalog","ceil"](pg_catalog.float8)': call('float8Ceil'),
  'function:["pg_catalog","ceiling"](pg_catalog.float8)': call('float8Ceil'),
  'function:["pg_catalog","floor"](pg_catalog.float8)': call('float8Floor'),
  'function:["pg_catalog","round"](pg_catalog.float8)': call('float8Round'),
  'function:["pg_catalog","trunc"](pg_catalog.float8)': call('float8Trunc'),
  'function:["pg_catalog","sign"](pg_catalog.float8)': call('float8Sign'),
  'function:["pg_catalog","sqrt"](pg_catalog.float8)': call('float8Sqrt'),
  'function:["pg_catalog","cbrt"](pg_catalog.float8)': call('float8Cbrt'),
} satisfies FunctionBindings<typeof PG18_NUMERIC, GoExpression>
