export const goJsonDependencies: Record<string, readonly string[]> = {
  SqlJsonPair: ['SqlJsonNode'],
  SqlJsonNode: ['SqlDecimal', 'SqlJsonPair'],
  SqlJson: ['SqlJsonNode'],
  SqlJsonb: ['SqlJsonNode'],
  jsonParser: [],
  jsonFail: ['SqlJson'],
  jsonbFail: ['SqlJsonb'],
  jsonParserSkip: ['jsonParser'],
  jsonParserFail: ['jsonParser'],
  jsonParserIdentEnd: ['jsonParser'],
  jsonHex: [],
  jsonParseString: ['jsonParser', 'jsonParserFail', 'jsonHex'],
  jsonParseNumber: ['jsonParser', 'jsonParserFail'],
  jsonParseValue: [
    'jsonParser',
    'jsonParserSkip',
    'jsonParserIdentEnd',
    'jsonParserFail',
    'jsonParseString',
    'jsonParseNumber',
    'decimalInput',
    'SqlJsonNode',
    'SqlJsonPair',
  ],
  jsonParse: ['jsonParser', 'jsonParseValue', 'jsonParserSkip', 'SqlJsonNode'],
  jsonbKeyCompare: ['jsonStringCompare'],
  jsonStringCompare: [],
  jsonbCanonicalize: ['SqlJsonNode', 'SqlJsonPair', 'jsonbKeyCompare'],
  jsonbEscape: [],
  jsonbFormat: ['SqlJsonNode', 'jsonbEscape', 'sqlDecimalText'],
  jsonInput: ['SqlJson', 'jsonParse', 'jsonFail'],
  jsonbInput: ['SqlJsonb', 'jsonParse', 'jsonbCanonicalize', 'jsonbFail'],
  jsonFromText: ['SqlJson', 'SqlText', 'jsonInput', 'jsonFail'],
  jsonbFromText: ['SqlJsonb', 'SqlText', 'jsonbInput', 'jsonbFail'],
  jsonText: ['SqlJson', 'SqlText'],
  jsonbText: ['SqlJsonb', 'SqlText', 'jsonbFormat'],
  jsonToJsonb: ['SqlJson', 'SqlJsonb', 'jsonbInput', 'jsonbFail'],
  jsonbToJson: ['SqlJson', 'SqlJsonb', 'jsonbFormat', 'jsonFail'],
  jsonTypeName: [],
  jsonTypeof: ['SqlJson', 'SqlText', 'jsonTypeName'],
  jsonbTypeof: ['SqlJsonb', 'SqlText', 'jsonTypeName'],
  jsonArrayLength: ['SqlJson', 'SqlInteger'],
  jsonbArrayLength: ['SqlJsonb', 'SqlInteger'],
  jsonField: ['SqlJsonNode'],
  jsonIndex: ['SqlJsonNode'],
  jsonAsText: ['SqlJsonNode', 'jsonbFormat', 'sqlDecimalText'],
  jsonObjectField: ['SqlJson', 'SqlText', 'jsonField', 'jsonFail'],
  jsonObjectFieldText: ['SqlJson', 'SqlText', 'jsonField', 'jsonAsText'],
  jsonbObjectField: ['SqlJsonb', 'SqlText', 'jsonField', 'jsonbFail'],
  jsonbObjectFieldText: ['SqlJsonb', 'SqlText', 'jsonField', 'jsonAsText'],
  jsonArrayElement: ['SqlJson', 'SqlInteger', 'jsonIndex', 'jsonFail'],
  jsonArrayElementText: ['SqlJson', 'SqlInteger', 'SqlText', 'jsonIndex', 'jsonAsText'],
  jsonbArrayElement: ['SqlJsonb', 'SqlInteger', 'jsonIndex', 'jsonbFail'],
  jsonbArrayElementText: ['SqlJsonb', 'SqlInteger', 'SqlText', 'jsonIndex', 'jsonAsText'],
  jsonPathIndex: [],
  jsonPathKeys: ['SqlArray', 'SqlText'],
  jsonExtract: ['SqlJsonNode', 'jsonField', 'jsonIndex', 'jsonPathIndex'],
  jsonExtractPath: ['SqlJson', 'SqlArray', 'jsonPathKeys', 'jsonExtract', 'jsonFail'],
  jsonExtractPathText: ['SqlJson', 'SqlArray', 'SqlText', 'jsonExtractPath', 'jsonAsText'],
  jsonbExtractPath: ['SqlJsonb', 'SqlArray', 'jsonPathKeys', 'jsonExtract', 'jsonbFail'],
  jsonbExtractPathText: ['SqlJsonb', 'SqlArray', 'SqlText', 'jsonbExtractPath', 'jsonAsText'],
  jsonbTypeRank: [],
  jsonbScalarCompare: ['SqlJsonNode', 'sqlDecimalCompare', 'jsonStringCompare'],
  jsonCmpToken: ['SqlJsonNode'],
  jsonWalk: ['jsonCmpToken', 'SqlJsonNode'],
  jsonTokenType: ['jsonCmpToken', 'jsonbTypeRank'],
  jsonbCompare: [
    'SqlJsonb',
    'SqlInteger',
    'jsonWalk',
    'jsonTokenType',
    'jsonbTypeRank',
    'jsonbScalarCompare',
    'jsonStringCompare',
  ],
  jsonbComparison: ['SqlJsonb', 'SqlBoolean', 'jsonbCompare'],
  jsonbEq: ['jsonbComparison'],
  jsonbNe: ['jsonbComparison'],
  jsonbLt: ['jsonbComparison'],
  jsonbLe: ['jsonbComparison'],
  jsonbGt: ['jsonbComparison'],
  jsonbGe: ['jsonbComparison'],
  jsonContainer: ['SqlJsonNode'],
  jsonbDeepContains: ['SqlJsonNode', 'jsonField', 'jsonContainer', 'jsonbScalarCompare'],
  jsonbContains: ['SqlJsonb', 'SqlBoolean', 'jsonbDeepContains'],
  jsonbContained: ['jsonbContains'],
  jsonbExists: ['SqlJsonb', 'SqlText', 'SqlBoolean', 'jsonField'],
  jsonbExistsAll: ['SqlJsonb', 'SqlArray', 'SqlBoolean', 'jsonPathKeys', 'jsonbExists'],
  jsonbExistsAny: ['SqlJsonb', 'SqlArray', 'SqlBoolean', 'jsonPathKeys', 'jsonbExists'],
  sqlIsNullJson: ['SqlJson', 'SqlBoolean'],
  sqlIsNotNullJson: ['SqlJson', 'SqlBoolean'],
  sqlCaseJson: ['SqlJson', 'SqlBoolean', 'jsonFail'],
  sqlCoalesceJson: ['SqlJson'],
  sqlIsNullJsonb: ['SqlJsonb', 'SqlBoolean'],
  sqlIsNotNullJsonb: ['SqlJsonb', 'SqlBoolean'],
  sqlCaseJsonb: ['SqlJsonb', 'SqlBoolean', 'jsonbFail'],
  sqlCoalesceJsonb: ['SqlJsonb'],
}
