export const goJsonDependencies: Record<string, readonly string[]> = {
  SqlJsonPair: ['SqlJsonNode'],
  SqlJsonNode: ['SqlDecimal', 'SqlJsonPair'],
  SqlJson: ['SqlJsonNode'],
  SqlJsonb: ['SqlJsonNode'],
  jsonParser: [],
  jsonFail: ['SqlJson'],
  jsonbFail: ['SqlJsonb'],
  jsonParserSkip: ['jsonParser'],
  jsonParserFail: ['jsonParser'],
  jsonParserIdentEnd: ['jsonParser'],
  jsonHex: [],
  jsonParseString: ['jsonParser', 'jsonParserFail', 'jsonHex'],
  jsonParseNumber: ['jsonParser', 'jsonParserFail'],
  jsonParseValue: [
    'jsonParser',
    'jsonParserSkip',
    'jsonParserIdentEnd',
    'jsonParserFail',
    'jsonParseString',
    'jsonParseNumber',
    'decimalInput',
    'SqlJsonNode',
    'SqlJsonPair',
  ],
  jsonParse: ['jsonParser', 'jsonParseValue', 'jsonParserSkip', 'SqlJsonNode'],
  jsonbKeyCompare: ['jsonStringCompare'],
  jsonStringCompare: [],
  jsonbCanonicalize: ['SqlJsonNode', 'SqlJsonPair', 'jsonbKeyCompare'],
  jsonbEscape: [],
  jsonbFormat: ['SqlJsonNode', 'jsonbEscape', 'sqlDecimalText'],
  jsonInput: ['SqlJson', 'jsonParse', 'jsonFail'],
  jsonbInput: ['SqlJsonb', 'jsonParse', 'jsonbCanonicalize', 'jsonbFail'],
  jsonFromText: ['SqlJson', 'SqlText', 'jsonInput', 'jsonFail'],
  jsonbFromText: ['SqlJsonb', 'SqlText', 'jsonbInput', 'jsonbFail'],
  jsonText: ['SqlJson', 'SqlText'],
  jsonbText: ['SqlJsonb', 'SqlText', 'jsonbFormat'],
  jsonToJsonb: ['SqlJson', 'SqlJsonb', 'jsonbInput', 'jsonbFail'],
  jsonbToJson: ['SqlJson', 'SqlJsonb', 'jsonbFormat', 'jsonFail'],
  jsonTypeName: [],
  jsonTypeof: ['SqlJson', 'SqlText', 'jsonTypeName'],
  jsonbTypeof: ['SqlJsonb', 'SqlText', 'jsonTypeName'],
  jsonArrayLength: ['SqlJson', 'SqlInteger'],
  jsonbArrayLength: ['SqlJsonb', 'SqlInteger'],
  jsonField: ['SqlJsonNode'],
  jsonIndex: ['SqlJsonNode'],
  jsonAsText: ['SqlJsonNode', 'jsonbFormat', 'sqlDecimalText'],
  jsonObjectField: ['SqlJson', 'SqlText', 'jsonField', 'jsonFail'],
  jsonObjectFieldText: ['SqlJson', 'SqlText', 'jsonField', 'jsonAsText'],
  jsonbObjectField: ['SqlJsonb', 'SqlText', 'jsonField', 'jsonbFail'],
  jsonbObjectFieldText: ['SqlJsonb', 'SqlText', 'jsonField', 'jsonAsText'],
  jsonArrayElement: ['SqlJson', 'SqlInteger', 'jsonIndex', 'jsonFail'],
  jsonArrayElementText: ['SqlJson', 'SqlInteger', 'SqlText', 'jsonIndex', 'jsonAsText'],
  jsonbArrayElement: ['SqlJsonb', 'SqlInteger', 'jsonIndex', 'jsonbFail'],
  jsonbArrayElementText: ['SqlJsonb', 'SqlInteger', 'SqlText', 'jsonIndex', 'jsonAsText'],
  jsonPathIndex: [],
  jsonPathKeys: ['SqlArray', 'SqlText'],
  jsonExtract: ['SqlJsonNode', 'jsonField', 'jsonIndex', 'jsonPathIndex'],
  jsonExtractPath: ['SqlJson', 'SqlArray', 'jsonPathKeys', 'jsonExtract', 'jsonFail'],
  jsonExtractPathText: ['SqlJson', 'SqlArray', 'SqlText', 'jsonExtractPath', 'jsonAsText'],
  jsonbExtractPath: ['SqlJsonb', 'SqlArray', 'jsonPathKeys', 'jsonExtract', 'jsonbFail'],
  jsonbExtractPathText: ['SqlJsonb', 'SqlArray', 'SqlText', 'jsonbExtractPath', 'jsonAsText'],
  jsonbTypeRank: [],
  jsonbScalarCompare: ['SqlJsonNode', 'sqlDecimalCompare', 'jsonStringCompare'],
  jsonCmpToken: ['SqlJsonNode'],
  jsonWalk: ['jsonCmpToken', 'SqlJsonNode'],
  jsonTokenType: ['jsonCmpToken', 'jsonbTypeRank'],
  jsonbCompare: [
    'SqlJsonb',
    'SqlInteger',
    'jsonWalk',
    'jsonTokenType',
    'jsonbTypeRank',
    'jsonbScalarCompare',
    'jsonStringCompare',
  ],
  jsonbComparison: ['SqlJsonb', 'SqlBoolean', 'jsonbCompare'],
  jsonbEq: ['jsonbComparison'],
  jsonbNe: ['jsonbComparison'],
  jsonbLt: ['jsonbComparison'],
  jsonbLe: ['jsonbComparison'],
  jsonbGt: ['jsonbComparison'],
  jsonbGe: ['jsonbComparison'],
  jsonContainer: ['SqlJsonNode'],
  jsonbDeepContains: ['SqlJsonNode', 'jsonField', 'jsonContainer', 'jsonbScalarCompare'],
  jsonbContains: ['SqlJsonb', 'SqlBoolean', 'jsonbDeepContains'],
  jsonbContained: ['jsonbContains'],
  jsonbExists: ['SqlJsonb', 'SqlText', 'SqlBoolean', 'jsonField'],
  jsonbExistsAll: ['SqlJsonb', 'SqlArray', 'SqlBoolean', 'jsonPathKeys', 'jsonbExists'],
  jsonbExistsAny: ['SqlJsonb', 'SqlArray', 'SqlBoolean', 'jsonPathKeys', 'jsonbExists'],
  jsonbNodeCopy: ['SqlJsonNode', 'SqlJsonPair'],
  jsonbConcat: ['SqlJsonb', 'jsonbCanonicalize', 'jsonbNodeCopy'],
  jsonbDeleteKey: ['SqlJsonb', 'jsonbFail'],
  jsonbDeleteIndex: ['SqlJsonb', 'jsonbFail'],
  jsonbDeleteKeys: ['SqlJsonb', 'SqlArray', 'jsonPathKeys', 'jsonbDeleteKey', 'jsonbFail'],
  jsonbPathInt: [],
  jsonbSetPath: ['SqlJsonNode', 'SqlJsonPair', 'jsonbPathInt', 'jsonbCanonicalize'],
  jsonbMutatePath: ['SqlJsonb', 'SqlArray', 'jsonPathKeys', 'jsonbSetPath', 'jsonbFail'],
  jsonbDeletePath: ['jsonbMutatePath'],
  jsonbSet: ['jsonbMutatePath'],
  jsonbInsert: ['jsonbMutatePath'],
  jsonbSetLax: [
    'SqlJsonb',
    'SqlArray',
    'SqlBoolean',
    'SqlText',
    'jsonbSet',
    'jsonbDeletePath',
    'jsonbFail',
  ],
  jsonFormatCompact: ['SqlJsonNode', 'jsonbEscape', 'sqlDecimalText'],
  jsonStripNullsNode: ['SqlJsonNode', 'SqlJsonPair'],
  jsonStripNulls: ['SqlJson', 'jsonStripNullsNode', 'jsonFormatCompact', 'jsonFail'],
  jsonbStripNulls: ['SqlJsonb', 'jsonStripNullsNode', 'jsonbCanonicalize', 'jsonbFail'],
  jsonbPretty: ['SqlJsonb', 'SqlText', 'jsonbEscape', 'jsonbFormat'],
  jsonbToBool: ['SqlJsonb', 'SqlBoolean'],
  jsonbToNumeric: ['SqlJsonb', 'SqlDecimal'],
  jsonbToInt2: ['jsonbToNumeric', 'int2FromDecimal'],
  jsonbToInt4: ['jsonbToNumeric', 'int4FromDecimal'],
  jsonbToInt8: ['jsonbToNumeric', 'int8FromDecimal'],
  jsonbToFloat4: ['jsonbToNumeric', 'float4FromDecimal'],
  jsonbToFloat8: ['jsonbToNumeric', 'float8FromDecimal'],
  jsonArrayText: ['SqlArrayElement', 'SqlText'],
  jsonTextPairs: ['SqlArray', 'jsonArrayText'],
  jsonObject: ['SqlJson', 'SqlArray', 'jsonTextPairs', 'jsonbEscape', 'jsonParse', 'jsonFail'],
  jsonObjectPair: ['SqlJson', 'SqlArray', 'jsonTextPairs', 'jsonbEscape', 'jsonParse', 'jsonFail'],
  jsonbObject: ['SqlJsonb', 'SqlArray', 'jsonTextPairs', 'jsonbCanonicalize', 'jsonbFail'],
  jsonbObjectPair: ['SqlJsonb', 'SqlArray', 'jsonTextPairs', 'jsonbCanonicalize', 'jsonbFail'],
  jsonDatumError: [
    'SqlInteger',
    'SqlFloat',
    'SqlDecimal',
    'SqlBoolean',
    'SqlText',
    'SqlUuid',
    'SqlEnum',
    'SqlJson',
    'SqlJsonb',
    'SqlArray',
  ],
  jsonDatumNull: [
    'SqlInteger',
    'SqlFloat',
    'SqlDecimal',
    'SqlBoolean',
    'SqlText',
    'SqlUuid',
    'SqlEnum',
    'SqlJson',
    'SqlJsonb',
    'SqlArray',
  ],
  jsonFloatText: [],
  jsonKeyString: ['jsonDatumError', 'jsonDatumNull', 'jsonFloatText', 'sqlDecimalText', 'uuidText'],
  jsonArrayFromSql: ['SqlArray', 'SqlJsonNode', 'jsonFromValue'],
  jsonFromValue: [
    'SqlJsonNode',
    'jsonDatumError',
    'jsonDatumNull',
    'jsonFloatText',
    'jsonbEscape',
    'jsonbFormat',
    'decimalInput',
    'sqlDecimalText',
    'uuidText',
    'jsonKeyString',
    'jsonArrayFromSql',
  ],
  arrayToJson: ['SqlJson', 'SqlArray', 'jsonArrayFromSql', 'jsonFail'],
  arrayToJsonPretty: ['SqlJson', 'SqlArray', 'jsonArrayFromSql', 'arrayToJson', 'jsonFail'],
  toJson: ['SqlJson', 'jsonDatumError', 'jsonDatumNull', 'jsonFromValue', 'jsonFail'],
  toJsonb: [
    'SqlJsonb',
    'jsonDatumError',
    'jsonDatumNull',
    'jsonFromValue',
    'jsonbCanonicalize',
    'jsonbFail',
  ],
  jsonBuildArray: ['SqlJson', 'jsonDatumError', 'jsonDatumNull', 'jsonFromValue', 'jsonFail'],
  jsonBuildObject: [
    'SqlJson',
    'jsonDatumError',
    'jsonDatumNull',
    'jsonKeyString',
    'jsonFromValue',
    'jsonbEscape',
    'jsonParse',
    'jsonFail',
  ],
  jsonbBuildArray: [
    'SqlJsonb',
    'jsonDatumError',
    'jsonDatumNull',
    'jsonFromValue',
    'jsonbCanonicalize',
    'jsonbFail',
  ],
  jsonbBuildObject: [
    'SqlJsonb',
    'jsonDatumError',
    'jsonDatumNull',
    'jsonKeyString',
    'jsonFromValue',
    'jsonbCanonicalize',
    'jsonbFail',
  ],
  sqlIsNullJson: ['SqlJson', 'SqlBoolean'],
  sqlIsNotNullJson: ['SqlJson', 'SqlBoolean'],
  sqlCaseJson: ['SqlJson', 'SqlBoolean', 'jsonFail'],
  sqlCoalesceJson: ['SqlJson'],
  sqlIsNullJsonb: ['SqlJsonb', 'SqlBoolean'],
  sqlIsNotNullJsonb: ['SqlJsonb', 'SqlBoolean'],
  sqlCaseJsonb: ['SqlJsonb', 'SqlBoolean', 'jsonbFail'],
  sqlCoalesceJsonb: ['SqlJsonb'],
}
