import { go } from '../ast.js'
import type { GoExpression } from '../ast.js'
import type { CallableMetadata } from '../../../postgres/builtins/catalog.js'
import type {
  CallableEmitter,
  FunctionBindings,
  OperatorBindings,
} from '../../../sql-semantics/signatures.js'
import { PG18_NUMERIC } from '../../../postgres/builtins/numeric.generated.js'

function call<M extends CallableMetadata>(helper: string): CallableEmitter<M, GoExpression> {
  return {
    helpers: [helper],
    emit: (metadata, operands) => ({
      type: metadata.result,
      expression: go.call(
        go.ident(helper),
        operands.map((operand) => operand.expression),
      ),
    }),
  }
}

export const goNumericOperators = {
  'operator:["pg_catalog","+"](pg_catalog.int2,pg_catalog.int2)': call('int2Add'),
  'operator:["pg_catalog","+"](pg_catalog.int2,pg_catalog.int4)': call('int4Add'),
  'operator:["pg_catalog","+"](pg_catalog.int2,pg_catalog.int8)': call('int8Add'),
  'operator:["pg_catalog","+"](pg_catalog.int4,pg_catalog.int2)': call('int4Add'),
  'operator:["pg_catalog","+"](pg_catalog.int4,pg_catalog.int4)': call('int4Add'),
  'operator:["pg_catalog","+"](pg_catalog.int4,pg_catalog.int8)': call('int8Add'),
  'operator:["pg_catalog","+"](pg_catalog.int8,pg_catalog.int2)': call('int8Add'),
  'operator:["pg_catalog","+"](pg_catalog.int8,pg_catalog.int4)': call('int8Add'),
  'operator:["pg_catalog","+"](pg_catalog.int8,pg_catalog.int8)': call('int8Add'),
  'operator:["pg_catalog","-"](pg_catalog.int2,pg_catalog.int2)': call('int2Sub'),
  'operator:["pg_catalog","-"](pg_catalog.int2,pg_catalog.int4)': call('int4Sub'),
  'operator:["pg_catalog","-"](pg_catalog.int2,pg_catalog.int8)': call('int8Sub'),
  'operator:["pg_catalog","-"](pg_catalog.int4,pg_catalog.int2)': call('int4Sub'),
  'operator:["pg_catalog","-"](pg_catalog.int4,pg_catalog.int4)': call('int4Sub'),
  'operator:["pg_catalog","-"](pg_catalog.int4,pg_catalog.int8)': call('int8Sub'),
  'operator:["pg_catalog","-"](pg_catalog.int8,pg_catalog.int2)': call('int8Sub'),
  'operator:["pg_catalog","-"](pg_catalog.int8,pg_catalog.int4)': call('int8Sub'),
  'operator:["pg_catalog","-"](pg_catalog.int8,pg_catalog.int8)': call('int8Sub'),
  'operator:["pg_catalog","*"](pg_catalog.int2,pg_catalog.int2)': call('int2Mul'),
  'operator:["pg_catalog","*"](pg_catalog.int2,pg_catalog.int4)': call('int4Mul'),
  'operator:["pg_catalog","*"](pg_catalog.int2,pg_catalog.int8)': call('int8Mul'),
  'operator:["pg_catalog","*"](pg_catalog.int4,pg_catalog.int2)': call('int4Mul'),
  'operator:["pg_catalog","*"](pg_catalog.int4,pg_catalog.int4)': call('int4Mul'),
  'operator:["pg_catalog","*"](pg_catalog.int4,pg_catalog.int8)': call('int8Mul'),
  'operator:["pg_catalog","*"](pg_catalog.int8,pg_catalog.int2)': call('int8Mul'),
  'operator:["pg_catalog","*"](pg_catalog.int8,pg_catalog.int4)': call('int8Mul'),
  'operator:["pg_catalog","*"](pg_catalog.int8,pg_catalog.int8)': call('int8Mul'),
  'operator:["pg_catalog","="](pg_catalog.int2,pg_catalog.int2)': call('integerEq'),
  'operator:["pg_catalog","="](pg_catalog.int2,pg_catalog.int4)': call('integerEq'),
  'operator:["pg_catalog","="](pg_catalog.int2,pg_catalog.int8)': call('integerEq'),
  'operator:["pg_catalog","="](pg_catalog.int4,pg_catalog.int2)': call('integerEq'),
  'operator:["pg_catalog","="](pg_catalog.int4,pg_catalog.int4)': call('integerEq'),
  'operator:["pg_catalog","="](pg_catalog.int4,pg_catalog.int8)': call('integerEq'),
  'operator:["pg_catalog","="](pg_catalog.int8,pg_catalog.int2)': call('integerEq'),
  'operator:["pg_catalog","="](pg_catalog.int8,pg_catalog.int4)': call('integerEq'),
  'operator:["pg_catalog","="](pg_catalog.int8,pg_catalog.int8)': call('integerEq'),
  'operator:["pg_catalog","<>"](pg_catalog.int2,pg_catalog.int2)': call('integerNe'),
  'operator:["pg_catalog","<>"](pg_catalog.int2,pg_catalog.int4)': call('integerNe'),
  'operator:["pg_catalog","<>"](pg_catalog.int2,pg_catalog.int8)': call('integerNe'),
  'operator:["pg_catalog","<>"](pg_catalog.int4,pg_catalog.int2)': call('integerNe'),
  'operator:["pg_catalog","<>"](pg_catalog.int4,pg_catalog.int4)': call('integerNe'),
  'operator:["pg_catalog","<>"](pg_catalog.int4,pg_catalog.int8)': call('integerNe'),
  'operator:["pg_catalog","<>"](pg_catalog.int8,pg_catalog.int2)': call('integerNe'),
  'operator:["pg_catalog","<>"](pg_catalog.int8,pg_catalog.int4)': call('integerNe'),
  'operator:["pg_catalog","<>"](pg_catalog.int8,pg_catalog.int8)': call('integerNe'),
  'operator:["pg_catalog","<"](pg_catalog.int2,pg_catalog.int2)': call('integerLt'),
  'operator:["pg_catalog","<"](pg_catalog.int2,pg_catalog.int4)': call('integerLt'),
  'operator:["pg_catalog","<"](pg_catalog.int2,pg_catalog.int8)': call('integerLt'),
  'operator:["pg_catalog","<"](pg_catalog.int4,pg_catalog.int2)': call('integerLt'),
  'operator:["pg_catalog","<"](pg_catalog.int4,pg_catalog.int4)': call('integerLt'),
  'operator:["pg_catalog","<"](pg_catalog.int4,pg_catalog.int8)': call('integerLt'),
  'operator:["pg_catalog","<"](pg_catalog.int8,pg_catalog.int2)': call('integerLt'),
  'operator:["pg_catalog","<"](pg_catalog.int8,pg_catalog.int4)': call('integerLt'),
  'operator:["pg_catalog","<"](pg_catalog.int8,pg_catalog.int8)': call('integerLt'),
  'operator:["pg_catalog","<="](pg_catalog.int2,pg_catalog.int2)': call('integerLe'),
  'operator:["pg_catalog","<="](pg_catalog.int2,pg_catalog.int4)': call('integerLe'),
  'operator:["pg_catalog","<="](pg_catalog.int2,pg_catalog.int8)': call('integerLe'),
  'operator:["pg_catalog","<="](pg_catalog.int4,pg_catalog.int2)': call('integerLe'),
  'operator:["pg_catalog","<="](pg_catalog.int4,pg_catalog.int4)': call('integerLe'),
  'operator:["pg_catalog","<="](pg_catalog.int4,pg_catalog.int8)': call('integerLe'),
  'operator:["pg_catalog","<="](pg_catalog.int8,pg_catalog.int2)': call('integerLe'),
  'operator:["pg_catalog","<="](pg_catalog.int8,pg_catalog.int4)': call('integerLe'),
  'operator:["pg_catalog","<="](pg_catalog.int8,pg_catalog.int8)': call('integerLe'),
  'operator:["pg_catalog",">"](pg_catalog.int2,pg_catalog.int2)': call('integerGt'),
  'operator:["pg_catalog",">"](pg_catalog.int2,pg_catalog.int4)': call('integerGt'),
  'operator:["pg_catalog",">"](pg_catalog.int2,pg_catalog.int8)': call('integerGt'),
  'operator:["pg_catalog",">"](pg_catalog.int4,pg_catalog.int2)': call('integerGt'),
  'operator:["pg_catalog",">"](pg_catalog.int4,pg_catalog.int4)': call('integerGt'),
  'operator:["pg_catalog",">"](pg_catalog.int4,pg_catalog.int8)': call('integerGt'),
  'operator:["pg_catalog",">"](pg_catalog.int8,pg_catalog.int2)': call('integerGt'),
  'operator:["pg_catalog",">"](pg_catalog.int8,pg_catalog.int4)': call('integerGt'),
  'operator:["pg_catalog",">"](pg_catalog.int8,pg_catalog.int8)': call('integerGt'),
  'operator:["pg_catalog",">="](pg_catalog.int2,pg_catalog.int2)': call('integerGe'),
  'operator:["pg_catalog",">="](pg_catalog.int2,pg_catalog.int4)': call('integerGe'),
  'operator:["pg_catalog",">="](pg_catalog.int2,pg_catalog.int8)': call('integerGe'),
  'operator:["pg_catalog",">="](pg_catalog.int4,pg_catalog.int2)': call('integerGe'),
  'operator:["pg_catalog",">="](pg_catalog.int4,pg_catalog.int4)': call('integerGe'),
  'operator:["pg_catalog",">="](pg_catalog.int4,pg_catalog.int8)': call('integerGe'),
  'operator:["pg_catalog",">="](pg_catalog.int8,pg_catalog.int2)': call('integerGe'),
  'operator:["pg_catalog",">="](pg_catalog.int8,pg_catalog.int4)': call('integerGe'),
  'operator:["pg_catalog",">="](pg_catalog.int8,pg_catalog.int8)': call('integerGe'),
  'operator:["pg_catalog","-"](,pg_catalog.int2)': call('int2Neg'),
  'operator:["pg_catalog","-"](,pg_catalog.int4)': call('int4Neg'),
  'operator:["pg_catalog","-"](,pg_catalog.int8)': call('int8Neg'),
  'operator:["pg_catalog","/"](pg_catalog.int2,pg_catalog.int2)': call('int2Div'),
  'operator:["pg_catalog","/"](pg_catalog.int2,pg_catalog.int4)': call('int4Div'),
  'operator:["pg_catalog","/"](pg_catalog.int2,pg_catalog.int8)': call('int8Div'),
  'operator:["pg_catalog","/"](pg_catalog.int4,pg_catalog.int2)': call('int4Div'),
  'operator:["pg_catalog","/"](pg_catalog.int4,pg_catalog.int4)': call('int4Div'),
  'operator:["pg_catalog","/"](pg_catalog.int4,pg_catalog.int8)': call('int8Div'),
  'operator:["pg_catalog","/"](pg_catalog.int8,pg_catalog.int2)': call('int8Div'),
  'operator:["pg_catalog","/"](pg_catalog.int8,pg_catalog.int4)': call('int8Div'),
  'operator:["pg_catalog","/"](pg_catalog.int8,pg_catalog.int8)': call('int8Div'),
  'operator:["pg_catalog","%"](pg_catalog.int2,pg_catalog.int2)': call('int2Mod'),
  'operator:["pg_catalog","%"](pg_catalog.int4,pg_catalog.int4)': call('int4Mod'),
  'operator:["pg_catalog","%"](pg_catalog.int8,pg_catalog.int8)': call('int8Mod'),
  'operator:["pg_catalog","&"](pg_catalog.int2,pg_catalog.int2)': call('int2And'),
  'operator:["pg_catalog","|"](pg_catalog.int2,pg_catalog.int2)': call('int2Or'),
  'operator:["pg_catalog","#"](pg_catalog.int2,pg_catalog.int2)': call('int2Xor'),
  'operator:["pg_catalog","<<"](pg_catalog.int2,pg_catalog.int4)': call('int2Shl'),
  'operator:["pg_catalog",">>"](pg_catalog.int2,pg_catalog.int4)': call('int2Shr'),
  'operator:["pg_catalog","~"](,pg_catalog.int2)': call('int2Not'),
  'operator:["pg_catalog","+"](,pg_catalog.int2)': call('int2Identity'),
  'operator:["pg_catalog","@"](,pg_catalog.int2)': call('int2Abs'),
  'operator:["pg_catalog","&"](pg_catalog.int4,pg_catalog.int4)': call('int4And'),
  'operator:["pg_catalog","|"](pg_catalog.int4,pg_catalog.int4)': call('int4Or'),
  'operator:["pg_catalog","#"](pg_catalog.int4,pg_catalog.int4)': call('int4Xor'),
  'operator:["pg_catalog","<<"](pg_catalog.int4,pg_catalog.int4)': call('int4Shl'),
  'operator:["pg_catalog",">>"](pg_catalog.int4,pg_catalog.int4)': call('int4Shr'),
  'operator:["pg_catalog","~"](,pg_catalog.int4)': call('int4Not'),
  'operator:["pg_catalog","+"](,pg_catalog.int4)': call('int4Identity'),
  'operator:["pg_catalog","@"](,pg_catalog.int4)': call('int4Abs'),
  'operator:["pg_catalog","&"](pg_catalog.int8,pg_catalog.int8)': call('int8And'),
  'operator:["pg_catalog","|"](pg_catalog.int8,pg_catalog.int8)': call('int8Or'),
  'operator:["pg_catalog","#"](pg_catalog.int8,pg_catalog.int8)': call('int8Xor'),
  'operator:["pg_catalog","<<"](pg_catalog.int8,pg_catalog.int4)': call('int8Shl'),
  'operator:["pg_catalog",">>"](pg_catalog.int8,pg_catalog.int4)': call('int8Shr'),
  'operator:["pg_catalog","~"](,pg_catalog.int8)': call('int8Not'),
  'operator:["pg_catalog","+"](,pg_catalog.int8)': call('int8Identity'),
  'operator:["pg_catalog","@"](,pg_catalog.int8)': call('int8Abs'),
} satisfies OperatorBindings<typeof PG18_NUMERIC, GoExpression>

export const goNumericFunctions = {
  'function:["pg_catalog","abs"](pg_catalog.int2)': call('int2Abs'),
  'function:["pg_catalog","abs"](pg_catalog.int4)': call('int4Abs'),
  'function:["pg_catalog","abs"](pg_catalog.int8)': call('int8Abs'),
  'function:["pg_catalog","int2"](pg_catalog.int4)': call('int2Cast'),
  'function:["pg_catalog","int2"](pg_catalog.int8)': call('int2Cast'),
  'function:["pg_catalog","int4"](pg_catalog.int2)': call('int4Cast'),
  'function:["pg_catalog","int4"](pg_catalog.int8)': call('int4Cast'),
  'function:["pg_catalog","int8"](pg_catalog.int2)': call('int8Cast'),
  'function:["pg_catalog","int8"](pg_catalog.int4)': call('int8Cast'),
  'function:["pg_catalog","mod"](pg_catalog.int2,pg_catalog.int2)': call('int2Mod'),
  'function:["pg_catalog","mod"](pg_catalog.int4,pg_catalog.int4)': call('int4Mod'),
  'function:["pg_catalog","mod"](pg_catalog.int8,pg_catalog.int8)': call('int8Mod'),
  'function:["pg_catalog","gcd"](pg_catalog.int4,pg_catalog.int4)': call('int4Gcd'),
  'function:["pg_catalog","gcd"](pg_catalog.int8,pg_catalog.int8)': call('int8Gcd'),
  'function:["pg_catalog","lcm"](pg_catalog.int4,pg_catalog.int4)': call('int4Lcm'),
  'function:["pg_catalog","lcm"](pg_catalog.int8,pg_catalog.int8)': call('int8Lcm'),
} satisfies FunctionBindings<typeof PG18_NUMERIC, GoExpression>
