export const goScalarDependencies: Record<string, readonly string[]> = {
  SqlText: [],
  booleanInput: ['SqlBoolean'],
  textInput: ['SqlText'],
  sqlBooleanNot: ['SqlBoolean'],
  sqlBooleanAnd: ['SqlBoolean'],
  sqlBooleanOr: ['SqlBoolean'],
  sqlIsNullInteger: ['SqlInteger', 'SqlBoolean'],
  sqlIsNotNullInteger: ['SqlInteger', 'SqlBoolean'],
  sqlCaseInteger: ['SqlBoolean', 'SqlInteger'],
  sqlCoalesceInteger: ['SqlInteger'],
  sqlIsNullFloat: ['SqlFloat', 'SqlBoolean'],
  sqlIsNotNullFloat: ['SqlFloat', 'SqlBoolean'],
  sqlCaseFloat: ['SqlBoolean', 'SqlFloat'],
  sqlCoalesceFloat: ['SqlFloat'],
  sqlIsNullDecimal: ['SqlDecimal', 'SqlBoolean'],
  sqlIsNotNullDecimal: ['SqlDecimal', 'SqlBoolean'],
  sqlCaseDecimal: ['SqlBoolean', 'SqlDecimal'],
  sqlCoalesceDecimal: ['SqlDecimal'],
  sqlIsNullBoolean: ['SqlBoolean', 'SqlBoolean'],
  sqlIsNotNullBoolean: ['SqlBoolean', 'SqlBoolean'],
  sqlCaseBoolean: ['SqlBoolean', 'SqlBoolean'],
  sqlCoalesceBoolean: ['SqlBoolean'],
  sqlIsNullText: ['SqlText', 'SqlBoolean'],
  sqlIsNotNullText: ['SqlText', 'SqlBoolean'],
  sqlCaseText: ['SqlBoolean', 'SqlText'],
  sqlCoalesceText: ['SqlText'],
  booleanEq: ['SqlBoolean'],
  textEq: ['SqlBoolean', 'SqlText'],
  booleanNe: ['SqlBoolean'],
  textNe: ['SqlBoolean', 'SqlText'],
  booleanLt: ['SqlBoolean'],
  textLt: ['SqlBoolean', 'SqlText'],
  booleanLe: ['SqlBoolean'],
  textLe: ['SqlBoolean', 'SqlText'],
  booleanGt: ['SqlBoolean'],
  textGt: ['SqlBoolean', 'SqlText'],
  booleanGe: ['SqlBoolean'],
  textGe: ['SqlBoolean', 'SqlText'],
  textLength: ['SqlText', 'SqlInteger'],
  textOctetLength: ['SqlText', 'SqlInteger'],
  textConcat: ['SqlText'],
}
