export const goTemporalDependencies: Record<string, readonly string[]> = {
  SqlDate: [],
  SqlTime: [],
  SqlTimestamp: [],
  SqlInterval: [],
  temporalDate2j: [],
  temporalJ2date: [],
  temporalIsLeap: [],
  temporalMonthDays: ['temporalIsLeap'],
  temporalPad: [],
  temporalSecondsText: ['temporalPad'],
  temporalSpecial: [],
  dateFormat: ['temporalJ2date', 'temporalPad'],
  timeFormat: ['temporalPad', 'temporalSecondsText'],
  timestampFormat: ['dateFormat', 'timeFormat'],
  intervalFormat: ['temporalPad', 'temporalSecondsText'],
  temporalParseDate: ['temporalDate2j', 'temporalMonthDays'],
  temporalParseTime: [],
  dateInput: ['SqlDate', 'temporalSpecial', 'temporalParseDate'],
  timeInput: ['SqlTime', 'temporalParseTime'],
  timestampInput: ['SqlTimestamp', 'temporalSpecial', 'temporalParseDate', 'temporalParseTime'],
  intervalInput: ['SqlInterval', 'temporalSpecial', 'temporalParseTime'],
  dateText: ['SqlDate', 'SqlText', 'dateFormat'],
  timeText: ['SqlTime', 'SqlText', 'timeFormat'],
  timestampText: ['SqlTimestamp', 'SqlText', 'timestampFormat'],
  intervalText: ['SqlInterval', 'SqlText', 'intervalFormat'],
  dateCompare: ['SqlDate', 'SqlInteger'],
  timeCompare: ['SqlTime', 'SqlInteger'],
  timestampCompare: ['SqlTimestamp', 'SqlInteger'],
  intervalSpan: ['SqlInterval'],
  intervalCompare: ['SqlInterval', 'SqlInteger', 'intervalSpan'],
  dateComparison: ['SqlDate', 'SqlBoolean', 'dateCompare'],
  timeComparison: ['SqlTime', 'SqlBoolean', 'timeCompare'],
  timestampComparison: ['SqlTimestamp', 'SqlBoolean', 'timestampCompare'],
  intervalComparison: ['SqlInterval', 'SqlBoolean', 'intervalCompare'],
  dateEq: ['SqlDate', 'SqlBoolean', 'dateComparison'],
  dateNe: ['SqlDate', 'SqlBoolean', 'dateComparison'],
  dateLt: ['SqlDate', 'SqlBoolean', 'dateComparison'],
  dateLe: ['SqlDate', 'SqlBoolean', 'dateComparison'],
  dateGt: ['SqlDate', 'SqlBoolean', 'dateComparison'],
  dateGe: ['SqlDate', 'SqlBoolean', 'dateComparison'],
  timeEq: ['SqlTime', 'SqlBoolean', 'timeComparison'],
  timeNe: ['SqlTime', 'SqlBoolean', 'timeComparison'],
  timeLt: ['SqlTime', 'SqlBoolean', 'timeComparison'],
  timeLe: ['SqlTime', 'SqlBoolean', 'timeComparison'],
  timeGt: ['SqlTime', 'SqlBoolean', 'timeComparison'],
  timeGe: ['SqlTime', 'SqlBoolean', 'timeComparison'],
  timestampEq: ['SqlTimestamp', 'SqlBoolean', 'timestampComparison'],
  timestampNe: ['SqlTimestamp', 'SqlBoolean', 'timestampComparison'],
  timestampLt: ['SqlTimestamp', 'SqlBoolean', 'timestampComparison'],
  timestampLe: ['SqlTimestamp', 'SqlBoolean', 'timestampComparison'],
  timestampGt: ['SqlTimestamp', 'SqlBoolean', 'timestampComparison'],
  timestampGe: ['SqlTimestamp', 'SqlBoolean', 'timestampComparison'],
  intervalEq: ['SqlInterval', 'SqlBoolean', 'intervalComparison'],
  intervalNe: ['SqlInterval', 'SqlBoolean', 'intervalComparison'],
  intervalLt: ['SqlInterval', 'SqlBoolean', 'intervalComparison'],
  intervalLe: ['SqlInterval', 'SqlBoolean', 'intervalComparison'],
  intervalGt: ['SqlInterval', 'SqlBoolean', 'intervalComparison'],
  intervalGe: ['SqlInterval', 'SqlBoolean', 'intervalComparison'],
  dateFinite: ['SqlDate', 'SqlBoolean'],
  timestampFinite: ['SqlTimestamp', 'SqlBoolean'],
  intervalFinite: ['SqlInterval', 'SqlBoolean'],
  makeDate: ['SqlDate', 'SqlInteger', 'temporalDate2j', 'temporalMonthDays'],
  makeTime: ['SqlTime', 'SqlInteger', 'SqlFloat'],
  makeTimestamp: ['SqlTimestamp', 'SqlInteger', 'SqlFloat', 'makeDate', 'makeTime'],
  makeInterval: ['SqlInterval', 'SqlInteger', 'SqlFloat'],
  sqlIsNullDate: ['SqlDate', 'SqlBoolean'],
  sqlIsNotNullDate: ['SqlDate', 'SqlBoolean'],
  sqlCaseDate: ['SqlDate', 'SqlBoolean'],
  sqlCoalesceDate: ['SqlDate'],
  sqlIsNullTime: ['SqlTime', 'SqlBoolean'],
  sqlIsNotNullTime: ['SqlTime', 'SqlBoolean'],
  sqlCaseTime: ['SqlTime', 'SqlBoolean'],
  sqlCoalesceTime: ['SqlTime'],
  sqlIsNullTimestamp: ['SqlTimestamp', 'SqlBoolean'],
  sqlIsNotNullTimestamp: ['SqlTimestamp', 'SqlBoolean'],
  sqlCaseTimestamp: ['SqlTimestamp', 'SqlBoolean'],
  sqlCoalesceTimestamp: ['SqlTimestamp'],
  sqlIsNullInterval: ['SqlInterval', 'SqlBoolean'],
  sqlIsNotNullInterval: ['SqlInterval', 'SqlBoolean'],
  sqlCaseInterval: ['SqlInterval', 'SqlBoolean'],
  sqlCoalesceInterval: ['SqlInterval'],
}
