export const goTemporalDependencies: Record<string, readonly string[]> = {
  SqlDate: [],
  SqlTime: [],
  SqlTimestamp: [],
  SqlInterval: [],
  temporalDate2j: [],
  temporalJ2date: [],
  temporalIsLeap: [],
  temporalMonthDays: ['temporalIsLeap'],
  temporalPad: [],
  temporalSecondsText: ['temporalPad'],
  temporalSpecial: [],
  dateFormat: ['temporalJ2date', 'temporalPad'],
  timeFormat: ['temporalPad', 'temporalSecondsText'],
  timestampFormat: ['temporalJ2date', 'temporalPad', 'timeFormat'],
  intervalFormat: ['temporalPad', 'temporalSecondsText'],
  temporalParseDate: ['temporalDate2j', 'temporalMonthDays'],
  temporalParseTime: [],
  dateInput: ['SqlDate', 'temporalSpecial', 'temporalParseDate'],
  timeInput: ['SqlTime', 'temporalParseTime'],
  timestampInput: ['SqlTimestamp', 'temporalSpecial', 'temporalParseDate', 'temporalParseTime'],
  intervalInput: ['SqlInterval', 'temporalSpecial', 'temporalParseTime'],
  dateText: ['SqlDate', 'SqlText', 'dateFormat'],
  timeText: ['SqlTime', 'SqlText', 'timeFormat'],
  timestampText: ['SqlTimestamp', 'SqlText', 'timestampFormat'],
  intervalText: ['SqlInterval', 'SqlText', 'intervalFormat'],
  dateCompare: ['SqlDate', 'SqlInteger'],
  timeCompare: ['SqlTime', 'SqlInteger'],
  timestampCompare: ['SqlTimestamp', 'SqlInteger'],
  intervalSpan: ['SqlInterval'],
  intervalCompare: ['SqlInterval', 'SqlInteger', 'intervalSpan'],
  dateComparison: ['SqlDate', 'SqlBoolean', 'dateCompare'],
  timeComparison: ['SqlTime', 'SqlBoolean', 'timeCompare'],
  timestampComparison: ['SqlTimestamp', 'SqlBoolean', 'timestampCompare'],
  intervalComparison: ['SqlInterval', 'SqlBoolean', 'intervalCompare'],
  dateEq: ['SqlDate', 'SqlBoolean', 'dateComparison'],
  dateNe: ['SqlDate', 'SqlBoolean', 'dateComparison'],
  dateLt: ['SqlDate', 'SqlBoolean', 'dateComparison'],
  dateLe: ['SqlDate', 'SqlBoolean', 'dateComparison'],
  dateGt: ['SqlDate', 'SqlBoolean', 'dateComparison'],
  dateGe: ['SqlDate', 'SqlBoolean', 'dateComparison'],
  timeEq: ['SqlTime', 'SqlBoolean', 'timeComparison'],
  timeNe: ['SqlTime', 'SqlBoolean', 'timeComparison'],
  timeLt: ['SqlTime', 'SqlBoolean', 'timeComparison'],
  timeLe: ['SqlTime', 'SqlBoolean', 'timeComparison'],
  timeGt: ['SqlTime', 'SqlBoolean', 'timeComparison'],
  timeGe: ['SqlTime', 'SqlBoolean', 'timeComparison'],
  timestampEq: ['SqlTimestamp', 'SqlBoolean', 'timestampComparison'],
  timestampNe: ['SqlTimestamp', 'SqlBoolean', 'timestampComparison'],
  timestampLt: ['SqlTimestamp', 'SqlBoolean', 'timestampComparison'],
  timestampLe: ['SqlTimestamp', 'SqlBoolean', 'timestampComparison'],
  timestampGt: ['SqlTimestamp', 'SqlBoolean', 'timestampComparison'],
  timestampGe: ['SqlTimestamp', 'SqlBoolean', 'timestampComparison'],
  intervalEq: ['SqlInterval', 'SqlBoolean', 'intervalComparison'],
  intervalNe: ['SqlInterval', 'SqlBoolean', 'intervalComparison'],
  intervalLt: ['SqlInterval', 'SqlBoolean', 'intervalComparison'],
  intervalLe: ['SqlInterval', 'SqlBoolean', 'intervalComparison'],
  intervalGt: ['SqlInterval', 'SqlBoolean', 'intervalComparison'],
  intervalGe: ['SqlInterval', 'SqlBoolean', 'intervalComparison'],
  dateFinite: ['SqlDate', 'SqlBoolean'],
  timestampFinite: ['SqlTimestamp', 'SqlBoolean'],
  intervalFinite: ['SqlInterval', 'SqlBoolean'],
  makeDate: ['SqlDate', 'SqlInteger', 'temporalDate2j', 'temporalMonthDays'],
  makeTime: ['SqlTime', 'SqlInteger', 'SqlFloat'],
  makeTimestamp: ['SqlTimestamp', 'SqlInteger', 'SqlFloat', 'makeDate', 'makeTime'],
  makeInterval: ['SqlInterval', 'SqlInteger', 'SqlFloat'],
  sqlIsNullDate: ['SqlDate', 'SqlBoolean'],
  sqlIsNotNullDate: ['SqlDate', 'SqlBoolean'],
  sqlCaseDate: ['SqlDate', 'SqlBoolean'],
  sqlCoalesceDate: ['SqlDate'],
  sqlIsNullTime: ['SqlTime', 'SqlBoolean'],
  sqlIsNotNullTime: ['SqlTime', 'SqlBoolean'],
  sqlCaseTime: ['SqlTime', 'SqlBoolean'],
  sqlCoalesceTime: ['SqlTime'],
  sqlIsNullTimestamp: ['SqlTimestamp', 'SqlBoolean'],
  sqlIsNotNullTimestamp: ['SqlTimestamp', 'SqlBoolean'],
  sqlCaseTimestamp: ['SqlTimestamp', 'SqlBoolean'],
  sqlCoalesceTimestamp: ['SqlTimestamp'],
  sqlIsNullInterval: ['SqlInterval', 'SqlBoolean'],
  sqlIsNotNullInterval: ['SqlInterval', 'SqlBoolean'],
  sqlCaseInterval: ['SqlInterval', 'SqlBoolean'],
  sqlCoalesceInterval: ['SqlInterval'],
  SqlTimestamptz: [],
  SqlTimeTz: [],
  temporalFormatZone: ['temporalPad'],
  temporalParseOffset: [],
  temporalSplitTimeAndZone: [],
  timestamptzFormat: ['temporalJ2date', 'temporalPad', 'timeFormat', 'temporalFormatZone'],
  timetzFormat: ['timeFormat', 'temporalFormatZone'],
  timestamptzInput: [
    'SqlTimestamptz',
    'temporalSpecial',
    'temporalParseDate',
    'temporalParseTime',
    'temporalSplitTimeAndZone',
    'temporalParseOffset',
  ],
  timetzInput: [
    'SqlTimeTz',
    'temporalParseTime',
    'temporalSplitTimeAndZone',
    'temporalParseOffset',
  ],
  timestamptzText: ['SqlTimestamptz', 'SqlText', 'timestamptzFormat'],
  timetzText: ['SqlTimeTz', 'SqlText', 'timetzFormat'],
  timestamptzCompare: ['SqlTimestamptz', 'SqlInteger'],
  timetzCompare: ['SqlTimeTz', 'SqlInteger'],
  timestamptzComparison: ['SqlTimestamptz', 'SqlBoolean', 'timestamptzCompare'],
  timetzComparison: ['SqlTimeTz', 'SqlBoolean', 'timetzCompare'],
  timestamptzEq: ['SqlTimestamptz', 'SqlBoolean', 'timestamptzComparison'],
  timestamptzNe: ['SqlTimestamptz', 'SqlBoolean', 'timestamptzComparison'],
  timestamptzLt: ['SqlTimestamptz', 'SqlBoolean', 'timestamptzComparison'],
  timestamptzLe: ['SqlTimestamptz', 'SqlBoolean', 'timestamptzComparison'],
  timestamptzGt: ['SqlTimestamptz', 'SqlBoolean', 'timestamptzComparison'],
  timestamptzGe: ['SqlTimestamptz', 'SqlBoolean', 'timestamptzComparison'],
  timetzEq: ['SqlTimeTz', 'SqlBoolean', 'timetzComparison'],
  timetzNe: ['SqlTimeTz', 'SqlBoolean', 'timetzComparison'],
  timetzLt: ['SqlTimeTz', 'SqlBoolean', 'timetzComparison'],
  timetzLe: ['SqlTimeTz', 'SqlBoolean', 'timetzComparison'],
  timetzGt: ['SqlTimeTz', 'SqlBoolean', 'timetzComparison'],
  timetzGe: ['SqlTimeTz', 'SqlBoolean', 'timetzComparison'],
  timestamptzFinite: ['SqlTimestamptz', 'SqlBoolean'],
  makeTimestamptz: ['SqlTimestamptz', 'SqlInteger', 'SqlFloat', 'makeTimestamp'],
  sqlIsNullTimestamptz: ['SqlTimestamptz', 'SqlBoolean'],
  sqlIsNotNullTimestamptz: ['SqlTimestamptz', 'SqlBoolean'],
  sqlCaseTimestamptz: ['SqlTimestamptz', 'SqlBoolean'],
  sqlCoalesceTimestamptz: ['SqlTimestamptz'],
  sqlIsNullTimeTz: ['SqlTimeTz', 'SqlBoolean'],
  sqlIsNotNullTimeTz: ['SqlTimeTz', 'SqlBoolean'],
  sqlCaseTimeTz: ['SqlTimeTz', 'SqlBoolean'],
  sqlCoalesceTimeTz: ['SqlTimeTz'],
  temporalCivil: [],
  temporalUnit: [],
  temporalPart: ['SqlDecimal'],
  temporalStrncmp10: [],
  temporalDowncaseUnit: [],
  temporalDecodeUnit: ['temporalStrncmp10', 'temporalDowncaseUnit', 'temporalUnit'],
  temporalJ2day: [],
  temporalIsoWeek: ['temporalDate2j', 'temporalJ2day'],
  temporalIsoYear: ['temporalDate2j', 'temporalJ2day'],
  temporalIsoWeekDate: ['temporalDate2j', 'temporalJ2day', 'temporalJ2date'],
  temporalNumericFromString: ['decimalInput'],
  temporalNumericScale: ['temporalNumericFromString'],
  temporalNumericScaleBig: ['temporalNumericFromString'],
  temporalPartNull: ['temporalPart'],
  temporalPartInf: ['temporalPart'],
  temporalPartInt: ['temporalPart'],
  temporalPartScaled: ['temporalPart'],
  temporalPartScaledBig: ['temporalPart'],
  temporalPartFloat: ['temporalPart'],
  temporalPartDecimal: ['temporalPart', 'SqlDecimal'],
  temporalPartError: ['temporalPart'],
  temporalPartToDecimal: [
    'temporalPart',
    'SqlDecimal',
    'SqlInteger',
    'decimalFromInteger',
    'decimalInput',
    'temporalNumericScale',
    'temporalNumericScaleBig',
  ],
  temporalPartToFloat: ['temporalPart', 'SqlFloat'],
  temporalTimestampCivil: ['temporalCivil', 'temporalJ2date'],
  temporalCivilTimestamp: ['temporalDate2j'],
  temporalDateTimestamp: [],
  temporalYearValue: [],
  temporalDecadeValue: [],
  temporalCenturyValue: [],
  temporalMillenniumValue: [],
  temporalIsoYearValue: ['temporalIsoYear'],
  temporalDowValue: ['temporalJ2day'],
  temporalTruncYear: [],
  temporalContains: [],
  temporalInfiniteTimestampPart: [
    'temporalPartNull',
    'temporalPartInf',
    'temporalPartError',
    'temporalContains',
  ],
  temporalTimestampPart: [
    'temporalDecodeUnit',
    'temporalInfiniteTimestampPart',
    'temporalTimestampCivil',
    'temporalPartError',
    'temporalPartInt',
    'temporalPartScaled',
    'temporalPartFloat',
    'temporalPartDecimal',
    'decimalAdd',
    'decimalDiv',
    'decimalSub',
    'decimalFromInteger',
    'sqlDecimalRound',
    'temporalIsoWeek',
    'temporalYearValue',
    'temporalDecadeValue',
    'temporalCenturyValue',
    'temporalMillenniumValue',
    'temporalIsoYearValue',
    'temporalDowValue',
    'temporalDate2j',
    'SqlInteger',
  ],
  temporalDateExtractPart: [
    'temporalDecodeUnit',
    'temporalJ2date',
    'temporalPartNull',
    'temporalPartInf',
    'temporalPartError',
    'temporalPartInt',
    'temporalContains',
    'temporalIsoWeek',
    'temporalYearValue',
    'temporalDecadeValue',
    'temporalCenturyValue',
    'temporalMillenniumValue',
    'temporalIsoYearValue',
    'temporalDowValue',
    'temporalDate2j',
  ],
  temporalTimePart: [
    'temporalDecodeUnit',
    'temporalPartError',
    'temporalPartInt',
    'temporalPartScaled',
    'temporalPartFloat',
  ],
  temporalInfiniteIntervalPart: [
    'temporalPartNull',
    'temporalPartInf',
    'temporalPartError',
    'temporalContains',
  ],
  temporalIntervalPart: [
    'temporalDecodeUnit',
    'temporalInfiniteIntervalPart',
    'temporalPartError',
    'temporalPartInt',
    'temporalPartScaled',
    'temporalPartScaledBig',
    'temporalPartFloat',
  ],
  temporalTimestampTrunc: [
    'temporalDecodeUnit',
    'temporalContains',
    'temporalTimestampCivil',
    'temporalIsoWeek',
    'temporalIsoWeekDate',
    'temporalCivilTimestamp',
    'temporalTruncYear',
  ],
  temporalIntervalTrunc: ['temporalDecodeUnit', 'temporalContains'],
  extractTimestamp: [
    'SqlText',
    'SqlTimestamp',
    'SqlDecimal',
    'temporalPartToDecimal',
    'temporalTimestampPart',
  ],
  extractTimestamptz: [
    'SqlText',
    'SqlTimestamptz',
    'SqlDecimal',
    'temporalPartToDecimal',
    'temporalTimestampPart',
  ],
  extractDate: [
    'SqlText',
    'SqlDate',
    'SqlDecimal',
    'temporalPartToDecimal',
    'temporalDateExtractPart',
  ],
  extractTime: ['SqlText', 'SqlTime', 'SqlDecimal', 'temporalPartToDecimal', 'temporalTimePart'],
  extractTimetz: [
    'SqlText',
    'SqlTimeTz',
    'SqlDecimal',
    'temporalPartToDecimal',
    'temporalTimePart',
  ],
  extractInterval: [
    'SqlText',
    'SqlInterval',
    'SqlDecimal',
    'temporalPartToDecimal',
    'temporalIntervalPart',
  ],
  datePartTimestamp: [
    'SqlText',
    'SqlTimestamp',
    'SqlFloat',
    'temporalPartToFloat',
    'temporalTimestampPart',
  ],
  datePartTimestamptz: [
    'SqlText',
    'SqlTimestamptz',
    'SqlFloat',
    'temporalPartToFloat',
    'temporalTimestampPart',
  ],
  datePartDate: [
    'SqlText',
    'SqlDate',
    'SqlFloat',
    'temporalDateTimestamp',
    'temporalPartToFloat',
    'temporalTimestampPart',
  ],
  datePartTime: ['SqlText', 'SqlTime', 'SqlFloat', 'temporalPartToFloat', 'temporalTimePart'],
  datePartTimetz: ['SqlText', 'SqlTimeTz', 'SqlFloat', 'temporalPartToFloat', 'temporalTimePart'],
  datePartInterval: [
    'SqlText',
    'SqlInterval',
    'SqlFloat',
    'temporalPartToFloat',
    'temporalIntervalPart',
  ],
  dateTruncTimestamp: ['SqlText', 'SqlTimestamp', 'temporalTimestampTrunc'],
  dateTruncTimestamptz: ['SqlText', 'SqlTimestamptz', 'temporalTimestampTrunc'],
  dateTruncInterval: ['SqlText', 'SqlInterval', 'temporalIntervalTrunc'],
}

const temporalArithmeticInternals = [
  'SqlDate',
  'SqlTime',
  'SqlTimestamp',
  'SqlInterval',
  'SqlTimestamptz',
  'SqlTimeTz',
  'SqlInteger',
  'SqlBoolean',
  'SqlFloat',
  'intervalSpan',
  'temporalDate2j',
  'temporalJ2date',
  'temporalMonthDays',
  'temporalRint',
  'temporalTsRound',
  'temporalFloatFitsInt32',
  'temporalFloatFitsInt64',
  'temporalAddInt32',
  'temporalAddInt64',
  'temporalSubInt64',
  'temporalDateIsInf',
  'temporalTimestampIsInf',
  'temporalIntervalIsInf',
  'temporalIntervalSentinel',
  'temporalIntervalFinite',
  'temporalIntervalSign',
  'temporalValidDate',
  'temporalValidTimestamp',
  'temporalTimestampFromCivil',
  'temporalTimestampCivilParts',
  'temporalAddMonths',
  'temporalTimestampAddInterval',
  'temporalTimeWrap',
  'temporalIntervalZoneSeconds',
  'temporalDt2local',
  'temporalNegInt32',
  'temporalIntervalNeg',
  'temporalIntervalAdd',
  'temporalIntervalSub',
  'temporalIntervalMul',
  'temporalTModulo',
  'temporalJustifyHours',
  'temporalJustifyDays',
  'temporalJustifyInterval',
  'temporalDateToTimestamp',
  'temporalDateToTimestampOverflow',
  'temporalTimestampToDate',
  'temporalTimestampToTime',
  'temporalDateAddInt',
  'temporalDateSubInt',
  'temporalTimestampSub',
  'temporalDateTimestampOrder',
  'temporalCheck2',
  'temporalCheck1',
  'temporalCmpBool',
] as const

const temporalArithmeticHelpers: Record<string, readonly string[]> = {
  temporalRint: [],
  temporalTsRound: ['temporalRint'],
  temporalFloatFitsInt32: [],
  temporalFloatFitsInt64: [],
  temporalAddInt32: [],
  temporalAddInt64: [],
  temporalSubInt64: [],
  temporalDateIsInf: [],
  temporalTimestampIsInf: [],
  temporalIntervalIsInf: [],
  temporalIntervalSentinel: ['SqlInterval'],
  temporalIntervalFinite: ['SqlInterval', 'temporalIntervalIsInf'],
  temporalIntervalSign: ['SqlInterval', 'intervalSpan'],
  temporalValidDate: [],
  temporalValidTimestamp: [],
  temporalTimestampFromCivil: ['temporalDate2j', 'temporalValidTimestamp'],
  temporalTimestampCivilParts: ['temporalJ2date'],
  temporalAddMonths: ['temporalAddInt32'],
  temporalTimestampAddInterval: [
    'SqlInterval',
    'temporalTimestampIsInf',
    'temporalIntervalIsInf',
    'temporalTimestampCivilParts',
    'temporalAddMonths',
    'temporalMonthDays',
    'temporalTimestampFromCivil',
    'temporalAddInt32',
    'temporalDate2j',
    'temporalJ2date',
    'temporalAddInt64',
    'temporalValidTimestamp',
  ],
  temporalTimeWrap: [],
  temporalIntervalZoneSeconds: ['SqlInterval', 'temporalIntervalIsInf'],
  temporalDt2local: ['temporalValidTimestamp'],
  temporalNegInt32: [],
  temporalIntervalNeg: [
    'SqlInterval',
    'temporalIntervalIsInf',
    'temporalIntervalSentinel',
    'temporalNegInt32',
    'temporalSubInt64',
    'temporalIntervalFinite',
  ],
  temporalIntervalAdd: [
    'SqlInterval',
    'temporalIntervalIsInf',
    'temporalIntervalSentinel',
    'temporalAddInt32',
    'temporalAddInt64',
    'temporalIntervalFinite',
  ],
  temporalIntervalSub: [
    'SqlInterval',
    'temporalIntervalIsInf',
    'temporalIntervalSentinel',
    'temporalSubInt64',
    'temporalIntervalFinite',
  ],
  temporalIntervalMul: [
    'SqlInterval',
    'temporalIntervalIsInf',
    'temporalIntervalNeg',
    'temporalIntervalSign',
    'temporalIntervalSentinel',
    'temporalFloatFitsInt32',
    'temporalFloatFitsInt64',
    'temporalTsRound',
    'temporalAddInt32',
    'temporalRint',
    'temporalIntervalFinite',
  ],
  temporalTModulo: [],
  temporalJustifyHours: [
    'SqlInterval',
    'temporalIntervalIsInf',
    'temporalTModulo',
    'temporalAddInt32',
  ],
  temporalJustifyDays: ['SqlInterval', 'temporalIntervalIsInf', 'temporalAddInt32'],
  temporalJustifyInterval: [
    'SqlInterval',
    'temporalIntervalIsInf',
    'temporalAddInt32',
    'temporalTModulo',
  ],
  temporalDateToTimestamp: ['temporalDateIsInf'],
  temporalDateToTimestampOverflow: ['temporalDateIsInf'],
  temporalTimestampToDate: ['temporalTimestampIsInf'],
  temporalTimestampToTime: ['temporalTimestampIsInf'],
  temporalDateAddInt: ['temporalDateIsInf', 'temporalValidDate'],
  temporalDateSubInt: ['temporalDateIsInf', 'temporalValidDate'],
  temporalTimestampSub: [
    'SqlInterval',
    'temporalTimestampIsInf',
    'temporalIntervalSentinel',
    'temporalSubInt64',
    'temporalJustifyHours',
  ],
  temporalDateTimestampOrder: ['temporalDateToTimestampOverflow', 'temporalTimestampIsInf'],
  temporalCheck2: [],
  temporalCheck1: [],
  temporalCmpBool: ['SqlInteger', 'SqlBoolean'],
}

const temporalArithmeticPublicDeps: Record<string, readonly string[]> = {
  intPlDate: ['datePlInt'],
  intervalPlDate: ['datePlInterval'],
  dateMiInterval: ['datePlInterval'],
  timePlDate: ['datePlTime'],
  timetzPlDate: ['datePlTimetz'],
  intervalPlTimestamp: ['timestampPlInterval'],
  timestampMiInterval: ['timestampPlInterval'],
  timestamptzPlInterval: ['timestampPlInterval'],
  intervalPlTimestamptz: ['timestamptzPlInterval'],
  timestamptzMiInterval: ['timestampMiInterval'],
  intervalPlTime: ['timePlInterval'],
  intervalPlTimetz: ['timetzPlInterval'],
  mulDInterval: ['intervalMul'],
  timestampFromDateTime: ['datePlTime'],
  timestamptzFromDateTime: ['datePlTime'],
  timestamptzFromDateTimetz: ['datePlTimetz'],
  timestampDateCompare: ['dateTimestampCompare'],
  dateTimestamptzCompare: ['dateTimestampCompare'],
  timestamptzDateCompare: ['dateTimestamptzCompare'],
  timestamptzTimestampCompare: ['timestampTimestamptzCompare'],
  dateTimestampEq: ['dateTimestampCompare'],
  dateTimestampNe: ['dateTimestampCompare'],
  dateTimestampLt: ['dateTimestampCompare'],
  dateTimestampLe: ['dateTimestampCompare'],
  dateTimestampGt: ['dateTimestampCompare'],
  dateTimestampGe: ['dateTimestampCompare'],
  timestampDateEq: ['timestampDateCompare'],
  timestampDateNe: ['timestampDateCompare'],
  timestampDateLt: ['timestampDateCompare'],
  timestampDateLe: ['timestampDateCompare'],
  timestampDateGt: ['timestampDateCompare'],
  timestampDateGe: ['timestampDateCompare'],
  dateTimestamptzEq: ['dateTimestamptzCompare'],
  dateTimestamptzNe: ['dateTimestamptzCompare'],
  dateTimestamptzLt: ['dateTimestamptzCompare'],
  dateTimestamptzLe: ['dateTimestamptzCompare'],
  dateTimestamptzGt: ['dateTimestamptzCompare'],
  dateTimestamptzGe: ['dateTimestamptzCompare'],
  timestamptzDateEq: ['timestamptzDateCompare'],
  timestamptzDateNe: ['timestamptzDateCompare'],
  timestamptzDateLt: ['timestamptzDateCompare'],
  timestamptzDateLe: ['timestamptzDateCompare'],
  timestamptzDateGt: ['timestamptzDateCompare'],
  timestamptzDateGe: ['timestamptzDateCompare'],
  timestampTimestamptzEq: ['timestampTimestamptzCompare'],
  timestampTimestamptzNe: ['timestampTimestamptzCompare'],
  timestampTimestamptzLt: ['timestampTimestamptzCompare'],
  timestampTimestamptzLe: ['timestampTimestamptzCompare'],
  timestampTimestamptzGt: ['timestampTimestamptzCompare'],
  timestampTimestamptzGe: ['timestampTimestamptzCompare'],
  timestamptzTimestampEq: ['timestamptzTimestampCompare'],
  timestamptzTimestampNe: ['timestamptzTimestampCompare'],
  timestamptzTimestampLt: ['timestamptzTimestampCompare'],
  timestamptzTimestampLe: ['timestamptzTimestampCompare'],
  timestamptzTimestampGt: ['timestamptzTimestampCompare'],
  timestamptzTimestampGe: ['timestamptzTimestampCompare'],
}

for (const name of [
  'datePlInt',
  'intPlDate',
  'dateMiInt',
  'dateMiDate',
  'datePlInterval',
  'intervalPlDate',
  'dateMiInterval',
  'datePlTime',
  'timePlDate',
  'datePlTimetz',
  'timetzPlDate',
  'timestampPlInterval',
  'intervalPlTimestamp',
  'timestampMiInterval',
  'timestampMiTimestamp',
  'timestamptzPlInterval',
  'intervalPlTimestamptz',
  'timestamptzMiInterval',
  'timestamptzMiTimestamptz',
  'timePlInterval',
  'intervalPlTime',
  'timeMiInterval',
  'timeMiTime',
  'timetzPlInterval',
  'intervalPlTimetz',
  'timetzMiInterval',
  'intervalPl',
  'intervalMi',
  'intervalUm',
  'intervalMul',
  'mulDInterval',
  'intervalDiv',
  'justifyHours',
  'justifyDays',
  'justifyInterval',
  'dateFromTimestamp',
  'dateFromTimestamptz',
  'timestampFromDate',
  'timestampFromDateTime',
  'timestampFromTimestamptz',
  'timestamptzFromTimestamp',
  'timestamptzFromDate',
  'timestamptzFromDateTime',
  'timestamptzFromDateTimetz',
  'timeFromTimestamp',
  'timeFromTimestamptz',
  'timeFromTimetz',
  'timeFromInterval',
  'timetzFromTime',
  'timetzFromTimestamptz',
  'intervalFromTime',
  'timezoneIntervalTimestamp',
  'timezoneIntervalTimestamptz',
  'timezoneIntervalTimetz',
  'dateTimestampCompare',
  'timestampDateCompare',
  'dateTimestamptzCompare',
  'timestamptzDateCompare',
  'timestampTimestamptzCompare',
  'timestamptzTimestampCompare',
  'dateTimestampEq',
  'dateTimestampNe',
  'dateTimestampLt',
  'dateTimestampLe',
  'dateTimestampGt',
  'dateTimestampGe',
  'timestampDateEq',
  'timestampDateNe',
  'timestampDateLt',
  'timestampDateLe',
  'timestampDateGt',
  'timestampDateGe',
  'dateTimestamptzEq',
  'dateTimestamptzNe',
  'dateTimestamptzLt',
  'dateTimestamptzLe',
  'dateTimestamptzGt',
  'dateTimestamptzGe',
  'timestamptzDateEq',
  'timestamptzDateNe',
  'timestamptzDateLt',
  'timestamptzDateLe',
  'timestamptzDateGt',
  'timestamptzDateGe',
  'timestampTimestamptzEq',
  'timestampTimestamptzNe',
  'timestampTimestamptzLt',
  'timestampTimestamptzLe',
  'timestampTimestamptzGt',
  'timestampTimestamptzGe',
  'timestamptzTimestampEq',
  'timestamptzTimestampNe',
  'timestamptzTimestampLt',
  'timestamptzTimestampLe',
  'timestamptzTimestampGt',
  'timestamptzTimestampGe',
]) {
  temporalArithmeticHelpers[name] = [
    ...temporalArithmeticInternals,
    ...(temporalArithmeticPublicDeps[name] ?? []),
  ]
}

Object.assign(goTemporalDependencies, temporalArithmeticHelpers)

const temporalOverlapsHelpers: Record<string, readonly string[]> = {
  temporalOverlaps: ['SqlBoolean'],
  temporalUsecOrder: [],
  temporalTimetzOrder: ['SqlTimeTz'],
  temporalFirstError: [],
  temporalItm2interval: ['SqlInterval', 'temporalIntervalFinite'],
  temporalTimestampAge: [
    'SqlInterval',
    'temporalTimestampIsInf',
    'temporalIntervalSentinel',
    'temporalTimestampCivilParts',
    'temporalMonthDays',
    'temporalItm2interval',
  ],
  overlapsTimestamp: [
    'SqlTimestamp',
    'SqlBoolean',
    'temporalFirstError',
    'temporalOverlaps',
    'temporalUsecOrder',
  ],
  overlapsTimestampIntervalInterval: [
    'SqlTimestamp',
    'SqlInterval',
    'SqlBoolean',
    'overlapsTimestamp',
    'timestampPlInterval',
  ],
  overlapsTimestampIntervalTimestamp: [
    'SqlTimestamp',
    'SqlInterval',
    'SqlBoolean',
    'overlapsTimestamp',
    'timestampPlInterval',
  ],
  overlapsTimestampTimestampInterval: [
    'SqlTimestamp',
    'SqlInterval',
    'SqlBoolean',
    'overlapsTimestamp',
    'timestampPlInterval',
  ],
  overlapsTimestamptz: [
    'SqlTimestamptz',
    'SqlBoolean',
    'temporalFirstError',
    'temporalOverlaps',
    'temporalUsecOrder',
  ],
  overlapsTimestamptzIntervalInterval: [
    'SqlTimestamptz',
    'SqlInterval',
    'SqlBoolean',
    'overlapsTimestamptz',
    'timestamptzPlInterval',
  ],
  overlapsTimestamptzIntervalTimestamptz: [
    'SqlTimestamptz',
    'SqlInterval',
    'SqlBoolean',
    'overlapsTimestamptz',
    'timestamptzPlInterval',
  ],
  overlapsTimestamptzTimestamptzInterval: [
    'SqlTimestamptz',
    'SqlInterval',
    'SqlBoolean',
    'overlapsTimestamptz',
    'timestamptzPlInterval',
  ],
  overlapsTime: [
    'SqlTime',
    'SqlBoolean',
    'temporalFirstError',
    'temporalOverlaps',
    'temporalUsecOrder',
  ],
  overlapsTimeIntervalInterval: [
    'SqlTime',
    'SqlInterval',
    'SqlBoolean',
    'overlapsTime',
    'timePlInterval',
  ],
  overlapsTimeIntervalTime: [
    'SqlTime',
    'SqlInterval',
    'SqlBoolean',
    'overlapsTime',
    'timePlInterval',
  ],
  overlapsTimeTimeInterval: [
    'SqlTime',
    'SqlInterval',
    'SqlBoolean',
    'overlapsTime',
    'timePlInterval',
  ],
  overlapsTimetz: [
    'SqlTimeTz',
    'SqlBoolean',
    'temporalFirstError',
    'temporalOverlaps',
    'temporalTimetzOrder',
  ],
  ageTimestamp: ['SqlTimestamp', 'SqlInterval', 'temporalCheck2', 'temporalTimestampAge'],
  ageTimestamptz: ['SqlTimestamptz', 'SqlInterval', 'temporalCheck2', 'temporalTimestampAge'],
  dateLarger: ['SqlDate', 'dateCompare'],
  dateSmaller: ['SqlDate', 'dateCompare'],
  timeLarger: ['SqlTime', 'timeCompare'],
  timeSmaller: ['SqlTime', 'timeCompare'],
  timestampLarger: ['SqlTimestamp', 'timestampCompare'],
  timestampSmaller: ['SqlTimestamp', 'timestampCompare'],
  timestamptzLarger: ['SqlTimestamptz', 'timestamptzCompare'],
  timestamptzSmaller: ['SqlTimestamptz', 'timestamptzCompare'],
  timetzLarger: ['SqlTimeTz', 'timetzCompare'],
  timetzSmaller: ['SqlTimeTz', 'timetzCompare'],
  intervalLarger: ['SqlInterval', 'intervalCompare'],
  intervalSmaller: ['SqlInterval', 'intervalCompare'],
}

Object.assign(goTemporalDependencies, temporalOverlapsHelpers)
