export const goTemporalDependencies: Record<string, readonly string[]> = {
  SqlDate: [],
  SqlTime: [],
  SqlTimestamp: [],
  SqlInterval: [],
  temporalDate2j: [],
  temporalJ2date: [],
  temporalIsLeap: [],
  temporalMonthDays: ['temporalIsLeap'],
  temporalPad: [],
  temporalSecondsText: ['temporalPad'],
  temporalSpecial: [],
  dateFormat: ['temporalJ2date', 'temporalPad'],
  timeFormat: ['temporalPad', 'temporalSecondsText'],
  timestampFormat: ['temporalJ2date', 'temporalPad', 'timeFormat'],
  intervalFormat: ['temporalPad', 'temporalSecondsText'],
  temporalParseDate: ['temporalDate2j', 'temporalMonthDays'],
  temporalParseTime: [],
  dateInput: ['SqlDate', 'temporalSpecial', 'temporalParseDate'],
  timeInput: ['SqlTime', 'temporalParseTime'],
  timestampInput: ['SqlTimestamp', 'temporalSpecial', 'temporalParseDate', 'temporalParseTime'],
  intervalInput: ['SqlInterval', 'temporalSpecial', 'temporalParseTime'],
  dateText: ['SqlDate', 'SqlText', 'dateFormat'],
  timeText: ['SqlTime', 'SqlText', 'timeFormat'],
  timestampText: ['SqlTimestamp', 'SqlText', 'timestampFormat'],
  intervalText: ['SqlInterval', 'SqlText', 'intervalFormat'],
  dateCompare: ['SqlDate', 'SqlInteger'],
  timeCompare: ['SqlTime', 'SqlInteger'],
  timestampCompare: ['SqlTimestamp', 'SqlInteger'],
  intervalSpan: ['SqlInterval'],
  intervalCompare: ['SqlInterval', 'SqlInteger', 'intervalSpan'],
  dateComparison: ['SqlDate', 'SqlBoolean', 'dateCompare'],
  timeComparison: ['SqlTime', 'SqlBoolean', 'timeCompare'],
  timestampComparison: ['SqlTimestamp', 'SqlBoolean', 'timestampCompare'],
  intervalComparison: ['SqlInterval', 'SqlBoolean', 'intervalCompare'],
  dateEq: ['SqlDate', 'SqlBoolean', 'dateComparison'],
  dateNe: ['SqlDate', 'SqlBoolean', 'dateComparison'],
  dateLt: ['SqlDate', 'SqlBoolean', 'dateComparison'],
  dateLe: ['SqlDate', 'SqlBoolean', 'dateComparison'],
  dateGt: ['SqlDate', 'SqlBoolean', 'dateComparison'],
  dateGe: ['SqlDate', 'SqlBoolean', 'dateComparison'],
  timeEq: ['SqlTime', 'SqlBoolean', 'timeComparison'],
  timeNe: ['SqlTime', 'SqlBoolean', 'timeComparison'],
  timeLt: ['SqlTime', 'SqlBoolean', 'timeComparison'],
  timeLe: ['SqlTime', 'SqlBoolean', 'timeComparison'],
  timeGt: ['SqlTime', 'SqlBoolean', 'timeComparison'],
  timeGe: ['SqlTime', 'SqlBoolean', 'timeComparison'],
  timestampEq: ['SqlTimestamp', 'SqlBoolean', 'timestampComparison'],
  timestampNe: ['SqlTimestamp', 'SqlBoolean', 'timestampComparison'],
  timestampLt: ['SqlTimestamp', 'SqlBoolean', 'timestampComparison'],
  timestampLe: ['SqlTimestamp', 'SqlBoolean', 'timestampComparison'],
  timestampGt: ['SqlTimestamp', 'SqlBoolean', 'timestampComparison'],
  timestampGe: ['SqlTimestamp', 'SqlBoolean', 'timestampComparison'],
  intervalEq: ['SqlInterval', 'SqlBoolean', 'intervalComparison'],
  intervalNe: ['SqlInterval', 'SqlBoolean', 'intervalComparison'],
  intervalLt: ['SqlInterval', 'SqlBoolean', 'intervalComparison'],
  intervalLe: ['SqlInterval', 'SqlBoolean', 'intervalComparison'],
  intervalGt: ['SqlInterval', 'SqlBoolean', 'intervalComparison'],
  intervalGe: ['SqlInterval', 'SqlBoolean', 'intervalComparison'],
  dateFinite: ['SqlDate', 'SqlBoolean'],
  timestampFinite: ['SqlTimestamp', 'SqlBoolean'],
  intervalFinite: ['SqlInterval', 'SqlBoolean'],
  makeDate: ['SqlDate', 'SqlInteger', 'temporalDate2j', 'temporalMonthDays'],
  makeTime: ['SqlTime', 'SqlInteger', 'SqlFloat'],
  makeTimestamp: ['SqlTimestamp', 'SqlInteger', 'SqlFloat', 'makeDate', 'makeTime'],
  makeInterval: ['SqlInterval', 'SqlInteger', 'SqlFloat'],
  sqlIsNullDate: ['SqlDate', 'SqlBoolean'],
  sqlIsNotNullDate: ['SqlDate', 'SqlBoolean'],
  sqlCaseDate: ['SqlDate', 'SqlBoolean'],
  sqlCoalesceDate: ['SqlDate'],
  sqlIsNullTime: ['SqlTime', 'SqlBoolean'],
  sqlIsNotNullTime: ['SqlTime', 'SqlBoolean'],
  sqlCaseTime: ['SqlTime', 'SqlBoolean'],
  sqlCoalesceTime: ['SqlTime'],
  sqlIsNullTimestamp: ['SqlTimestamp', 'SqlBoolean'],
  sqlIsNotNullTimestamp: ['SqlTimestamp', 'SqlBoolean'],
  sqlCaseTimestamp: ['SqlTimestamp', 'SqlBoolean'],
  sqlCoalesceTimestamp: ['SqlTimestamp'],
  sqlIsNullInterval: ['SqlInterval', 'SqlBoolean'],
  sqlIsNotNullInterval: ['SqlInterval', 'SqlBoolean'],
  sqlCaseInterval: ['SqlInterval', 'SqlBoolean'],
  sqlCoalesceInterval: ['SqlInterval'],
  SqlTimestamptz: [],
  SqlTimeTz: [],
  temporalFormatZone: ['temporalPad'],
  temporalParseOffset: [],
  temporalSplitTimeAndZone: [],
  timestamptzFormat: ['temporalJ2date', 'temporalPad', 'timeFormat', 'temporalFormatZone'],
  timetzFormat: ['timeFormat', 'temporalFormatZone'],
  timestamptzInput: [
    'SqlTimestamptz',
    'temporalSpecial',
    'temporalParseDate',
    'temporalParseTime',
    'temporalSplitTimeAndZone',
    'temporalParseOffset',
  ],
  timetzInput: [
    'SqlTimeTz',
    'temporalParseTime',
    'temporalSplitTimeAndZone',
    'temporalParseOffset',
  ],
  timestamptzText: ['SqlTimestamptz', 'SqlText', 'timestamptzFormat'],
  timetzText: ['SqlTimeTz', 'SqlText', 'timetzFormat'],
  timestamptzCompare: ['SqlTimestamptz', 'SqlInteger'],
  timetzCompare: ['SqlTimeTz', 'SqlInteger'],
  timestamptzComparison: ['SqlTimestamptz', 'SqlBoolean', 'timestamptzCompare'],
  timetzComparison: ['SqlTimeTz', 'SqlBoolean', 'timetzCompare'],
  timestamptzEq: ['SqlTimestamptz', 'SqlBoolean', 'timestamptzComparison'],
  timestamptzNe: ['SqlTimestamptz', 'SqlBoolean', 'timestamptzComparison'],
  timestamptzLt: ['SqlTimestamptz', 'SqlBoolean', 'timestamptzComparison'],
  timestamptzLe: ['SqlTimestamptz', 'SqlBoolean', 'timestamptzComparison'],
  timestamptzGt: ['SqlTimestamptz', 'SqlBoolean', 'timestamptzComparison'],
  timestamptzGe: ['SqlTimestamptz', 'SqlBoolean', 'timestamptzComparison'],
  timetzEq: ['SqlTimeTz', 'SqlBoolean', 'timetzComparison'],
  timetzNe: ['SqlTimeTz', 'SqlBoolean', 'timetzComparison'],
  timetzLt: ['SqlTimeTz', 'SqlBoolean', 'timetzComparison'],
  timetzLe: ['SqlTimeTz', 'SqlBoolean', 'timetzComparison'],
  timetzGt: ['SqlTimeTz', 'SqlBoolean', 'timetzComparison'],
  timetzGe: ['SqlTimeTz', 'SqlBoolean', 'timetzComparison'],
  timestamptzFinite: ['SqlTimestamptz', 'SqlBoolean'],
  makeTimestamptz: ['SqlTimestamptz', 'SqlInteger', 'SqlFloat', 'makeTimestamp'],
  sqlIsNullTimestamptz: ['SqlTimestamptz', 'SqlBoolean'],
  sqlIsNotNullTimestamptz: ['SqlTimestamptz', 'SqlBoolean'],
  sqlCaseTimestamptz: ['SqlTimestamptz', 'SqlBoolean'],
  sqlCoalesceTimestamptz: ['SqlTimestamptz'],
  sqlIsNullTimeTz: ['SqlTimeTz', 'SqlBoolean'],
  sqlIsNotNullTimeTz: ['SqlTimeTz', 'SqlBoolean'],
  sqlCaseTimeTz: ['SqlTimeTz', 'SqlBoolean'],
  sqlCoalesceTimeTz: ['SqlTimeTz'],
  temporalCivil: [],
  temporalUnit: [],
  temporalPart: ['SqlDecimal'],
  temporalStrncmp10: [],
  temporalDowncaseUnit: [],
  temporalDecodeUnit: ['temporalStrncmp10', 'temporalDowncaseUnit', 'temporalUnit'],
  temporalJ2day: [],
  temporalIsoWeek: ['temporalDate2j', 'temporalJ2day'],
  temporalIsoYear: ['temporalDate2j', 'temporalJ2day'],
  temporalIsoWeekDate: ['temporalDate2j', 'temporalJ2day', 'temporalJ2date'],
  temporalNumericFromString: ['decimalInput'],
  temporalNumericScale: ['temporalNumericFromString'],
  temporalNumericScaleBig: ['temporalNumericFromString'],
  temporalPartNull: ['temporalPart'],
  temporalPartInf: ['temporalPart'],
  temporalPartInt: ['temporalPart'],
  temporalPartScaled: ['temporalPart'],
  temporalPartScaledBig: ['temporalPart'],
  temporalPartFloat: ['temporalPart'],
  temporalPartDecimal: ['temporalPart', 'SqlDecimal'],
  temporalPartError: ['temporalPart'],
  temporalPartToDecimal: [
    'temporalPart',
    'SqlDecimal',
    'SqlInteger',
    'decimalFromInteger',
    'decimalInput',
    'temporalNumericScale',
    'temporalNumericScaleBig',
  ],
  temporalPartToFloat: ['temporalPart', 'SqlFloat'],
  temporalTimestampCivil: ['temporalCivil', 'temporalJ2date'],
  temporalCivilTimestamp: ['temporalDate2j'],
  temporalDateTimestamp: [],
  temporalYearValue: [],
  temporalDecadeValue: [],
  temporalCenturyValue: [],
  temporalMillenniumValue: [],
  temporalIsoYearValue: ['temporalIsoYear'],
  temporalDowValue: ['temporalJ2day'],
  temporalTruncYear: [],
  temporalContains: [],
  temporalInfiniteTimestampPart: [
    'temporalPartNull',
    'temporalPartInf',
    'temporalPartError',
    'temporalContains',
  ],
  temporalTimestampPart: [
    'temporalDecodeUnit',
    'temporalInfiniteTimestampPart',
    'temporalTimestampCivil',
    'temporalPartError',
    'temporalPartInt',
    'temporalPartScaled',
    'temporalPartFloat',
    'temporalPartDecimal',
    'decimalAdd',
    'decimalDiv',
    'decimalSub',
    'decimalFromInteger',
    'sqlDecimalRound',
    'temporalIsoWeek',
    'temporalYearValue',
    'temporalDecadeValue',
    'temporalCenturyValue',
    'temporalMillenniumValue',
    'temporalIsoYearValue',
    'temporalDowValue',
    'temporalDate2j',
    'SqlInteger',
  ],
  temporalDateExtractPart: [
    'temporalDecodeUnit',
    'temporalJ2date',
    'temporalPartNull',
    'temporalPartInf',
    'temporalPartError',
    'temporalPartInt',
    'temporalContains',
    'temporalIsoWeek',
    'temporalYearValue',
    'temporalDecadeValue',
    'temporalCenturyValue',
    'temporalMillenniumValue',
    'temporalIsoYearValue',
    'temporalDowValue',
    'temporalDate2j',
  ],
  temporalTimePart: [
    'temporalDecodeUnit',
    'temporalPartError',
    'temporalPartInt',
    'temporalPartScaled',
    'temporalPartFloat',
  ],
  temporalInfiniteIntervalPart: [
    'temporalPartNull',
    'temporalPartInf',
    'temporalPartError',
    'temporalContains',
  ],
  temporalIntervalPart: [
    'temporalDecodeUnit',
    'temporalInfiniteIntervalPart',
    'temporalPartError',
    'temporalPartInt',
    'temporalPartScaled',
    'temporalPartScaledBig',
    'temporalPartFloat',
  ],
  temporalTimestampTrunc: [
    'temporalDecodeUnit',
    'temporalContains',
    'temporalTimestampCivil',
    'temporalIsoWeek',
    'temporalIsoWeekDate',
    'temporalCivilTimestamp',
    'temporalTruncYear',
  ],
  temporalIntervalTrunc: ['temporalDecodeUnit', 'temporalContains'],
  extractTimestamp: [
    'SqlText',
    'SqlTimestamp',
    'SqlDecimal',
    'temporalPartToDecimal',
    'temporalTimestampPart',
  ],
  extractTimestamptz: [
    'SqlText',
    'SqlTimestamptz',
    'SqlDecimal',
    'temporalPartToDecimal',
    'temporalTimestampPart',
  ],
  extractDate: [
    'SqlText',
    'SqlDate',
    'SqlDecimal',
    'temporalPartToDecimal',
    'temporalDateExtractPart',
  ],
  extractTime: ['SqlText', 'SqlTime', 'SqlDecimal', 'temporalPartToDecimal', 'temporalTimePart'],
  extractTimetz: [
    'SqlText',
    'SqlTimeTz',
    'SqlDecimal',
    'temporalPartToDecimal',
    'temporalTimePart',
  ],
  extractInterval: [
    'SqlText',
    'SqlInterval',
    'SqlDecimal',
    'temporalPartToDecimal',
    'temporalIntervalPart',
  ],
  datePartTimestamp: [
    'SqlText',
    'SqlTimestamp',
    'SqlFloat',
    'temporalPartToFloat',
    'temporalTimestampPart',
  ],
  datePartTimestamptz: [
    'SqlText',
    'SqlTimestamptz',
    'SqlFloat',
    'temporalPartToFloat',
    'temporalTimestampPart',
  ],
  datePartDate: [
    'SqlText',
    'SqlDate',
    'SqlFloat',
    'temporalDateTimestamp',
    'temporalPartToFloat',
    'temporalTimestampPart',
  ],
  datePartTime: ['SqlText', 'SqlTime', 'SqlFloat', 'temporalPartToFloat', 'temporalTimePart'],
  datePartTimetz: ['SqlText', 'SqlTimeTz', 'SqlFloat', 'temporalPartToFloat', 'temporalTimePart'],
  datePartInterval: [
    'SqlText',
    'SqlInterval',
    'SqlFloat',
    'temporalPartToFloat',
    'temporalIntervalPart',
  ],
  dateTruncTimestamp: ['SqlText', 'SqlTimestamp', 'temporalTimestampTrunc'],
  dateTruncTimestamptz: ['SqlText', 'SqlTimestamptz', 'temporalTimestampTrunc'],
  dateTruncInterval: ['SqlText', 'SqlInterval', 'temporalIntervalTrunc'],
}
