export const goTextDependencies: Record<string, readonly string[]> = {
  bpcharText: ['SqlText'],
  booleanText: ['SqlText', 'SqlBoolean'],
  varcharCoerce: ['SqlText', 'SqlInteger', 'SqlBoolean'],
  bpcharCoerce: ['SqlText', 'SqlInteger', 'SqlBoolean'],
  bpcharLength: ['SqlInteger', 'SqlText'],
  bpcharEq: ['SqlText', 'SqlBoolean', 'bpcharText', 'textEq'],
  bpcharNe: ['SqlText', 'SqlBoolean', 'bpcharText', 'textNe'],
  bpcharLt: ['SqlText', 'SqlBoolean', 'bpcharText', 'textLt'],
  bpcharLe: ['SqlText', 'SqlBoolean', 'bpcharText', 'textLe'],
  bpcharGt: ['SqlText', 'SqlBoolean', 'bpcharText', 'textGt'],
  bpcharGe: ['SqlText', 'SqlBoolean', 'bpcharText', 'textGe'],
  sqlTextSubstring: [],
  textSubstring: ['SqlText', 'SqlInteger', 'sqlTextSubstring'],
  textSubstringLength: ['SqlText', 'SqlInteger', 'sqlTextSubstring'],
  textLeft: ['SqlText', 'SqlInteger'],
  textRight: ['SqlText', 'SqlInteger'],
  textTrimBoth: ['SqlText'],
  textTrimBothSpace: ['SqlText', 'textTrimBoth'],
  textTrimLeft: ['SqlText'],
  textTrimLeftSpace: ['SqlText', 'textTrimLeft'],
  textTrimRight: ['SqlText'],
  textTrimRightSpace: ['SqlText', 'textTrimRight'],
  textReplace: ['SqlText'],
  textTranslate: ['SqlText'],
  textPosition: ['SqlInteger', 'SqlText'],
  textStartsWith: ['SqlBoolean', 'SqlText'],
  textSplitPart: ['SqlText', 'SqlInteger'],
  textReverse: ['SqlText'],
  textAscii: ['SqlInteger', 'SqlText'],
  textBitLength: ['SqlInteger', 'SqlText'],
  textRepeat: ['SqlText', 'SqlInteger'],
  textPadLeft: ['SqlText', 'SqlInteger'],
  textPadLeftSpace: ['SqlText', 'SqlInteger', 'textPadLeft'],
  textPadRight: ['SqlText', 'SqlInteger'],
  textPadRightSpace: ['SqlText', 'SqlInteger', 'textPadRight'],
  textOverlayLength: ['SqlText', 'SqlInteger', 'sqlTextSubstring'],
  textOverlay: ['SqlText', 'SqlInteger', 'textOverlayLength', 'textLength'],
  textLikeNextChar: [],
  textLikeCharLen: [],
  textLikeMatch: ['textLikeNextChar'],
  textLike: ['SqlBoolean', 'SqlText', 'textLikeMatch'],
  textNotLike: ['SqlBoolean', 'SqlText', 'textLikeMatch'],
  textLikeEscape: ['SqlText', 'textLikeCharLen'],
  textAsciiCase: ['SqlText'],
  textAsciiLower: ['SqlText', 'textAsciiCase'],
  textAsciiUpper: ['SqlText', 'textAsciiCase'],
  textAsciiInitcap: ['SqlText', 'textAsciiCase'],
  textILike: ['SqlBoolean', 'SqlText', 'textLike', 'textAsciiLower'],
  textNotILike: ['SqlBoolean', 'SqlText', 'textNotLike', 'textAsciiLower'],
  nameInput: ['SqlText', 'textLikeCharLen'],
  byteaFromHex: [],
  byteaInput: ['SqlText', 'byteaFromHex'],
  byteaDecode: ['byteaFromHex'],
  byteaHex: [],
  byteaLikeMatch: [],
  byteaLike: ['SqlBoolean', 'SqlText', 'byteaDecode', 'byteaLikeMatch'],
  byteaNotLike: ['SqlBoolean', 'SqlText', 'byteaDecode', 'byteaLikeMatch'],
  byteaLikeEscape: ['SqlText', 'byteaDecode', 'byteaHex'],
  byteaCompare: ['SqlInteger', 'SqlText', 'byteaDecode'],
  byteaComparison: ['SqlBoolean', 'SqlInteger', 'SqlText', 'byteaCompare'],
  byteaEq: ['SqlBoolean', 'SqlText', 'byteaComparison'],
  byteaNe: ['SqlBoolean', 'SqlText', 'byteaComparison'],
  byteaLt: ['SqlBoolean', 'SqlText', 'byteaComparison'],
  byteaLe: ['SqlBoolean', 'SqlText', 'byteaComparison'],
  byteaGt: ['SqlBoolean', 'SqlText', 'byteaComparison'],
  byteaGe: ['SqlBoolean', 'SqlText', 'byteaComparison'],
  byteaCat: ['SqlText', 'byteaDecode', 'byteaHex'],
  byteaLarger: ['SqlText', 'byteaCompare'],
  byteaSmaller: ['SqlText', 'byteaCompare'],
  byteaOctetLength: ['SqlInteger', 'SqlText', 'byteaDecode'],
  byteaBitLength: ['SqlInteger', 'byteaOctetLength'],
  byteaBitCount: ['SqlInteger', 'SqlText', 'byteaDecode'],
}
