export const goTextDependencies: Record<string, readonly string[]> = {
  bpcharText: ['SqlText'],
  booleanText: ['SqlText', 'SqlBoolean'],
  varcharCoerce: ['SqlText', 'SqlInteger', 'SqlBoolean'],
  bpcharCoerce: ['SqlText', 'SqlInteger', 'SqlBoolean'],
  bpcharLength: ['SqlInteger', 'SqlText'],
  bpcharEq: ['SqlText', 'SqlBoolean', 'bpcharText', 'textEq'],
  bpcharNe: ['SqlText', 'SqlBoolean', 'bpcharText', 'textNe'],
  bpcharLt: ['SqlText', 'SqlBoolean', 'bpcharText', 'textLt'],
  bpcharLe: ['SqlText', 'SqlBoolean', 'bpcharText', 'textLe'],
  bpcharGt: ['SqlText', 'SqlBoolean', 'bpcharText', 'textGt'],
  bpcharGe: ['SqlText', 'SqlBoolean', 'bpcharText', 'textGe'],
  sqlTextSubstring: [],
  textSubstring: ['SqlText', 'SqlInteger', 'sqlTextSubstring'],
  textSubstringLength: ['SqlText', 'SqlInteger', 'sqlTextSubstring'],
  textLeft: ['SqlText', 'SqlInteger'],
  textRight: ['SqlText', 'SqlInteger'],
  textTrimBoth: ['SqlText'],
  textTrimBothSpace: ['SqlText', 'textTrimBoth'],
  textTrimLeft: ['SqlText'],
  textTrimLeftSpace: ['SqlText', 'textTrimLeft'],
  textTrimRight: ['SqlText'],
  textTrimRightSpace: ['SqlText', 'textTrimRight'],
  textReplace: ['SqlText'],
  textTranslate: ['SqlText'],
  textPosition: ['SqlInteger', 'SqlText'],
  textStartsWith: ['SqlBoolean', 'SqlText'],
  textSplitPart: ['SqlText', 'SqlInteger'],
  textReverse: ['SqlText'],
  textAscii: ['SqlInteger', 'SqlText'],
  textBitLength: ['SqlInteger', 'SqlText'],
  textRepeat: ['SqlText', 'SqlInteger'],
  textPadLeft: ['SqlText', 'SqlInteger'],
  textPadLeftSpace: ['SqlText', 'SqlInteger', 'textPadLeft'],
  textPadRight: ['SqlText', 'SqlInteger'],
  textPadRightSpace: ['SqlText', 'SqlInteger', 'textPadRight'],
  textOverlayLength: ['SqlText', 'SqlInteger', 'sqlTextSubstring'],
  textOverlay: ['SqlText', 'SqlInteger', 'textOverlayLength', 'textLength'],
  textLikeNextChar: [],
  textLikeCharLen: [],
  textLikeMatch: ['textLikeNextChar'],
  textLike: ['SqlBoolean', 'SqlText', 'textLikeMatch'],
  textNotLike: ['SqlBoolean', 'SqlText', 'textLikeMatch'],
  textLikeEscape: ['SqlText', 'textLikeCharLen'],
  textAsciiCase: ['SqlText'],
  textAsciiLower: ['SqlText', 'textAsciiCase'],
  textAsciiUpper: ['SqlText', 'textAsciiCase'],
  textAsciiInitcap: ['SqlText', 'textAsciiCase'],
  textILike: ['SqlBoolean', 'SqlText', 'textLike', 'textAsciiLower'],
  textNotILike: ['SqlBoolean', 'SqlText', 'textNotLike', 'textAsciiLower'],
  nameInput: ['SqlText', 'textLikeCharLen'],
  byteaFromHex: [],
  byteaInput: ['SqlText', 'byteaFromHex'],
  byteaDecode: ['byteaFromHex'],
  byteaHex: [],
  byteaLikeMatch: [],
  byteaLike: ['SqlBoolean', 'SqlText', 'byteaDecode', 'byteaLikeMatch'],
  byteaNotLike: ['SqlBoolean', 'SqlText', 'byteaDecode', 'byteaLikeMatch'],
  byteaLikeEscape: ['SqlText', 'byteaDecode', 'byteaHex'],
  byteaCompare: ['SqlInteger', 'SqlText', 'byteaDecode'],
  byteaComparison: ['SqlBoolean', 'SqlInteger', 'SqlText', 'byteaCompare'],
  byteaEq: ['SqlBoolean', 'SqlText', 'byteaComparison'],
  byteaNe: ['SqlBoolean', 'SqlText', 'byteaComparison'],
  byteaLt: ['SqlBoolean', 'SqlText', 'byteaComparison'],
  byteaLe: ['SqlBoolean', 'SqlText', 'byteaComparison'],
  byteaGt: ['SqlBoolean', 'SqlText', 'byteaComparison'],
  byteaGe: ['SqlBoolean', 'SqlText', 'byteaComparison'],
  byteaCat: ['SqlText', 'byteaDecode', 'byteaHex'],
  byteaLarger: ['SqlText', 'byteaCompare'],
  byteaSmaller: ['SqlText', 'byteaCompare'],
  byteaOctetLength: ['SqlInteger', 'SqlText', 'byteaDecode'],
  byteaBitLength: ['SqlInteger', 'byteaOctetLength'],
  byteaBitCount: ['SqlInteger', 'SqlText', 'byteaDecode'],
  byteaSlice: [],
  byteaSubstr: ['SqlText', 'SqlInteger', 'byteaDecode', 'byteaHex', 'byteaSlice'],
  byteaSubstrLength: ['SqlText', 'SqlInteger', 'byteaDecode', 'byteaHex', 'byteaSlice'],
  byteaPosition: ['SqlInteger', 'SqlText', 'byteaDecode'],
  byteaOverlayLength: ['SqlText', 'SqlInteger', 'byteaDecode', 'byteaHex', 'byteaSlice'],
  byteaOverlay: ['SqlText', 'SqlInteger', 'byteaOverlayLength', 'byteaOctetLength'],
  byteaTrim: ['SqlText', 'byteaDecode', 'byteaHex'],
  byteaTrimBoth: ['SqlText', 'byteaTrim'],
  byteaTrimLeft: ['SqlText', 'byteaTrim'],
  byteaTrimRight: ['SqlText', 'byteaTrim'],
  byteaReverse: ['SqlText', 'byteaDecode', 'byteaHex'],
  byteaGetByte: ['SqlInteger', 'SqlText', 'byteaDecode'],
  byteaGetBit: ['SqlInteger', 'SqlText', 'byteaDecode'],
  byteaSetByte: ['SqlText', 'SqlInteger', 'byteaDecode', 'byteaHex'],
  byteaSetBit: ['SqlText', 'SqlInteger', 'byteaDecode', 'byteaHex'],
  byteaFromSigned: [],
  byteaFromInt: ['SqlInteger', 'SqlText', 'byteaHex', 'byteaFromSigned'],
  byteaFromInt2: ['SqlInteger', 'SqlText', 'byteaFromInt'],
  byteaFromInt4: ['SqlInteger', 'SqlText', 'byteaFromInt'],
  byteaFromInt8: ['SqlInteger', 'SqlText', 'byteaFromInt'],
  byteaToSigned: [],
  byteaToInt: ['SqlInteger', 'SqlText', 'byteaDecode', 'byteaToSigned'],
  byteaToInt2: ['SqlInteger', 'SqlText', 'byteaToInt'],
  byteaToInt4: ['SqlInteger', 'SqlText', 'byteaToInt'],
  byteaToInt8: ['SqlInteger', 'SqlText', 'byteaToInt'],
  byteaEncodingName: [],
  byteaHexText: [],
  byteaHexValue: [],
  byteaHexDecodeText: ['byteaHexValue'],
  byteaBase64Encode: [],
  byteaBase64Value: [],
  byteaBase64Decode: ['byteaBase64Value'],
  byteaEscapeEncode: [],
  byteaEscapeDecode: [],
  byteaEncode: [
    'SqlText',
    'byteaDecode',
    'byteaEncodingName',
    'byteaHexText',
    'byteaBase64Encode',
    'byteaEscapeEncode',
  ],
  byteaDecodeFormat: [
    'SqlText',
    'byteaEncodingName',
    'byteaHexDecodeText',
    'byteaBase64Decode',
    'byteaEscapeDecode',
    'byteaHex',
  ],
}
