export const goTextDependencies: Record<string, readonly string[]> = {
  bpcharText: ['SqlText'],
  booleanText: ['SqlText', 'SqlBoolean'],
  varcharCoerce: ['SqlText', 'SqlInteger', 'SqlBoolean'],
  bpcharCoerce: ['SqlText', 'SqlInteger', 'SqlBoolean'],
  bpcharLength: ['SqlInteger', 'SqlText'],
  bpcharEq: ['SqlText', 'SqlBoolean', 'bpcharText', 'textEq'],
  bpcharNe: ['SqlText', 'SqlBoolean', 'bpcharText', 'textNe'],
  bpcharLt: ['SqlText', 'SqlBoolean', 'bpcharText', 'textLt'],
  bpcharLe: ['SqlText', 'SqlBoolean', 'bpcharText', 'textLe'],
  bpcharGt: ['SqlText', 'SqlBoolean', 'bpcharText', 'textGt'],
  bpcharGe: ['SqlText', 'SqlBoolean', 'bpcharText', 'textGe'],
  sqlTextSubstring: [],
  textSubstring: ['SqlText', 'SqlInteger', 'sqlTextSubstring'],
  textSubstringLength: ['SqlText', 'SqlInteger', 'sqlTextSubstring'],
  textLeft: ['SqlText', 'SqlInteger'],
  textRight: ['SqlText', 'SqlInteger'],
  textTrimBoth: ['SqlText'],
  textTrimBothSpace: ['SqlText', 'textTrimBoth'],
  textTrimLeft: ['SqlText'],
  textTrimLeftSpace: ['SqlText', 'textTrimLeft'],
  textTrimRight: ['SqlText'],
  textTrimRightSpace: ['SqlText', 'textTrimRight'],
  textReplace: ['SqlText'],
  textTranslate: ['SqlText'],
  textPosition: ['SqlInteger', 'SqlText'],
  textStartsWith: ['SqlBoolean', 'SqlText'],
  textSplitPart: ['SqlText', 'SqlInteger'],
  textReverse: ['SqlText'],
  textAscii: ['SqlInteger', 'SqlText'],
  textBitLength: ['SqlInteger', 'SqlText'],
  textRepeat: ['SqlText', 'SqlInteger'],
  textPadLeft: ['SqlText', 'SqlInteger'],
  textPadLeftSpace: ['SqlText', 'SqlInteger', 'textPadLeft'],
  textPadRight: ['SqlText', 'SqlInteger'],
  textPadRightSpace: ['SqlText', 'SqlInteger', 'textPadRight'],
  textOverlayLength: ['SqlText', 'SqlInteger', 'sqlTextSubstring'],
  textOverlay: ['SqlText', 'SqlInteger', 'textOverlayLength', 'textLength'],
}
