export const goUuidDependencies: Record<string, readonly string[]> = {
  SqlUuid: [],
  uuidHexDigit: [],
  uuidInput: ['SqlUuid', 'uuidHexDigit'],
  uuidFromText: ['SqlUuid', 'SqlText', 'uuidInput'],
  uuidText: ['SqlUuid', 'SqlText'],
  uuidCompare: ['SqlUuid', 'SqlInteger'],
  uuidComparison: ['SqlUuid', 'SqlBoolean', 'uuidCompare'],
  uuidEq: ['SqlUuid', 'SqlBoolean', 'uuidComparison'],
  uuidNe: ['SqlUuid', 'SqlBoolean', 'uuidComparison'],
  uuidLt: ['SqlUuid', 'SqlBoolean', 'uuidComparison'],
  uuidLe: ['SqlUuid', 'SqlBoolean', 'uuidComparison'],
  uuidGt: ['SqlUuid', 'SqlBoolean', 'uuidComparison'],
  uuidGe: ['SqlUuid', 'SqlBoolean', 'uuidComparison'],
  uuidExtractVersion: ['SqlUuid', 'SqlInteger'],
  sqlIsNullUuid: ['SqlUuid', 'SqlBoolean'],
  sqlIsNotNullUuid: ['SqlUuid', 'SqlBoolean'],
  sqlCaseUuid: ['SqlUuid', 'SqlBoolean'],
  sqlCoalesceUuid: ['SqlUuid'],
}
