[package]
name = "pgsid-check-evaluator"
version = "0.0.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
pgsid-regex-engine = { path = "../regex-engine" }

[build-dependencies]
pgsid-check-timezone-data = { path = "../../tools/check-timezone-data" }
pgsid-check-unicode-data = { path = "../../tools/check-unicode-data" }
