// Generate the sqlc disagreement register — the adjudicator's worklist.
//
//   pnpm exec tsx tests/probe/sqlc-register.ts        # writes docs/sqlc-disagreements.md
//
// For every borrowed query both engines can speak about, compares sqlc's
// expected nullability (expected.json — the IR, see
// tests/unit/query/sqlc-corpus/PROVENANCE.md) against the walk's claims and
// emits one register entry per disagreeing column. The suite
// (sqlc-corpus.test.ts) pins the CENSUS; this file carries the CASES, with
// an empty Disposition per entry for the adjudication to fill.
//
// Neither side is presumed right. The adjudication protocol is printed at
// the top of the register.

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { PGlite } from "@electric-sql/pglite";
import { uuid_ossp } from "@electric-sql/pglite/contrib/uuid_ossp";
import { pgcrypto } from "@electric-sql/pglite/contrib/pgcrypto";
import { ltree } from "@electric-sql/pglite/contrib/ltree";
import { pg_trgm } from "@electric-sql/pglite/contrib/pg_trgm";
import { citext } from "@electric-sql/pglite/contrib/citext";
import { parseSql } from "../../src/ast.js";
import { snapshotCatalog } from "../../src/catalog/snapshot.js";
import { buildNullabilityCatalog } from "../../src/query/catalog-adapter.js";
import { inferNullability } from "../../src/query/nullability-walk.js";
import {
  loadSqlcCases,
  sqlcExpectedNullability,
  SQLC_MACRO_RE,
} from "../unit/query/sqlc-corpus.js";

const OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "docs", "sqlc-disagreements.md");

const HEADER = `# sqlc disagreement register

Generated by \`tests/probe/sqlc-register.ts\` from the vendored corpus
(\`tests/unit/query/sqlc-corpus/\`, upstream release pinned in its
PROVENANCE.md). The census behind it is pinned in \`sqlc-corpus.test.ts\`;
regenerate after any corpus refresh or engine change that moves those pins.

## Adjudication protocol

Neither engine is presumed right; only a counterexample with data decides.

- **sqlc-stronger** (sqlc claims NOT NULL, the walk claims nullable): build
  a data state under the case's schema and run the query. A NULL in the
  column CONVICTS sqlc — the state + query is the repro for an upstream
  ticket. No witness after honest attempts → read the walk's trace
  (\`inferNullabilityTraced\`) for the rule that should have proven it: a
  pgsid imprecision candidate — fixture it.
- **pgsid-stronger** (the walk claims notNull, sqlc claims nullable): sqlc
  conservatism is expected in bulk (it has no promotion, key, or CHECK
  reasoning) and is not ticket-worthy. A witness NULL here would be a PGSID
  UNSOUNDNESS — top severity, before anything else.
- Record every outcome in the Disposition line: \`ticket <url>\`,
  \`pgsid-fixed <commit>\`, \`conservatism-expected <why>\`, or
  \`unresolved <what blocks>\`.
`;

async function main() {
  const pg = await PGlite.create({
    extensions: { uuid_ossp, pgcrypto, ltree, pg_trgm, citext },
  });
  const sections: string[] = [];
  let sqlcStronger = 0;
  let pgsidStronger = 0;

  for (const c of loadSqlcCases()) {
    await pg.exec("BEGIN;");
    let catalog;
    try {
      await pg.exec(c.schema);
      catalog = await buildNullabilityCatalog(await snapshotCatalog(pg));
    } catch {
      await pg.exec("ROLLBACK;");
      continue;
    }
    let prepId = 0;
    for (const q of c.queries) {
      if (SQLC_MACRO_RE.test(q.sql)) continue;
      const expected = sqlcExpectedNullability(c, q);
      if (typeof expected === "string") continue;
      // The suite's PREPARE gate, mirrored: an entry the adjudicator cannot
      // RUN cannot be adjudicated, and the census counts only these.
      await pg.exec("SAVEPOINT reg;");
      let prepared = false;
      try {
        await pg.exec(`PREPARE reg_${c.name.replace(/\W/g, "_")}_${prepId++} AS ${q.sql.replace(/;\s*$/, "")}`);
        prepared = true;
      } catch {
        /* not PostgreSQL-valid */
      } finally {
        await pg.exec("ROLLBACK TO SAVEPOINT reg;");
      }
      if (!prepared) continue;
      let stmt;
      try {
        stmt = (await parseSql(q.sql)).stmts?.[0]?.stmt;
        if (!stmt) continue;
      } catch {
        continue;
      }
      let claims;
      try {
        claims = await inferNullability(stmt, catalog);
      } catch {
        continue;
      }
      if (expected.length !== claims.length) {
        sections.push(
          `## shape-skew — \`${c.name}/${q.name}\`\n\n` +
            `sqlc IR arity ${expected.length}, walk (and PostgreSQL) ${claims.length}.\n\n` +
            "```sql\n" + q.sql + "\n```\n\n**Disposition:** _unresolved_\n",
        );
        continue;
      }
      for (let i = 0; i < expected.length; i++) {
        const s = expected[i]!.notNull;
        const p = claims[i]!.notNull;
        if (s === p) continue;
        const cls = s && !p ? "sqlc-stronger" : "pgsid-stronger";
        if (cls === "sqlc-stronger") sqlcStronger++;
        else pgsidStronger++;
        sections.push(
          `## ${cls} — \`${c.name}/${q.name}\` column ${i} (\`${expected[i]!.column}\`)\n\n` +
            `sqlc: ${s ? "NOT NULL" : "nullable"} · walk: ${p ? "notNull" : "nullable"} · ` +
            `schema: \`tests/unit/query/sqlc-corpus/cases/${c.name}/schema.sql\`\n\n` +
            "```sql\n" + q.sql + "\n```\n\n**Disposition:** _unresolved_\n",
        );
      }
    }
    await pg.exec("ROLLBACK;");
  }
  await pg.close();

  const body =
    HEADER +
    `\nEntries: ${sections.length} (sqlc-stronger ${sqlcStronger}, ` +
    `pgsid-stronger ${pgsidStronger}, shape-skew ${sections.length - sqlcStronger - pgsidStronger}).\n\n` +
    sections.join("\n");
  writeFileSync(OUT, body);
  // eslint-disable-next-line no-console
  console.log(`wrote ${OUT}: ${sections.length} entries`);
}

main().catch(e => {
  // eslint-disable-next-line no-console
  console.error(e);
  process.exit(1);
});
