// Generate the sqlc disagreement register — the ADJUDICATED view.
//
//   pnpm exec tsx tests/probe/sqlc-register.ts        # writes docs/sqlc-disagreements.md
//
// The register used to be the source of truth and this script used to destroy
// it: it emitted `_unresolved_` per entry, so regenerating after a corpus
// refresh threw away every disposition someone had reasoned out. That is
// inverted now. The truth lives per case, beside the vendored files:
//
//   cases/<case>/schema.sql, query.sql, expected.json   vendored (sqlc's)
//   cases/<case>/data.sql                               ours — the data state
//   cases/<case>/adjudication.json                      ours — the conclusion
//   tickets/T*.md                                       ours — upstream drafts
//
// and this script only ASSEMBLES them. Regenerating is now safe by
// construction, because there is nothing here to lose.
//
// The verdicts it prints are the ones `sqlc-corpus.test.ts` pins
// (DISAGREEMENTS and ADJUDICATED in sqlc-corpus.ts, both re-derived from rows
// on every run), so the register cannot drift from the suite: if a state stops
// producing its NULL, the suite fails before this file is ever regenerated.

import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  loadSqlcCases,
  SQLC_VERSION,
  DISAGREEMENTS,
  ADJUDICATED,
} from "../unit/query/sqlc-corpus.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, "..", "..", "docs", "sqlc-disagreements.md");
const TICKETS = join(HERE, "..", "unit", "query", "sqlc-corpus", "tickets");

function main(): void {
  const cases = loadSqlcCases();
  const sqlByKey = new Map<string, string>();
  const caseOf = new Map<string, string>();
  for (const c of cases) {
    for (const q of c.queries) {
      sqlByKey.set(`${c.name}/${q.name}`, q.sql);
      caseOf.set(`${c.name}/${q.name}`, c.name);
    }
  }

  const census: Record<string, number> = {};
  const sections: string[] = [];

  for (const key of Object.keys(DISAGREEMENTS).sort()) {
    const classification = DISAGREEMENTS[key]!;
    const verdictLine = ADJUDICATED[key] ?? "UNADJUDICATED";
    const [verdict, dispositionPart] = verdictLine.split(" · ");
    const disposition = (dispositionPart ?? "unresolved").replace(/\s*\(T\d\)$/, "");
    census[disposition] = (census[disposition] ?? 0) + 1;

    // `case/Query#i (col)` → the query key, and the column if there is one.
    const queryKey = key.replace(/#\d+ \(.*\)$/, "");
    const caseName = caseOf.get(queryKey)!;
    const c = cases.find(x => x.name === caseName)!;
    const local = key.slice(caseName.length + 1);
    const entry = c.adjudication?.entries[local];
    const ticket = /\((T\d)\)/.exec(verdictLine)?.[1];

    const col = /#(\d+) \((.*)\)$/.exec(key);
    const head = col
      ? `## ${classification} — \`${queryKey}\` column ${col[1]} (\`${col[2]}\`)`
      : `## shape-skew — \`${queryKey}\``;

    let body = `${head}\n\n`;
    body += `sqlc/walk: ${classification} · observed: **${verdict}** · schema: ` +
      `\`tests/unit/query/sqlc-corpus/cases/${caseName}/schema.sql\`\n\n`;
    body += "```sql\n" + (sqlByKey.get(queryKey) ?? "") + "\n```\n\n";
    if (c.adjudication) body += `**Data state** — ${c.adjudication.why}\n\n`;
    if (c.data) {
      const seed = c.data.split("\n").filter(l => !/^--/.test(l) && l.trim()).join("\n");
      body += "```sql\n" + seed + "\n```\n\n";
    }
    const args = c.adjudication?.args?.[queryKey.split("/")[1]!];
    if (args) body += `**Bindings** — ${args.map(a => JSON.stringify(a)).join(", ")}\n\n`;
    if (entry) body += `${entry.note}\n\n`;
    body += `**Disposition:** \`${disposition}\``;
    body += ticket ? ` — [${ticket}](../tests/unit/query/sqlc-corpus/tickets/${ticket}.md)\n` : "\n";
    sections.push(body);
  }

  const ticketFiles = existsSync(TICKETS)
    ? readdirSync(TICKETS).filter(f => f.endsWith(".md")).sort()
    : [];

  const header = `# sqlc disagreement register

**Generated** by \`tests/probe/sqlc-register.ts\` from the per-case files —
\`cases/<case>/adjudication.json\` and \`cases/<case>/data.sql\` beside the
vendored corpus, and \`tickets/T*.md\`. Do not edit this file: edit the case,
and regenerate. Regenerating is safe, which it was not before — the
dispositions used to live here and be destroyed on every run.

Corpus release: **${SQLC_VERSION}** (\`tests/unit/query/sqlc-corpus/PROVENANCE.md\`).
Every conclusion below records the release it was drawn against, and
\`sqlc-corpus.test.ts\` fails when the two part.

## How an entry is decided

Neither engine is presumed right; only a counterexample with data decides.

- **sqlc-stronger** (sqlc claims NOT NULL, the walk claims nullable): the
  case's \`data.sql\` is built to produce a NULL in that column. Observing one
  CONVICTS sqlc — verdict \`sqlc-convicted\`, and the state is the upstream
  repro. Not observing one after an honest attempt is \`attempted\`, and the
  walk's trace then names the rule that should have proven it.
- **pgsid-stronger** (the walk claims notNull, sqlc claims nullable): sqlc
  conservatism is expected in bulk and is not ticket-worthy. The state is built
  to break the walk's claim anyway; a NULL here would be a PGSID UNSOUNDNESS,
  and it is not a verdict this file can print — it fails the suite outright.
- The verdicts are re-derived from rows on **every** suite run, not read from
  here. This file is a view.

Entries: ${Object.keys(DISAGREEMENTS).length}. Census by disposition: ` +
    Object.entries(census)
      .sort()
      .map(([k, v]) => `${k} ${v}`)
      .join(" · ") +
    `.\n\nVerdicts: ` +
    Object.entries(
      Object.values(ADJUDICATED).reduce<Record<string, number>>((acc, v) => {
        const key = v.split(" · ")[0]!;
        acc[key] = (acc[key] ?? 0) + 1;
        return acc;
      }, {}),
    )
      .sort()
      .map(([k, v]) => `${k} ${v}`)
      .join(" · ") +
    `. No pgsid unsoundness: every pgsid-stronger claim survived a state built to break it.\n\n`;

  const ticketIndex = ticketFiles.length
    ? "## Upstream drafts\n\nDrafted, not filed. One per DEFECT rather than per entry.\n\n" +
      ticketFiles
        .map(f => {
          const first = readFileSync(join(TICKETS, f), "utf8").split("\n")[0]!;
          return `- [${first.replace(/^#\s*/, "")}](../tests/unit/query/sqlc-corpus/tickets/${f})`;
        })
        .join("\n") +
      "\n\n"
    : "";

  writeFileSync(OUT, header + ticketIndex + sections.join("\n"));
  console.log(`wrote ${OUT}: ${sections.length} entries, ${ticketFiles.length} ticket drafts`);
}

main();
