-- The window construction: lag on the partition's first row addresses a row
-- outside it — the reason lag is excluded from NEVER_NULL_WINDOW_FNS.
-- @signature anyelement
-- @null  SELECT lag(x) OVER (ORDER BY x) FROM (VALUES (1)) t(x)
-- @value SELECT lag(x) OVER (ORDER BY x) FROM (VALUES (1),(2)) t(x) ORDER BY x OFFSET 1
