-- Migration: 0005_broken_plpgsql
-- A migration where the first statement (valid DDL) succeeds, but the
-- second statement (a PL/pgSQL function) has a semantic error caught by
-- plpgsql_check. The apply pipeline halts on the function error, and
-- the schema state reverts to before this migration (ROLLBACK).

CREATE TABLE public.audit_log (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id bigint NOT NULL,
  action text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE FUNCTION public.log_user_action(uid bigint, act text)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  r record;
BEGIN
  FOR r IN SELECT * FROM public.users LOOP
    RAISE NOTICE '%', r.nonexistent_field;
  END LOOP;
END;
$$;
