-- ADVERSARIAL FINDING 13 — rank 2, shape defect.
--
-- Falsifying data: none needed.
-- Observed: PostgreSQL's RowDescription is [a, b]; the engine reports ONE
-- column named after the function.
--
-- Suspected mechanism: `resolveTableFunctionColumns` (nullability-walk.ts)
-- renames positionally from `entry.cteColumns` — the alias's NAME list. A
-- **column definition list** (`AS z(a integer, b text)`) is a different AST
-- field: the RangeFunction's per-function `coldeflist`, carrying names AND
-- types, and it is what makes a `RETURNS SETOF record` function callable at
-- all. It is never read, so the record function falls through the
-- unknown-metadata branch to a single conservative column.
--
-- Both renderings lose the shape: a user `RETURNS SETOF record` function
-- (`rec_pairs() AS z(n integer, s text)`) and the builtin record-returning
-- family (`jsonb_to_recordset(…) AS z(a integer, b text)`, `json_to_record`,
-- `xml_to_record`). The coldeflist is mandatory for these calls, so every
-- such query has the wrong shape.
SELECT * FROM jsonb_to_recordset('[{"a":1,"b":"x"}]'::jsonb) AS z(a integer, b text)
-- engine claims: one column, @nullable — PostgreSQL emits two.
