-- RANK 7 (register material) — the composite-star arm refuses legal SQL.
-- `expandCompositeStar` resolves only two shapes: a bare alias (`(t).*`)
-- and a function call (`(f(x)).*`). A composite COLUMN
-- (`(c.p).*`), a subquery's composite column (`(s.c).*`), and a ROW
-- constructor (`(ROW(1,2)).*`, whose arity is countable at parse time) all
-- throw `UnsupportedNodeError(composite-star, …)` — sound, but the whole
-- statement is refused rather than one column blunted.
--
-- Measured: PostgreSQL expands (c.p).* to ["sku","qty"] and (ROW(1,2)).* to
-- ["f1","f2"]. A composite column's fields would all be nullable (a NULL
-- composite nulls every field — the fix phase measured exactly this for the
-- FuncCall arm), so the precise answer is cheap.
-- @refused: composite-star / ColumnRef
SELECT (c.p).* FROM cc c
