-- ADVERSARIAL FINDING 12 — rank 2 (shape) producing rank 1 (notNull).
--
-- Falsifying data: none needed.
-- Observed: PostgreSQL's RowDescription is [n, s, o] over two rows
-- ((1,'a',1) and (2,NULL,2)); the engine reports TWO columns [n, s] and, by
-- the resulting off-by-one, hands `WITH ORDINALITY`'s always-present bigint
-- counter to position 1 — claiming `s` notNull, which row 2 falsifies.
--
-- Suspected mechanism: `resolveTableFunctionColumns` (nullability-walk.ts)
-- pushes exactly ONE column per function item when the catalog has no
-- metadata for the name ("Unknown function (e.g. a pg_catalog SRF like
-- generate_series): a single column, conservatively nullable"). That is right
-- for a scalar SRF and wrong for **multi-argument `unnest`**, which is a
-- special form: `unnest(a, b, c)` in FROM expands to one column PER ARRAY
-- ARGUMENT, zip-style, padding the short arrays with NULL. The ordinality
-- column is then appended at the wrong ordinal, and the positional alias-list
-- rename lands on the wrong columns.
--
-- Without ORDINALITY the same statement is a pure shape defect (two array
-- arguments → engine 1 column, PostgreSQL 2; three → 1 vs 3). `ROWS FROM
-- (unnest(a), unnest(b))` is the spelling that is NOT affected — there each
-- function item really does contribute one column.
SELECT * FROM unnest(ARRAY[1,2], ARRAY['a']) WITH ORDINALITY AS z(n, s, o)
-- engine claims: n @nullable, s @notNull  <-- FALSE (it is the ordinality
-- column's flag, landed one position early)
