-- SWEEP-4 FINDING 7 (rank 3). Quarantined: the `@param` line below is the
-- engine's CURRENT claim — it makes none, which under the suite's rule for a
-- nullable parameter is itself the claim, and it is WRONG.
--
-- Falsifying data: none — the binding is the whole test.
-- Observed: binding NULL to $1 RAISES `domain nn_text does not allow null
-- values`, in every state, while the all-valid control succeeds.
--
-- `param-soundness.test.ts` states the rule at the top of the file:
--
--     nullable — universal: binding NULL must never raise, in any state.
--
-- The engine already holds the fact that convicts it. Priority 1 claims this
-- statement's OUTPUT notNull on the reasoning "returns NOT NULL domain -> PG
-- enforces at call boundary" — i.e. the call either yields a non-null value
-- or RAISES. Whether it raises depends on whether the body maps NULL to
-- NULL, and the walk reads exactly that (priority 5, `resolveSqlFunctionBody`
-- with the call's argument vector). The output side consumes both halves;
-- the parameter side consumes neither, so the rejection is invisible.
--
-- The class is bounded and catalog-visible, which is what makes it fixable:
-- a NON-STRICT function declared to return a NOT NULL DOMAIN whose body is
-- NULL-preserving. Measured, with the controls:
--
--   sw4_dom_id($1)      body `SELECT x::nn_text`   -> RAISES   (claimed nullable)
--   sw4_dom_echo($1)    body `SELECT x`            -> RAISES   (claimed nullable)
--   dom_lenient($1)     body `SELECT 'd'::nn_text` -> ACCEPTED (claimed nullable — correct)
--   dom_strict($1)      STRICT                     -> ACCEPTED (short-circuits; correct)
--   $1::nn_text         mechanism A                -> RAISES   (claimed notNull — correct)
--
-- The corpus cannot express it: every NOT-NULL-domain-returning function in
-- `fixtures/schema.sql` returns a CONSTANT (always_text, tag_of, over_fn,
-- always_positive, safe_name, plpgsql_domain_fn, dom_lenient, dom_strict),
-- so the whole class is unreached rather than merely unlikely — the
-- charter's thesis about the generated half, one level up.
--
-- WIDER, AND A CONTRACT QUESTION RATHER THAN A BUG: a plpgsql body that
-- simply RAISEs on NULL (`sw4_raiser`) rejects the same binding with nothing
-- catalog-visible behind it, and no static analysis can see it. That says
-- the suite's "nullable is universal" rule is not achievable for arbitrary
-- user functions, and the doc's own other sentence — "claims mean raises;
-- absence of a claim promises nothing" — reads the other way. The two
-- statements are in `docs/argument-nullability.md` a few hundred lines
-- apart. This is the dual of the reachability question that document already
-- records as open on the `notNull` side, and the fix phase has to decide the
-- wording before it decides the code.
--
-- Suspected mechanism: param-nullability.ts — no rule consumes
-- `funcReturnsNotNullDomain` at a call site, so mechanism C's value flow
-- stops at the function boundary.
--
-- Attack-catalog entry: the free-form session, from B's "confirm it stops
-- SOUNDLY rather than merely early".
-- @args ["v"]
SELECT sw4_dom_id($1) AS d  -- @notNull
