-- FINDING 5 (rank 2) — relation resolution ignores search_path.
-- `NullabilityCatalog.resolveTable`'s documented contract (src/query/types.ts)
-- is "resolve by (schema, name) via search_path — if schema is undefined,
-- search each schema in the search path in order". The implementation
-- (catalog-adapter.ts) hardcodes `public`. Under
-- `SET search_path = app_s, public` PostgreSQL resolves app_s.t; the engine
-- answers for public.t — a different arity, different names, different
-- flags — and does so silently, because public.t resolves fine.
--
-- Observed RowDescription: ["zzz","qqq","www"] (app_s.t).
-- Engine list: ["id","name","val","active"] with id/active @notNull
-- (public.t, from fixtures/schema.sql).
--
-- The mirror case is an over-refusal: `SELECT * FROM app_only` under the
-- same search_path REFUSES (`unresolvable relation app_only`) for a
-- relation PostgreSQL resolves — see search-path-refusal.sql. The two
-- halves belong to one fix: the catalog needs the search path the consumer
-- will run the query under.
-- @no-rows: no data seeded; the defect is in the column LIST, which
-- PostgreSQL reports through RowDescription without any row.
SELECT * FROM t
